tools/loader/loader.cpp

And group the options a bit so they're easier to find.

[loader] Put -model option in "loader" category

---

lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/OpenCL.h

Addresses @jfix71 review comments on #966

[opencl] Fix spelling and improve comments.

---

lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/OpenCL.h

OpenCL backend may need to generate a specialized source code for OpenCL kernels or compile the same source code with different options (e.g. different macro definitions) at runtime. This requires the ability to compile and use multiple cl_programs at the same time.
This PR does the following:
- Re-factors existing code to support multiple source programs
- Adds ability to find a kernel with a given name in a specific program or in any of the programs compiled so far
- Adds a cache of compiled programs so that if there is a request to compile the same source code with the same options for the same OpenCL device, the existing compiled program is reused.

[opencl] Support multiple source programs in OpenCL backend

---

include/glow/Base/Type.h
lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/kernels.cl

- Fix the implementation of the PoolMaxWithXY kernel
- Fix the type of arguments
- Store the coordinates of the found max value
- Support debugprint instruction
- Support gather instruction
- Fix inserttensor support
- Fix a bug in the OpenCL kernel
- Support tensors of up to 4 dimensions

[opencl] Improve/add support for a number of instructions

---

README.md

Align this with pytorch/pytorch.

[docs] Update communication channels.

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

[quantization/optimization] Sink Rescale node down past certain nodes.

---

tests/unittests/InterpreterTest.cpp

@stoklund, I've added a bit more comments to the test.

[trivial] Add comment to the test as per review comments.

---

lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/kernels.cl

After adding these two missing kernels, it is now finally possible to run ptb, mnist and cifar10 using the OpenCL backend.

[opencl] Add kernels for poolmaxwithxygrad and for transposing tensors with elements of index type

---

lib/Backends/CPU/libjit/libjit_conv.cpp

Looks like there was a small bug at the upper edge of the Y dimension.  Now #1008 passes :-D

[libjit] Fix Y edge case in CPU conv

---

tests/unittests/BackendTestUtils.cpp
tests/unittests/BackendTestUtils.h
tests/unittests/JITTest.cpp

1x3x3x32 input * 64x1x1x32 filter

[jittest] Test small convolutions

---

tests/unittests/InterpreterTest.cpp

a convnet to recognize two classes of images (Line and Cross). Now the accuracy rate is 88.5%

[Interpreter] Add a simple convnet unit test

---

lib/Importer/ONNX.cpp
tests/images/run.sh

GobalAveragePool operator is supported in ONNX. Add this one in ONNX loader

[Importer] Support GlobalAveragePool op in ONNX importer

---

lib/Optimizer/IROptimizer.cpp
tests/unittests/IROptTest.cpp
tests/unittests/OperatorTest.cpp

Takes the CPU backend from 4.3 to 3.3 seconds on ptb.
Updated the `sliceVectors` test so that one of its Slices will produce an ExtractTensor that can be optimized.

[IROptimizer] Optimize extracttensor into tensorview

---

lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/kernels.cl

This kernel runs much faster on OpenCL GPU backends compared to the existing matrix multiplication kernel.
It's performance on tall and skinny matrices is not that good yet. We may need to add specialized kernels for those use-cases.

[opencl] Implement a tiled matrix multiplication

---

lib/Backends/CPU/libjit/libjit.cpp

[TopK] Don't call sort() if K is one.  Use the existing unit tests. I also verified the correctness of the fr2en test.

[TopK] Don't call sort() if K is one.

---

tests/unittests/InterpreterTest.cpp

This test is more of MLTest rather than strictly InterpreterTest. To avoid the additional mess and better preserve git history I'll rename it on a separate PR.

[opencl/jit] Make sure that training tests work on all backends.

---

include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
lib/Importer/Caffe2.cpp
lib/Importer/ONNX.cpp
tests/unittests/OperatorTest.cpp

Support Squeeze operator by adding CreateSqueeze() method to Function class

[Operator] Support Squeeze Operator

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/OperatorTest.cpp
tests/unittests/graphOptzTest.cpp

Optimize a sequence of matrix multipliers into one large matrix multiplication. Larger matrix multiplications are more likely to utilize the hardware because they expose more data-level parallelism.  Notice that this commit only implements the combination of LHS matrices. Combining RHS matrices will land in a future commit.

[Opt] Merge a sequence of mat muls into one large mat mul.

---

include/glow/Base/Tensor.h
lib/Base/Tensor.cpp

It's nice to be able to use errs() for debugging, since it's unbuffered.

[tensor] Pass optional ostream to dump

---

lib/Backends/Interpreter/Interpreter.h
lib/Backends/Interpreter/InterpreterNodes.cpp
lib/Graph/Graph.cpp
tests/unittests/quantizationTest.cpp

Support group arg for quantized I8 implementation of Convolution.

[Interpreter] Support group arg for Convolution.

---

lib/Backends/CPU/LLVMIRGen.cpp

Improve the error reporting when we can't load the library. I am adding this feature because the user "neni" ran into issues loading glow on linux and we were not able to diagnose the problem with the current reporting.

Report an error when can't load the glow library.

---

lib/Backends/CPU/LLVMIRGen.cpp
lib/Backends/CPU/libjit/libjit_conv.cpp
lib/Optimizer/Lower.cpp

This reverts commit 7b8457a26830ea00ea3ad5141e3d1d81badf3f28, which was committed by accident. Just reverting it in this pull request.

Revert "[CPU] Support group arg for Convolution"

---

lib/Importer/Caffe2.cpp

Will be used for C2 seq2seq model.

[Caffe2] Support Gather

---

include/glow/Graph/Graph.h
lib/Backends/CPU/LLVMIRGen.cpp
lib/Backends/CPU/libjit/libjit.cpp
lib/Backends/Interpreter/InterpreterNodes.cpp
lib/Graph/Graph.cpp
lib/Graph/Nodes.cpp
lib/Importer/Caffe2.cpp
tests/unittests/BackendTestUtils.cpp
tests/unittests/OperatorTest.cpp
tools/ClassGen/InstrGen.cpp
tools/ClassGen/NodeGen.cpp

Add Log node/instr

---

tests/unittests/HyphenTest.cpp

This unit test was failing intermittently because it depended too closely on
the numbers delivered by nextRand(). The intermittent behavior can be observed
with:
tests/JITTest --gtest_filter=HyphenTest.network --gtest_repeat=25
Make this test less sensitive by:
1. Use a deterministically seeded RNG for shuffling the training data.
2. Increate the training mini batch size 10 -> 25.
3. Double the number of training iterations.
With these changes, the test still runs in ~600 ms.

Stabilize the HyphenTest.network unit test.

---

tests/unittests/quantizationTest.cpp

Builds an explicitly initialized 2 GRU graph and tests quantization identically to end2end test. Adds a single TopKNode to make sure some quantization test coverage is available for that node type.
Addresses #985 by increasing test coverage in glow/lib/Quantization.cpp
Possible issues:
Runs with following warning on CPU backend
```
remark: /home/anthony/glow/lib/Backends/CPU/libjit/libjit.cpp:677:13: loop not vectorized: call instruction cannot be vectorized
warning: <unknown>:0:0: loop not vectorized: failed explicitly specified loop vectorization
```

[tests] Add GRU quantization test

---

examples/fr2en.cpp
include/glow/Quantization/Quantization.h
lib/Quantization/Quantization.cpp
tests/unittests/quantizationTest.cpp
tools/loader/Loader.cpp

Change the quantization procedure to return a new function. This change
is mainly for making the API consistent.

[quantization] Change the quantization procedure to return a new func.

---

tests/unittests/MLTest.cpp

[Test] add a simple unit tests.
I plan to add new features, such as quantization, to this test in future commits.

[Test] add a simple unit tests.

---

lib/Backends/CPU/LLVMIRGen.cpp
lib/Backends/CPU/libjit/libjit_conv.cpp

This commit support "group" arg in convolution for cpu backend except the DKKC8 format.

[ONNX] Support group arg for Convolution

---

lib/Backends/CPU/LLVMIRGen.cpp

By default, LLVM would emit some diagnostics, remarks, etc. It is fine for a static compiler, but not necessary for a JIT. Let's disable it by providing a dummy diagnostics handler, that does not emit anything. In particular, this allows us to get rid of the annoying "cannot vectorize" warnings.
The LLVM APIs for setting the diagnostics handlers have changed in the LLVM 6.0, therefore we have to use a slightly different code for LLVM versions before and after LLVM 6.0.

[LLVM] Do not emit any warnings or diagnostics when JITting

---

README.md
examples/CMakeLists.txt
examples/char-rnn.cpp

The char-rnn program is based on a blog post by Andrej Karpathy: "The
Unreasonable Effectiveness of Recurrent Neural Networks". This is a
small program that reads text from a file and generates random text
based on the input. In each step the network is asked, given the current
buffer of N chars, what is the next char? After a few minutes of
training interesting texts come up.
This is a text program that's designed to stress the Glow compiler
optimizer. There are a bunch of unrealized opportunities for
optimizations, for example horizontal fusion of softmax and matrix
multiplications, buffer optimizations, etc.
--- Example for generated texts ---
A transcript of the movie "When Harry met sally":
Man: I was sitters.
Harry: Hi.
Harry: I can a lot on the startake.
Sally: Harry. They ate …

Add a new test program (char-rnn)

---

tests/unittests/MLTest.cpp

The main characteristic of the test is that it features two inputs.
The goal is to make sure the scheduler (and graph lowering in general)
is able to properly enforce the dependencies between the nodes with
something more complicated than a straight chain of operators.

[unittests] Add a matrix recognition test

---

include/glow/ExecutionEngine/ExecutionEngine.h
lib/Backends/CPU/LLVMIRGen.cpp
lib/ExecutionEngine/ExecutionEngine.cpp

1. Move ifdef into a function.
2. Update comments and method name.

Two small cleanups

---

tests/images/run.sh
utils/download_onnx_models.sh

For ONNX model, I'm only adding one run, because compilation time is quite slow, because Group Convolution is being unrolled to multiple nodes.

[Imagenet] Add shufflenet.

---

tests/unittests/graphTest.cpp

This opt is now disabled for Interpreter and CPU backends, and enabled for OpenCL backend.

[UnitTest] Test if unrolling grouped conv is disabled for Interpreter and CPU backends.

---

include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
tests/unittests/OperatorTest.cpp

Another operator used by seq2seq. I implemented it as a series of splats/multiplies/adds.

[Graph/OperatorTest] Add weightedSum operator

---

lib/Backends/CPU/libjit/libjit_matmul.cpp

With packing implemented, it's now shockingly competitive with Eigen, depending on the size :-D.  I benchmarked fr2en (batch size = 30) since that has a lot of matmuls, and this implementation is about 10% faster (10s -> 9s).
For skinny matrices it's actually a bit slower than the existing implementation -- essentially the packing doesn't buy you anything because the skinny matrix fits in cache, so you're just shuffling memory around.  Eigen shows similar behavior.  MKL doesn't, but I'm betting they special case packing, and I'm not really convinced it's worthwhile here, since this is sort of a tech demo.
Another optimization that would help is for matrices that aren't perfectly tiled by the 3x32 dot product, implementing special kernels like 2x32 to speed up the edges.

[libjit_matmul] Implement packing of A and B matrices

---

lib/Backends/CPU/FunctionSpecializer.cpp

We don't want to specialize arguments which are pointers to floating point and quantized buffers, because this is likely to significantly increase the code size without any big performance benefits.
Also, improve the comments and describe this logic.

[llvm-func-specializer] Don't specialize any arguments that are buffers of quantized values

---

include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
tests/unittests/OperatorTest.cpp

It's implemented using a BatchedAdd followed by a Div, with the denominator of the Div as a Splat with value set to the size of the axis that is being reduced over. More support for seq2seq.

[Graph/OperatorTest] Add BatchedReduceMean operator

---

lib/IR/IRGen.cpp
tools/ClassGen/InstrBuilder.cpp
tools/ClassGen/InstrGen.cpp

Also added missing newline from InstrBuilder.cpp

[InstrGen/IRGen] AutoIRGen GatherNode.

---

tests/unittests/MLTest.cpp

- 1 test from Interpreter/InterpreterAndCPU (871 ms total)
- 1 test from JIT/InterpreterAndCPU (1066 ms total)

[quantizationTest]: Add quantization for convNetForImageRecognition()

---

lib/Backends/CPU/FunctionSpecializer.cpp

Introduce addArgToBeSpecialized and isArgToBeSpecialized helper methods to hide away the explicit bit-masks computations.

[llvm-function-specializer] Minor code simplifications

---

lib/Backends/CPU/DebugInfo.cpp

No debug information is going to be emitted for the code generated from the Glow IR if  the emission of debug info is not enabled.
But any debug information from the Glow's library (e.g. libjit) should be stripped as well. Let's strip the debug info as early as possible, so that the LLVM's optimizer does not need to spend any time to preserve the debug info during optimizations.
It also makes the LLVM IR dump much smaller.

[debug-info] Strip any debug info from the loaded Glow's library (libjit) if the emission of debug info is not enabled

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

Modified the GraphOptimizer::optimizeReshape() function, making it able to eliminate reshape node that follows a splat node, by replace with a new splat node.

[GraphOptimizer]Eliminate reshape node that follows a splat node.

---

examples/fr2en.cpp

We were instrumenting the graph and then throwing it away.  Instead, keep track of it in a member variable.

[fr2en] Fix quantization

---

include/glow/Importer/CommonOperatorLoader.h
include/glow/Importer/ProtobufLoader.h
lib/Importer/Caffe2.cpp
lib/Importer/ONNX.cpp
lib/Importer/ProtobufLoader.cpp
tools/loader/ImageClassifier.cpp

- Use llvm::StringRef instead of std::string
- Rename getOrCreateNodeByName into getOrCreateVariableByName
NFC

[Importer] Clean-up the ProtobufLoader API

---

lib/Graph/Graph.cpp

[Graph] Fix unused variable warning in release mode

---

README.md

Fixes https://github.com/pytorch/glow/issues/1180

[travis] Change the link to the travis build.

---

docs/Testing.md
tools/loader/CMakeLists.txt
tools/loader/ModelRunner.cpp

Sometimes it's useful to load a model and run it without any additional user inputs. Simply use whatever weights/inputs are written in init_net.

[ML examples] Introduce ModelRunner

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

The batchNorm optimization used to assume that the inputs of the related
convolution node were all variables. This is not enforced anywhere and may
actually be wrong.
The fix consists in checking that the inputs of the convolution node are indeed
variables. Moreover, we check that these variables are used only by this
convolution node before doing the transformation. Otherwise we will incorrectly
change the inputs of the other users.
This fixes issue #1178 for the graph optimizer.

[GraphOptimizer] Fix batchNorm optimization

---

include/glow/Graph/Graph.h
include/glow/Graph/Node.h
include/glow/Graph/UseDef.h
include/glow/IR/IR.h
lib/Optimizer/Quantization.cpp

Graph shouldn't depend on headers from IR or Optimizer.

[graph] Fix layering violations

---

lib/Backends/OpenCL/OpenCL.cpp

Move the often repeated logic for providing the buffers arguments into a dedicated function.
Teach this code to ignore the predicate operands as they are not supported by the OpenCL backend yet.
This PR should fix the issue demonstrated by #1200

[opencl] Re-factor and improve the logic to pass buffer operands to OpenCL kernels

---

lib/Backends/CPU/GlowJIT.cpp

* Add the option --dump-jit-symbol-info to dump addresses of JITted functions
This option can be very useful e.g. for debugging crashes inside the code produced by the CPU JIT.
* Add debugger events listener
This allows to the JIT to inform the debugger about the dynamically generated object file. Using this information, the debugger can show proper stack traces, etc.
This feature currently works only on Linux, because LLVM's MachO RuntimeDyld does not support debug info loading yet.
The main motivation for this PR was the debugging experience last week, when @beicy was hunting a bug in the JITted code. This PR should make it easier to debug the JITted code.

[cpu] Improve the ability to debug JITted code

---

lib/Optimizer/GraphOptimizer.cpp

Inspired by https://github.com/pytorch/glow/pull/1220.
Mostly to be defensive in case node will have multiple outputs.

[cleanup] Make code more defensive to multiple outputs.

---

tests/unittests/OperatorTest.cpp

Tests the fix from https://github.com/pytorch/glow/pull/1220

[OperatorTest] Add test for concat of operators with multiple results (TopK)

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

Saw this in fr2en now due to @ZchiPitt 's opti on reshape + concat.

[GraphOptimizer] Optimize Reshape(Reshape(x)) -> Reshape(x)

---

include/glow/Graph/Node.h
include/glow/Graph/Nodes.h
include/glow/Importer/CommonOperatorLoader.h
lib/Backends/CPU/Transforms.cpp
lib/Graph/Grad.cpp
lib/Graph/Graph.cpp
lib/Graph/Nodes.cpp
lib/IR/IR.cpp
lib/IR/IRGen.cpp
lib/Importer/Caffe2.cpp
lib/Importer/ONNX.cpp
lib/Optimizer/GraphOptimizer.cpp
lib/Optimizer/Lower.cpp
tests/unittests/OperatorTest.cpp
tests/unittests/graphOptzTest.cpp
tests/unittests/graphTest.cpp
tools/ClassGen/InstrBuilder.cpp

There were several bugs exposed by missing index.
This PR changes the behavior to use an explicit index.

[cleanup] getType should have explicit index.

---

include/glow/Backends/LayoutConverter.h
lib/Backends/OpenCL/Transforms.cpp
tests/unittests/graphOptzTest.cpp

Fix a couple of places that were missed by #1224

[cleanup] Fix a couple of places missed by the "getType should have explicit index" cleanup

---

examples/fr2en.cpp

I added in a `createVariable()` that takes a required TrainKind parameter before an optional VisibilityKind, so that we don't need to specify the default VisibilityKind every time we're creating Variables with a non-default TrainKind. Then used it for fr2en, and added back Public visibility on output. Patch up for https://github.com/pytorch/glow/pull/1225

[Graph/fr2en] Put back Variable::TrainKind::None everywhere, and fix visibility on output

---

lib/Optimizer/IROptimizer.cpp
tests/unittests/IROptTest.cpp

When coalescing two interval through copies, merge then into one big
interval. This is legal because the buffers have the same value for
that interval.
Given our share buffers optimization only considers one interval at
a time, this effectively teaches it how to consider intervals that
have been copy-coalesced.
This fixes #1240.

[IROptimizer] Teach the share buffers opti how to propagate copies

---

tests/unittests/graphTest.cpp

This test illustrates our issue when there are temporary NodeValues
around. Those temporary NodeValues contributes to the use list whereas
they should not.
The test reflects the current state of our use lists but we should fix
that eventually.
NFC.

[unittests][graph] Add a test case for the uselist

---

include/glow/Graph/Node.h
include/glow/Graph/Nodes.h
include/glow/Importer/CommonOperatorLoader.h
lib/Graph/Grad.cpp
lib/Graph/Graph.cpp
lib/Graph/Node.cpp
lib/Graph/Nodes.cpp
lib/IR/IRGen.cpp
lib/Importer/Caffe2.cpp
lib/Importer/ONNX.cpp
lib/Optimizer/GraphOptimizer.cpp
lib/Optimizer/Lower.cpp
lib/Quantization/Quantization.cpp
tests/unittests/OperatorTest.cpp

This is the followup from the https://github.com/pytorch/glow/pull/1224
Need to check OpenCL backend as well (looks good).

[cleanup] Remove default index on dims.

---

.travis.yml
cmake/modules/CoverageSupport.cmake
utils/install_protobuf.sh

Thanks @artemrakhov for helping and reproducing the original issue on Linux.

[travis] Support newer gcc.

---

.travis.yml

Relax a bit requirement on the compiler, g++5 should have required c++14 support.

[travis] Use g++5.

---

lib/Backends/CPU/CPUBackend.cpp
lib/Backends/CPU/CPUFunction.cpp
lib/Backends/CPU/CPUFunction.h
lib/Backends/Interpreter/Interpreter.cpp
lib/ExecutionEngine/ExecutionEngine.cpp
tests/unittests/BackendCorrectnessTest.cpp

I wish CI would warn me when I'd forgotten to do this.

[trivial] clang-format

---

include/glow/Backends/Backend.h
include/glow/Backends/CompiledFunction.h
include/glow/ExecutionEngine/ExecutionEngine.h
lib/Backends/CPU/CPUBackend.cpp
lib/Backends/CPU/CPUBackend.h
lib/Backends/CPU/CPUFunction.cpp
lib/Backends/CPU/CPUFunction.h
lib/Backends/CPU/Transforms.cpp
lib/Backends/Interpreter/Interpreter.cpp
lib/Backends/Interpreter/Interpreter.h
lib/Backends/Interpreter/InterpreterFunction.cpp
lib/Backends/Interpreter/InterpreterFunction.h
lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/OpenCL.h
lib/Backends/OpenCL/Transforms.cpp
lib/ExecutionEngine/ExecutionEngine.cpp
tests/unittests/BackendCorrectnessTest.cpp
tests/unittests/BackendTest.cpp
tests/unittests/BackendTestUtils.h

I think this is the light at the end of the tunnel for #1234

[backends] Finish CompiledFunction refactoring

---

include/glow/Backends/LayoutConverter.h
include/glow/Graph/Graph.h
include/glow/Graph/Nodes.h
include/glow/IR/IRBuilder.h
lib/Backends/CPU/LLVMIRGen.cpp
lib/Backends/CPU/libjit/libjit.cpp
lib/Backends/Interpreter/InterpreterNodes.cpp
lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/kernels.cl
lib/Graph/Graph.cpp
lib/Graph/Nodes.cpp
lib/IR/IRBuilder.cpp
lib/IR/IRGen.cpp
lib/Importer/Caffe2.cpp
lib/Importer/ONNX.cpp
lib/Optimizer/GraphOptimizer.cpp
lib/Optimizer/IROptimizer.cpp
lib/Quantization/Quantization.cpp
tests/unittests/OperatorTest.cpp
tests/unittests/basicIRTest.cpp
tests/unittests/graphTest.cpp
tools/ClassGen/Backends/CPU/CPUSpecificNodesVerification.h
tools/ClassGen/Backends/OpenCL/OpenCLSpecificInstrs.h
tools/ClassGen/Backends/OpenCL/OpenCLSpecificNodes.h
tools/ClassGen/Backends/OpenCL/OpenCLSpecificNodesVerification.h
tools/ClassGen/InstrGen.cpp
tools/ClassGen/NodeGen.cpp

For both AveragePool and MaxPool operators.

Non-square padding for Pooling

---

README.md

CodingStandards -> Coding Standards

Fix a typo in the readme. NFC.

---

include/glow/Graph/Node.h
lib/Graph/Graph.cpp

- Each node referring to another node N (i.e. having N as its input) should have a proper entry in the use-list of the node N.
- Each use from the use-list of a node N should refer to node N.

[graph-verifier] Add more checks for checking the consistency of Nodes use-lists

---

include/glow/Graph/Graph.h
include/glow/Graph/Node.h
include/glow/IR/IR.h
lib/Graph/Node.cpp
tests/unittests/graphTest.cpp

It is now possible to access the function that holds a node directly
from a node.

[GraphIR] Add a parent link to the nodes

---

tests/unittests/OperatorTest.cpp

Fix this test so that there are actual quantize and dequantize instructions executed, as they were optimized out previously.

[quantization][opencl]QuantizeAndDequantize

---

.gitmodules

That contain some onnxifi declarations as well as we could get the onnx.proto.
Also probably worth to consolidate submodules in ThirdParty folder (gtest for example).

[onnx] Add onnx as a submodule.

---

include/glow/Importer/ONNX.h
lib/Importer/ONNX.cpp

This PR is towards fixing https://github.com/pytorch/glow/issues/1190.
****
Currently, there is an issue with the way how the graph is loaded and the expectation of all input tensors to be initialized.
****
As part of the ONNXIFI interface, Glow would be required to test whether a specific model/node is supported by the backend.
There are two pieces involved:
1) Make sure that Glow supports particular ONNX graph
2) Make sure that specific backend supports operators from the graph
This PR makes checking (1) easier. Note, as part of the ONNXIFI interface there will be calls on the compatibility of the graph and backend. The graph is represented as a pointer to serialized proto + size.
For the testing, as of now, I made sure that the ONNX loader works fine as part of the ImageClassifier.

[onnx] Make ONNX loader more robust

---

include/glow/Base/Tensor.h
include/glow/Base/Type.h
lib/Backends/CPU/AllocationsInfo.cpp
lib/Backends/CPU/libjit/libjit.cpp
lib/Backends/OpenCL/OpenCL.cpp
lib/Base/Tensor.cpp
lib/Base/Type.cpp
tests/unittests/OperatorTest.cpp
tests/unittests/tensorsTest.cpp

Now Tensor with 0 dimensions is valid thing, representing a scalar. Size=1 for this Tensor, and you can access element[0]

[Operators] Allow Tensor to have 0 dimensions.

---

lib/Graph/Graph.cpp

Update the verifier code to check that at most one write happens
for each variable.
NFC.

[Function] Check that each variable is written at most once

---

lib/Backends/OpenCL/OpenCL.cpp

A minor change to enable profiling of buffer copies. It is useful to understand how much time is lost on copying the data around.

[opencl] Profile host->gpu, gpu->host and gpu->gpu buffer copies

---

examples/char-rnn.cpp
examples/cifar10.cpp
examples/mnist.cpp
examples/ptb.cpp
include/glow/ExecutionEngine/ExecutionEngine.h
tests/unittests/BackendTestUtils.cpp
tests/unittests/HyphenTest.cpp
tests/unittests/MLTest.cpp
tests/unittests/OperatorTest.cpp
tests/unittests/gradCheckTest.cpp
tests/unittests/graphGradTest.cpp

TrainingConfig should not be a part of the execution engine and this commit just moves it out. Once this commit lands I will continue to clean things in this area.

Remove TrainingConfig from the execution engine.

---

include/glow/Graph/Graph.h
lib/Graph/Grad.cpp
lib/Graph/Graph.cpp
lib/IR/IRGen.cpp
tests/unittests/OperatorTest.cpp
tools/ClassGen/NodeGen.cpp

Addresses https://github.com/pytorch/glow/issues/1318

Add count/axis to InsertTensorNode, and move Tile to use it instead of ConcatNode

---

docs/Quantization.md

…ader
Explain how we can use the different schema for quantization and
the main differences between them.
NFC.

[docs/Quantization] Document the quantization-schema option of the loader

---

include/glow/Quantization/Base/Base.h
include/glow/Quantization/Quantization.h
lib/Backends/CPU/LLVMIRGen.cpp
lib/Backends/Interpreter/InterpreterNodes.cpp
lib/Optimizer/Lower.cpp
lib/Quantization/Base/Base.cpp
lib/Quantization/Quantization.cpp
lib/Quantization/Serialization.cpp
tests/unittests/OperatorTest.cpp
tests/unittests/quantizationTest.cpp

Just simple replace of name_ by name where it's needed.

[trivial] Comply with the FB naming convention for public members.

---

CONTRIBUTING.md

I guess I should be in that list by now :).
NFC.

[CONTRIBUTING] Add myself as a maintainer

---

lib/Graph/Graph.cpp
lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphTest.cpp

- Rename getResultTypeOfLogicalOp into getResultTypeOfBooleanOp and improve the comments
- Add a test to check that Cmp nodes are created with proper output types

Minor cleanups addressing the code review feedback for #1352. NFC

---

include/glow/Base/Tensor.h
lib/Base/Tensor.cpp
lib/Graph/Nodes.cpp

[Tensor] move the init method from Variable to Tensor.

Start to untangle Variable: move init into Tensor

---

lib/Backends/CPU/BundleSaver.cpp
lib/Backends/CPU/GlowJIT.cpp
lib/Backends/CPU/GlowJIT.h

I meant to do this as part of #1357 but I must not have pushed to my development branch.  Oopsie.

[trivial] Define FACEBOOK_INTERNAL instead of FACEBOOK

---

lib/Onnxifi/onnxifiGlow.cpp

* Update onnx submodule SHA
* Change some types in the onnxifi interface
./tests/images/run.sh works fine.

[onnxifi] Update onnx submodule to pull in latest onnxifi breaking changes.

---

lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/OpenCL.h
lib/Backends/OpenCL/Transforms.cpp
lib/Backends/OpenCL/kernels_fwd_quantized_conv.cl

The OCLConvolutionInst works perfect with the resnet50 now. However i have to comment out ReLUNode in isOpSupported() in openCL.h, otherwise it would cause wrong results.

[quantization][opencl]: Support quantization for OCLConvolution

---

CMakeLists.txt
examples/CMakeLists.txt
lib/Backends/CPU/CMakeLists.txt
lib/Backends/Interpreter/CMakeLists.txt
lib/Base/CMakeLists.txt
lib/CMakeLists.txt
lib/CodeGen/CMakeLists.txt
lib/ExecutionEngine/CMakeLists.txt
lib/IR/CMakeLists.txt
lib/Optimizer/CMakeLists.txt
lib/Quantization/Base/CMakeLists.txt
lib/Quantization/CMakeLists.txt
lib/Support/CMakeLists.txt
tests/CMakeLists.txt
tools/loader/CMakeLists.txt

No reason for whitespace at BOF and some linters complain.

[trivial][cmake] Remove whitespace at beginning-of-file

---

tests/images/run.sh
utils/build_llvm.sh
utils/download_caffe2_models.sh
utils/download_onnx_models.sh
utils/encode_caffe2_protoc.sh
utils/format.sh
utils/license.sh
utils/s3put.sh

ShellCheck has a bunch of cool static analyses for bash scripts.  I went through and fixed a bunch of warnings from it.  Nothing terribly critical, unless someone was planning on adding a bunch of filenames with spaces to our repo :-p

ShellCheck fixes

---

include/glow/Importer/CommonOperatorLoader.h
lib/Importer/Caffe2.cpp
lib/Importer/ONNX.cpp

Each commit is pretty self explanatory.

Assorted Caffe2 importer support for seq2seq

---

lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/kernels.cl
tests/unittests/OperatorTest.cpp

Support matmul and tiled_matmul for quantization on opencl backend

[opencl][quantization]: Support matmul and tiled_matmul for quantization

---

lib/Importer/CMakeLists.txt

Thanks @compnerd for the cmake suggestions!

[cmake] Use copy_if_different for generated protobuf sources

---

include/glow/Importer/CommonOperatorLoader.h

With the Reshape operator, the output shape information can be passed as protobuf attribute, but also as input tensor. The protobuf attribute case was complete, but the management of the input input tensor giving the output shape was incomplete (shape dimension with value 0 and -1) was not handled.
This PR fixes this issue.

-1 and 0 values correctly handled by Reshape when the shape is given as a constant tensor

---

lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/kernels.cl
tests/unittests/OperatorTest.cpp

Support quantization for batchedAdd

[opencl][quantization]: Support quantization for batchedAdd

---

lib/Backends/CPU/Transforms.cpp

Extracted from https://github.com/pytorch/glow/pull/1393.

[NFC] Add a small comment in CPUBackend::transformPostLowering.

---

include/glow/Importer/CommonOperatorLoader.h
lib/Importer/Caffe2.cpp

All related to seq2seq support.

More assorted support in Caffe2/CommonOperatorLoader

---

tests/unittests/OperatorTest.cpp

Missing tests for https://github.com/pytorch/glow/pull/1416

Add tests for IndexTy for Div and Gather

---

tests/unittests/graphTest.cpp

… a reasonable way
Right now, we have no way to check the use list of each result individually.
This test illustrates how confusing it is and this issue is tracked in #1346.
NFC.

[unittest][Graph] Check that the use list of multi-res node behave in a reasonable way

---

lib/Onnxifi/Base.cpp
lib/Onnxifi/Base.h
lib/Onnxifi/onnxifiGlow.cpp

[onnxifi] Add support for the newly added onnxGetEventState onnxifi method.

---

tests/unittests/gradCheckTest.cpp

One day @opti-mix pointed out, that if we deleted body of `fwdConvolutionGradInst()`, the test would still pass. The problem was in net architecture: if Conv is not willing to learn, FC would take all work on itself, and FC's weights could learn required thing, so that resulting net as a whole would perform correctly. I changed the net and made sure that if we remove gradient's code, the test fails.

[GradientTests] Fix Convolution Gradient tests to be more strict.

---

lib/Importer/ONNX.cpp
tests/models/CMakeLists.txt
tests/models/onnxModels/simpleConv.onnxtxt
tests/unittests/CMakeLists.txt
tests/unittests/ImporterTestUtils.h
tests/unittests/onnxImporterTest.cpp

This PR is for ONNX model loader unittest:
-- the ONNX models under-testing live in ./tests/models/onnxModels/.;
-- to avoid adding binary files in our repo, all the ONNX models used for unittests should be in text format and end with .onnxtxt. (The script used to generate simple ONNX model will be in another PR).
-- to run the test unit alone, be sure to run it under the build directory, and run it like: ./tests/onnxImporterTest

[unittest] First unittest for ONNX importer

---

include/glow/Graph/Node.h
lib/Graph/Node.cpp
tests/unittests/graphTest.cpp

Prior to this patch the only way to get to the users of a node value
was to get through the users of the related node and filtered out
the uses of that did not match the result number.
This feature is now directly accessible through the NodeValueIterator
class and exposed via the new methods NodeValue::getUsers,
NodeValue::getNumUsers, and NodeValue::hasOneUse.
This fixes #1346.

[NodeValue] Provide methods to access the users of a NodeValue

---

lib/Graph/Nodes.cpp

As discussed in the https://github.com/pytorch/glow/issues/1452 we should check against the expectation of having the same quantization params for pooling nodes.

[verifier] Verify pooling nodes have the same element type and S,O for quantized types.

---

include/glow/Base/Type.h
tests/unittests/BackendCorrectnessTest.cpp

[Type] Do not allow a dimension of zero

---

lib/Importer/ONNX.cpp
tests/unittests/onnxImporterTest.cpp

We've got some ONNX models converted from TensorFlow where the convolution filter tensor is the output of a transpose (related to the conversion of depthwise convolution that is not supported by ONNX). This PR fixes Glow for this use-case.
I also removed the usage of the "kernel_shape" attribute in the ONNX loader since the kernel shape is given by the tensor itself.

Made convolution support the filter as node output (not only as constant tensor)

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

We've got some ONNX models with an 'identity' transpose. It was not automatically removed by Glow. This PR removes the transpose node in such a case.

[Optimizer] Remove single identity transpose from the graph

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

The first part of the rescale optimization proposed in #1481: combine rescale down with convolution node.

[graph-optimizer] Combine Rescale down with Convolution node

---

include/glow/Graph/Utils.h
lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp
tests/unittests/graphTest.cpp

The previous version of `optimizeArithmeticNodes()` and `simplifyNode()`, which used a combination of a worklist and recursion, made this error prone, and hard to debug/understand. I simplified it by moving to just a worklist.
The previous version also had a bug. There were extra adds and maxes in Resnet50 because `simplifyNodes()` canonicalizes by creating a new node, but the old node was not being replaced by the new node. I think it was assumed it would be done recursively up the stack, but it was not the case. The added test case shows displays such a pattern. The adds and maxes were essentially being split into `n` new nodes given `n` users.
These extra nodes would have been recombined during CSE, however the `optimizeArithmeticNodes()` pass comes after CSE. Even still, it would be …

[GraphOptimizer] Fix/simplify optimizeArithmeticNodes()

---

docs/AOT.md

Describe how the relocation-model option affects the generation of
the bundle for AOT. Also, add some details on the files that are
read for the network model.
NFC.

[docs] Document the relocation-model option for AOT

---

include/glow/Graph/Node.h
include/glow/Graph/Nodes.h
lib/Graph/Graph.cpp
lib/Graph/Node.cpp
lib/Graph/Nodes.cpp
tools/ClassGen/NodeBuilder.cpp

Prevent getInputName() from returning a dangling pointer

---

include/glow/Importer/ONNXIFILoader.h
lib/Importer/ONNXIFILoader.cpp
lib/Onnxifi/onnxifiGlow.cpp

Cover all operations from resnet50 in the `compatibility` call.
cc: @yinghai @Maratyszcza

[onnxifi] Support more operations.

---

PULL_REQUEST.md
PULL_REQUEST_TEMPLATE.md

*Description*:
* Create a PR template for the description of the PR which is used on each pull request
* Github will automatically insert the content of PULL_REQUEST_TEMPLATE.md into description
* Clarify requirements for each section
*Testing*: no tests are required

[docs] Add PR template and clarify requirements for the PR description.

---

lib/Backends/Interpreter/InterpreterNodes.cpp

*Description*:
Before this commit the 'copy' method was listed under the 'convolution'
section. This commit moves the 'copy' method and adds a few labels. I
found this when I was reading the reference implementation for our
convolutions and decided to clean it up.
*Testing*: Ran the tests locally. 
*Documentation*: This commit just adds a comment.

[cleanup] Update the comments and move a function. NFC.

---

docs/NewBackendSpecificNode.md

*Description*:
add document on adding a new target specific node 
Try to fix #1550

add document on adding a new target specific node 

---

include/glow/ExecutionEngine/ExecutionEngine.h

*Description*: Update the method comments. They were horribly outdated. 
*Testing*: None.
*Documentation*: This is a doc change.

Update two method comments. NFC.

---

lib/Backends/CPU/libjit/libjit.cpp
tests/unittests/graphTest.cpp

*Description*:
Run clang-format on the code base.
*Testing*: None/Trivial

[fix-format] Fix format code base.

---

lib/Backends/CPU/AllocationsInfo.cpp
lib/Backends/CPU/AllocationsInfo.h
lib/Backends/CPU/BundleSaver.cpp
lib/Backends/CPU/CPUBackend.cpp
lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/OpenCL.h
tests/unittests/BackendTest.cpp

*Description*: This PR adds PH execution engine support for the CPU and OpenCL backends. 
This PR depends on #1597 (and includes it). #1597 needs to land before this PR is reviewed.

 [Placeholder] Teach the OCL and CPU backends to handle Placeholders.

---

include/glow/Backends/Backend.h
lib/Backends/CPU/AllocationsInfo.h

*Description*: Fix two doxygen comments.
*Testing*: none
*Documentation*: This is a documentation fix.

Fix two doxygen comments.

---

lib/IR/GraphScheduler.cpp
lib/IR/GraphScheduler.h

This commit splits the code in GraphScheduler.cpp into separate
header and source files. This will allow scheduler unit tests to be
added in future commits.
**Testing**
All existing unit tests pass.

[GraphScheduler] Split scheduler into .h and .cpp

---

docs/IR.md

*Description*: Add a short paragraph that describes Placeholder nodes and a reference to the migration plan.
*Testing*: None.
*Documentation*: This is a documentation change.

[doc] Document the Placeholder nodes.

---

README.md

Updated the clone instructions in our README to be more explicit.

[docs] Add instructions for cloning glow

---

tests/unittests/MLTest.cpp

*Description*: Remove the use of variables from a few tests.
*Testing*: This commit updates some tests. 

[Placeholder] Remove the use of variables from a few tests.

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

*Description*: Add optimization to merge ReluNode(Rescale(in)) -> ReluNode(in). Similar to others that exist for the Arithmetic nodes.
*Testing*: Added unit test.

[GraphOptimizer] Combine Rescale down with Relu node

---

docs/IR.md

*Description*:
Reflect the design goal we have in mind for predication:
Predication is an optimization and if it doesn't help the performance,
the predicates can be ignored.
NFC.
*Testing*: N/A
*Documentation*: Document our intent regarding predication.

[docs][IR] Update the section about predication support

---

tests/unittests/MLTest.cpp

*Description*: Update some tests to use Placeholders.
*Testing*: This commit updates a few tests to use the new API.
*Documentation*: none.

[Placeholder] Update some tests to use Placeholders.

---

tests/unittests/GemmTest.cpp

*Description*:
Update placeholder usage in GemmTest.
*Testing*:
Existing unit tests.
N/A

[Placeholder] Use Placeholders in GemmTest.

---

tests/unittests/graphSchedulerTest.cpp

*Description*:
Use createPlaceholder in graphSchedulerTest.
*Testing*:
Existing unit tests.
N/A

[Placeholder] Use Placeholders in graphSchedulerTest.

---

tests/unittests/graphGradTest.cpp

*Description*:
Fix placeholders in graphGradTest.
*Testing*:
Existing unit tests
N/A

[Placeholder] Use Placeholders in graphGradTest.

---

include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
tests/unittests/graphOptzTest.cpp

*Description*: Start moving graphOptzTest to placeholders & context.
*Testing*: These tests.

[Placeholder] Convert some graphOptz tests to placeholders

---

include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
tests/unittests/graphOptzTest.cpp

*Description*: In summary.
*Testing*: N/A

[Placeholders] Finish migration of GraphOptz

---

examples/char-rnn.cpp
include/glow/Graph/Graph.h
lib/Graph/Graph.cpp

**Description**:
Replace vars by placeholders in char-rnn.
**Testing**:
Running ./bin/char-rnn < input
**Documentation**:
N/A

[Placeholder] Replace vars by placeholders in char-rnn.

---

examples/ptb.cpp

*Description*:
Replace vars with placeholders in ptb test example.
*Testing*:
Run ./bin/ptb
```
Perplexity scores in copy-pastable format:
/// Iteration 1: 105.4579
/// Iteration 2: 82.3274
/// Iteration 4: 70.8094
/// Iteration 6: 63.8546
/// Iteration 8: 58.4330
/// Iteration 10: 53.7943
/// Iteration 12: 49.7214
/// Iteration 14: 46.1715
/// Iteration 16: 43.1474
/// Iteration 18: 40.5605
/// Iteration 20: 38.2837
Note, that small 1E-4 error is considered acceptable and may be coming from fast math optimizations.
```
N/A

[Placeholder] Replace vars with placeholders in ptb test example.

---

examples/cifar10.cpp

*Description*:
Replace vars by placeholders in cifar10 test.
*Testing*:
./bin/cifar10 run.
```
rdzhabarov-mbp:release_build rdzhabarov$ ./bin/cifar10 
Loading the CIFAR-10 database.
Training.
Training - iteration #0
0) Expected: frog Got: deer
1) Expected: truck Got: ship
2) Expected: truck Got: ship
3) Expected: deer Got: horse
4) Expected: automobile Got: ship
5) Expected: automobile Got: deer
6) Expected: bird Got: airplane
7) Expected: horse Got: horse
Iteration #0 score: 10%
===-------------------------------------------------------------------------===
Miscellaneous Ungrouped Timers
===-------------------------------------------------------------------------===
---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
23.0709 (100.0%)   0.0543 (100.0%) …
```

[Placeholder] Replace vars by placeholders in cifar10 test.

---

examples/fr2en.cpp

*Description*:
Replace vars by placeholders in fr2en.
*Testing*:
Running ./bin/fr2en
N/A

[Placeholder] Replace vars by placeholders in fr2en.

---

tests/unittests/BackendTest.cpp

This commit replaces all calls to `createVariable` in `BackendTest.cpp`
with `createPlaceholder` as part of the migration from `Variables` to
`Placeholders`.
**Testing**
All unit tests, including `BackendTest.cpp`, still pass.
```
meghanl-mbp:build_DEBUG meghanl$ ./tests/backendTest 
[==========] Running 15 tests from 5 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from Interpreter
[ RUN      ] Interpreter.NotImplementedSave
[       OK ] Interpreter.NotImplementedSave (3 ms)
[ RUN      ] Interpreter.profileQuantizationForANetwork
[       OK ] Interpreter.profileQuantizationForANetwork (3 ms)
[----------] 2 tests from Interpreter (6 ms total)
[----------] 1 test from Context
[ RUN      ] Context.basicContextTest
[       OK ] …
```

[Placeholder] Replace createVariable with createPlaceholder in BackendTest.cpp

---

tests/unittests/graphGradTest.cpp

This commit replaces `Variables` with `Placeholders` in
`graphGradtest.cpp` as part of the overall migration from `Variables` to
`Placeholders`.
**Testing**
```
[0/1] Running tests...
Test project /Users/meghanl/fbsource/glow/build_DEBUG
Start  1: partitionTest
1/21 Test  #1: partitionTest ....................   Passed    0.04 sec
Start  2: tensorsTest
2/21 Test  #2: tensorsTest ......................   Passed    0.37 sec
Start  3: gradCheckTest
3/21 Test  #3: gradCheckTest ....................   Passed    4.22 sec
Start  4: IROptTest
4/21 Test  #4: IROptTest ........................   Passed    0.01 sec
Start  5: basicIRTest
5/21 Test  #5: basicIRTest ......................   Passed    0.00 sec
Start  6: backendTest
6/21 Test  #6: backendTest …
```

[Placeholder] Migrate graphGradTest to Placeholders

---

tests/unittests/OperatorTest.cpp

*Description*:
Replace vars with placeholders in the operator test (part 1).
*Testing*:
Existing tests.
N/A

[Placeholder] Replace vars with placeholders in operator test (part 1).

---

tests/unittests/graphTest.cpp

*Description*: Converts most of graphTest to placeholders.  There are two tests that mostly exist to exercise the Variable API, that I've left alone.  We can deal with them when we go to change that API completely.

[Placeholders] Convert graphTest

---

tests/unittests/OperatorTest.cpp

*Description*:
Replace vars by placeholders in operatorTest (part 2)
*Testing*:
Running unit tests.
N/A

[Placeholder] Replace vars by placeholders in operatorTest (part 2)

---

tests/unittests/BackendTestUtils.cpp

This commit replaces uses of `createVariable` with `createPlaceholder`
in `BackendTestUtils.cpp` as part of the overall migration from
`Variables` to `Placeholders`.
**Testing**

[Placeholder] Migrate BackendTestUtils.cpp

---

tests/unittests/OperatorTest.cpp

*Description*:
Replace vars by placeholders in operatorTest
*Testing*:
Existing unit tests
N/A

[Placeholder] Replace vars by placeholders in operatorTest (part 3)

---

README.md

*Description*: updated README.md to include libpng-dev package to apt-get install instructions
*Testing*: None -- documentation change only
*Documentation*: README.md updated
* Fixes #1703

[Documentation] Updated Ubuntu section of README.md to include libpng-dev

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

*Description*:
GLOW uses NHWC format for convolutions and this leads to appearance of a transpose before matmuls in some classification networks if NCHW is used as input layout. This patch adds optimization to get rid of such transpose by merging it into matmul and reordering matmul's weights.
*Testing*:
Added a test in graphOptzTest.
Verified with internal classification net.
N/A

[GraphOptimizer] Optimization to merge Transpose into MatMul

---

tests/unittests/quantizationTest.cpp

[Placeholders] Use convertPlaceholdersToConstants in quantizationTest

---

lib/Graph/Grad.cpp
lib/Graph/Graph.cpp
tests/unittests/gradCheckTest.cpp

*Description*:  Fix the differentiation of batchNormalization nodes.
*Testing*: Updated the unit test. 
#1334

[Placeholder] Fix the differentiation of batchNormalization nodes.

---

examples/cifar10.cpp
include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
tests/unittests/BackendTest.cpp
tests/unittests/BackendTestUtils.cpp
tests/unittests/MLTest.cpp
tests/unittests/OperatorTest.cpp
tests/unittests/gradCheckTest.cpp
tests/unittests/graphGradTest.cpp
tests/unittests/graphTest.cpp

*Description*: Replace everywhere we create an FC with the placeholder version.
*Testing*: `ninja check`, `ninja all`

[Placeholders] Always createFullyConnected with placeholders

---

examples/cifar10.cpp
include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
tests/unittests/BackendTest.cpp
tests/unittests/BackendTestUtils.cpp
tests/unittests/MLTest.cpp
tests/unittests/gradCheckTest.cpp
tests/unittests/graphGradTest.cpp
tests/unittests/graphOptzTest.cpp

This is stacked on top of the FC PR, please ignore that commit when reviewing.

 [Placeholders] Convert remaining createConv to PH

---

include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
lib/Importer/Caffe2.cpp
tests/models/caffe2Models/clip_op_default_net.pbtxt
tests/models/caffe2Models/clip_op_net.pbtxt
tests/unittests/caffe2ImporterTest.cpp

*Description*: add new operator "Clip" in caffe2 model importer
also add unittest for the new operator
*Testing*: ninja all && ninja test
[Optional Fixes #issue] resolve #1706

[importer]  add Clip operator for caffe2 model importer

---

CMakeLists.txt
examples/char-rnn.cpp
examples/cifar10.cpp
examples/fr2en.cpp
examples/mnist.cpp
examples/ptb.cpp
lib/Backends/CPU/BundleSaver.cpp
lib/Backends/CPU/CMakeLists.txt
lib/Backends/CPU/GlowJIT.cpp
lib/Backends/CPU/GlowJIT.h
lib/Backends/CPU/LLVMIRGen.cpp
tools/loader/Loader.cpp

*Description*:
Add LLVM 7 support.
based on https://github.com/pytorch/glow/pull/1677
@compnerd do you mind stamp this. I fixed all compilation errors.
*Testing*:
CI tests
N/A

[llvm7] Add support for LLVM 7

---

lib/Importer/ONNXIFILoader.cpp

*Description*:
Add more operators to be checked in compatibility call.
*Testing*:
Manual for now. We are working on test driver support.
N/A
cc: @yinghai @bertmaher

[onnxifi] Add support to more operators for compatibility call.

---

include/glow/Graph/Node.h
lib/Graph/Node.cpp
lib/Optimizer/Lower.cpp

NFC. Some cleanup as suggested by @rdzhabarov in https://github.com/pytorch/glow/pull/1654

Add static/const to lower* functions

---

examples/mnist.cpp
lib/Backends/Interpreter/InterpreterNodes.cpp
lib/ExecutionEngine/ExecutionEngine.cpp
tests/unittests/CMakeLists.txt

*Description*: FB's internal linter flagged a few things.  I don't think any of the shadowing was causing real problems though, it's just nicer not to have it.

Fix some lint

---

include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
lib/Importer/Caffe2.cpp
lib/Importer/ONNX.cpp
tests/unittests/graphOptzTest.cpp

[Placeholders] Migrate batchnorm

---

.travis.yml

*Description*:
Exit with 1 on failure from the `ninja test`.
*Testing*:
CI
N/A
@jfix71 this should be on a safe side.

[travis] Add exit 1 on test failure

---

examples/char-rnn.cpp
lib/Backends/CPU/CMakeLists.txt
lib/Backends/CPU/CommandLine.cpp
lib/Backends/CPU/FunctionSpecializer.cpp
lib/Backends/CPU/GlowJIT.cpp
lib/Backends/CPU/LLVMIRGen.cpp

*Description*:
Fix SIOF for RNG and category param.
*Testing*:
CI tests
N/A
Fixes https://github.com/pytorch/glow/issues/1765

[fix SIOF] Fix two SIOFs

---

docs/Backends.md

This document should make it easier and more clear what is necessary for a backend to implement and what each API should be used for.

[Backends.md] Add documentation on APIs for backends

---

lib/Importer/ONNX.cpp

*Description*: We're using llvm_unreachable to handle input validation, and we need to raise recoverable errors instead.
*Testing*: #1736 test plan, but with test_averagepool_2d_same_lower
Partially addresses #1755

[ONNX] Raise error but don't die if auto_pads != VALID

---

tools/loader/ImageClassifier.cpp
tools/loader/Loader.cpp
tools/loader/Loader.h
tools/loader/ModelRunner.cpp
tools/loader/TextTranslator.cpp

*Description*:
[PH] Refactor the context definition outside of the loader. NFC. This is a cleanup commit in preparation for the removal of variables. This commit removes a global variable. 
*Testing*: Ran ninja test and ./test/images/run.sh
*Documentation*: none

[PH] Refactor the context definition outside of the loader. NFC.

---

include/glow/Importer/CommonOperatorLoader.h

*Description*: Glow requires static shapes, so yield an error if non-constant reshape is given.
*Testing*: onnx test case, test_reshape_reordered_dims
See #1755

[importer] Report error if reshape given with non-constant shape input

---

lib/Importer/ONNX.cpp
lib/Optimizer/GraphOptimizer.cpp

*Description*:
Minor cleanups to make Lint happy.
*Testing*:
CI
N/A

[trivial] Fixing linter warnings

---

tests/unittests/OperatorTest.cpp

Making sure transpose works with the interpreter.
The underlying implementation uses Tensor::transpose which already support FP16. Thus NFC.

[Backend][Interpreter] Add a test case for FP16 transpose. NFC

---

lib/Backends/Interpreter/InterpreterFunction.h
lib/Backends/Interpreter/InterpreterNodes.cpp
tests/unittests/OperatorTest.cpp

*Description*
This PR refactors implementation of the avg pool inst and adds the right dispatch code to run this it in half precision.
*Testing*
Related to #1329.

[Backend][Interpreter] Implement fp16 avg pool

---

lib/Backends/Interpreter/InterpreterFunction.h
lib/Backends/Interpreter/InterpreterNodes.cpp
tests/unittests/OperatorTest.cpp

*Description*
This commit templatizes the implementation of MatMul and adds the
dispatch code to execute the single precision or half precision
variant for floating point types.
*Testing*

[Backend][Interpreter] Implement FP16 MatMul

---

lib/Importer/Caffe2ModelLoader.cpp
lib/Onnxifi/Base.cpp
tests/unittests/caffe2ImporterTest.cpp
tests/unittests/onnxImporterTest.cpp

[format] Run ./utils/format.sh fix

---

examples/char-rnn.cpp
examples/cifar10.cpp
examples/fr2en.cpp
examples/mnist.cpp
examples/ptb.cpp
include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
tests/unittests/BackendTest.cpp
tests/unittests/BackendTestUtils.cpp
tests/unittests/GemmTest.cpp
tests/unittests/HyphenTest.cpp
tests/unittests/MLTest.cpp
tests/unittests/OperatorTest.cpp
tests/unittests/gradCheckTest.cpp
tests/unittests/graphGradTest.cpp
tests/unittests/graphOptzTest.cpp
tests/unittests/graphTest.cpp
tests/unittests/partitionTest.cpp
tests/unittests/quantizationTest.cpp

*Description*:
[cleanup] Simplify the SaveNode builder. NFC.
*Documentation*: none

[cleanup] Simplify the SaveNode builder. NFC.

---

tests/unittests/BackendTestUtils.h

Forgot to remove these in https://github.com/pytorch/glow/pull/1804

[BackendTestUtils.h | cleanup] Remove deleted functions' declarations

---

docs/IR.md

*Description*:
[doc] Update the docs and mention constants and placeholders.
*Testing*: NFC.
*Documentation*: This is a doc change.
#1334

[doc] Update the docs and mention constants and placeholders.

---

tools/ClassGen/InstrBuilder.cpp

*Description*:
Support autoIRGen for nodes with multiple results in InstrGen. 
This functionality may be needed for some of our backends.
*Testing*:
ninja test

Support autoIRGen for nodes with multiple results in InstrGen

---

lib/Graph/Graph.cpp
tests/unittests/graphTest.cpp

*Description*: Constants should never be written to, so I'm adding a verification pass checking this.
*Testing*: Added a test.

[Graph] Verify that Constants are never written to

---

utils/format.sh

*Description*:
Output what was changed after running: `format.sh check`
*Testing*:
Tested locally
N/A

[trivial] Make diff output better

---

lib/Backends/CPU/GlowJIT.cpp

Explain why we need to change the behaviour of the symbol lookup from the JIT
subsystem.  NFC.
*Description*:
*Testing*:

CPUBackend: add a comment for the symbol lookup

---

.circleci/config.yml

*Description*:
Just make circleci not fail.
*Testing*:
CI
N/A

[Trivial] Minimal configuration to make CircleCI happy

---

tools/loader/ImageClassifier.cpp

*Description*: It's useful to see all top K labels along with their probabilities.
*Testing*: Ran image-classifier on Resnet50 with different topk options
*Documentation*: Added command-line option `-topk` with description.
Example output:
```
File: tests/images/imagenet/cat_285.png
Label-K1: 285 (probability: 0.5823)
Label-K2: 281 (probability: 0.3601)
Label-K3: 282 (probability: 0.0456)
```

[ImageClassifier] Add option for printing the top-k labels

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

*Description*: On Resnet50, many BatchNormalizationNodes were no longer being merged with the Convolution node before it. This commit fixes the problem.
It occurred because [this commit](https://github.com/pytorch/glow/commit/bd18db777cb775672ab47d626c019e979ac9edc8) removed trainable from Variables. This means that constant deduplication, which did not apply to trainable variables, now does apply and is merging 7 biases which are the same. Instead of giving up when the filter/bias have multiple uses, instead duplicate the filter/bias and allow the optimization to proceed.
*Testing*: Added a unit test

[GraphOptimizer] Fix the Conv-BatchNorm optimization

---

include/glow/Importer/CommonOperatorLoader.h
include/glow/Importer/ProtobufLoader.h
lib/Importer/Caffe2ModelLoader.cpp
lib/Importer/ONNXModelLoader.cpp
lib/Importer/ProtobufLoader.cpp

*Description*:
NFC, cleaning up entries of vars in loaders.
*Testing*:
trivial, unit tests.
N/A

[Placeholders/Constants] Remove last entry of variables from loaders.

---

lib/Optimizer/GraphOptimizer.cpp

*Description*:
This is a cleanup rather than a functional change.
Transpose and Reshape nodes may prevent other optimizations from triggering (e.g. BatchNorm + Convolution merge, Transpose + MatMul merge). As optimizeTranspose and optimizeReshape do not depend on other optimizations, it makes sense to do them first, so that Transposes and Reshapes would be optimized out and let other optimizations work.
I did some optimization re-ordering related to reshape/transpose in my previous PRs (#1680, #1782). This is just a cleaner way to handle it. I think it's better to put the optimizations in the beginning and have an explicit comment explaining why we are doing this, rather than have implicit optimization ordering.
*Testing*:
No new tests, since it's just a clean up.
N/A

[GraphOptimizer] Do transpose and reshape optimizations first

---

lib/Importer/ONNXIFIModelLoader.cpp
lib/Importer/ONNXModelLoader.cpp
tests/models/onnxModels/clip.onnxtxt
tests/unittests/onnxImporterTest.cpp

*Description*:
Add support for ONNX Clip operator and wire ONNXIFI support.
*Testing*:
Added test
N/A
Fixes https://github.com/pytorch/glow/issues/1706

[onnxifi] Add support for clip operator.

---

lib/Importer/ONNXIFIModelLoader.cpp
lib/Importer/ONNXModelLoader.cpp
tests/models/onnxModels/dot_product.onnxtxt
tests/unittests/onnxImporterTest.cpp

*Description*:
Add DotProduct support to ONNXIFI backend.
*Testing*:
added unit test.
N/A

[onnxifi] Add DotProduct to ONNX parser.

---

lib/Onnxifi/Base.h
lib/Onnxifi/ThreadPool.cpp
lib/Onnxifi/onnxifiGlow.cpp

*Description*:
Some cleanups + adding a single thread for an interpreter and multiple threads for CPU backend.
*Testing*:
Onnxifi tests
N/A

[onnxifi] Some cleanups and supply number of workers.

---

include/glow/Graph/Graph.h
lib/Backends/Interpreter/InterpreterNodes.cpp
lib/Graph/Graph.cpp
lib/Graph/Nodes.cpp
tests/unittests/OperatorTest.cpp
tools/ClassGen/InstrGen.cpp
tools/ClassGen/NodeGen.cpp

*Description*: That's it.
*Testing*: New operatorTest.
*Documentation*: Docstrings
Partial fix for #1885

[graph] Implement LengthsToRanges (interp only)

---

include/glow/Importer/CommonOperatorLoader.h
tests/models/onnxModels/sum1.onnxtxt
tests/unittests/onnxImporterTest.cpp

*Description*:
We have seen cases where we have sum with 1 input. It's pretty trivial to support that. 
*Testing*:
unittest

[Import] Support Sum with 1 Input

---

lib/Backends/CPU/LLVMIRGen.cpp
lib/Backends/CPU/libjit/libjit.cpp
tests/unittests/OperatorTest.cpp

*Description*: That's it
*Testing*: Enable CPU backend for operatorTest
Fixes #1885

[cpu] Implement LengthsToRanges

---

lib/Graph/Nodes.cpp
lib/Importer/Caffe2ModelLoader.cpp
tests/models/caffe2Models/lengths_to_ranges.pbtxt
tests/models/caffe2Models/lengths_to_ranges_init_net.pbtxt
tests/unittests/caffe2ImporterTest.cpp

*Description*: N/A
*Testing*: New caffe2ImporterTest
Partial fix for #1885
Depends on #1891, please review only the top commit.

 [caffe2] Import LengthsToRanges

---

lib/Importer/ONNXIFIModelLoader.cpp
lib/Importer/ONNXModelLoader.cpp
tests/models/onnxModels/lengths_to_ranges.onnxtxt
tests/unittests/onnxImporterTest.cpp

*Description*: that's it
*Testing*: new onnxImporterTest
Another piece of #1885

[onnx importer] Import LengthsToRanges

---

lib/Importer/Caffe2ModelLoader.cpp
tests/models/caffe2Models/NCHW2NHWC_predict_net.pbtxt
tests/unittests/caffe2ImporterTest.cpp

*Description*:
https://caffe2.ai/docs/operators-catalogue.html#nchw2nhwc
*Testing*:
Test added.

[Caffe2 Importer] Add NCHW2NHWC Caffe2 op.

---

CMakeLists.txt
examples/CMakeLists.txt
lib/CodeGen/CMakeLists.txt
lib/Graph/CMakeLists.txt
lib/IR/CMakeLists.txt
lib/Onnxifi/CMakeLists.txt
lib/Quantization/CMakeLists.txt
lib/Support/CMakeLists.txt
tests/unittests/CMakeLists.txt
tools/loader/CMakeLists.txt

This reverts commit efba7c45ed4c9e94ca63af63952827b4a224c307.

Revert "[cmake] Fix a bunch of dependencies so BUILD_SHARED_LIBS work"

---

tools/loader/ImageClassifier.cpp

*Description*: Allow for streaming in filenames for inference, allowing for inference to be run multiple times after compiling once. This is done by passing `-` as the input image filenames command line parameter; then filenames are passed via stdin for each next batch of images to infer. The program is not compiled until the first set of filenames is provided. The first set of filenames passed is used to set the input shape for the compiled model, meaning that same batch size must be used for future inferences.
*Testing*: Manually tested using different input shapes
*Documentation*: Added/updated command line option description.

[ImageClassifier] Add option for streaming input filenames

---

include/glow/Graph/Graph.h
include/glow/Importer/CommonOperatorLoader.h
lib/Backends/Interpreter/InterpreterFunction.h
lib/Backends/Interpreter/InterpreterNodes.cpp
lib/Graph/Graph.cpp
lib/Graph/Nodes.cpp
tests/unittests/OperatorTest.cpp
tools/ClassGen/InstrGen.cpp
tools/ClassGen/NodeGen.cpp

*Description*:
Add support of BatchOneHot operator from Caffe2.
*Testing*:
`ninja test`
Specs & impl for new op can be found here:
https://caffe2.ai/docs/operators-catalogue.html#batchonehot

[Operator] Support BatchOneHot

---

include/glow/Support/Float16.h
tests/unittests/float16Test.cpp

*Description*
Add operator+=, -=, <= for float16
*Testing*

[Float16] Add a few operators that are needed for the interpreter support

---

include/glow/ExecutionEngine/ExecutionEngine.h

*Description*:
This getter can be useful e.g. for writing tests, when you want to inspect the compiled function.
*Testing*:
ninja test

Add a getter ExecutionEngine::getCompiledFunction

---

docs/ModelLoader.md
utils/export_onnx_model.py

*Description*: running an ONNX model exported from PyTorch pretrained model
*Testing*:

running an ONNX model exported from PyTorch pretrained model

---

lib/Importer/ONNXIFIModelLoader.cpp
lib/Importer/ONNXModelLoader.cpp
tests/models/onnxModels/FCTransposed.onnxtxt
tests/unittests/onnxImporterTest.cpp

*Description*:
Add ONNX/ONNXIFI support for FCTransposed.
Modeled based on the C2 loader.
*Testing*:
Added unit test for loader.
N/A

[ONNXLoader] Handle FCTransposed op type.

---

docs/Lexicon.md

It is normal to have certain acryonyms used during conversations about the
technical matter.  Keep a reference to the common terms to allow others to
decipher what is being conveyed.
*Description*:
*Testing*:

docs: introduce a dictionary of lexicon

---

docs/Lexicon.md

*Description*:
These come up quite commonly in conversation.  Add a handful of them to the
lexicon.
*Testing*:
n/a
This PR is to add doc.

[docs] add some ML specific terminology

---

lib/Onnxifi/Base.cpp
lib/Onnxifi/Base.h
lib/Onnxifi/onnxifiGlow.cpp

*Description*:
This patch should allow handling of concurrent execution of inferences on the caller side.
On the Glow side, we limit concurrency by a number of threads in a thread pool per backend.
This PR should allow running multithreaded C2 execution on a single Glow thread.
*Testing*:
onnxifi integration test
N/A

[onnxifi] Throttle input concurrency with fixed number of threads on Glow side, configured per backend.

---

lib/Backends/Interpreter/InterpreterFunction.h
lib/Backends/Interpreter/InterpreterNodes.cpp

*Description*:
This PR implements the missing pieces for fp16 support in the interpreter to support all the operators used in inference.
*Testing*:
TODO, thus WIP.

[WIP]Full fp16 interpreter

---

docs/Lexicon.md

*Description*:
* define DMA
* fix header for "C" to be same size as other headers
*Testing*:
* look at markdown rendering in https://github.com/jackm321/glow/blob/update_lexicon/docs/Lexicon.md
* update docs/Lexicon.md

[docs] Update docs/Lexicon.md

---

lib/Backends/CPU/LLVMIRGen.cpp
lib/Backends/CPU/libjit/libjit.cpp
tests/unittests/OperatorTest.cpp

*Description*: What it says on the tin.
*Testing*: Enable SLS and SLWS operator tests

[cpu] Implement SparseLengthsWeightedSum

---

docs/Lexicon.md

[trivial] Add RAUW (Replace All Uses With) to the lexicon

---

include/glow/Importer/CommonOperatorLoader.h
lib/Importer/Caffe2ModelLoader.cpp
lib/Importer/ONNXIFIModelLoader.cpp

*Description*:
The import process for the two ops are the same for ONNX and Caffe2. 
*Testing*:
Unit test
n/a

Unifying import of SparseLengthsSum and SparseLengthsWeightedSum

---

CODE_OF_CONDUCT.md

*Description*:
See title.
*Testing*:
n/a
updated code of conduct doc with the proper link.
Following up on https://github.com/pytorch/glow/pull/1954

[trivial][docs] Update the link to code of conduct.

---

include/glow/Base/IO.h
lib/Base/CMakeLists.txt
lib/Base/IO.cpp
tests/unittests/CMakeLists.txt
tests/unittests/UtilsTest.cpp

*Description*: Some very rough functions for doing binary I/O on Tensors.
*Testing*: New UtilsTest
*Documentation*: Doxygen!
Part of #1976

[base] Utility functions for reading/writing binary tensor blobs

---

lib/Backends/CPU/LLVMIRGen.cpp
lib/Backends/CPU/libjit/libjit.cpp
tests/unittests/quantizationTest.cpp

*Description*:
Added quantization profiling to CPU backend. Basically ported from interpreter engine.
*Testing*:
Expanded Quantization test in unittests.
N/A

[Quantization] Enabling quantization profiling in CPU bakend.

---

tools/loader/ImageClassifier.cpp

*Description*: Convert the input every time we get new inputs, and only after the graph is compiled. Do not convert the output back to fp32 anymore, as it forces making extra copies unnecessarily, and was incorrectly resetting the type of the SM tensor in the context.
*Testing*: Manually tested running in streaming mode with `-convert-inout-to-fp16`
Fixes https://github.com/pytorch/glow/issues/1992

[ImageClassifier] Fix convert-inout-to-fp16

---

include/glow/Importer/CommonOperatorLoader.h
lib/Importer/Caffe2ModelLoader.cpp
lib/Importer/ONNXIFIModelLoader.cpp
tests/models/onnxModels/batch_matmul.onnxtxt
tests/unittests/onnxImporterTest.cpp

*Description*:
Import  BatchMatMul to ONNX
*Testing*:
unittest
Fixes https://github.com/pytorch/glow/issues/1970

Import BatchMatMul to ONNX

---

lib/Backends/CPU/GlowJIT.cpp

*Testing*:
ninja test
manual run of resnet50 with `-cpu -dump-jit-symbol-info`

[jit] Restore the functionality for dumping JIT symbols that got lost during the LLVM6 to LLVM7 transition

---

lib/Backends/CPU/LLVMIRGen.cpp
lib/Backends/CPU/libjit/libjit.cpp
lib/Quantization/Base/Profile.cpp
tests/unittests/quantizationTest.cpp

*Description*:
* Init histogram with 0
* Unused var warning
* OpenCL quantization test fix
*Testing*:
CI + unit tests with open CL
n/a

[fixes] Various fixes: openCL test, init histogram with 0.

---

lib/Importer/ONNXModelLoader.cpp

*Description*:
Fix handle type.
*Testing*:
unit tests
n/a
cc: @yinghai

[fix] Fix types for handles.

---

tests/images/run.sh
tools/loader/ImageClassifier.cpp

*Description*: RBG values go from 0 to 255, not 256.
*Testing*: `run.sh`

[ImageClassifier] Change 0to256 to 0to255

---

.circleci/config.yml

Bump docker image to 230 in circle CI

---

include/glow/Importer/CommonOperatorLoader.h
lib/Importer/Caffe2ModelLoader.cpp
lib/Importer/ONNXModelLoader.cpp

*Description*:
Move Clip and SparseToDense to common parsing
*Testing*:
existing unit tests
n/a
cc: @yinghai

[common loader] Move Clip and SparseToDense to common parsing.

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

*Description*: Found this in quantized en2gr, similar to other optimizations we already have.
*Testing*: Added unit test

[GraphOptimizer] Fuse RescaleNodes down into MatMulNodes

---

CMakeLists.txt
examples/bundles/CMakeLists.txt

*Description*:
Do not build bundles by default. It takes 40min on CI.
*Testing*:
CI
n/a

[build] Do not build bundles by default. It takes 40min on CI.

---

include/glow/IR/IRBuilder.h
lib/IR/IRBuilder.cpp

*Description*: create quantize type weight
*Testing*:

[IRBuilder] support create weight with quantize type

---

include/glow/Importer/CommonOperatorLoader.h
lib/Importer/Caffe2ModelLoader.cpp
lib/Importer/ONNXIFIModelLoader.cpp
tests/models/onnxModels/gather.onnxtxt
tests/unittests/onnxImporterTest.cpp

*Description*:
Add common support for Gather/BatchGather
*Testing*:
Unit tests
n/a
cc: @yinghai

[onnx loaders] Support Gather ops in onnxifi loader.

---

README.md

*Description*: [Readme] add a link to the roadmap page.
*Testing*: None
*Documentation*: This PR updates the doc.

[Readme] add a link to the roadmap page.

---

.circleci/build.sh
CMakeLists.txt
tests/unittests/BackendCorrectnessTest.cpp
tests/unittests/BackendTest.cpp
tests/unittests/CMakeLists.txt
tests/unittests/MLTest.cpp
tests/unittests/OperatorTest.cpp
tests/unittests/convTest.cpp

*Description*:
Enable all open cl tests on CI.
*Testing*:
CI
n/a
Fixes https://github.com/pytorch/glow/issues/1181

[opencl] Enable all opencl tests on CI

---

lib/Graph/Graph.cpp

*Description*:
Rewrote a few line to avoid code duplication.
*Testing*:
Current test cases.

[trivial] Rewrote some duplicated code.

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

*Description*: This was found in en2gr. An element-wise Mul has two users, one of which is a rescale. The optimization was duplicating the Mul just with different output scale/offset, because it merged the rescale into the Mul. This PR stops this optimization from occurring if the input to the rescale has more than one user.
Note that backends may actually prefer to duplicate the Mul instead of Rescaling -- this is another instance related to https://github.com/pytorch/glow/issues/1641. I think it makes sense to by default not duplicate the Rescale's input.
*Testing*: Added unit test. Verified that en2gr no longer has this duplicate Mul.

[GraphOptimizer] Only fuse Rescales into input if input has one user

---

include/glow/Backends/BackendUtils.h
lib/Backends/BackendUtils.cpp
lib/Backends/CPU/AllocationsInfo.cpp
lib/Backends/CPU/AllocationsInfo.h
lib/Backends/CPU/CMakeLists.txt
lib/Backends/CPU/CPUBackend.cpp
lib/Backends/Interpreter/Interpreter.cpp
lib/Backends/Interpreter/InterpreterFunction.cpp
lib/Backends/OpenCL/OpenCL.cpp

*Description*: Moved generateRuntimeBundle to BackendUtils and updated backend to use it.
*Testing*: ninja test and run.sh are good.
Fixes #1988

[BackendUtils]Moved generateRuntimeBundle to BackendUtils.

---

lib/Graph/Nodes.cpp
lib/Graph/VerifierHelper.cpp

*Description*: I'd really like to keep CentOS 7/gcc 4.8.5 limping along if possible.

[verifier] Make template argument deduction happy (gcc 4.8)

---

tools/loader/ImageClassifier.cpp

[image-classifier] Remove dead code

---

docs/CodingStandards.md

More good suggestions for the checklist!

[doc] Add ArrayRef to coding standards checklist

---

.circleci/build.sh
.travis.yml
tests/unittests/onnxImporterTest.cpp

*Description*: It'd be nice to keep our CI build clean of warnings, so let's enabled -Werror there.
*Testing*: CI

[ci] Build with -Werror in CI

---

CONTRIBUTING.md
README.md
docs/CodingStandards.md

*Description*:
Update steps for OpenCL installation. Now the process is straightforward.
Misc updates to the docs.
*Testing*:
n/a
Updated readme

[docs] Misc updates: update OpenCL docs, maintainers etc.

---

tests/unittests/CMakeLists.txt

*Description*: Add the generation of gtest xml file for a better integration with jUnit
*Testing*: N/A

[tests] add the generation of xml google test reports

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp
tests/unittests/quantizationTest.cpp

*Description*: Add optim: Dequantize(rescale) -> Dequantize()
We've got this case in one of our models with our backend.
*Testing*: Added test: mergeRescaleIntoDequantize

[Quantization] Dequantize(rescale) -> Dequantize()

---

include/glow/Base/Tensor.h
tests/unittests/tensorsTest.cpp

*Description*: Per #2082, Tensors zero() to 0 always which is not correct for quantized types which may have a zero offset. This changes zero() to set each item to the offset, and isZero() to check against the offset for quantized types.
*Testing*: All unittests, but especially tensor tests reset and the new test zeroQuantizedTensor.
fixes #2082.

 [quantization] fix Tensor zero() and isZero() to respect quantized offset

---

include/glow/Base/Tensor.h
tests/unittests/tensorsTest.cpp
tools/loader/ImageClassifier.cpp

*Description*: I keep wanting a method like this to build batches.
*Testing*: New testcase

[tensor] Add insertSlice to insert sub-regions of a tensor

---

examples/CMakeLists.txt
examples/lenet-loader.cpp

*Description*: I want to be able to point people to a really simple, concise example of using glow to read a protobuf and do inference.  Our `tools/loader` is nice, but is a bit much to digest quickly.
*Testing*: bin/lenet-loader
*Documentation*: We should probably document our examples in `docs/` but that's kind of beyond the scope of this PR.

[examples] Simple example of loading a protobuf

---

lib/Backends/CPU/AllocationsInfo.cpp
lib/Backends/CPU/libjit/libjit_conv.cpp
lib/Optimizer/GraphOptimizer.cpp
lib/Optimizer/IROptimizer.cpp

*Description*: When fixing such mistake in my own code, I notices that there were other occurrences.
*Testing*: N/A

[grammar] Fix 'the the' occurences.

---

lib/Importer/Caffe2ModelLoader.cpp
lib/Importer/ONNXModelLoader.cpp

Some issues flagged by FB linter.

[easy] Fix some lint

---

examples/CMakeLists.txt
lib/Backends/CMakeLists.txt
lib/Backends/OpenCL/CMakeLists.txt
lib/CodeGen/CMakeLists.txt
lib/Onnxifi/CMakeLists.txt
lib/Quantization/Base/CMakeLists.txt
lib/Quantization/CMakeLists.txt
lib/Support/CMakeLists.txt
tests/unittests/CMakeLists.txt
tools/loader/CMakeLists.txt
tools/png2bin/CMakeLists.txt

Fiddling with shared libraries again, and a bunch of missing dependences showed up.

[easy] Add some missing dependences

---

include/glow/Importer/Caffe2ModelLoader.h
include/glow/Importer/CommonOperatorLoader.h
include/glow/Importer/ONNXModelLoader.h
lib/Importer/Caffe2ModelLoader.cpp
lib/Importer/ONNXModelLoader.cpp
tests/models/onnxModels/addMultiBroadcastOp7.onnxtxt
tests/models/onnxModels/divMultiBroadcastOp7.onnxtxt
tests/models/onnxModels/mulMultiBroadcastOp7.onnxtxt
tests/models/onnxModels/subMultiBroadcastOp7.onnxtxt
tests/unittests/onnxImporterTest.cpp

*Description*: Support Multidimensional broadcasting for arithmetic operations (Add, Sub, Mul, Div) 
https://github.com/onnx/onnx/blob/master/docs/Broadcasting.md
*Testing*: Added a test for Add, Sub, Mul, Div (ONNX opset 7)

[ONNX] support multidirectional broadcasting in the importer

---

examples/CMakeLists.txt

Of course I forgot to test this with the new shared libs hotness.

[easy] Fix deps for resnet-verify

---

.circleci/test.sh
examples/CMakeLists.txt

*Description*:  This is more in keeping with the structure of the test, and I might add a new build config that maybe shouldn't run onnxifi.
*Testing*: CI
Base on #2118

 [ci] Refactor onnxifi test run into the test-type switch

---

docs/Quantization.md

*Description*:
1. Added "loading quantized caffe2 models"
2. Added one of our previous quantization design: forcing some types of quantized nodes output have the same quantization param as the input 
*Testing*:
N/A

[Quantization] Quantization docs updates

---

include/glow/Importer/CommonOperatorLoader.h
include/glow/Importer/ProtobufLoader.h
lib/Importer/Caffe2ModelLoader.cpp
lib/Importer/ONNXIFIModelLoader.cpp
lib/Importer/ONNXModelLoader.cpp
lib/Importer/ProtobufLoader.cpp
tools/loader/TextTranslator.cpp

*Description*:
Ensure there is no memory leaks associated with allocated tensors in various loaders
*Testing*:
Existing unit tests
N/A
Fixes https://github.com/pytorch/glow/issues/2115

[onnx loader] Replace raw pointers with unique ptr.

---

tests/benchmark/CMakeLists.txt
tests/models/onnxModels/lengths_sum.onnxtxt
tests/models/onnxModels/sparseToDense.onnxtxt

*Description*: tabs bad!
*Testing*:

[trivial] Tabs to spaces

---

examples/cifar10.cpp

*Description*:
Add a 2nd model to the cifar10 example that is close to VGG as implemented in pytorch vision vgg.py / vgg11. This is currently missing the `Dropout` layers as I couldn't find a builtin node for that in glow.
*Testing*:
Ran the cifar10 example with `-model-vgg`, accuracy is improving more steadily than with the jumpy behavior of the default model.
Related to #2111

[examples][cifar10] Add VGG like model, some refactoring

---

lib/Graph/Graph.cpp
lib/Optimizer/IROptimizer.cpp

*Description*:
Contains two patches to avoid two cases of nondeterminism in the compiler.
*Testing*:
see individal commits.
* #1948

Fix some nondeterminism

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

*Description*: Self-explanatory. Same idea as folding quantize into Constant.
*Testing*: Added a couple tests.

[GraphOptimizer] Fold Quantize into Splat

---

include/glow/Base/Tensor.h
include/glow/Graph/Context.h
include/glow/Graph/Graph.h
lib/Graph/Context.cpp
lib/Graph/Graph.cpp
tests/unittests/graphTest.cpp

*Description*: Helper methods for retrieving the size used by the data parts of Module and Context, for use in provisioning.
*Testing*: Ninja all + 2 new tests

[graph] Add methods to Tensor, Module and Context to get the memory size of contained data.

---

include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
lib/Optimizer/GraphOptimizer.cpp
tests/unittests/graphOptzTest.cpp

*Description*: More missing optimizations for getting rid of RescaleQuantized
*Testing*: Added a couple tests

[GraphOptimizer] Fuse Rescales up into MatMul/SparseLengthsWeightedSum

---

docs/Onnxifi.md

*Description*: I've got this working entirely with open-source repos, so I thought the rest of the world would like to know how it's done.
*Testing*: Follow the doc!
*Documentation*: New doc: Onnxifi.md

[docs] Document how to build and use PyTorch with ONNXIFI

---

lib/Onnxifi/onnxifiGlow.cpp

*Description*: With this style, you should be able to add an arbitrary number of #ifdef blocks and have them work.
*Testing*: test_onnxifi.py from the pytorch repo.

[onnxifi] Refactor onnxGetBackendIDs to make it easier to add optional backends

---

lib/Onnxifi/onnxifiGlow.cpp

Reverts pytorch/glow#2203
@yinghai depends on the backend array for some work in progress.

Revert "[onnxifi] Refactor onnxGetBackendIDs to make it easier to add optional backends"

---

include/glow/Base/TaggedList.h
include/glow/IR/IR.h
lib/Base/CMakeLists.txt
lib/Base/TaggedList.cpp
lib/IR/IR.cpp
tests/unittests/CMakeLists.txt
tests/unittests/TaggedListTest.cpp

*Description*:
A TaggedList is an intrusive linked list similar to `llvm::ilist`, except a
TaggedList maintains a node ordering so it is possible to compare relative
positions of two nodes in constant time.
*Testing*:
`ninja test`
Doxygen comments and unit tests.
Fixes #1766.

Add a Taggedlist and use it for InstrListTy in IRFunction

---

include/glow/Backends/LayoutConverter.h
lib/Optimizer/Lower.cpp
tests/unittests/GemmTest.cpp
tests/unittests/GradCheckTest.cpp
tests/unittests/GraphOptzTest.cpp
tests/unittests/GraphTest.cpp
tests/unittests/OperatorTest.cpp

For consistency across the codebase.

[Cleanup][NFC] Add missing * to all found uses of auto with pointer

---

lib/Base/TaggedList.cpp

*Description*:
TSIA. Tiny fix. 
*Testing*:

Replace non-ascii characters

---

CMakeLists.txt

*Description*:
Fix linking against protobuf built as dll.
*Testing*:
Unit tests.
NA

[FIX] Fix linking against protobuff.

---

lib/Importer/Caffe2ModelLoader.cpp
lib/Importer/ProtobufLoader.cpp
lib/Onnxifi/Base.cpp
lib/Onnxifi/Base.h
lib/Onnxifi/onnxifiGlow.cpp

*Description*:
Mainly fixed parameter ordering when building the ONNXIFI backend IDs. Also added more informative error messages. 
This is a pairing PR of https://github.com/pytorch/pytorch/pull/15472.  
*Testing*:
Integration tests

[ONNXIFI] Fixes to make C2 protobuf through ONNXIFI work

---

tests/unittests/OperatorTest.cpp

*Description*:
Our internal test system is case insensitive... 
*Testing*:
Run unittest internally and see both tests run

Change matmul unittest name

---

include/glow/Backends/BackendUtils.h

*Description*:
Removed "const" and added a default Constructor in RuntimeBundle Class.
*Testing*:
Ninja check

[Trivial] RuntimeBundle

---

lib/Importer/Caffe2ModelLoader.cpp

*Description*:
Just found quantized resnet50 failed due to improper error checking: 
For quantized ops, there is an arg "order" to indicate it is "NHWC" or "NCHW", and in the quantized resnet50 model, all orders are "NHWC". Therefore, the input of quantized conv and pool don't have to be only "Transposed" or "Storage" type.  So the current error checking caused the crash.
*Testing*: ninja check, run.sh

[Caffe2ModelLoader] Fix an error-checking

---

lib/Importer/ProtobufLoader.cpp
lib/Onnxifi/Base.h

*Description*:
Some trivial fixes in onnxifi.
*Testing*:
CI
cc: @yinghai

[cleanup] Trivial fixes

---

include/glow/Graph/Graph.h
include/glow/Importer/CommonOperatorLoader.h

This commit addresses comments made on #2233 just after it was merged regarding
the implementation of the `GatherRanges` operator.
**Testing**
All tests pass.

[C2/ONNX] Fix leftover comments from #2233

---

include/glow/Base/Tensor.h

*Description*:
Comment fix.
*Testing*:
n/a

[trivial] Fixing some comments in past PRs.

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/GraphOptzTest.cpp

*Description*:
Extend optimization which merges Transpose into MatMul, so that it'd merge Transpose into FC as well. Some backends do not lower FC to MatMul + BatchedAdd, so for such backends this transformation might be useful.
*Testing*:
Added a new unit test in GraphOptzTest
N/A
Fixes #2250

[GraphOptimizer] Extend optimization which merges Transpose into MatMul, so that it'd merge Transpose into FC as well

---

include/glow/Graph/Graph.h
tests/unittests/GraphOptzTest.cpp

[trivial] Unused Context in test. s/variable/constant.

---

examples/fr2en.cpp
include/glow/Quantization/Quantization.h
lib/Backends/CPU/CPUBackend.cpp
lib/Backends/Interpreter/Interpreter.cpp
lib/Quantization/Quantization.cpp
tests/unittests/BackendCorrectnessTest.cpp
tests/unittests/MLTest.cpp
tests/unittests/QuantizationTest.cpp
tools/loader/Loader.cpp

*Description*:
* Loader param for quantization precision
* Custom precision in quantization procedure
*Testing*:
* Unit tests (int16 quantization test).
Will update quantization doc.
cc: @bertmaher this should help with the automatic quantization you'll be doing for int16.

[quantization] Support int16 loader and custom precision in quantization procedure

---

include/glow/Quantization/Quantization.h
lib/Backends/OpenCL/OpenCL.h
lib/Quantization/Quantization.cpp
tests/unittests/QuantizationTest.cpp
tools/loader/Loader.cpp

*Description*:
Enable ability to specify target quantization precision during the profiling. 
*Testing*:
unit tests

[quantization] Generate quantization profile info with required precision

---

lib/Optimizer/GraphOptimizer.cpp

*Description*: Refactored inlined macros, in to template code. I think it's easier to read, and at least in VS easier to step in to.
*Testing*: Unit Tests.

[Refactor] Refactoring macro in to template code.

---

lib/Backends/Interpreter/InterpreterFunction.h
tests/unittests/BackendTestUtils.h

*Description*: from fb internal linter
*Testing*: CI

[trivial] Missing explicit, extra semi

---

tests/unittests/CMakeLists.txt

*Description*: The haphazard organization of our unittests CMakeLists did not spark joy.
*Testing*: ninja all && ninja test

[unittests] Organize our tests/unittests/CMakeLists.txt better

---

examples/resnet-concurrent.cpp

*Description*: We apparently don't build this on our Travis gcc 4.8.5 config so it slipped through.  (I'll try to fix that separately)

Moar gcc-4.8.5 fixes

---

docs/Backends.md

*Description*: Added section about compileWithoutConstants, removed context from both compile function signatures.
*Testing*: Documentation only change.
*Documentation*: Updated  
Fixes #2226

Updated Backends.md to include compileWithoutConstants.

---

tests/unittests/Caffe2ImporterTest.cpp
tests/unittests/OnnxImporterTest.cpp

*Description*: To make it easier to integrate into build systems with different roots.
*Testing*: ninja Caffe2ImporterTest

[Caffe2ImporterTest] Allow definition of test data path

---

.circleci/build.sh
.circleci/config.yml
.circleci/test.sh

*Description*:
Run thread sanitizer on Glow since we started getting multithreaded code in.
```
cmake -GNinja -DCMAKE_CXX_FLAGS=-Werror -DGLOW_WITH_CPU=ON '-DGLOW_USE_SANITIZER='\''Thread'\''' -DGLOW_WITH_OPENCL=OFF ../
....
-fsanitize=thread 
```
*Testing*:
CI
n/a

[ci] Run TSAN on CI.

---

tests/unittests/ExecutorTest.cpp

*Description*:
Fix ExecutorTest.
@ayermolo could you please check if this fixes compilation. I do not have win host handy ...
*Testing*:
CI + manual run on win.
n/a
Fixes https://github.com/pytorch/glow/issues/1144

[windows/compile] Fix compilation for VS.

---

docs/NewOperators.md

*Description*:
Add a file documenting the basic steps for implementing a new operator.
*Testing*:
Look at markdown [preview](https://github.com/jackm321/glow/blob/new_operator_doc/docs/NewOperators.md)
yes

Document process of adding an operator

---

examples/resnet-runtime.cpp
include/glow/Backends/DeviceManager.h
include/glow/Backends/QueueBackedDeviceManager.h
include/glow/Partitioner/Partitioner.h
include/glow/Runtime/Executor/Executor.h
include/glow/Runtime/HostManager/HostManager.h
include/glow/Runtime/Provisioner/Provisioner.h
include/glow/Runtime/RuntimeTypes.h
lib/Backends/CPU/CPUDeviceManager.cpp
lib/Backends/CPU/CPUDeviceManager.h
lib/Backends/DeviceManagers.cpp
lib/Backends/Interpreter/InterpreterDeviceManager.cpp
lib/Backends/Interpreter/InterpreterDeviceManager.h
lib/Runtime/Executor/Executor.cpp
lib/Runtime/Executor/ThreadPoolExecutor.cpp
lib/Runtime/Executor/ThreadPoolExecutor.h
lib/Runtime/HostManager/HostManager.cpp
lib/Runtime/Provisioner/Provisioner.cpp
tests/unittests/ExecutorTest.cpp
tests/unittests/ProvisionerTest.cpp

*Description*: Moved common types to RuntimeTypes, moved DeviceManager into runtime namespace.
*Testing*: Unit tests and resnet-runtime example pass.

[Runtime][NFC] Runtime Cleanup

---

include/glow/Partitioner/Partitioner.h
include/glow/Runtime/RuntimeTypes.h
lib/Partitioner/Partitioner.cpp

*Description*:
Use "size_t" to for memory type.
*Testing*:
ninja check.

[cleanup] To make the type of memory consistent with getSizeInBytes() in Type.h

---

tests/unittests/HostManagerTest.cpp

*Description*: Small fix for types. Changed to more standard c++ unsigned.

[GLOW] Small fix for type not supported by VS.

---

tests/unittests/Caffe2ImporterTest.cpp

*Description*:
- Don't check numerical results (done in OperatorTest)
- Verify expected node types
*Testing*:
Tests still pass
No change

[Caffe2ImporterTest] Clean up ReplaceNaN test

---

README.md

[Readme] Remove nonexistent flag from brew install command

---

README.md

[Readme] Add header files workaround to readme

---

tests/unittests/Caffe2ImporterTest.cpp
tests/unittests/OperatorTest.cpp

*Description*:
Don't check numerical results (done in OperatorTest)
Verify expected node types for Clip
*Testing*: unit test passed
no change

Move numerical test of Clip operator to OperatorTest

---

examples/tracing-compare.cpp
tests/onnxifi/build_onnxifi_tests.sh
tests/onnxifi/test.sh
utils/caffe2_model_runner.py

Because I keep getting nagged by an annoying compliance bot, here are some copyright headers.

[trivial] Copyright headers

---

lib/Backends/CPU/LLVMIRGen.cpp
lib/Backends/OpenCL/OpenCL.cpp

These `GLOW_ASSERT()` were previously noops, should have been `GLOW_UNREACHABLE()`.

[trivial] Fix incorrect usage of GLOW_ASSERT()

---

.circleci/test.sh

*Description*:
Forgot to update the error message
*Testing*:

[Trivial] Fix RELEASE_WITH_EXPENSIVE_TESTS warning

---

include/glow/Importer/CommonOperatorLoader.h

*Description*:
Return an error instead of false because false indicates a common operator could not be loaded.
*Testing*:
`ninja test`
none added

[Easy] Remove unnecessary Expected<bool> in loaders

---

examples/tracing-compare.cpp
lib/Backends/CPU/CMakeLists.txt
tests/unittests/OnnxImporterTest.cpp

*Description*: Minor fixes to get things working again with Windows.

Few fixes for windows build.

---

.gitignore

Add some internal caches used by IDEs to .gitignore

---

lib/Quantization/Quantization.cpp

*Description*: This logic may not be called into only after Batch was quantized -- it could be called into by `canConvert()`, and so we need to handle the case where the graph is not quantized.
*Testing*: I found this when working on https://github.com/pytorch/glow/pull/2235. I don't think I can repro the broken test without other stacked changes from there. This PR fixes tests in that PR but I want to unblock it here with a smaller bite-sized commit.

[Quantization] Fix logic for MM + BA lowered from FC

---

lib/Onnxifi/onnxifiGlow.cpp

Fixed a nits in glow onnxifi extension mode.

Fix the support of onnxifi extension mode in glow

---

lib/Backends/CPU/libjit/libjit.cpp

NFC. Place all helpers located in the same anonymous namespace, and make them all static.

[NFC][libjit] Refactor a little to make all helpers static + anon

---

docs/Backends.md
lib/Onnxifi/Base.cpp

*Description*:
Fix broken build
*Testing*:
CI
Also update transformPostLowering description in Backends.md

Fix transformPostLowering in Onnxifi/base

---

include/glow/Runtime/Provisioner/Provisioner.h
lib/Runtime/Provisioner/Provisioner.cpp

*Description*: This updates the provisioner to honor logicalDevice in the DAGNode. 
*Testing*: unit tests pass, resnet-runtime runs successfully.

Added logicalDevice support to provisioner

---

tests/unittests/DeviceManagerTest.cpp

This commit modifies `DeviceManagerTest` to check that the outputs of
networks it runs are correct. Without this, all test cases in `DeviceManagerTest`
can still pass if there is a bug in the `runFunction` implementation of
a class that extends `DeviceManager`.
**Testing**
**Fixes**
This commit fixes #2471.

[DeviceManager] Modify DeviceManagerTest to check network outputs

---

tests/unittests/GradCheckTest.cpp

*Description*:
Some test cases in GradCheckTest do not exercise operations being tested properly. These tests were proved to compute zero gradients, which means that input doesn't affect output at all. With the change at 165, 4 out of 17 tests fail.
This can happen either when 1) the test case has a bug in wring the graph or 2) the training process trains variables unrelated to input to emulate output.
This PR fixes those tests so that they can pass the check at line 165: 3. They were fixed to make the operation to the input matter to the output after training. gradientCheckFCConcatRELU is removed since hidden weights introduced by FC completely ignores the input. Also it's unclear what operation gradientCheckFCConcatRELU is actually testing.
Note that a fundamental way to improve this …

[unittests] Fix GradCheckTest to exercise operations being tested.

---

examples/resnet-runtime.cpp
examples/tracing-compare.cpp
include/glow/Backends/DeviceManager.h
include/glow/Backends/DummyDeviceManager.h
include/glow/Backends/QueueBackedDeviceManager.h
include/glow/Runtime/HostManager/HostManager.h
include/glow/Runtime/RuntimeTypes.h
lib/Backends/CPU/CPUDeviceManager.cpp
lib/Backends/CPU/CPUDeviceManager.h
lib/Backends/DeviceManagers.cpp
lib/Backends/Interpreter/InterpreterDeviceManager.cpp
lib/Backends/Interpreter/InterpreterDeviceManager.h
lib/Backends/OpenCL/OpenCLDeviceManager.cpp
lib/Backends/OpenCL/OpenCLDeviceManager.h
lib/ExecutionEngine/ExecutionEngine.cpp
lib/Runtime/HostManager/HostManager.cpp
tests/unittests/DeviceManagerTest.cpp
tests/unittests/HostManagerTest.cpp

*Description*: Introduced new DeviceConfig struct to hold device configuration information for device managers. Changed factory and constructors to accept new struct instead of the current name parameter.
*Testing*: ninja test and resnet-runtime

New DeviceManager config object

---

lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/OpenCLDeviceManager.cpp
lib/Backends/OpenCL/OpenCLDeviceManager.h
tests/unittests/DeviceManagerTest.cpp

*Description*: Added OpenCLDeviceConfig object to OpenCL Device Manager. Also added command line parameter support for OCL device manager when a config object is not provided.
*Testing*: ninja test and resnet-runtime
Fixes #2479

[Runtime][OpenCL Device Manager]Added OpenCL Device Manager config object

---

examples/resnet-concurrent.cpp
examples/tracing-compare.cpp
include/glow/Backends/DeviceManager.h
include/glow/Backends/DummyDeviceManager.h
include/glow/Backends/QueueBackedDeviceManager.h
include/glow/Runtime/HostManager/HostManager.h
include/glow/Runtime/Provisioner/Provisioner.h
include/glow/Support/Error.h
lib/Backends/CPU/CPUDeviceManager.cpp
lib/Backends/Interpreter/InterpreterDeviceManager.cpp
lib/Backends/OpenCL/OpenCLDeviceManager.cpp
lib/Backends/OpenCL/OpenCLDeviceManager.h
lib/ExecutionEngine/ExecutionEngine.cpp
lib/Runtime/HostManager/HostManager.cpp
lib/Runtime/Provisioner/Provisioner.cpp
lib/Support/Error.cpp
tests/unittests/DeviceManagerTest.cpp
tests/unittests/ExecutorTest.cpp
tests/unittests/ProvisionerTest.cpp

*Description*:
Return `GlowErr`s from methods in DeviceManager, Provisioner, HostManager, Executor, etc and handle them in onnxifi.
*Testing*:
`Ninja check`
Comments

Add GlowErrs to runtime

---

lib/Runtime/HostManager/HostManager.cpp

*Description*:
Fix the HostManager check of `provision` call.
*Testing*:
run `resnet-runtime`
none

Fix HostManager llvm::Error check

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/GraphOptzTest.cpp

*Description*: Found this pattern in a private model after applying https://github.com/pytorch/glow/pull/2518.
*Testing*: Added unit test.

[GraphOptz] Add optimization for dequantize(splat)

---

lib/Optimizer/GraphOptimizer.cpp
tests/unittests/GraphOptzTest.cpp

*Description*: Looking at Inception_V3 spotted some opportunities to produce better graph. Made Transpose sinking below concat more generic to eliminate Transpose nodes. Added swapping Transpose and Rescale to open opportunity for it to be folded in to Convolution. If not it will be sinked later again.
Also made sinking RELU below concat more generic.
Not sure why there was artificial restriction on two inputs.  Maybe someone can elaborate on this.
*Testing*: Unit tests, Inception_V3.

Graph Optimizer Concat and RELU related optimizations

---

lib/Quantization/Quantization.cpp
tests/unittests/QuantizationTest.cpp

*Description*: This PR adds the ability to rowwise-quantize an FC that was already lowered to MM + BA. Because of lowering before quantization we were lowering FCs before looking for them to rowwise-quantize them, meaning lowered FCs weren't being rowwise-quantized.
*Testing*: Added unit tests.

[Quantization] Rowwise-quantize already lowered FC

---

tools/ClassGen/NodeGen.cpp

*Description*: Just making auto gen code prettier.
*Testing*:

Trivial adding new lines.

---

tests/unittests/CMakeLists.txt
tests/unittests/OperatorGradTest.cpp

*Description*:
Please see the comment for computeGradient().
*Testing*:
Run GradCheckTest
Partially fixing #2513

[unittests] Create OperationGradTest to isolate unit tests for gradient computation

---

include/glow/Runtime/Provisioner/Provisioner.h
lib/Runtime/HostManager/HostManager.cpp
lib/Runtime/Provisioner/Provisioner.cpp
tests/unittests/HostManagerTest.cpp

*Description*: Fixed HostManager concurrent test and added additional concurrent test. 
Added method to Provisioner to removed unused compiledFunctions.
*Testing*: ninja test passed

Fixed Hostmanager concurrent test

---

lib/Backends/Backend.cpp
tests/unittests/TraceEventsTest.cpp

*Description*: When auto instrumenting we add Placeholders to the Module to hold the backing tensors for the instrumented metrics. When compiling twice we end up creating multiple placeholders, some which that don't have an associated weight in the IR which breaks when collecting constants. This fixes auto instrumentation by reusing a previous backing tensor if the size matches.
*Testing*: new unit tests, asan.

[Tracing] Fix issues when compiling & instrumenting twice

---

include/glow/Backends/BackendUtils.h
tests/unittests/ExecutorTest.cpp

*Description*: This adds default values to the fields on RuntimeSymbolInfo.

Adding default values to Runtime Symbol struct

---

tests/unittests/OnnxImporterTest.cpp

*Description*:
Failing internal tests because of incorrect paths.
*Testing*:
CI
ran internal tests
none

Add missing GLOW_DATA_PATH to ONNXImporter tests

---

lib/LLVMIRCodeGen/FunctionSpecializer.cpp

[function-specializer] Do not try to specialize function declarations

---

cmake/modules/GlowDefaults.cmake
docs/Backends.md
examples/CMakeLists.txt
include/glow/Backends/Backend.h
include/glow/Support/Register.h
lib/Backends/CMakeLists.txt
lib/Backends/CPU/CMakeLists.txt
lib/Backends/CPU/CPUBackend.cpp
lib/Backends/CPU/CPUFactory.cpp
lib/Backends/Interpreter/CMakeLists.txt
lib/Backends/Interpreter/Interpreter.cpp
lib/Backends/Interpreter/InterpreterFactory.cpp
lib/Backends/OpenCL/CMakeLists.txt
lib/Backends/OpenCL/OpenCL.cpp
lib/Backends/OpenCL/OpenCLFactory.cpp
tests/unittests/CMakeLists.txt

*Description*:
* Introduce static registration factory for general purpose registration of Backends/DeviceManagers/etc
* Migrate backends to register via Factory
*Testing*:
CI
doxygen

[Backends] Static registration for backends.

---

tests/unittests/HostManagerTest.cpp

*Description*:  Fix windows VS build.
*Testing*:

VS trivial uint -->unsigned

---

include/glow/Partitioner/Partitioner.h
include/glow/Partitioner/PartitionerUtils.h
lib/Partitioner/Partitioner.cpp
lib/Partitioner/PartitionerUtils.cpp

*Description*:
This PR 1) Make the nodes/functions working sequence fixed based on their names. Therefore, the internal optimization sequence is consistent for each run.
2) Fixed a few bugs related to communication cost.
3) Polished partitions combination optimization.
*Testing*:
ninja check, runtime-resnet.
#2298 

[Partitioner] Polish code and fix a few bugs to make optimization sequence consistent for each run.

---

lib/Backends/OpenCL/OpenCL.cpp
lib/LLVMIRCodeGen/DebugInfo.cpp
tools/png2bin/CMakeLists.txt

*Description*:
fixing artifacts from https://github.com/pytorch/glow/pull/2494 which were extracted from that PR.
* do not expose some symbols from opencl
* remove unnecessary dependencies
*Testing*:
ci
n/a

[build] Random changes for improving cmake.

---

lib/Backends/OpenCL/OpenCL.cpp

*Description*:
In OpenCL, the device can define maximum sizes separately for each dimension, but the total maximum WG size can be less than the multiple of all of the dimension maximums. In that case it simply means that not all dimensions can be set at their maximum at the same time. This patch accounts for that and reduces the second dimension to meet the maximum WG size limit of the device.
*Testing*: ninja check   results match the situation without the change, these fail/skip (LLVM 8, no asserts build) with both:
```
1 - onnx_gtests (Not Run)
2 - onnxifi_test_driver_gtests (Not Run)
30 - QuantizationTest (Child aborted)
```

[OpenCL] Account for a case were device max WG size limits dims.

---

include/glow/LLVMIRCodeGen/GlowJIT.h
lib/LLVMIRCodeGen/DebugInfo.cpp
lib/LLVMIRCodeGen/GlowJIT.cpp

*Description*:
Fix fbcode build with the latest Glow.
*Testing*:
CI
n/a

[fix] Fix internal build.

---

include/glow/Backends/DummyDeviceManager.h
lib/Backends/CPU/CPUDeviceManager.cpp
lib/Backends/Interpreter/InterpreterDeviceManager.cpp
lib/Runtime/HostManager/HostManager.cpp
tests/unittests/ExecutorTest.cpp

*Description*: Looking at documentation looks like index is required for formatting. In VS in debug was causing run time exception.
*Testing*:
*Documentation*: http://llvm.org/doxygen/FormatVariadic_8h_source.html

Trivial Fixing formatting for formatv().

---

tests/unittests/OperatorTest.cpp

[OperatorTest] Add fp16 test for FC

---

tests/unittests/OperatorTest.cpp

Missed one in https://github.com/pytorch/glow/pull/2596 😞

[unbreak][OperatorTest] Remove one last schema

---

tools/loader/ImageClassifier.cpp

Image list file is used to specify the list of images that user wants to infer.

User can pass an input image list file containing list of images

---

include/glow/Base/Image.h
lib/Base/Image.cpp
tools/loader/ImageClassifier.cpp

*Description*:
Move this function so it could be reused in other files.
*Testing*:
`ninja all`

[NFC] Move loadImagesAndPreprocess() to Image.h

---

README.md
docs/logo.svg

*Description*: Convert the Glow blurry logo to SVG.

Convert the Glow blurry logo to SVG.

---

include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
lib/Graph/Nodes.cpp
lib/Optimizer/Lower.cpp
tests/unittests/OperatorTest.cpp
tools/ClassGen/NodeGen.cpp

Implementing PRelu node creation and lowering (required for #2501).
PRelu is parameterized leaky Relu:
slope * x      if x < 0
x                   if x > =0
where slope is a parameter (not constant).
Lowering is implemented from the above description by:
select(cmpLTE(x, 0), mul(slope, x), x)
Unit tests pass.

[New Operator] PRelu node creation, lowering and unittest

---

examples/lenet-loader.cpp
examples/resnet-concurrent.cpp
examples/resnet-runtime.cpp
examples/resnet-verify.cpp
examples/tracing-compare.cpp
include/glow/Base/Image.h
lib/Base/Image.cpp
tests/unittests/ImageTest.cpp
tools/loader/ImageClassifier.cpp
tools/png2bin/png2bin.cpp

User has the control over the normalization

Command line option to pass mean, standard deviation for input normalization

---

lib/Onnxifi/InlineOnnxifi.cpp

*Description*:
Removing uuid from the profile name.
*Testing*:
CI
n/a
@ayermolo

[onnxifi] Do not use uuid for profile

---

lib/Partitioner/Partitioner.cpp

*Description*:
*Testing*:
Current tests.

[Partitioner] Fix a bug a remove duplicated children.

---

include/glow/Importer/CommonOperatorLoader.h

Tested in fbcode already. Recover UINT8=>ElemKind::Int8Qty path.

[onnxifi] Recover int8Qty

---

include/glow/Backends/BackendUtils.h
lib/Backends/BackendUtils.cpp
tests/unittests/BackendTest.cpp

*Description*: Adds a new field: symbolCategory to the symbolInfo object. This denotes whether the symbol is a Placeholder, constant, or activation.
*Testing*: Added new unit test.
Fixes #2597

Added symbolCategory to symbol info in the runtimeBundle.

---

lib/Backends/Habana/Habana.cpp

Summary:
When we have partitioned models in which a Module has multiple
Functions, when we're looking for an output Placeholder we need to be specific
about which Function uses that Placeholder as an output (since it could be an
output for a *different* Function).
Reviewed By: rdzhabarov
Differential Revision: D14840737

[habana] Find SaveNode of output Placeholder w.r.t. specific Function

---

lib/Quantization/Quantization.cpp

I'm not really sure why this logic is here. It doesn't really make sense to me -- given some `DequantizeNode`, it adds an entry to `nodeToTQP_` to map from the `DequantizeNode's` output to its \*input's\* quantization parameters. Meanwhile, normally this maps from a Node's output to that output's quantization parameters. So I don't get what's going on here. Without the logic, all unit tests still pass and I also tested `resnet50` and `en2gr`.
If anyone has a good idea why it's necessary please let me know and I'd be happy to kill this PR.

[Quantizer] Remove logic for updating nodeToTQP_

---

lib/Onnxifi/Base.cpp

*Description*:
* Add padding to input tensor passed from C2 if needed.
* Back tensor by memory allocated by C2 if padding is not needed (should be majority of cases)
* Allocate new chunk of memory in case padding needed
*Testing*:
Tested on internal build. No good tests on onnxifi yet.
n/a
@yinghai @jackm321

[onnxifi] Pad input tensor if it's smaller than the size of input placeholder.

---

README.md

*Description*
See title
*Testing*:
preview
yes

Add glog dep to README

---

include/glow/Importer/ONNXModelLoader.h
lib/Importer/ONNXModelLoader.cpp
tests/models/onnxModels/castToFloat.onnxtxt
tests/models/onnxModels/castToFloat16.onnxtxt
tests/models/onnxModels/castToInt32.onnxtxt
tests/models/onnxModels/castToInt64.onnxtxt
tests/unittests/OnnxImporterTest.cpp

Add partial support for the Cast operator : float, float16, non quantized int32 & int64.
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Cast
*Testing*: Added related ONNX tests
*Documentation*: not needed
Fixes #2640

[ONNX] Partial support for the ONNX Cast operator

---

tests/images/run.sh
tools/loader/ImageClassifier.cpp

*Description*:
Extending ImageClassifier class and correspondent script to check expected labels explicitly.
*Testing*:
./tests/images/run.sh
Extending existed functionality for a strict check of expected lables

New changes for ImageClassifier class and correspondent script.

---

tests/unittests/OnnxImporterTest.cpp

*Description*:
Fix as per PR title.
*Testing*:
CI
n/a
@beicy to unblock you real quick.

[onnxmodeltest] Fix breaking behavior when GLOW_DATA_PATH is defined.

---

lib/Backends/Habana/HabanaDeviceManager.cpp
lib/Onnxifi/GlowOnnxifiManager.cpp
tests/unittests/HabanaBackendTest.cpp
tools/ClassGen/Backends/Habana/HabanaSpecificNodesVerification.h

See the individual commits for details.  These are all tiny so I didn't want to create four separate PRs.

[habana] Clean up loose ends from Habana backend merge

---

lib/Runtime/Provisioner/Provisioner.cpp

*Description*:
Replacing the standalone function with the lambda to be inlined in std::sort algorithm
*Testing*:
ninja test
Compiler cannot inline a standalone function as a predicate, cause it doesn't have a unique type.

Replaced function with lambda to inline predicate code for std::sort

---

lib/Onnxifi/Base.cpp

*Description*:
Sorry, https://github.com/pytorch/glow/pull/2725 was checked in too soon and I found an ordering issue when comparing to internal diff. 
*Testing*:
internal test. 

[ONNXIFI] Initialize tensor before execution

---

lib/Partitioner/Partitioner.cpp

*Description*:
When we create the initial partitions, we can combine the level cut and mapping together.  In addition, add the function to remove duplicate memory calculating.
*Testing*:
ninja check. restnet-runtime.

[Patitioner] Refactor the initializing partition code.

---

include/glow/Backends/TraceEvents.h
lib/Onnxifi/Base.cpp
lib/Onnxifi/Base.h
lib/Onnxifi/HostManagerOnnxifi.cpp
lib/Onnxifi/HostManagerOnnxifi.h
lib/Onnxifi/InlineOnnxifi.cpp
lib/Onnxifi/InlineOnnxifi.h
lib/Onnxifi/onnxifiGlow.cpp

*Description*:
Transfer Glow trace events across onnxifi interface
*Testing*:
Synced and tested internally
doxygen

Transfer trace events from Glow across ONNXIFI interface

---

lib/Graph/Graph.cpp
lib/Graph/Nodes.cpp
lib/Optimizer/GraphOptimizer.cpp
lib/Optimizer/Lower.cpp
tests/unittests/GraphOptzTest.cpp
tools/ClassGen/NodeGen.cpp

*Description*:
Add ChannelShuffle node. It's lowered in Lower.
*Testing*:
Related GraphOptimizer test is updated.
Fixes #2722

Add support for ChannelShuffle node.

---

README.md

[README] Update build docs with DLLVM_DIR

---

utils/build_llvm.sh

*Description*: Update the llvm build script to use v8.0.
*Testing*: Tested locally on my mac.
*Documentation*: None. 
CC @mortzur

Update the llvm build script to use v8.0

---

lib/Quantization/Quantization.cpp
tests/unittests/QuantizationTest.cpp

*Description*: Fix an issue where the quantizer was breaking when trying to quantize a `TopKNode` that only has its indices used, because it was expecting any quantized outputs to always have a use.
*Testing*: Added unit test.
Fixes #2338

[Quantization] Allow for nodes with outputs with no users

---

CMakeLists.txt
cmake/modules/Glog.cmake
lib/Base/CMakeLists.txt

*Description*:
Add cmake configs for glog
*Testing*:
Build on osx
CI on linux
Fixes #2732

Add glog cmake configs

---

include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
tests/unittests/GraphTest.cpp

*Description*:
I was bitten by this when was dumping in the tmp file and was not able to find it.
*Testing*:
CI
n/a

[easy/graph] Do not remove dumped graph file right away

---

include/glow/Graph/Graph.h
lib/Graph/Graph.cpp
lib/Graph/Nodes.cpp
lib/Optimizer/Lower.cpp
tests/unittests/Caffe2ImporterTest.cpp
tests/unittests/OnnxImporterTest.cpp
tools/ClassGen/NodeGen.cpp

*Description*: Useful for a private backend.
*Testing*: Updated tests.

Add ReplaceNaN Node so backends can prevent lowering if desired

---

tests/unittests/DeviceManagerTest.cpp

*Description*:
Lint always complains about this during importing.
*Testing*:
run lint, error is gone
None

Fix DeviceManagerTest lint

---

lib/Optimizer/IROptimizer.cpp

Only instructions whose names contain a substring from the list will be debug-instrumented. This is very useful for debugging big NN models, where dumping inputs and outputs of all instructions usually produces huge logs, which are hard to navigate. Limiting the printing to specific instructions significantly reduces the size of the logs and shows only what the user wants to see.

[ir-optimizer] Add option -instrument-debug-only to instrument only instructions from the provided list

---

lib/Graph/Grad.cpp
tests/unittests/GradCheckTest.cpp
tests/unittests/GraphGradTest.cpp

*Description*:
Training some sparse features CNN requires Gradient for MatMulNode
*Testing*:
Run unit test: checkMatMulToGradTest

Add Gradient for MatMulNode.

---

lib/Onnxifi/Base.cpp

*Description*:
This change was left behind in a recent sync
*Testing*:
CI

Sync change to gh that was left behind

---

tests/unittests/Caffe2ImporterTest.cpp

*Description*:
Found a typo, felt empowered enough to correct it.

[tests] Fix misspelling in a comment. NFC.

---

tests/unittests/HabanaBackendTest.cpp

*Description*: A few unit tests that stress test performance aspects of the Habana backend.
*Testing*: new tests
Originally contributed by @nrsatish

[habana] Perf-related unit tests

---

lib/Backends/Habana/Habana.cpp
lib/Backends/Habana/Habana.h
lib/Backends/Habana/HabanaDeviceManager.cpp
lib/Backends/Habana/HabanaDeviceManager.h
lib/Base/Tensor.cpp
lib/Onnxifi/onnxifiGlow.cpp
tests/unittests/BackendTestUtils.h
tests/unittests/DeviceManagerTest.cpp

*Description*:
This commit brings over changes that were made internally at FB for glow-h.
* Most of the changes are in lib/Backends/Habana/* and are just replaying changes made internally. Hopefully reviewing those should be easy enough for @bertmaher or @rdzhabarov who made most of those changes.
* DeviceManagerTest changes are to parameterize by backend kind
* HabanaBackendTest change adds one test case which is currently disabled.
*Testing*:
ninja all && ninja test
Habana specific testing will be done internally.

Merge glow-h changes in internal repo to github master

---

lib/Graph/Grad.cpp
tests/unittests/GradCheckTest.cpp
tests/unittests/GraphGradTest.cpp

*Description*:
Added Gradient for  BatchedReduceAddNode type
*Testing*:
Run unit tests

Adding a gradient for BatchedReduceAddNode type.

---

lib/Backends/Habana/Habana.cpp

*Description*:
Few glow updates to comply with newer Habana release.
*Testing*:
Unit tests.
n/a

[habana] Update to make 0.1.8 work.

---

lib/Graph/Grad.cpp
tests/unittests/GradCheckTest.cpp
tests/unittests/GraphGradTest.cpp

*Description*:
Added Gradient for GatherNode.
Indices shouldn't contain duplicate values (restriction).
*Testing*:
Run unit tests.

Added Gradient for Gather Node (with some restrictions).

---

lib/Graph/Grad.cpp
tests/unittests/GradCheckTest.cpp

*Description*:
Fixing Gradient for BatchedReduceAdd Node.
*Testing*:
Run unit tests for the generic case.

Fixing Gradient for BatchedReduceAddNode.

---

lib/Backends/Habana/HabanaDeviceManager.cpp
lib/Onnxifi/HostManagerOnnxifi.cpp

*Description*: We need a way to set these externally.
*Testing*: Used them.
*Documentation*: Help strings?

[glow] Add command line flags for # devices and Habana memory capacity

---

lib/Backends/Habana/Habana.cpp
tests/unittests/HabanaBackendTest.cpp

*Description*:
It works fine on 1.8. Enable it back. Bring additional test from fbcode.
fbcode - D15243041
*Testing*:
Unit tests
n/a

[Habana] Enable gather and move test from fbcode.

---

lib/Backends/TraceEvents.cpp

*Description*: I had noticed that some of the Scoped TraceEvents had incorrect timestamps, often with zero duration. There were two causes of this:
* In one case I forgot to name the object, which means it's destroyed immediately.
* Since the trace block object is never referenced the compiler was reordering the end timestamp to immediately after the creation of the object (rather than when the scope ended). Adding a memory fence prevents this reordering.
*Testing*: unit tests & a manual test inspecting trace events.

[tracing] fix ScopedTraceBlock reordering bug

---

lib/Backends/BackendUtils.cpp

*Description*: This PR adds a command line flag ( reuse-activation-memory-allocations) which allows toggling reuse of activation allocations. This is useful for debugging.
*Testing*: ninja test, ran with resnet-runtime. 
fixes #2870

Added a command line flag to toggle activations memory allocation reuse
