pytorch/glow

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h
Use these helpers to copy mutable and constant weights to device and to copy mutable weights from device.
Also make sure, that constant weights are copied to the device only once.
=> [opencl] Add helper methods to copy values to and from OpenCL devices

tests/unittests/BackendTestUtils.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/JITTest.cpp
All of our transposes in unit tests are 4D.  Which is probably realistic, but we should exercise more stuff.
=> [unittest] Simple 2D transpose test

lib/Backends/OpenCL/OpenCL.cpp
Use size in elements instead of size in bytes for the computation of a slice size.
=> [opencl] Fix a trivial bug in the implementation of gather

lib/Backends/CPU/libjit/libjit_matmul.cpp, tests/benchmark/GemmBench.cpp
Our matmul implementation is pretty good. In this PR I changed the implementation of the register-blocked multiplication. Before we were multiplying 2 * 4 registers. This is 8 FMAs for 6 loads. I changed this to 3 * 4. This resulted in 12 FMAs for 7 loads, which gives a better compute ratio. 
Additionally, with the 8-FMA implementation we did not have enough operations to fill the two ports of FMA that had a latency of 5 each. This resulted in 80% utilization. 
By providing 12 FMAs we saturate the FMA ports and jump to 100% utilization. 
On the benchmark that checks [768 x 768] * [768 x 768], we jump from 80 Gflops/sec to 100Gflops/sec.
=> [CPU] Tune the matmul implementation for better FMA utilization

tests/unittests/InterpreterTest.cpp
Current line coverage is 76.8%  but should be much higher.
This is due to high skew by some of the low coverage pieces. Fix coverage for backends.
=> [trivial/coverage] Increase coverage for Backends related code.

tests/unittests/InterpreterTest.cpp
This test runs in about 1 second now, rather than 10.  (I tried with some different random seeds, and it seems to still converge reliably)
=> [unittest] Use momentum to converge nonLinear test faster

include/glow/Graph/Nodes.h, lib/Optimizer/GraphOptimizer.cpp
Provide a proper initialization value to createVariable. The default value of 0 asserts when the training kind is Xavier.
=> Fix a Variable creation bug in optimizeTranspose

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/Backends/OpenCL/kernels.cl, tests/unittests/OCLTest.cpp
This operation is necessary for the training mode. It is not optimized for speed yet.
The implementation is making use of atomics to ensure the correctness of the results when this kernel is executed by multiple threads on GPUs.
=> [opencl] Add convolutiongrad support

include/glow/Base/Type.h, lib/Backends/OpenCL/CMakeLists.txt, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/Backends/OpenCL/Transforms.cpp, lib/Backends/OpenCL/kernels.cl, lib/Backends/OpenCL/kernels_fwd_conv.cl, tools/ClassGen/Backends/OpenCL/CMakeLists.txt, tools/ClassGen/Backends/OpenCL/OpenCLSpecificInstrs.h, tools/ClassGen/Backends/OpenCL/OpenCLSpecificInstrsVerification.h, tools/ClassGen/Backends/OpenCL/OpenCLSpecificNodes.h, tools/ClassGen/Backends/OpenCL/OpenCLSpecificNodesVerification.h, tools/ClassGen/CMakeLists.txt, tools/ClassGen/InstrGen.cpp, tools/ClassGen/NodeGen.cpp
This implementation uses standalone parameterized convolution kernels heavily based on the kernels produced by libDNN. 
The kernel is parameterized by means of macro-definitions, which define such properties like size of the filter, padding, stride, sizes of workgroups, etc.  The OpenCL backend produces specialized convolution kernels by providing these parameters based on the parameters of the current convolution instruction and its operands. 
To achieve their efficiency, the kernels work with inputs and weights in the NCHW format, which is often used for GPUs kernels due to more optimal memory access behavior. Since Glow by default uses the NHWC format, I introduced new OpenCL-backend nodes and instructions for convolutions and pooling. NHWC versions of these nodes are converted into …
=> [opencl] Implement fast convolution kernels

examples/ptb.cpp, include/glow/Base/Tensor.h, include/glow/IR/IRBuilder.h, lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/CPU/AllocationsInfo.h, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/DebugInfo.cpp, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/IR/IRBuilder.cpp, lib/IR/IRGen.cpp, lib/IR/Instrs.cpp, lib/Optimizer/IROptimizer.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/IROptTest.cpp, tests/unittests/OCLTest.cpp, tools/ClassGen/InstrGen.cpp
The main aim here is optimizing the pattern seen by Concats IRGen'd into InsertTensor. If all inserts are into the first dimension, then we can replace the InsertTensor with a TensorView with the same offset as the InsertTensor. This is because the underlying memory is contiguous for the InsertTensor/TensorView.
This improves ptb execution time on the CPU backend from 7.1 -> 6.2 seconds, which has a big ConcatNode.
For now it only applies to insert tensors with an alloc as the input; I believe this is most common/important.
=> Optimize InsertTensors into TensorViews with Offsets.

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/kernels.cl
Use more threads when launching the kernels and let each thread do less work. It increases the amount of work that can be done in parallel and leads to a better GPU utilization.
PTB is much faster with these changes.
=> [opencl] Improve performance of inserttensor, extracttensor and transpose

tests/unittests/CMakeLists.txt, tests/unittests/UtilsTest.cpp
I was pretty sure this was the case from looking at code/comments, but, "trust but verify".  This test takes 1 ms in the common case so it's not like it adds any real overhead.
=> [test] Verify that nextRandInt actually gets a closed interval

include/glow/Base/Tensor.h, tests/unittests/JITTest.cpp
So, JITTest.quantizedBatchAddTest fails with this diff, but it looks like its numerically unstable anyways (it fails several times if I run it with `--gtest_repeat=20`, even without this diff).  Is our interp quantization supposed to be equivalent to cpu always?
=> [tensor] Template specialization of randomize for integral types

lib/Backends/OpenCL/OpenCL.cpp, lib/Graph/Graph.cpp
A var used only in assert() is viewed as "unused var" in release-mode. Fixed the code the avoid this warning reporting in Release build.
=> fixed the Release build warning issue

examples/fr2en.cpp, examples/ptb.cpp, include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, lib/Importer/Caffe2.cpp, lib/Importer/ONNX.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Optimizer/Lower.cpp, lib/Quantization/Quantization.cpp, tests/unittests/InterpreterTest.cpp
Change the Concat API to accept NodeValue instead of Node*. We may want
to concat nodes with multiple results and the Node* API does not allow
this.
=> [Graph] change the Concat API to accept NodeValue instead of Node*

lib/Optimizer/GraphOptimizer.cpp
Don't try to merge quantized matrices because their quantization parameters may not match.
This was detected by @rdzhabarov in CR.
=> Don't try to merge quantized matrices.

lib/Backends/CPU/libjit/libjit.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/JITTest.cpp
The first commit adds a new unit test that stresses the insert/extract tensor instructions. The second commit simplifies the implementation of insert/extract. The recursive implementation was not optimizable and resulted in a sequence of recursive calls for each pixel for each dimension. The new version (which is a sequence of loops) optimizes pretty well.
=> Cleanup the Insert/Extract implementation and add a unit test. 

tests/unittests/OperatorTest.cpp
Didn't see this last night since I wasn't running with ASAN locally (and Travis doesn't run with OpenCL)
=> [tests] Disable OpenCL GroupConvolution (ASAN violation)

.gitignore, tests/unittests/CMakeLists.txt, tests/unittests/HyphenTest.cpp
This test lives in its own .cpp file, but runs as part of the JITTest suite.
It trains and tests a small MLP network to hyphenate words.
=> Add a new HyphenTest unit test.

include/glow/Graph/Graph.h, lib/Graph/Grad.cpp
to address the issue: https://github.com/pytorch/glow/issues/1050
=> [cleanup] Add constness to the param in differentiate function.

lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/CPU/FunctionSpecializer.cpp, lib/Backends/CPU/LLVMIRGen.cpp
This verification is similar to that done in LLVM's `CallInst::init`, but is only done on Debug builds of LLVM.
Also fixed a bug that is caught by this verification.
=> Add verification of function signatures for LLVM CallInsts

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, tests/unittests/quantizationTest.cpp
Allow nodes in different functions to have the same names. This change allows us to clone functions and keep the original names. This is useful for a number of use cases. First, we can perform quantization on the cloned functions. Second, preserving node names is useful for multi-versioning compilation for different resources on the device and for different batch sizes. Finally, this allows us to remove some of the workarounds that we have around function cloning.
After landing this change I plan to add another end-to-end quantization test ("where's Waldo" test) and cleanup some of the cloning APIs.
=> [Graph] Allow nodes in different functions to have the same names.

lib/Backends/OpenCL/kernels.cl
We should never use size_t in kernels declarations, because its size is platform dependent.
And we should use C-style casts in our kernels, because OpenCL is based on C, not C++.
Big thanks to @terminal-oni, who reported these issues in #1076
=> [opencl] Fix a couple of reported bugs related to the usage of size_t and type casts

lib/Backends/CPU/LLVMIRGen.cpp, tests/unittests/JITTest.cpp
An instruction cannot be included into a stacked kernel if any of its mutated buffers overlap with any buffer used by instructions added to the stacked kernel before, but do not occupy exactly the same memory region. This condition comes from the fact that all buffers used by a stacked data-parallel kernel should be unrelated (i.e. no overlap) or data-parallel (i.e. occupy exactly the same memory region).
This should fix the "Heisenbug" discovered by @jfix71, where disabling the sharing of buffers, but enabling the hoisting of `dealloc_activation` instructions resulted in some unit tests failures.
=> [stacking] Fix a very subtle bug happening during the creation of stacked kernels

include/glow/Base/Tensor.h, include/glow/Graph/Graph.h, include/glow/Graph/Nodes.h, include/glow/Support/Random.h, lib/Graph/Grad.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Support/Random.cpp, tests/unittests/GemmTest.cpp, tests/unittests/HyphenTest.cpp, tests/unittests/JITTest.cpp, tests/unittests/MLTest.cpp, tests/unittests/OCLTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/UtilsTest.cpp, tests/unittests/gradCheckTest.cpp, tests/unittests/tensorsTest.cpp
This WIP addresses #1066.
1. Add a PRNG state to Module, seeded from a command line argument.
2. Require explicit PRNG state for `Handle::initXavier,randomize`.
3. TODO: Remove global state PRNG functions.
The `CPU/InterpAndCPU.QuantizedCmpLTEAndSelect` test is failing, presumably because it is sensitive to its pseudo-random sequence. I'll investigate.
=> Deterministic pseudo-random numbers

lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h
Group convolution is supported in CPU and Interpreter Backends.
=> Disable unrolling grouped convolution opt (lowerGroupConvolutionNode) lowerGroupConvolutionNode

lib/Backends/CPU/FunctionSpecializer.cpp, lib/Backends/CPU/LLVMIRGen.h
- The function specializer should use function cloning instead of relying on the inliner to perform specialization
The function specializer was relying on the inliner to kick in and produce a specialized body of a function by substituting constant arguments. This works for simple cases, but does not allow for performing any specialization before inlining, which is required in some cases.
This PR uses LLVM's cloning utilities to create the specialized body and makes the function specializer self-contained and not dependent on the LLVM's optimizer passes.
- Add a utility function for specializing specific calls for constant arguments
=> [llvm] More robust and flexible function specialization implementation

lib/Backends/CPU/FunctionSpecializer.cpp, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/Pipeline.cpp
Some NN models result in really huge number of Glow IR instructions. When they are emitted as LLVM IR it in turn results in very, very big "main" functions. And this is really bad for JIT performance, because it significantly increases the compilation times as many LLVM optimization passes have to iterate over very long instruction lists.
This commit introduces the logic to split big "main" function in LLVM IR into smaller ones. This is done during the LLVMIRGen phase. The algorithm basically allows to irgen at most N Glow IR instructions into a single LLVM function. If there are more Glow IR instructions to be lowered into LLVM IR, then a new LLVM function is created and called at the very end of the current LLVM function currently generated by LLVMIRGen. From this moment, LLVMIRGen …
=> [llvm] Limit the size of the emitted LLVM IR in the "main" function. Split it into multiple functions if required.

lib/Backends/CPU/FunctionSpecializer.cpp, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/Pipeline.cpp
Reverts pytorch/glow#1108
It looks like the current issue of producing huge LLVM functions was solved in a different way at the Glow graph and IR levels by introducing insert_tensor instructions with axis and by fixing issues with group convolutions.
Thus there is no need to complicate our LLVM codegen today.  Should the problem of generating huge LLVM functions pop up in the future again, we need to see if this or any other approach should be used to solve it.
=> Revert "[llvm] Limit the size of the emitted LLVM IR in the "main" function. Split it into multiple functions if required."

.travis.yml
Our tests are taking a long time - PRs are at 40 minutes right now, and seem to frequently time out.  I think this arrangement of builds will give us similar coverage, but might be faster, so I'm creating the PR to check.
=> [travis] Switch ASAN to Release mode; switch existing Release mode test to Debug

lib/Optimizer/IROptimizer.cpp
Not only this IRBuilder object was created, but never used, but it resulted in a rather significant compilation slow-down, because it is was created inside an often called hot function and apparently the destructor of IRBuilder is calling IRBuilder::deallocateActiveInstrs, which iterates over all IR instructions each time it is called.
=> [ir-optimizer] Remove unused IRBuilder object

include/glow/IR/IR.h, include/glow/IR/IRUtils.h, lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/CPU/AllocationsInfo.h, lib/Backends/CPU/DebugInfo.cpp, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/LLVMIRGen.h, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/IR/IR.cpp, lib/IR/IRBuilder.cpp, lib/IR/IRUtils.cpp, lib/Optimizer/IROptimizer.cpp, tests/unittests/IROptTest.cpp, tools/ClassGen/InstrBuilder.cpp
This change solves a number of compilation performance issues, because instructions can be found in the list or removed from the list very quickly.
The change touches many of the loops iterating over the instruction lists.
While looking at the loops iterating over the Glow IR instructions, also take the chance to tighten their const correctness. This includes tightening the const correctness of some APIs used by those loops as well.
=> [ir] Represent Glow IR instructions lists using LLVM's intrusive lists

lib/Optimizer/IROptimizer.cpp
I've found this to be useful when debugging.
=> [IROptimizer] Add command line option -dump-opt-mod to dump the optimized Module.

include/glow/Base/Tensor.h, include/glow/Base/Type.h
It looks like assert conditions were set incorrectly for max_tensor_dimensions -- we are allocating arrays of size `max_tensor_dimensions` to hold the shape of Tensors, but then disallowing Tensors of size exactly `max_tensor_dimensions`, which doesn't make any sense (e.g. we allocated the shape array to allow for up to 6 dimensions, but only allowed for up to 5 dimensional tensors).
=> [Tensor/Type] Fix asserts for allowed size of tensors

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, tests/unittests/OperatorTest.cpp
More support for seq2seq. This is essentially the opposite of Squeeze. I've seen it called either expand dims (Caffe2, numpy, TF) or unsqueeze (ONNX); I went with the majority naming.
=> [Graph/OperatorTest] Add ExpandDims operator, implemented as a Reshape

tests/unittests/MLTest.cpp
A few things have consistently come up in ML tests: 1. Calling setName() after creating a function named "main", and 2. putting an activation function between the last FC and softmax/regression.
I suspect these patterns get copied from existing tests, so, let's fix the existing tests :-).
=> [mltest] Consistently follow some best practices

include/glow/Graph/Graph.h, include/glow/Graph/Node.h, include/glow/Graph/Utils.h, include/glow/IR/IR.h, lib/Backends/CPU/Transforms.cpp, lib/Backends/OpenCL/Transforms.cpp, lib/Graph/Grad.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/IR/GraphScheduler.cpp, lib/IR/IRGen.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Optimizer/Lower.cpp, lib/Optimizer/Quantization.cpp, lib/Quantization/Quantization.cpp, tests/unittests/BackendTest.cpp, tests/unittests/graphGradTest.cpp, tests/unittests/graphOptzTest.cpp, tests/unittests/graphTest.cpp
Nodes are often moved around or removed from the nodes lists by different optimization passes and thus it makes sense to use LLVM's intrusive lists to make such operations fast.
=> Represent lists of graph nodes using LLVM's intrusive lists

tests/unittests/MLTest.cpp
If I understand correctly, we should always set EE's batchSize equal to the batch dimension of the training tensors, so that SGD is done "properly".  (If I don't understand correctly, this diff is a good opportunity to correct me :-D ).  I guess this doesn't really "matter", but it makes the test code easier to understand for folks like me who are learning ML while trying to write a test case.
=> [mltest] Set batchSize where it makes sense

tests/unittests/MLTest.cpp
hi. a few changes i made since my last try:
1). Systematically generated training/testing data, instead of randomly. (Trains faster with simpler network)
2). Use 2 fc only. One with 4 output depth, one with 1 output depth. Used an tanh activation function in between. (I have tried with sigmoid, but worse than tanh)
3). Training data is still sampled from [0.75,1.5], with testing data sampled from [1.1, 1.2]. 
4). The execution time of this MLTest is much shorter than last try. 
- Interpreter/MLTest (86 ms total)
- JIT/MLTest (386 ms total)
- OpenCL/MLTest (948 ms total)
Short than existing test like "learnXor"
=> [mltest] LearnLog: new ML test case

lib/Backends/CPU/FunctionSpecializer.cpp, lib/Backends/CPU/LLVMIRGen.h
The code is still broken/buggy because we only avoid specialization when
the input array is float-ptr, and not when it's say, i8-ptr.
=> [Cleanup] Refactor the argument specializer a bit. NFC.

include/glow/Base/Tensor.h, include/glow/Graph/Graph.h, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/CPU/libjit/libjit_defs.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/Base/Tensor.cpp, lib/Graph/Graph.cpp, lib/Optimizer/Lower.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/OperatorTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/NodeGen.cpp
For seq2seq, we need to add in an axis for batched reduce add. This means the current simple implementation is no longer sufficient, since we need to reduce in dimensions other than the first one. I am wondering if the implementation I have here in InterpreterNodes for `fwdBatchedReduceAddInst()` is a preferable direction compared to the other options.
The problem is that we don't know the number of dimensions of the tensor that we want to iterate over ahead of time. To handle this in other cases, we generally do one of two things. One, write multiple cases for each different number of dimensions of different loop nest depths (e.g. in `tryTransposeFastImpl()`, `libjit_transpose_generic()`, `libjit_insert_tensor()`). Or two, have a generic recursive version (e.g. in …
=> Add axis to the batched add reduce

tests/unittests/CMakeLists.txt, tests/unittests/GemmTest.cpp
This runs much faster, and the point of this test is the correctness of libjit_matmul, not the JIT infra itself.
=> [tests] Use libjit directly in GemmTest

lib/Backends/CPU/FunctionSpecializer.cpp, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/LLVMIRGen.h, lib/Backends/CPU/libjit/libjit.cpp
This patch disables the specialization of the 'offset' parameter in the insert/extract tensor instruction. It does so by asking the specializer not to specialize certain arguments that are passed in a set of LLVM values. It's important to disable the specialization of the insert/extract instructions because the code is instantiated multiple times with slightly different offsets, and this causes code bloat.
After disabling the specialization of the offset I had to fix the implementation in that could not figure out that the offsets don't alias with anything in the loop.
=> [Specializer] Allow codegen to disable selected argument specialization

tools/loader/ImageClassifier.cpp
Removing the assert, because every ONNX model is different. Later we may see models, supporting any batch size.
=> [ImageClassifier] Remove assert for ONNX models and batch size.

include/glow/Importer/ProtobufLoader.h, lib/Importer/Caffe2.cpp, lib/Importer/ONNX.cpp, lib/Importer/ProtobufLoader.cpp
Enable more code sharing (e.g., hashNodeByName calls getNodeByName now), add
more methods to create and register variables.
Thanks to this change, the map that registers the variable is modified in only
one function. Moreover, now, all the calls to createVariable are encapsulated
in a method, which will make the transition to use load nodes easier.
NFC.
=> [importer] Refactor the creation of variables

include/glow/IR/IR.h, lib/Backends/CPU/CMakeLists.txt, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/DebugInfo.cpp, lib/Backends/CPU/FunctionSpecializer.cpp, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/LLVMIRGen.h, lib/IR/IR.cpp
This is supposed to be a fix for #1157 
While debugging the issue, I also changed a couple of things to make the debug info emission more robust and to make the debugging of Glow networks in terms of Glow IR more convenient.
Here is a list of changes:
- Legalize names of all instructions
Names of instructions inside IRFunctions are always uniqued. But they were not legalized and thus they could not be used in the debugger, when debugging Glow networks, because debuggers expect legal C identifiers as variable names.
- Do not explicitly emit debug info for specialized functions
There is no need to explicitly emit a debug info for the specialized function. If the original function had it, the cloner would have automatically copied it into the specialized function. And if the original …
=> [debug-info] Improvements and bug-fixes related to debug info emission

include/glow/Support/Support.h, lib/Support/Support.cpp
This PR provides glow::outs(), glow::errs() and glow::dbgs() which are similar to llvm::outs(), llvm::errs() and llvm::dbgs(). For now their just wrap the corresponding LLVM functions.
The main difference is that these functions can always be used, even under debugger, which is different from their LLVM counterparts which can be used under debugger only when debug builds of LLVM are used.
For example, you can use these streams in LLDB to dump LLVM module or types like:
`print llmod->print(glow::outs(), 0, 0, 0)`
=> Provide helper functions to return output streams for stdout, stderr and debug output

include/glow/Support/Debug.h, lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/FunctionSpecializer.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/IR/GraphScheduler.cpp, lib/Optimizer/IROptimizer.cpp, lib/Support/CMakeLists.txt, lib/Support/Debug.cpp
I wanted to use this debugging functionality but realized I needed a Debug build of llvm to get access to -debug and -debug-only.  Feels like we should have our own flavor, so I've added -debug-glow and -debug-glow-only.
=> [support] Introduce DEBUG_GLOW macro

lib/Backends/CPU/DebugInfo.cpp
This variable is used only in an assert, when DEBUG mode is used. In release mode, a warning was produced.
Thanks @beicy for noticing it!
=> Silence a warning about unused variable `name`. NFC.

lib/Graph/Graph.cpp, tests/unittests/graphTest.cpp
`Module::vars_` calls `erase` using the iterator taken from a copied variable list. This causes iterators of `vars_` to iterate more than its size and access invalid memory.
=> [fix] Fix variable erasure.

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/IR/IRGen.cpp, tests/unittests/OperatorTest.cpp, tools/ClassGen/NodeGen.cpp
The load node represents the action of loading a variable to the
local memory of the device.
This is the first step to handle the flow of data across different
devices. The rough plan is:
- Model memory transfer explicitly with Save and Load nodes
- Extend Variables with some information about their location (e.g., addrspace x on GPU)
- Teach codegen how to materialize those synchronization point (right now we lower Loads into copys)
- Extend the runtime to issue the right DMA (more generally) transactions
=> [GraphIR] Add a Load node

lib/Backends/Backends.cpp, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h
Until now, Backends.cpp included backends-specific header files defining backend classes with all the internal details. This exposed way too much information about the backends implementations. But it was not really necessary. Backends.cpp just needs to know how to create new instances of backends, i.e. it just needs declarations of createXYZBackend methods.
Let's move all such declarations into a dedicated central header file Backend.h and stop including the backend-specific header files into Backend.cpp.
Each new backend needs to add its create method to Backend.h
=> Stop exposing details of the backends implementations

lib/Graph/Nodes.cpp
I was flipping through Nodes.cpp and this caught my eye.  For what it's used for (hashing) it probably doesn't matter too much, it just seems closer to the intent of the code.
=> [graph] Make toBinary use memcpy instead of float->int casts

tools/ClassGen/Backends/OpenCL/OpenCLSpecificNodesVerification.h
Fixes missed change from from https://github.com/pytorch/glow/pull/1154 which has broken the OCL unit tests.
=> [OpenCLSpecificNodesVerification] Fix broken pad for conv output dims

include/glow/Graph/Graph.h, include/glow/IR/IR.h, lib/Graph/Graph.cpp, lib/IR/IR.cpp
I keep wanting to build filenames like `std::string(F->getName()) + "_suffix"`, and it's kind of tedious to wrap that in `(...).c_str()`.  I picked `llvm::StringRef` since it's lightweight compared to `std::string`
=> Use llvm::StringRef for dumpDAG methods

lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphOptzTest.cpp
It appears that tests for the folding were missing :).
Added the base one + multiple usages.
=> [quantization] Fold quantize node into variable with multiple usages.

include/glow/Backends/LayoutConverter.h, lib/Backends/OpenCL/Transforms.cpp
This allows for other backends to do NCHW conversion more simply. Note that because OCL currently only supports equal padding, it does not use the templatized version of the conversion loop for Conv.
=> [OCL/Backends] Templatize NCHW conversion for use by other backends

lib/Backends/CPU/libjit/libjit.cpp, lib/Quantization/Quantization.cpp
Should be covered by existing quantization tests for interpreter and CPU backends.
=> [quantization] Unify quantization math with Caffe2.

lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphOptzTest.cpp
If the inputs of concat are all reshape nodes, and the inputs of reshape are able to be concatenated, then we can perform concat first and then reshape.
`Concat(Reshape(x) * N) -> Reshape(Concat(x * N)).`
=> [graph-optimizer]  Optimization on ConcatNode

docs/Optimizations.md, lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphOptzTest.cpp
@jfix71 mentioned that there are some redundant rescales on the fr2en graph.
This PR should help to eliminate those as well.
=> [quantization/optimization] Merge rescales into min, max nodes.

tests/unittests/graphTest.cpp
Warning when building in non-cpu, non-open cl mode.
=> [fix warning] Fix compiler warning

examples/fr2en.cpp, lib/Graph/Graph.cpp, tools/ClassGen/NodeBuilder.cpp
Some places used the Node instead of NodeValue to get the type and dims. This issue was uncovered due the opti recently landed by @ZchiPitt , as the inputs were previously Reshapes but are now TopKs. Also small cleanup to use `getIndices()` directly instead of the implicit NodeValue via `{topk, 1}`.
=> Unbreak/cleanup fr2en 

include/glow/Backends/Backend.h, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.h
`Backend::clear` isn't called anywhere except the various destructors, so I think we should just fold it in to those.  It's existence makes me a bit uncomfortable anyways, since it seems like an invitation to leave unexpected state lingering around
=> [backends][nfc] Remove Backend::clear()

include/glow/IR/IR.h, include/glow/IR/IRBuilder.h, lib/Backends/CPU/DebugInfo.cpp, lib/IR/IR.cpp, lib/IR/IRBuilder.cpp, tools/ClassGen/InstrBuilder.cpp
Currently we do this only when outputting the IR for human consumption (dump ir, emit debug info).  But this means we're mutating the state of the world before outputting it, which can be weird for debugging; and it prevents us from using `const IRFunction *` in surprising places.
=> [ir] Give instruction unique names eagerly

include/glow/IR/IR.h, lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/CPU/AllocationsInfo.h, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/CPU/DebugInfo.cpp, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/LLVMIRGen.h, lib/Backends/Interpreter/Interpreter.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/IR/IR.cpp
Backends should just look at the IR function, not mutate it.  Hopefully this will make future refactoring easier, too.
The only functionality change is that the CPU backend was `clear`ing the IR in its destructor.  That feels like a no-no since the IR is really owned by the EE.
=> Make IRFunction const in backends

examples/ptb.cpp, include/glow/ExecutionEngine/ExecutionEngine.h, lib/ExecutionEngine/ExecutionEngine.cpp, tests/unittests/BackendTest.cpp, tools/loader/Loader.cpp
To preserve debuggability, I added -dump-ir and -dump-ir-dag to ExecutionEngine, which also saves us re-implementing it in every example program :-).
I did have to work around the lack of getIR in one unit test, which is the most substantial code change in this diff.
=> [ee] Remove getIR from API

.travis.yml
Matrix does not support conditional switch off for subjobs, which would be needed if we want to run cron jobs (for time consuming runs of run.sh etc).
Currently, matrix capabilities are not used anyways.
=> [travis] Make jobs instead of matrix.

lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h
We don't need to hang on to LLVMIRGen or AllocationsInfo after generating code.  It turns out it's fairly easy to make these stack allocated in `init()`.
=> [cpu] Make codegen not retain state

include/glow/Importer/ProtobufLoader.h, lib/Importer/ProtobufLoader.cpp, tools/loader/ImageClassifier.cpp
This patch wires the load node in the importer.
This is one step closer for making the load and save nodes the
only users of Variable.
=> [importer] Use Variable through Load node

tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTest.cpp
I was looking into making backends own their passed-in IRFunction (i.e. the unique_ptr interface in #1234 ) and hit a weird memory bug stemming from this issue. In these cases we invoke the backend before we've finished building our IR, since the dtor still needs to `deallocateActiveInstructions()`.  We could manually call that, but it still leaves us with a dangling pointer.
Also note the irOpt tests all call ::optimize on partially built IR for this same reason, but I don't think it's a problem there since the IR is still under construction anyways.
=> [unittest] Properly scope IRBuilder before invoking backend

include/glow/Quantization/Base/Base.h, include/glow/Quantization/Quantization.h, lib/Optimizer/Lower.cpp, lib/Quantization/Base/Base.cpp, lib/Quantization/Quantization.cpp
Our IntLookupTable is a nice generic transformation, but it's not clear every backend would want to use its exact implementation. This PR allows a backend to prevent the transformation (via `shouldLower()`), and then implement the quantized Tanh/Sigmoid however they want (e.g. replace it with their own backend-specific insts/nodes, etc.).
=> [Quantization/Lower] Move to lowering quantized Tanh/Sigmoid to IntLookupTable

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/Transforms.cpp, lib/Backends/OpenCL/kernels.cl, tests/unittests/OperatorTest.cpp, tools/ClassGen/Backends/OpenCL/OpenCLSpecificInstrs.h, tools/ClassGen/Backends/OpenCL/OpenCLSpecificNodes.h, tools/ClassGen/Backends/OpenCL/OpenCLSpecificNodesVerification.h
So far, the first half of the output values are correct, but the rest are all zero. The test is NonSquarePaddingConvolution in OperatorTest.cpp
=> Non-Square padding for OpenCL backend

include/glow/Backends/Backend.h, include/glow/Backends/CompiledFunction.h, lib/Backends/CPU/CMakeLists.txt, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/CPU/CPUFunction.cpp, lib/Backends/CPU/CPUFunction.h, lib/Backends/CPU/FunctionSpecializer.cpp, lib/Backends/CPU/Pipeline.cpp, lib/Backends/Interpreter/CMakeLists.txt, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp
Finally I think things are in shape to bite off #1234.  This PR creates the CompiledFunction interface, and modifies Backend::init (now known as `compile`) to produce it, and implements that interface in the Interpreter.  (All other tests and backends are not ported yet).
What do you all think?  (In retrospect maybe the interpreter was a weird place to start, because its "forward pass" is very heavyweight.  But hopefully that doesn't cloud things too much.)
=> [backend] Factor out CompiledFunction from Interpreter

include/glow/Importer/ProtobufLoader.h, lib/Importer/ProtobufLoader.cpp
Users of ProtobufLoader should not need to create variables directly.
NFC.
=> [ProtobufLoader] Make createVariable a protected API

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h
The OpenCL backend references/mutates quite a bit of state during execution, so I'm essentially wrapping everything in the current backend inside a CompiledFunction.  At least this subdivision lets us maintain some separation between backend creation and function compilation.
=> Use CompiledFunction in OpenCL Backend

lib/Graph/Nodes.cpp, lib/Importer/ProtobufLoader.cpp, tools/ClassGen/NodeGen.cpp
Change the name of the input to Address so that we can use getVariable
to return the properly typed variable.
NFC.
=> [GraphIR] Have LoadNode::getVariable return Variable

include/glow/Graph/Grad.h, include/glow/Graph/Node.h, include/glow/Graph/Nodes.h, lib/Graph/Grad.cpp, lib/Graph/Graph.cpp, lib/Graph/Node.cpp, lib/Graph/Nodes.cpp, lib/IR/IRGen.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Optimizer/Lower.cpp, lib/Quantization/Quantization.cpp, tests/unittests/graphTest.cpp, tools/ClassGen/MemberType.h, tools/ClassGen/NodeBuilder.cpp
This PR consists of three major changes:
- It introduces a new type NodeHandle that is used instead of NodeValue inside Nodes to reference the results of other Nodes. NodeHandles register themselves as users in the use-lists. NodeValue becomes a simple POD which does not register itself in the use-lists.
- The affected APIs are updated to use NodeHandle instead of NodeValue where appropriate
- The UnownedNodeValueMap type is removed as it is not needed anymore
=> Introduce a NodeHandle type to make sure that use-lists of Nodes only contain uses by other Nodes

tests/images/run.sh, tools/loader/ImageClassifier.cpp
We are working with models trained for inputs in the -1:1 range.
This small PR then proposes to add the "1to1" mode to the image classifier application.
=> Add the 1to1 mode (-1:1 range) to the image classifier application

include/glow/Graph/Node.h, lib/Graph/Node.cpp, tests/unittests/graphTest.cpp, tools/ClassGen/NodeBuilder.cpp
It is now possible to iterate over a use-list of a Node and see which nodes refer to it. NodeUse has now a getUser() method to get this information.
To provide this functionality, we store in each NodeHandle a pointer to the parent node that contains it.
One possible concern regarding this PR is that we add a pointer per NodeHandle, which increases the amount of memory used by Nodes. I was playing with the idea of using (small) offsets from the beginning of the object instead of pointers. But this does not work with nodes like Concat, which contain `std::vector<NodeHandle>`. Such handles inside vectors are allocated on heap and can be very far away from the beginning of the parent object. Therefore, their offsets may require as much memory as a pointer. Hopefully, this possible memory …
=> Provide the functionality to iterate over all nodes referencing a given node

lib/Graph/Graph.cpp
Cleanups based on @rdzhabarov review of #1280
- Use `auto *`
- Use `llvm_unreachable`
- Use `const auto &`
=> Minor cleanups of the graph verifier. NFC.

include/glow/Graph/Node.h, tests/unittests/graphTest.cpp, tools/ClassGen/NodeBuilder.cpp
Prior to this patch, copying a NodeHandle around (like with a vector::resize)
would not properly set the tracking of the value.
For instance, this was impossible to pretty print nodes with vector of inputs
like concat, because our pretty printer was doing creating a local NodeHandle.
This patch features a proper copy constructor for NodeHandle and at the same
time, make sure pretty printing vectors of NodeHandle doesn't create temporary
objects.
NFC.
=> [GraphIR] Add a proper copy constructor for NodeHandle

tests/unittests/graphTest.cpp
Our graph does not model the memory dependencies explicitly.
As a result, if we have a variable is written and read on different
data paths, the scheduler may be unlucky and we read the wrong
version of the variable.
Essentially, if you have:
A
/ \
write read
The scheduler can produce either:
write A
read A
or
read A
write A
Obviously this does not produce the same output.
Glow intended semantic is that write should happen last, but with
our current algorithm, this is actually possible to fool the
scheduler not to do that.
=> [unittest] Add a test case exposing a bug in our scheduler

include/glow/Importer/Caffe2.h, include/glow/Importer/CommonOperatorLoader.h, include/glow/Importer/ONNX.h, lib/Importer/Caffe2.cpp, lib/Importer/ONNX.cpp
Some ONNX ops have different versions. For example, Gemm-1 and Gemm-6 has "broadcast" attr whose default value is 0, while Gemm-7 and Gemm-8 version have no such attribute and always broadcast Tensor C. So we get op_version for each model to handle different op versions if necessary. This PR is triggered by inception_v2 ONNX model and only handles Gemm op versions. I think we could support different op version by demand in the future.
=> [ONNX] ONNX operator version 

lib/Graph/Graph.cpp
We already check that when a node has a parent link its parent holds a
reference to the node, but we were missing the check in the other direction.
The patch adds this check.
NFC.
=> [GraphIR] Verify that all nodes belongs to the function that holds them

lib/Optimizer/GraphOptimizer.cpp
The call of simplifyNode for the RHS was ignored when the call of simplifyNode for the LHS was successful. It was ignored even if RHS was actually simplified and thus any nodes created by this simplification were produced, but never used and later removed by the dead code elimination pass.
=> [graph-optimizer] Avoid useless calls of the simplifyNode transformation

lib/Backends/OpenCL/kernels.cl
Replace the use of nearbyintf() with round(), as it was not fully supported by OpenCL
=> [fix]Replace the use of nearbyintf() with round()

include/glow/Base/Type.h, include/glow/Importer/CommonOperatorLoader.h, lib/Importer/Caffe2.cpp
Since only Caffe2 support FC op, we move it to Caffe2.cpp. In ONNX, if the input is 2-dims, Gemm op can be used to represent FC. If the input has > 2dims, we can use Reshape+Gemm for FC layer.
According to Caffe2 FC defs, the input and weight don't have to be 2-dims, and they will be coerced into 2D dims for calculation. In Glow's FC node, the input will be flatten to 2-dims, but the weight needs to be 2D. Therefore, the weight loaded from Caffe2 model should be coerced into 2-dims before the FC node is created.
The "axis" and "axis_w" params of FC operators in Caffe2 are supported. https://caffe2.ai/docs/operators-catalogue.html#fc . The params are used in inception_v1 models.
=> [Importer] Support "axis" and "axis_w" params of  "FC" op in Caffe2.

lib/IR/GraphScheduler.cpp, tests/unittests/graphTest.cpp
When a variable is used as output in a save node, this is expected
to be its last use. Make sure the GraphSchedule looks at the implicit
dependencies between all the uses of a variable and its save node
when walking the dependencies.
This fixes issue #1283.
=> [GraphScheduler] Honor memory dependencies implied by the SaveNode

lib/Graph/Nodes.cpp
Check that types of inputs/outputs and their gradients are the same.
=> [graph-verifier] Add stricter checks for gradient nodes

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/Backends/OpenCL/kernels.cl, tests/unittests/OperatorTest.cpp
Support quantization for RescaleQuantizedInst
-- Modified the "RescaleNode" test so that createRescaleQuantized() didn't get optimized out. 
-- RescaleNode test stands as the test for this PR
=> [quantization][opencl]: Support quantization for RescaleQuantizedInst

lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/CPU/AllocationsInfo.h, lib/Backends/CPU/BundleSaver.cpp, lib/Backends/CPU/CPUBackend.cpp
We don't currently reuse the AllocationsInfo object anywhere, and it seems better to discourage that anyways.
=> [cpu] Remove AllocationsInfo::clear. NFC

lib/Backends/OpenCL/kernels.cl
Remove trailing underscore in public struct fields in kernels.cl
=> [trivial]: Remove trailing underscore in public struct fields

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/Backends/OpenCL/Transforms.cpp, lib/Backends/OpenCL/kernels.cl, tests/unittests/OperatorTest.cpp
Support quantization for the slow implementation of ConvolutionInst.
-- Changed the Transform.cpp so that we execute the slow convolution inst when input type is quantized.
=> [quantization][opencl]: Support quantization for the slow ConvolutionInst

lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit_conv.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/BackendTestUtils.h
Before generating libjit_convDKKC8_f function, we can guarantee that (output_channel / group) is divisible by 64. However, in libjit_convDKKC8_f function, we handle "8 * numDepthRegs * depthStrips" channels per time (i.e. d += 8 * numDepthRegs * depthStrips). The  (output_channel / group) may not be divisible by 8 * numDepthRegs * depthStrips. Under such circumstance, the calculated filter index may be out-of-bounds. (An example is in Inception_v1 Caffe2 model, the outChannel is 192, numDepthRegs is 8 and depthStrips is 2.)
One solution is in node level, we apply DKKC8 only if output_channel / group is divisible by 512, since numDepthRegs could be only 2 or 8 and depthStrips could be only 1, 2, 4, 8. But I think this would affect the performance. 
The second way is add boundary check in …
=> [CPU] Fix DKKC8 filter out-of-bounds issue.

include/glow/Base/Tensor.h, lib/Base/Tensor.cpp
Replace calls to sliceSize with Type::getSliceSize(). Slice information is related to Type and not to the tensor. Graph node operands are not backed by tensors and we still want to figure out information about them without allocating a tensor.
=> [Cleanup] Move the method sliceSize from Tensor to Type.

tests/images/run.sh, utils/download_caffe2_models.sh, utils/download_onnx_models.sh
The following result is for both Caffe2 and ONNX models:
Model: inception_v1
File: tests/images/imagenet/cat_285.png Result:281
File: tests/images/imagenet/dog_207.png Result:207
File: tests/images/imagenet/zebra_340.png Result:340
Model: inception_v2
File: tests/images/imagenet/cat_285.png Result:173
File: tests/images/imagenet/dog_207.png Result:124
File: tests/images/imagenet/zebra_340.png Result:79
Model: bvlc_alexnet
File: tests/images/imagenet/cat_285.png Result:281
File: tests/images/imagenet/dog_207.png Result:207
File: tests/images/imagenet/zebra_340.png Result:340
For inception_v2, I run caffe2_pb_runner.py and got the same result. But it is not added into run.sh due to the incorrect results.
=> [run.sh] Add inception_v1 and bvlc_alexnet models.

include/glow/Optimizer/Optimizer.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Grad.cpp, lib/Graph/Nodes.cpp, lib/Optimizer/Lower.cpp, tests/unittests/graphTest.cpp, tools/ClassGen/NodeGen.cpp
I removed the CompilationMode from `lower()` in a separate commit here as well. This resolves https://github.com/pytorch/glow/issues/1309.
=> Add MeanVarNormalization for use by BatchNormalization for training

include/glow/Quantization/Base/Base.h, include/glow/Quantization/Quantization.h, lib/Quantization/Base/Base.cpp, lib/Quantization/Quantization.cpp, tests/unittests/quantizationTest.cpp, tools/loader/Loader.cpp
Plumb quantization schema up to the load command line so that we can choose which kind of quantization (symmetric/asymmetric) we want to use.
This is related to #1321.
=> Add quantization schema

include/glow/Graph/Nodes.h, lib/IR/IRGen.cpp, tests/unittests/graphOptzTest.cpp, tools/ClassGen/NodeBuilder.h
Our node generator added the Node suffix to all nodes, but our variables
don't have the 'Node' suffix. To get things to work someone added the
line:
class VariableNode : public Variable{};
This commit removes all references to VariableNode and teaches NodeGen 
not to emit the Node suffix.
=> Variable: Remove the VariableNode hack. NFC.

lib/Backends/CPU/LLVMIRGen.cpp
I saw a "control reaches end of non-void function" error here when compiling with `-Wreturn-type`.  We could also use `GLOW_ASSERT(false && ...)`, but either way we need to do something that actually terminates the function here.
=> [trivial] Use GLOW_UNREACHABLE where appropriate

lib/Backends/OpenCL/kernels.cl
doing `float(5)` doesn't work in `C99`. We should always use `(float)5`
=> [OpenCL] Fix compilation error in a kernel.

lib/Importer/Caffe2.cpp
A Caffe2 model has those 2 operators. Glow doesn't support MKL ops now, so we just pass the value in the network to make sure the model can be supported.
=> [Operators] Support CopyCPUToMKL and CopyMKLToCPU

include/glow/Backends/LayoutConverter.h
Until now these functions always assumed the types of elements to be float. But this assumption does not hold e.g. for quantized types.
=> [opencl] Fix functions for converting into the NCHW layout to support all types of payloads

include/glow/Graph/Nodes.h, lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphOptzTest.cpp
This is an alternative to https://github.com/pytorch/glow/pull/1235
For Variables that are 256 elements or smaller and of the same type, are never written into, are private, and have no train kind, this will attempt to combine them into a single shared variable. This is particularly useful for IntLookupTables of the same "kind" (e.g. Tanh lookup tables), which often use the same data as their lookup table Var. Note that 256 is a heuristic used to ensure compile time isn't too long.
Also, note that I needed to add this after all other passes are complete, and not part of `optimize()` -- I added it to `optimize()` initially, but there are potential issues with other passes adding in new nodes that write to Variables. For example, `lower()` was creating new Save nodes for Variables that had …
=> Perform Variable CSE on Variables of small enough size

include/glow/Graph/Node.h, include/glow/IR/IR.h
`default` is removed in stable llvm anyways, and it looks like it doesn't add anything here.
=> Use ilist_node_traits instead of default

lib/Backends/OpenCL/OpenCL.h
This should help to make element-wise max operation to be quantized in the Resnet50 with openCL backend.
The conversion logic/execution is covered by quantization end2end test. cc: @ZchiPitt
=> [trivial] Add ReLU to the list of supported operations for openCL.

lib/Graph/Graph.cpp, lib/Optimizer/GraphOptimizer.cpp
- Fix the implementation of createCmpEQ
The implementation should be aware of the quantization. Use the same approach that we use for createCmpLTE.
- Fix a quantization related bug in sinkCode
When sinkCode performs the arith(transpose(x), transpose(y)) -> transpose(arith(x, y)) transform, it should take the quantization into account. Specifically, it should create correct types for the transformed arith operation.
=> [quantization] A couple of bug fixes to support quantization

include/glow/Optimizer/Partition.h, lib/Optimizer/CMakeLists.txt, lib/Optimizer/Partition.cpp, tests/unittests/CMakeLists.txt, tests/unittests/partitionTest.cpp
The FunctionGraph representation and the partitioning process seemed like the least controversial parts of the partitioning PR, so I've extracted them, cleaned up and simplified the logic, and put them up for review.
`glow::partition()` is now a standalone function that produces a `FunctionGraph`.  How this graph is executed is an orthogonal question; currently the test simply uses serial execution of the subgraphs, which is the simplest approach.
=> [partition] Introduce FunctionGraph and produce it via partition()

lib/Backends/CPU/BundleSaver.cpp, lib/Backends/CPU/GlowJIT.cpp, lib/Backends/CPU/GlowJIT.h
I'm not super-happy about this PR, but the API for Orc JIT seems to have churned a lot.  I've tried llvm stable, llvm master, and FB's internal stable branch, and they *all* have little differences from each other, and of course from llvm6.  So... I'm thinking -DFACEBOOK is about the best way to handle this for the present, and at some point we can migrate fully to llvm7 once that's a stable release.
=> Work around OrcJIT API instability

include/glow/Importer/ONNX.h, include/glow/Importer/ProtobufLoader.h, lib/Importer/Caffe2.cpp, lib/Importer/ONNX.cpp, lib/Importer/ProtobufLoader.cpp, tools/loader/ImageClassifier.cpp, tools/loader/ModelRunner.cpp
The loaders were pretty specific to image classification before this, and so assumed/only supported loading networks with a single output.
=> Support multiple outputs in proto loaders and runners

include/glow/Importer/CommonOperatorLoader.h, include/glow/Importer/ProtobufLoader.h, lib/Importer/Caffe2.cpp, lib/Importer/ONNX.cpp, lib/Importer/ProtobufLoader.cpp
Verified that `run.sh` still is correct.
Note that some operators have multiple outputs, which are not used by us for inference. For example, Reshape outputs `old_shape` which is unused. In these cases I explicitly set the `nodeValueByName_` instead of calling `addNodeAsOutput()`.
=> [Importer] Change Node/Variable APIs to return NodeValues

examples/char-rnn.cpp, examples/cifar10.cpp, examples/fr2en.cpp, examples/mnist.cpp, examples/ptb.cpp, include/glow/Base/Tensor.h, include/glow/Graph/Graph.h, include/glow/Graph/Nodes.h, include/glow/Importer/ProtobufLoader.h, lib/Backends/CPU/Transforms.cpp, lib/Base/Tensor.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Importer/ProtobufLoader.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Optimizer/Lower.cpp, lib/Optimizer/Partition.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/HyphenTest.cpp, tests/unittests/MLTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/gradCheckTest.cpp, tests/unittests/graphGradTest.cpp, tests/unittests/graphOptzTest.cpp, tests/unittests/graphTest.cpp, tests/unittests/partitionTest.cpp, tests/unittests/quantizationTest.cpp
This commit removes the initialization code from Variable and moves it to the code that creates the variable. After this change Tensors needs to be initialized externally and not by the Variable constructor like they are today. This is a pretty big patch that touches many many files, but most of the changes are mechanical. 
I tried to make this patch as simple as possible and there are still a few things that we need to clean up. For example, the default values for arguments don't make sense in a few places. We should change the boolean training flag to an enum, etc.
=> [Variable] Remove the tensor initialization from Variable. NFC.

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, lib/Importer/Caffe2.cpp, tests/unittests/OperatorTest.cpp
This is very similar to our merging matmuls optimization. Instead of the merged LHS matrices each being individual matrices that we concat together, they're already essentially concatenated together as  each batch of the LHS tensor we already have. This means they're already logically arranged correctly in memory and instead of inserting/slicing them like we do for merged matmuls optimization we just reshape before and after.
Also, it means our optimizations for merging matmuls should work nicely with this. That is, other matmuls/batch matmuls can be merged into this one using the same merge matmuls optimization we already have.
=> Support batch matmul as a normal matmul plus a couple reshapes

lib/Backends/CPU/LLVMIRGen.cpp
While CMake lets us decide where to put libjit.bc, other systems (such as buck) don't have this flexibility.  Using an environment variable lets us override the default search path.
=> [cpu] Introduce GLOW_LIBJIT_PATH for non-standard libjit location

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, tests/unittests/OperatorTest.cpp
Found the bug that splat int8 kernel always receives 0 as the input value. Fixed it and ReLU works with the opencl quantization now.
=> [fix] Fix the problem ReLU node does not work with OpenCL quantization

include/glow/Importer/CommonOperatorLoader.h, lib/Graph/Graph.cpp, lib/Importer/Caffe2.cpp
1. Support Sigmoid.
2. Support BatchGather.
3. Support broadcasting of 0-dimensional tensors.
4. Support transposed RHS for MatMul.
=> [Caffe2 Importer] Make more operators to be available from importer

lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/CPU/libjit/libjit_conv.cpp
Using C-style includes here works around some very obscure issues with FB's internal build system.
=> [libjit] Use .h-style include paths

tools/ClassGen/InstrBuilder.cpp, tools/ClassGen/InstrBuilder.h
Prior to this commit, it was impossible to describe more than one
inplace property. This would limit our ability to set the inplace
property on instruction with more than one result.
With this patch, it is now possible to define one inplace property
list for each output of an instruction. To use this feature
simply invoke inplaceOperand method for each output on the
declaration of the instruction.
=> [InstrGen] Teach inplaceOperand how to deal with several results

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, tests/unittests/BackendTest.cpp
This commit adds a unit test that checks that we can compile functions
without depending on the IR.  We compile some function and then delete
the function. Later we execute the code and check that things work.
=> [IR] Add a test that we can compile code without graph deps.

include/glow/Support/Memory.h
Allocation failure is a real runtime possibility that we should handle (by dying immediately :) ).  Let's always-assert here, not just in debug mode.
=> [support] Always abort if posix_memalign fails

lib/Backends/CPU/AllocationsInfo.cpp, tests/unittests/OperatorTest.cpp
Fixes a bug in calculating addresses for the CPU backend. Previously it assumed the source of a tensor view would be the underlying alloc activation. However, we can have multiple tensor views stacked, in which case the offset was not being correctly calculated.
The test case tests this via a slice (IRGen'd into an extract and then optimized into a tensor view), and then a reshape of this slice (which is also a tensor view). Thus the tensorviews are stacked. I also added more stacked slices/reshapes.
=> [AllocationsInfo] Fix stacked tensorviews bug on CPU Backend

CMakeLists.txt
The link with LLVM consumes a substantial amount of resources (cpu time, memory), and I find very convenient to have an option to disable the build of tests and examples when developing.
=> Add cmake options to disable examples and/or tests build.

utils/scripts/visualize_allocations.py
This commit adds a script that visualizes the memory allocation of activations in the heap. This script is pretty basic (no tests, no input validation, etc.) and I am just adding it in hope it would be useful for other people who want to visualize memory management.
Example:
=> Add a script to visualize the neural network activation heap.

include/glow/Importer/Caffe2.h, lib/Importer/Caffe2.cpp
Refactored `loadWeights()` to load each operator via `loadWeight()`, and then call it from the `loadNetwork()` loop when encountering ConstantFill, GivenTensorIntFill, or GivenTensorInt64Fill.
=> Support ConstantFill, GivenTensorIntFill, GivenTensorInt64Fill in predict_net

tools/ClassGen/NodeGen.cpp
NFC.
Was not obvious from the definition of the node and in particular, I missed it was fixed at construction time and thought it was re-profiled while running the profile... Which doesn't make much sense but that would imply that someone thinks while reading the description :P.
=> [NodeGen] Describe how the new scale and offset are chosen for the rescale node

tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/OperatorTest.cpp
Randomize function generates values in [low; high] range, thus [-128; 127] must be used for S8 tensors.
=> [unittests] Fix randomize usage for S8 tensor generation.

lib/Backends/CPU/Transforms.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/BackendTestUtils.h
Recently sinkRescaleQuantizeNode was extended for Min/Max nodes (https://github.com/pytorch/glow/commit/1e5fdff1c90ea22795641fea52a10c485a09c730). This broke CPUMaxSplat transformation, because now Max nodes can have different quantization scale or offset for input and output, which is not supported by CPUMaxSplat node.
This patch fixes this issue by pulling Rescale node out from Max node, before replacing it with CPUMaxSplat.
=> [cpu] Fix CPUMaxSplat transformation

include/glow/Importer/CommonOperatorLoader.h
Using some ONNX models, we figured out that support for some operators were missing in the loader:
- sqrt
- reciprocal
- min
- max
The IR nodes already existed so only the loader has been extended.
=> Add support for more operators to the model loader

lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp
More seq2seq support, to get running on the Interpreter and CPU backends. Note that gather for the interpreter was already supported, as its implementation works for any type.
=> Support IndexTy for Div and Gather

include/glow/Importer/CommonOperatorLoader.h, include/glow/Importer/ProtobufLoader.h, lib/Importer/ProtobufLoader.cpp
Variables loaded from protos should not be trainable by default. This improves constant deduplication.
=> [ProtobufLoader] Set vars created from protos to default untrainable

lib/Quantization/Quantization.cpp
Don't know why Div node was not supported for quantization when given the profiling scale and offset.  But some network do need support for div node.
=> [quantization]: Support div node for quantization

include/glow/Importer/ONNX.h, include/glow/Importer/ONNXIFILoader.h, lib/Importer/CMakeLists.txt, lib/Importer/ONNX.cpp, lib/Importer/ONNXIFILoader.cpp, lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, lib/Onnxifi/onnxifiGlow.cpp
* Support init Graph and add more mock functions to support end2end onnxifi run;
* Move onnxifi model loading logic to a separate class.
Note, I was running through the toy example which does processing of conv node (has a dependency on C2). Integration test for this code (C2 independent) is being worked on onnx side (once it's done, I'll integrate it here).
cc: @Maratyszcza @yinghai
=> [onnxifi] Adding more functionality to the onnxifi prototype.

lib/Onnxifi/onnxifiGlow.cpp
* ONNXIFI_STATUS_UNSUPPORTED_PARAMETER was removed in the newest version of onnxifi, and replaced by ONNXIFI_STATUS_UNSUPPORTED_PROPERTY
* ONNXIFI method definition changes
=> [onnxifi] Update onnx submodule + trivial changes.

lib/Backends/OpenCL/OpenCL.h
Support several nodes for int8 operation:
-- FullyConnectedNode (lowered to matmul and batchedAdd)
-- ConcatNode (lowered to inserttensor)
-- ReshapeNode (lowered to copyinst)
-- SliceNode (lowered to extracttensor)
=> [opencl]: Support several nodes for int8 operation

lib/Quantization/Quantization.cpp, tests/unittests/quantizationTest.cpp
Quantize splat node in Quantization.cpp:quantizeNode()
As i talked with @rdzhabarov, this support is anyhow needed if the original graph has splat node, and we have to quantize it based on profiling information
=> [quantization]: Quantize splat node

include/glow/Importer/ONNX.h, include/glow/Importer/ONNXIFILoader.h, lib/Importer/CMakeLists.txt, lib/Importer/ONNX.cpp, lib/Importer/ONNXIFILoader.cpp, lib/Onnxifi/CMakeLists.txt
Currently CMakefile to build ONNX has issue that when glow lib is used with onnx lib in the same process, there will be protobuf registration conflicts. This was studied and solved during Pythorch/Onnx integration. We reuse the solution in CMakefile in onnx to build onnx protobuf lib to avoid the issue. 
@rdzhabarov
=> [ONNXIFI] Use CMakefile in onnx to build onnx library

include/glow/Graph/Node.h, include/glow/Importer/CommonOperatorLoader.h, lib/Graph/Graph.cpp, lib/Graph/Node.cpp, lib/Importer/Caffe2.cpp, lib/Importer/ONNX.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Optimizer/Lower.cpp, lib/Optimizer/Partition.cpp, lib/Quantization/Quantization.cpp, tests/unittests/graphOptzTest.cpp, tests/unittests/graphTest.cpp, tools/ClassGen/InstrBuilder.cpp, tools/ClassGen/NodeBuilder.cpp
The change is pretty mechanical. Namely, this changes the pattern
NodeValue-><Node_method>
Into
NodeValue.getNode()-><Node_method>
Also, as part of this change, we actually get cleaner accesses to
dimensions, types, etc. Indeed, instead of hardcoding the index of
the result, the NodeValue directly gets us the right value.
Related to #1346.
NFC.
=> [NodeValue] Get rid of the implicit conversion when using the operator->

include/glow/Importer/ONNX.h, lib/Importer/ONNX.cpp
In the image classifier the input image shape is not checked with regard to the ONNX input declaration.
In case of input image shape mistake, the wrong image shape is propagated accross the model and some indirect errors are usually generated (for instance for a convolution operator inside the model). 
Since the ONNX model declares inputs, it is possible to check the input image shape before any shape propagation and generate an accurate error message. This is what does this PR.
=> Check the consistency between  image and declared ONNX input

docs/Quantization.md, include/glow/Quantization/Base/Base.h, lib/Quantization/Base/Base.cpp, tests/unittests/quantizationTest.cpp, tools/loader/Loader.cpp
This PR adds a new schema symmetric with uint8 that basically feature symmetric range for both int8 and uint8.
Uint8 are represented as int8 with an offset -128.
=> [quantization] Add a symmetric with uint8 mode

lib/Importer/ONNXIFILoader.cpp
Simple bug. This will get us through the initGraph phase. 
@rdzhabarov
=> [ONNXIFI] Fix incorrect return value in loadWeight

lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/LLVMIRGen.h
Small PR to fix const correctness in LLVMIRGen class in CPU back-end.
=> [nfc][cpu] Fix const correctness in LLVMIRGen.

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, lib/Quantization/Quantization.cpp, tests/unittests/MLTest.cpp, tests/unittests/graphTest.cpp, tests/unittests/quantizationTest.cpp, tools/loader/ImageClassifier.cpp
This pr is due to the [issue](https://github.com/pytorch/glow/issues/1441) that we found some FP weights are not used after quantization anymore but they are not removed. 
The reason behind this bug, is that when we perform quantization on an existing function, we create a new quantized function, but we didn't remove the old, which still uses some non-quantized useless variables.
We propose the fix here to remove the old function after quantizing it, and it successfully helped the DCE remove those unused variables.
=> [fix][quantization]Erase the old function after we create the new quantized function

utils/scripts/gen_caffe2_model.py, utils/scripts/gen_onnx_model.py
The 2 files in this PR is to provide an sample code for generating simple Caffe2/ONNX models used for our Caffe2/ONNX importer unit testing. The generated model is in text format.  Currently, the files generate a simple CNN with a convolution layer only. Users should customize the code to generate their only models.
=> [utils] Add two script to help generate simple caffe2/onnx models used for importer unittest.

include/glow/Base/Type.h, tests/unittests/OperatorTest.cpp
Flatten takes a tensor of dimensions [d0, d1, ... dN] and an axis and
produces a 2D tensor of dimensions:
[d0 x d1 x ... x d_axis-1, d_axis x d_axis+1 x ... x dN]
Prior to this patch we would allow axes between [1; rank), where rank
is N + 1.
However, the caffe2 flatten operator allow to use axes up to rank.
In that case, the flattening consists in squashing all the dimensions
together and only have one row:
[d0 x d1 x ... x dN, 1]
This patch thus now allows axes between [1; rank] for the flatten operator.
=> [Node] Allow axes equal to the rank of the tensor for Flatten

include/glow/Importer/ONNX.h, include/glow/Importer/ONNXIFILoader.h, include/glow/Importer/ProtobufLoader.h, lib/Importer/ONNX.cpp, lib/Importer/ONNXIFILoader.cpp, lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, lib/Onnxifi/onnxifiGlow.cpp
towards issue: https://github.com/pytorch/glow/issues/1190
* Set output nodes
* Handle set graph IO ONNXIFI method
* Perform inference as part of the Run() method
cc: @yinghai @Maratyszcza 
running ```pytest -s test_onnxifi.py```, it passes e2e for ReLU and Conv nets.
=> [onnxifi] Load output nodes, perform setIO and run the Graph.

include/glow/Base/Tensor.h, tests/unittests/tensorsTest.cpp, tools/loader/ModelRunner.cpp
When running the model-runner, we don't explicitly delete the loader
that we dynamically allocate. Although the memory will be reclaimed
at the end of the process, this made leak sanitizer to complain.
NFC.
=> [ModelRunner] Make leak sanitizer happy

include/glow/Backends/LayoutConverter.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/Backends/OpenCL/Transforms.cpp, lib/Backends/OpenCL/kernels.cl, tests/unittests/OperatorTest.cpp, tests/unittests/graphTest.cpp, tools/ClassGen/Backends/OpenCL/OpenCLSpecificInstrs.h, tools/ClassGen/Backends/OpenCL/OpenCLSpecificNodes.h
OpenCL fast kernel for group (group > 1) convolution has some issues which are need to be investigated further. Now for group conv, we only call the slow kernel.
=> [openCL] add group param to conv for OpenCL backend

include/glow/CodeGen/MemoryAllocator.h, lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/CPU/AllocationsInfo.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/CodeGen/MemoryAllocator.cpp
The types should be able to represent any address in the address space of the device, whose memory is being allocated by means of the MemoryAllocator. This device may be different from the host running Glow. E.g. Glow may run on a host with a 32-bit address space, but use a  MemoryAllocator for a GPU or an accelerator with a 64-bit address space.
Therefore, to be on the safe side use `uint64_t` instead of `size_t` in MemoryAllocator APIs.
Update the user's of the API to use `uint64_t` instead of `size_t`.
=> Make sure that MemoryAllocator uses wide-enough unsigned types for reresenting the address space being allocated

include/glow/Support/Compiler.h
As `GLOW_ASSERT` and `GLOW_UNREACHABLE` are supposed to be the drop-in replacements for `assert` and `llvm_unreachable` in terms of APIs, they should use the same output stream, which is stderr. It also helps with testing, as some testing frameworks like `gtest` allow for testing the assertions and expect the messages to be written to stderr.
=> GLOW_ASSERT and GLOW_UNREACHABLE should write messages to stderr

examples/fr2en.cpp, include/glow/Quantization/Quantization.h, lib/Quantization/Quantization.cpp, tests/unittests/MLTest.cpp, tests/unittests/quantizationTest.cpp, tools/loader/Loader.cpp
closes https://github.com/pytorch/glow/issues/1482
image-classifier run looks good with dump/load profile.
=> [quantization] Remove original function when needed after running quantization.

include/glow/CodeGen/MemoryAllocator.h, lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/CodeGen/MemoryAllocator.cpp, tests/unittests/memoryAllocatorTest.cpp
- There is a new version of the `allocate` API that supports eviction.
If the allocator cannot find enough free space to satisfy the allocation request, it tries to find a set of allocated blocks whose eviction would result in freeing enough space to allocate the memory block of requested size. The client may specify which allocated blocks cannot be evicted.
The current version of the allocator uses a first-fit approach when it looks for the buffers to be evicted.
- Also, each allocation now takes a `handle` parameter and associates this handle with the allocation. A handle is typically a client-specific object, representing what is being allocated, e.g. a `Value *` whose payload is being allocated by means of a MemoryAllocator. Clients can use handles to deallocate buffers, to describe …
=> Extend MemoryAllocator to handle evictions and to support handles

tests/unittests/BackendCorrectnessTest.cpp
The type of output node was inconsistent with the one in function "inferNonSquarePaddingConv" due to some incorrect "copy&paste".
=> [unnitest] A bugfix for nonSquarePaddingConvtTest in BackendCorrectnessTest.cpp

lib/Backends/OpenCL/kernels.cl, lib/Backends/OpenCL/kernels_fwd_conv.cl, lib/Backends/OpenCL/kernels_fwd_quantized_conv.cl, tests/unittests/memoryAllocatorTest.cpp
For a .cl file, we temporally renamed it as a .cpp file, changed the file content not to be string, applied ./utils/format.sh and then converted it back.
=> [cleanup] Clean up the format (by running ./utils/format.sh) and one warning.

include/glow/ExecutionEngine/ExecutionEngine.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Quantization/Quantization.cpp, tests/unittests/quantizationTest.cpp
Add quantization support for LRN and SoftMax in GLOW middle-end, making possible for any back-and to implement them, if needed.
=> [quantization] Add quantization support for LRN and SoftMax in middle-end

include/glow/Base/Tensor.h, include/glow/Graph/Nodes.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Graph.cpp, lib/Importer/Caffe2.cpp, lib/Importer/ONNX.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/GemmTest.cpp, tests/unittests/tensorsTest.cpp
This function does not only copy the content of a tensor, but also changes the type. Therefore, it is better to rename it as "assign".
=> [Tensor] Remane the method "copyFrom" in Tensor class to "assign".

include/glow/CodeGen/MemoryAllocator.h, lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/CodeGen/MemoryAllocator.cpp, tests/unittests/CMakeLists.txt, tests/unittests/memoryAllocatorTest.cpp
- MemoryAllocators should have names
It makes it easier to debug  memory allocation related issues and to produce more detailed debug output.
- Add to MemoryAllocator the API to get sizes of allocated memory blocks
This API is useful for some backends. It is also fast as it does not require traversing all allocations.
=> A couple of usability improvements to MemoryAllocator API

tests/unittests/memoryAllocatorTest.cpp
memoryAllocatorTest was recently extended by 63cbea89. Including IR.h caused a build failure (due to  cmake missing dependency for the test):
In file included from include/glow/IR/IR.h:19:0,
from tests/unittests/memoryAllocatorTest.cpp:18:
include/glow/Base/Traits.h:71:33: fatal error: glow/AutoGenInstr.def: No such file or directory
But it looks like IR.h is not needed in the test and can be removed, preventing the issue.
=> [unittest] Fix memoryAllocatorTest

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, tests/unittests/OperatorTest.cpp, tests/unittests/quantizationTest.cpp
Support TopK for OpenCL backend, with also quantization support.
Also enabled end2endGRU test for OpenCL now.
For the time being the actual computation of TopK is performed on the host side and not by means of an OpenCL kernel. We may add an optimized kernel in the future.
=> [opencl][quantization]: Support TopK for OpenCL backend, with also quantization support

include/glow/Importer/ONNX.h, include/glow/Importer/ONNXIFILoader.h, lib/Importer/ONNX.cpp, lib/Importer/ONNXIFILoader.cpp, lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, lib/Onnxifi/onnxifiGlow.cpp
Add proper support for onnxGetBackendCompatibility ONNXIFI method.
```
onnxGetBackendCompatibility(onnxBackendID backendID, size_t onnxModelSize,
const void *onnxModel) 
```
An important use case for onnxGetBackendCompatibility is when onnxModel contains only a single operation. It does not have weights and it does not have inputs.
This PR allows checking whether specific ONNX operation is supported by the Glow and specific backend.
towards fixing https://github.com/pytorch/glow/issues/1190.
=> [onnxifi] Support compatibility function.

lib/Graph/Nodes.cpp, lib/Importer/Caffe2.cpp, tests/models/caffe2Models/concat_add_axis_predict_net.pbtxt, tests/models/caffe2Models/concat_predict_net.pbtxt, tests/models/caffe2Models/matmul_trans_RHS_predict_net.pbtxt, tests/unittests/caffe2ImporterTest.cpp
Each commit fixes a different bug:
- First one has to do with our modeling of concat which has a slightly different resulting shape between glow and caffe2
- Second one has to do with the indices used in the transpose for batched matmul.
Note: I stacked these commits in the same PR, because I use a newly introduced file (empty_init_net.pbtxt) in both of them.
=> Fix bugs in our Caffe2 importer

include/glow/Importer/ONNXIFILoader.h, include/glow/Importer/ProtobufLoader.h, lib/Importer/Caffe2.cpp, lib/Importer/ONNX.cpp, lib/Importer/ProtobufLoader.cpp, lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, tests/unittests/caffe2ImporterTest.cpp, tests/unittests/onnxImporterTest.cpp, tools/loader/ImageClassifier.cpp, tools/loader/ModelRunner.cpp
There's no reason to save outputs by SaveNodes instead of Variables. It is potentially dangerous because non-quantized graphs are often erased after they are quantized, and so any references to the SaveNodes from the non-quantized graph are no longer valid.
This is the case since https://github.com/pytorch/glow/pull/1458
=> Move ProtobufLoader output map to Variables instead of SaveNodes

lib/Importer/ONNXIFILoader.cpp
cc: @yinghai @Maratyszcza 
There are some operators which need to be added to the `compatibility` mode and it seems that we are good to go with resnet50 after that.
=> [onnxifi] Inputs in the graph contain weights as well. We need to filter them out.

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Optimizer/Lower.cpp, lib/Quantization/Quantization.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/quantizationTest.cpp, tools/ClassGen/NodeGen.cpp
This is not yet ready for review.
Will clean this up a bit later. @jfix71 see if this patch helps with the problem you were seeing.
Essentially it was a bit misleading to have ReLU lowered to Max node with the negative floating point range. Now we create ReLU with the output type according to quantization parameters after profiling (Before that was a sequence of Max->Rescale and Rescale can go away etc).
=> [quantization] Properly quantize ReLU.

include/glow/Base/Tensor.h
Since https://github.com/pytorch/glow/pull/1471 landed, tensors should always have positive size, since we have zero-dimensional tensors that still have size 1.
=> [Tensor.h] Remove unnecessary check for size() in reset

include/glow/Base/Tensor.h, include/glow/Base/Type.h, lib/Backends/CPU/LLVMIRGen.cpp, lib/Base/Tensor.cpp, tests/unittests/tensorsTest.cpp
Add int16 type to be able to use int16 tensors in back-end. Not used in the middle-end at the moment.
=> [Type.h] Add type Int16QTy

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/kernels.cl
This is required to e.g. properly pass struct parameters of types like ShapeNHWC, ShapeNCHW, etc. The definitions of these types on the host side use size_t for their members and they should be defined on the OpenCL's side using integer types of the same width.
Since the size of size_t on the host side is not guaranteed to be of a fixed-width known to OpenCL, it has to be provided to OpenCL dynamically. Thus, the size is passed down to the OpenCL code as a macro definition. This macro definition is then used to define in OpenCL the type cl_host_size_t matching the size_t on the host side.
=> [opencl] Define a type cl_host_size_t exactly matching the type size_t used on the host side

lib/Backends/CPU/libjit/libjit_defs.h
Refer to https://stackoverflow.com/questions/22265610/why-ssize-t-in-visual-studio-2010-is-defined-as-unsigned
=> [msvc] define ssize_t for MSVC.

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/kernels.cl, tests/unittests/OperatorTest.cpp
Mul and Div ops have different formulas for computing resulting scale. So dispatching code must have some branching, like LLVMIRGen has.
Now I'm wondering why you didn't see discrepancy on Mac, given that it was a bug in `OpenCL.cpp`, happening before any OpenCL dispatching. Is it possible that random init in unit test is platform dependent?
Also increasing number of test runs in the test.
Fixes #1548
=> [OpenCL] Fix bug in dispatching Div kernel.

lib/Importer/ONNXIFILoader.cpp
*Description*: Remove unused var warning for `inDataSigned`
*Testing*: N/A
=> [ONNXIFILoader.cpp] Remove unused var warning

include/glow/Base/Type.h, include/glow/Support/Compiler.h, lib/CodeGen/MemoryAllocator.cpp, lib/Onnxifi/onnxifiGlow.cpp, tests/unittests/HyphenTest.cpp
*Description*:
* run clang-format on the code base.
* fix unused var warning
*Testing*:
existing unit tests
=> [cleanup] Fix compilation warning and clag-format code base.

CMakeLists.txt
Fix the `CollectHeaders` rule by replacing `src` (that doesn't exists) by `lib`.
=> Fix the CollectHeaders custom target

tests/unittests/CMakeLists.txt
*Description*:
Formating issue in CMakeLists. <tab> character was used.
*Testing*:
Check if cmake still works.
=> [unittests] Fix tab character in CMakeLists. NFC

lib/Onnxifi/Base.h, lib/Onnxifi/onnxifiGlow.cpp
*Description*:
Previously ONNXIFI was running on Interpreter backend only. The execution time is pretty slow and especially for the debug builds it's painful.
This PR allows running ONNXIFI on CPU backend if Glow is compiled with CPU support.
Note, make sure that env var GLOW_LIBJIT_PATH is set correctly to point to the libjit.bc when running integration test, e.g., export GLOW_LIBJIT_PATH=/Users/rdzhabarov/src/release_build/libjit.bc.
*Testing*:
Manual integration test for C2->Glow with Resnet-50.
```
rdzhabarov-mbp:onnx rdzhabarov$ pytest -s test_onnxifi.py 
======================================================================================== test session starts =========================================================================================
platform darwin -- Python 2.7.14, …
```
=> [onnxifi] Prefer to rely on the CPU backend, but if it's not available fallback to the Interpreter.

lib/Optimizer/GraphOptimizer.cpp
*Description*:
Another assignment of this boolean is done first thing at the beginning
of the next do;while loop.
This useless assignment triggers annoying warnings in our internal flow.
NFC.
*Testing*:
ninja check
=> [GraphOptimizer] Remove useless assignment from DCE

lib/Backends/CPU/libjit/libjit.cpp
*Description*:
This commit "tiles" the 2d transpose method. Processing the input matrix
in small blocks ensures that the source and destination will stay in
cache. Notice that scanning 1 row at a time and storing the scalar into
some column brings and invalidates many cache lines. The tiled scan
helps to reduce the number of used destination cache lines. I measured a
4x speedup on a small local benchmark. We could further improve this
procedure using vector instructions for the transpose of the single tile
and with recursive blocking of the 2d matrix.
*Testing*:
I ran a local benchmark (described above). Ran ninja check and the ./run.sh test to run inference on the ONNX models. 
I updated the comment in the implementation of the operation.
=> [CPU] Improve the 2D transpose implementation.

lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/CPU/LLVMIRGen.h
The CPU backend contains all the LLVM IR generation logic and we found very useful to have the possibility to create a backend derived from the CPU backend by simply enabling these 3 possibilities:
- add the possibility to inherit from `CPUBackend`
- add the possibility to call `CPUBackend::compile()` with an object derived from `LLVMIRGen`
- make `LLVMIRGen::generateLLVMIRForInstr` virtual
=> Added the minimum needed to make the CPU backend inheritable

docs/Testing.md, tools/loader/CMakeLists.txt, tools/loader/Loader.cpp, tools/loader/Loader.h, tools/loader/TextTranslator.cpp
Add TextTranslator program for driving text translation
*Description*:
This commit adds a program for driving text translation, similar to the ImageClassifier for image classification. It does pre and post processing of the data, converting between input text and dictionary tokens, as well as determining the highest likelihood sentence from the beam search output of the model.
It is loosely based on loading a model from pytorch_translate (https://github.com/pytorch/translate/tree/master/pytorch_translate/cpp). It includes command-line parameters for setting the model's max input and output sentence lengths, as well as beam size. It also allows for specifying a length penalty when determining the highest likelihood output sentence (this is for post-processing the output translation, …
=> Add TextTranslator program for driving text translation

lib/Quantization/Quantization.cpp, tests/unittests/quantizationTest.cpp
*Description*: Add missing quantization support from a profile for BatchedReduceAdd and MatMul
*Testing*: Added nodes to quantizationTest's end2end test
=> [Quantization] Support quantizing BatchedReduceAdd and MatMul from profile

lib/Backends/CPU/libjit/libjit_conv.cpp
Description: libjit_conv seems to inconsistently use const parameters, which causes annoying const_casts in callers. So I've normalized the use of const parameters: input pointers are const, scalars are non-const.
Testing: Ran `ninja all`
Documentation: N/A
=> [CPU backend] Cleanup use of const parameters in libjit_conv.cpp

docs/AOT.md, docs/Quantization.md, tests/images/run.sh, tools/loader/ImageClassifier.cpp
*Description*: Models may expect different names for the input image in ImageClassifier. We previously had a hack that allowed for two different names. This properly allows the model to have its image name specified.
*Testing*: updated and verified `run.sh` works
*Documentation*: Added.
=> [ImageClassifier] Add command line option for the model's expected input image name

docs/Quantization.md, include/glow/Base/Traits.h, include/glow/Quantization/Quantization.h, lib/Quantization/Quantization.cpp, tests/unittests/quantizationTest.cpp, tools/loader/Loader.cpp
*Description*: We may prefer to not quantize every node kind in a model if it causes unacceptable accuracy loss. This commit adds the ability to disable quantization for node kinds that would otherwise be quantized, preventing accuracy loss.
*Documentation*: Added.
=> Add option to disable quantizing specified node kinds

tests/unittests/CMakeLists.txt
*Description*:
We copy all required files to binary directory, would be logical to point to the binary dir as working dir.
*Testing*:
ctest + individual runs of onnx/caffe2 importer tests.
=> [unittest] Since we copy all files to the BUILD dir already, set working dir there as well.

docs/IR.md, include/glow/Graph/Graph.h, include/glow/Graph/Nodes.h, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, tests/unittests/graphTest.cpp, tools/ClassGen/NodeGen.cpp
This PR is the first few steps in the implementation of the Placeholder node. The plan is discussed in #1334. Placeholder are unbound variables where the content of the tensor is provided by the execution engine or the AOT compiler at runtime. 
This PR introduces Storage as a superclass for Variable (bound) and Placeholder (unbound). This PR also adds a simple unit test that checks that we can create new Placeholder nodes. This PR does not implement any of the infrastructure that's required to do anything useful with Placeholder variables, such as loading content into them, deleting them, pretty dotty-printer, etc. 
Potentially controversial decisions:
1. Placeholder and Variable inherit from Storage.
2. The name Placeholder.
3. The API for getVar and getPlaceholder instead of getStorage. …
=> Placeholder: add Placeholder as a new kind of input/output to the graph.

include/glow/Backends/CompiledFunction.h, include/glow/ExecutionEngine/ExecutionEngine.h, lib/Backends/CPU/CPUFunction.cpp, lib/Backends/CPU/CPUFunction.h, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Graph.cpp, lib/IR/GraphScheduler.cpp, lib/IR/IRGen.cpp, lib/Onnxifi/Base.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/partitionTest.cpp, tools/loader/Loader.cpp, tools/loader/Loader.h
*Description*:
Implement the logic for executing Placeholders in the execution engine. This commit changes the backend interface and adds the ability to pass Placeholder variables in addition to Variables. 
This change breaks the out-of-tree backends.
This is the first step in adding support for placeholder variables in the execution engine. The commit adds support to the interpreter but not to the OpenCL and CPU backends. The support in the interpreter is single threaded at the moment.
In the next few PRs I'll complete the execution engine support in different backends for across all node kinds (SaveNode, for example).
*Testing*: Ran tests locally and added a new test.
*Documentation*: No functional changes to document. 
issue #1334
=> [Placeholder] Add support for Placeholders in the execution engine

lib/Backends/Interpreter/InterpreterNodes.cpp
*Description*: Since getWeightHandle is generic, we use it to replace the "getTensor(v)->getHandle<ElemTy>(tensor)" expression.
*Testing*: Current unittests, ./tests/images/run.sh
=> [Cleanup] Replace getTensor(v)->getHandle<ElemTy>(tensor) with getWeightHandle<ElemTy>(tensor)

include/glow/Backends/CompiledFunction.h, include/glow/ExecutionEngine/ExecutionEngine.h, lib/Backends/CPU/CPUFunction.cpp, lib/Backends/CPU/CPUFunction.h, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Graph.cpp, lib/Onnxifi/Base.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/partitionTest.cpp, tools/loader/Loader.cpp, tools/loader/Loader.h
*Description*:
This commit reverts the parts of the PR #1586 that pass the placeholder
variables in the run command of the execution engine. At first I thought
that this would allow to eliminate the variables from the high-level
parts of the compilation, but I realized that we need to start with
fixing all of the backends and add support to the compiled function.
#1586
*Testing*: Ran the local test. Removed the two placeholder tests.
=>  Revert: [Placeholder] Add support for Placeholders in the execution engine.

docs/Testing.md, utils/download_caffe2_models.sh
*Description*: Unrolled Caffe2 protos for en2gr have been uploaded along with associated dictionaries for translation, so I'm adding it to the download script.
*Testing*: Works with `text-translator`
*Documentation*: Added
=> [download_caffe2_models.sh] Add en2gr

lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/CPU/libjit/libjit_conv.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Backends/OpenCL/kernels.cl
In convolution, max pool, and avg pool ops, we rename filterSize(s) with kernelSize(s), since "filter" could also mean "weight" in some cases.
*Testing*: 
unittest, ./tests/images/run.sh
*Documentation*: 
None
=> [Cleanup] Replace filterSize(s) with kernelSize(s).

examples/char-rnn.cpp, examples/cifar10.cpp, examples/fr2en.cpp, examples/mnist.cpp, examples/ptb.cpp, include/glow/ExecutionEngine/ExecutionEngine.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Onnxifi/Base.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/GemmTest.cpp, tests/unittests/HyphenTest.cpp, tests/unittests/MLTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/caffe2ImporterTest.cpp, tests/unittests/gradCheckTest.cpp, tests/unittests/graphTest.cpp, tests/unittests/onnxImporterTest.cpp, tests/unittests/partitionTest.cpp, tests/unittests/quantizationTest.cpp, tools/loader/Loader.cpp
*Description*:
This PR refactors the execution engine and removes all of the logic that is responsible for updating variables into external helper functions. It does not make sense for the execution engine, that managed the lifetime of the compiled function to also update variables, and once we migrate to placeholders we won't be able to rely on the execution engine to update the variables/placeholders for us, because they won't be tied to the run() method. 
This change removes the runBatch() method and keeps a simple run() method. All of the variable changes happen before the execution happens. This is the API change for the unit tests:
Before:
EE.run({var1, var2}, {inputs1, inputs2});	 
After:
updateVariables({var1, var2}, {inputs1, inputs2});
EE.run();
*Testing*: I ran "ninja check", …
=> [ExecutionEngine] Remove the logic that updates variables from the EE.

include/glow/Importer/CommonOperatorLoader.h, lib/Importer/ONNX.cpp, tools/loader/ImageClassifier.cpp
*Description*:
GLOW compiler supports caffe2 and ONNX models in NCHW format. Using tf2onnx, ONNX graphs can be generated from tensorflow checkpoints. The input to the graph in this case is in the NHWC format.  The ONNX graphs generated from tensorflow models also have some operators like tf.Identity and tf.MatMul that is not currently supported by the GLOW compiler ONNX code. The pull request is for the changes to support this additional feature for googlenet_v1_slim.onnx and google_v4_slim.onnx generated from tensorflow pretrained models. 
*Testing*: Ran tests/images/run.sh, ran ninja test, all tests passed with "-DGLOW_WITH_OPENCL=OFF -DGLOW_WITH_CPU=OFF
*Documentation*: tf2onnx tool - https://github.com/onnx/tensorflow-onnx/tree/master/tf2onnx
Pretrained googlenet models - …
=> [Loader] Changes to support ONNX graphs generated from tensorflow in NHWC format

include/glow/Backends/Backend.h, include/glow/Backends/CompiledFunction.h, include/glow/ExecutionEngine/ExecutionEngine.h, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/ExecutionEngine/ExecutionEngine.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/quantizationTest.cpp
*Description*:
Implement the logic for executing Placeholders in the execution engine.
This commit changes the backend interface and adds the ability to pass
Placeholder variables in addition to Variables. This change breaks the
out-of-tree backends.
This is the first step in adding support for placeholder variables in
the execution engine. The commit adds support to the interpreter but not
to the OpenCL and CPU backends.
*Testing*: Ran the local tests (ninja check)
*Documentation*: updated doxygen comments.
Related to #1586 and #1334.
=> [Placeholder] Allow executing Placeholders in the execution engine.

include/glow/Optimizer/Optimizer.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Optimizer/IROptimizer.cpp, tests/unittests/IROptTest.cpp
*Description*: CompilationMode is unused during optimize() for IRFunction. Remove it.
=> Remove unused CompilationMode from optimize() for IRFunction

examples/bundles/resnet50/Makefile, examples/bundles/vgg19/Makefile, examples/bundles/zfnet512/Makefile
Missed adding these in https://github.com/pytorch/glow/pull/1578
I cannot verify things are working as it seems we have a regression here (see https://github.com/pytorch/glow/issues/1604). I verified that https://github.com/pytorch/glow/pull/1578 was not the cause of this regression. So I cannot verify the full bundle creation, however this PR will still be required for the full fix.
=> [bundles | fix] Add missing model_input_name for all Makefiles

examples/bundles/resnet50/resnet50.cpp
*Description*:
At some point the output of the network changed from "output" to
"gpu_0/softmax". Reflect that when reading the result from the
bundle.
*Testing*:
Ran the makefile of the bundle of resnet50
This fixes #1604
=> [bundles/resnet50] Read from the right output tensor

examples/bundles/vgg19/Makefile, examples/bundles/vgg19/vgg19.cpp, examples/bundles/zfnet512/zfnet512.cpp
*Description*:
Fix vgg19 and vfnet512 bundles.
They were both reading from the wrong tensor.
Also vgg19 needed to be updated to use the new name for 128to127 image_mode.
*Testing*:
Ran the respective makefile
=> Fix the other bundles

include/glow/ExecutionEngine/ExecutionEngine.h, include/glow/Graph/Context.h, lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/CPU/BundleSaver.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/OpenCL/OpenCL.h, lib/Base/CMakeLists.txt, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/CMakeLists.txt, lib/Graph/Context.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTest.cpp, tests/unittests/onnxImporterTest.cpp
*Description*:
While writing a unit test that replaces some Variable with a Placeholder
I realized that in most cases we mainly care about allocating new
tensors, and not moving an existing tensor into the context. To
implement the new 'allocate' method I had to move the Context into the
Graph library, because it depends on the Placeholder class to figure out
the type of the Placeholder for Tensor allocatio method I had to move
the Context into the Graph library, because it depends on the
Placeholder class to figure out the type of the Placeholder for Tensor
allocation.
*Testing*: Updated the unit test.
=> [Context] Add a method to allocate a new backing tensor.

include/glow/Backends/Backend.h, include/glow/ExecutionEngine/ExecutionEngine.h, include/glow/Optimizer/Optimizer.h, lib/Backends/Backends.cpp, lib/Backends/CPU/CMakeLists.txt, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/Interpreter/CMakeLists.txt, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h, lib/Backends/OpenCL/CMakeLists.txt, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/ExecutionEngine/CMakeLists.txt, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Optimizer/CMakeLists.txt, lib/Optimizer/IROptimizer.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/CMakeLists.txt, tests/unittests/IROptTest.cpp, tests/unittests/quantizationTest.cpp, tools/loader/CMakeLists.txt
This PR allows for Backends to take a Function pointer for `compile()` and `save()`, instead of a IRFunction. The EE now does this. This allows for example for a backend to decide whether it wants to use our Instruction level IR or implement its own. The Interpreter, CPUBackend, and OpenCL backend all still use our Instruction level IR.
Note that I needed to keep the `compile()` that takes the IRFunction around, as it is used during unit tests. I couldn't think of good ways to change the unit tests to be able to remove it. Open to suggestions.
Also, the first commit here moves the IROptimizer's `optimize()` to take a bool for `shouldShareBuffers` so that Optimizer no longer depends on Backends. This prevents a cyclic dependence from the second commit.
(I also verified that bundling still …
=> Allow for backend to accept a Function instead of IRFunction

include/glow/Graph/Graph.h, include/glow/Graph/Nodes.h, lib/Graph/Grad.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/IR/GraphScheduler.cpp, tests/unittests/BackendTest.cpp, tests/unittests/MLTest.cpp, tests/unittests/gradCheckTest.cpp, tests/unittests/graphGradTest.cpp, tests/unittests/graphTest.cpp
*Description*: Allow the differentiation of Placeholder nodes. This PR includes two main parts. First, we add a flag to Placeholder to match the Variable node and allow the differentiation of the selected nodes. The second part fixes a few places (scheduler, cloner, etc) that assume that all storage nodes are Variable. 
*Testing*: Added unit tests and ran ninja check.
This is related to #1334. This PR is a step in the direction of eliminating the Variables, and is required for porting our unit tests to Placeholders instead of training mutable variables.
=> Allow the differentiation of Placeholder nodes.

lib/Graph/Grad.cpp
*Description*:
Fix a differentiation bug related to Placeholders. The line assumed that
the destination is a variable. 
*Testing*:
This bug was exposed in PR #1622. I did not add a specific test for this because as soon as we migrate more tests to using Placeholders this code will be tested.
=> [Placeholder] Fix a differentiation bug related to Placeholders.

lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphOptzTest.cpp
*Description*: Add optimization for replacing Concat of a single input with that input. This is seen in en2gr.
*Testing*: Added unit test. Fixed another unit test this opt breaks.
=> [GraphOptimizer] Add optimization for replacing Concat of a single input with that input

lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphOptzTest.cpp
*Description*: We were missing optimizations for identities for dividing/multiplying by 1. These are seen in en2gr.
=> [GraphOptimizer] Add identities for div/mul by one

tools/loader/TextTranslator.cpp
For some reason it seems using size_t for llvm cl opts does not work. Moving to unsigned instead. I'm able to change these command line params now, when before it was giving me a runtime error.
```
text-translator: for the -max_input_len option: Cannot find option named '10'!
```
=> [TextTranslator | NFC] Move to unsigned instead of size_t

lib/IR/GraphScheduler.cpp, lib/IR/GraphScheduler.h, tests/unittests/CMakeLists.txt, tests/unittests/graphSchedulerTest.cpp
This commit fixes an underflow bug in
`ChildMemSizeBasedScheduler::orderChildNodesAndSchedule` that can
cause incorrect scheduling. There is code in this function that
orders the children of a node by the amount of memory they free up
by executing. For each node, this is computed as `maxSize - resultSize`,
where `maxSize` is the total memory needed to compute and store the node's
`inputs`, and `resultSize` is the total memory needed to store the node's
outputs. For some nodes, such as a `Concat` that takes `Variables` as input,
`resultSize > maxSize`, so this subtraction underflows, and the scheduler
thinks that the node frees up a lot of memory and schedules it before
some or all of its siblings that actually free up more memory.
This commit fixes this bug by modifying …
=> [GraphScheduler] Fix underflow bug

include/glow/Base/Type.h, lib/Base/Type.cpp, tests/unittests/basicIRTest.cpp
Now displays correct information for 16 and 32 bits quantized types.
=> More generic dotty graph generation for quantized types

lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphOptzTest.cpp
*Description*:
This patch series makes sure the predicates are properly preserved through the sinkCode optimization.
The PR is quite lengthy, but the relevant changes (i.e., not test cases) are pretty small (maybe ~20 lines in GraphOptimizer.cpp).
The bulk of the PR is an hardening of the sinkCode tests + new tests for predication.
*Testing*:
ninja check
At this point, predicates don't change the behavior of the program anyway
=> Preserve the predicate across the sinkCode optimization

examples/mnist.cpp, include/glow/ExecutionEngine/ExecutionEngine.h, include/glow/Graph/Graph.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Graph.cpp, tools/ClassGen/NodeGen.cpp
*Description*:
* Migrate the MNIST test from using Variables to using Placeholders.
* Add two convenient methods to allow the easy migration
between Variables to Placeholders. The new methods updateVariable and
runBatch will be merged with the existing runBatch and updateVariable
methods as soon as we delete the last use.
*  Add new node builders that generate Placeholders and not variables. The
new APIs will allow us to migrate our unit tests from using mutable
bound variables to unbounded placeholders. As soon as we finish the
migration we'll merge the new APIs with the regular builder methods
above. The methods are not annotated with oxygen comments because it's
only a copy that needs to go away as soon as the migration is complete.
* Add the unsafe method: getPlaceholder() to …
=> Remove all mutable bound variables from the first test

lib/Optimizer/GraphOptimizer.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/graphOptzTest.cpp
*Description*: Merge Reshape nodes into private Variables with a single use. Similar to a Reshape(Splat) optimization with the same purpose.
*Testing*: Added a unit test. This opt also broke other unit tests which reshaped private variables, so I made all those variables public to prevent breaking the tests.
=> [GraphOptimizer] Merge Reshape into private Variables with one use

utils/download_test_db.py
*Description*: It uses some libraries whose APIs changed between 2 and 3 (urllib, pickle).  Check those.
*Testing*:  `python{2,3} download_test_db.py`
Fixes #1648
=> [utils] Make download_test_db py3 compatible

.travis.yml, tests/unittests/MLTest.cpp, utils/format.sh
*Description*:
Allow format.sh to process `fix` and `check` args.
When in `check` mode format.sh exits with the error exit code if code base requires formatting.
* `check` is intended to be used as part of the CI.
* `fix` is intended to be used when running format.sh locally.
*Testing*:
Local run with `check` and `fix` params.
Running on Travis with `check` param.
format.sh outputs required args if it's invoked with incorrect args.
=> [format.sh] Allow format.sh to check whether the code base does not comply with the clang-format.

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Optimizer/Lower.cpp, tests/unittests/OperatorTest.cpp, tools/ClassGen/NodeGen.cpp
*Description*: Backends may prefer to be passed a TileNode instead of implementing it as an InsertTensorNode/Instruction. Add the TileNode explicitly so that the backend can prevent lowering. I also added the creator for InsertTensorNode since it did not already exist.
*Testing*: Current tests for Tile should cover this already. I also added a test for InsertTensorNode which was not previously explicitly tested.
=> Add TileNode, lowered to InsertTensorNode

lib/Backends/CPU/LLVMIRGen.h
*Description*:
Small change to make CPU backend inheritable (continues https://github.com/pytorch/glow/pull/1562).
*Testing*:
NFC, so no testing.
NFC, so no documentation updates.
=> [CPU] Make LLVMIRGen::generateLLVMIRForModule virtual

lib/Optimizer/Quantization.cpp, tests/unittests/MLTest.cpp
*Description*:
Fix the profile-guided quantization of placeholders. The problem was
that we were not profiling placeholder nodes. This commit also ports the
tests from Variables to Placeholders.
*Testing*: Ported the test to use PH.
=> [Placeholder/Quantization] Fix the profile-guided quantization of PH.

include/glow/Graph/Context.h, include/glow/Graph/Graph.h, lib/Graph/Context.cpp, lib/Graph/Graph.cpp, tests/unittests/BackendTest.cpp
*Description*:
[Placeholder] Allow the SaveNode builder to accept Placeholders.
Allow the SaveNode builder to accept Placeholders. This API is used in some of the upcoming unit test changes.
[Context] Add two allocation methods to the context.
Add two allocation methods to the context. These methods can be used to
verify that all placeholders are allocated. I'll include the actual
check in the next PR, that requires some restructuring of compile() and
some tests.
Example:
```
#ifndef NDEBUG
auto *P = ctx.getFirstUnallocated(F->getParent()->getPlaceholders());
(void) P;
assert(nullptr == P && "Found an unallocated placeholder");
#endif
```
=> [Placeholder ] Add two allocation methods to the context and update SaveNode.

include/glow/Graph/Graph.h, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/Interpreter/Interpreter.cpp, lib/Graph/Graph.cpp, lib/Quantization/Quantization.cpp, tests/unittests/quantizationTest.cpp
Allow for a Tile to be quantized based on the profile that was gathered for it. I added Tile to the end2end quantization test.
Slice and Gather were already supported, but not yet added to the CPU Backend.
=> [Quantization] Support for Slice, Gather, Tile

lib/Graph/Nodes.cpp, tests/unittests/quantizationTest.cpp
This check only makes sense if we are using `quantization::Schema::Asymmetric`. Currently the schema is only used when dumping the profile, so it's not possible to know what schema is used when loading the profile/quantizing. Hence I am removing this verify.
This unbreaks models with relus when loading a profile that was dumped with `-quantization-schema=symmetric`. I verified this with Resnet50. I also added a unit test for Relu with symmetric parameters.
=> [Nodes] Do not verify offset of quantized ReluNode

tests/unittests/BackendTest.cpp
This commit fixes a compiler warning for `BackendTest.cpp` introduced by #1671.
**Testing**
Without this patch, the warning appears when compiling:
```
meghanl-mbp:build_DEBUG meghanl$ ninja all
[2/3] Building CXX object tests/unittests/CMakeFiles/backendTest.dir/BackendTest.cpp.o
/Users/meghanl/fbsource/glow/glow/tests/unittests/BackendTest.cpp:230:9: warning: unused variable 'saveTensor' [-Wunused-variable]
auto *saveTensor = C.allocate(savePlaceholder);
^
1 warning generated.
[3/3] Linking CXX executable tests/backendTest
```
With this patch, it does not:
```
meghanl-mbp:build_DEBUG meghanl$ ninja all
[3/3] Linking CXX executable tests/backendTest
meghanl-mbp:build_DEBUG meghanl$ 
```
All unit tests still pass.
=> [NFC] Fix warning introduced by #1671

include/glow/Base/Tensor.h, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/graphTest.cpp, tests/unittests/tensorsTest.cpp
*Description*:
This PR adds fp16 support for the convolution node in the interpreter
*Testing*:
Added test cases
This depends on #1660 and is related to #1329
=> Fp16 interpreter support: Convolution

include/glow/Graph/Graph.h, lib/Graph/Grad.cpp, lib/Graph/Graph.cpp, tests/unittests/gradCheckTest.cpp
This commit replaces `Variables` in `gradCheckTest` with `Placeholders`
as part of the larger migration to `Placeholders`.
**Testing**
```
[0/1] Running tests...
Test project /Users/meghanl/fbsource/glow/build_DEBUG
Start  1: partitionTest
1/21 Test  #1: partitionTest ....................   Passed    0.04 sec
Start  2: tensorsTest
2/21 Test  #2: tensorsTest ......................   Passed    0.33 sec
Start  3: gradCheckTest
3/21 Test  #3: gradCheckTest ....................   Passed    4.09 sec
Start  4: IROptTest
4/21 Test  #4: IROptTest ........................   Passed    0.01 sec
Start  5: basicIRTest
5/21 Test  #5: basicIRTest ......................   Passed    0.01 sec
Start  6: backendTest
6/21 Test  #6: backendTest ...................... …
```
=> [Placeholder] Migrate gradCheckTest to Placeholders

lib/Quantization/Base/Base.cpp, tests/unittests/quantizationTest.cpp
*Description*:
schema == SymmetricWithUInt8 and offset == 0 makes the
```
assert(result.offset == -128 || schema != quantization::Schema::SymmetricWithUInt8)
```
fail
*Testing*:
./tests/quantizationTest
N/A
cc: @opti-mix who discovered assert failure on dumping profile for some models.
=> [bug fix] When schema is symmetric with unit8 we need to allow 0 check in the assert.

tests/unittests/graphGradTest.cpp
This commit migrates a `createSave` call in `graphGradTest.cpp` to the
version that creates a `Placeholder` instead of a `Variable`. This
should have been included as part of #1679.
**Testing**
=> [Placeholders] Migrate forgotten createSave in graphGradTest

lib/Backends/CPU/libjit/libjit_conv.cpp, lib/Backends/CPU/libjit/libjit_defs.h
*Description*: GCC doesn't support OpenCL vectors (`ext_vector_type`), which causes libjit to be miscompiled under GCC.  Clang supports GCC vectors (`vector_size`) but has different syntax for casting/broadcasting.  Platform-specific #ifdefs seem like the best way forward
*Testing*: GemmTest
Fixes #1661
=> [libjit] Make vector types compatible with GCC

tests/unittests/graphTest.cpp
*Description*:
I found this case by adding an assertion in the SaveNode that saves into variables.
*Testing*: This is a test.
*Documentation*: none. 
#1334
=> [Placeholder] Migrate the last use of variables in one test.

README.md
*Description*:
Currently, Glow does not work with LLVM7.0 and ```brew install llvm``` attempts to install llvm7.
*Testing*:
Run the command.
README.md update
=> [docs] Update instructions for llvm installation

tests/unittests/OperatorTest.cpp
*Description*: [Placeholder] Update tests that were creating variables that were saved into.
*Testing*: This updates tests. I found this issue by adding assert false into the save node that created variables. 
*Documentation*: none.
#1334.
=> [Placeholder] Update tests that were creating variables that were saved into.

include/glow/Graph/Node.h, include/glow/Optimizer/Optimizer.h, lib/Graph/Node.cpp, lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphOptzTest.cpp
*Description*: Add an optimization pass that replaces Placeholders with constants, so that the values can be used in optimization.  Placeholders are bound to values passed in via a Context, minus a blacklist (to avoid binding, e.g., function inputs).  I haven't yet wired the new conversion pass into the ExecutionEngine optimization pipeline, because I think we'll want to experiment with where it's called with respect to training and inference passes before baking it in.
*Testing*: A new test in graphOptz, plus a second commit that converts many of the tests that require constants to use the new pass.
*Documentation*: None, yet.
Fixes #1623
=> [Optimizer] Optimization to convert Placeholders to Variables (Constants)

lib/Importer/ONNX.cpp, lib/Importer/ONNXIFILoader.cpp
*Description*:
We should include `onnx/onnx_pb.h` instead of `onnx/onnx.pb.h` directly as it has annotation like `ONNX_API` defined. 
*Testing*:
```
cmake -G Ninja ..  -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm
```
And it works. 
N/A
=> [ONNX] Include correct ONNX header

examples/mnist.cpp
*Description*: After our recent placeholder conversions, our examples no longer use constant weights during inference.  Let's try out the new constant-conversion opt, starting with mnist.
*Testing*: `./bin/mnist`
=> [examples] Convert PH->constants in mnist

examples/char-rnn.cpp, examples/fr2en.cpp
*Description*: Convert char-rnn and fr2en, which are the only other examples that compile for inference.  char-rnn is an interesting one.  Since we run multiple rounds of inference, we need to clone the function before each round, or else we'll keep stale variable values around in future inference runs.
*Testing*:  Manually validate that char-rnn and fr2en produce the same results as they used to.
=> [examples] convertPlaceholdersToConstants in other examples

include/glow/Base/Tensor.h
*Description*:
Recently @beicy debugged an issue where doing `auto H = T.extractSlice(i).getHandle();` resulted in corrupted Handle. This happened because `T.extractSlice(i)` was creating a temporary Tensor object, which was destroyed on the same line. So Handle outlived Tensor it was pointing at. Such errors could be caught at compilation stage.
*Testing*:
Make sure that `auto TT = Tensor(424.).getHandle();` does not compile.
Let me know what you think. I don't see `&&` specifier used in this way in our codebase. But maybe we should add it everywhere else, e.g. `getUnsafePtr()`, `getUnowned()`.
=> [Tensor] Disallow GetHandle() when Tensor is an rvalue object

examples/bundles/resnet50/Makefile, examples/bundles/vgg19/Makefile, examples/bundles/zfnet512/Makefile
*Description*: Does anyone mind if we make the bundle makefiles echo commands by default?  I started to look at #1726 and it'd be a lot easier to tell what's happening if the commands were echoed.  People can always run `make -s` if the console spam is annoying.
*Testing*:  `make`
*Documentation*:  N/A
=> [bundles] Don't silence Makefiles by default

lib/Importer/CMakeLists.txt, lib/Importer/Caffe2.cpp, lib/Importer/caffe2.proto
*Description*:
Change the path we include `caffe2.pb.h` so that it conforms to fb internal build system. For OSS, this doesn't have any effect. I also updated `caffe2.proto` to sync up with Pytorch repo. 
*Testing*:
Build should pass as is. 
=> Make the caffe2.proto inclusion better

include/glow/Graph/Graph.h, lib/Graph/Grad.cpp, tests/unittests/gradCheckTest.cpp
*Description*:
[Placeholder] Remove the ability to differentiate variables.
This commit removes the ability to differentiate variables. From this
point we can only differentiate placeholders. It looks like we've
reached this point because all of the tests are passing. 
@bertmaher 's recent change removed all of the trainable variables.
#1334
=> [Placeholder] Remove the ability to differentiate variables.

include/glow/Graph/Graph.h, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Importer/Caffe2.cpp, tests/models/caffe2Models/replace_nan_predict_net.pbtxt, tests/unittests/OperatorTest.cpp, tests/unittests/caffe2ImporterTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/NodeGen.cpp
This commit fixes #1704 and adds support for the `ReplaceNaN` Caffe2 operator to the
Caffe2 model importer. This operator accepts one tensor as an input and
a value as an argument, and replaces all elements of the input that are
`NaN` with the given value. To implement this operator, this commit adds a new
Glow node, `IsNaN`, which accepts an input tensor and outputs a tensor in
which each element is a boolean indicating whether or not the
corresponding element in the input is `NaN`. With this new node in
hand, a `ReplaceNaN` operator is implemented as a `Select` node with the
`ReplaceNaN` input as one of the inputs, a `Splat` node created using the replacement value
as the other input, and the output of an `IsNaN` node as the comparator
input. This `IsNaN` node becomes a …
=> [Caffe2] Implement ReplaceNaN operator

lib/Importer/ONNX.cpp, tests/models/onnxModels/averagePool3D.onnxtxt, tests/unittests/onnxImporterTest.cpp
*Description*: We were crashing on a 3D average pool, because we expect to do a 4D transpose for NCHW to NHWC (rather than a 5D transpose).  Return false instead.
*Testing*: Death test for onnxModelLoader.  (Note that ONNXIFI will not die; this is the standalone ONNX model loader that dies when a model can't be loaded, which seems proper.)
Fixes #1736
=> [Importer] Report error if model contains non-2D pool

lib/Backends/CPU/BundleSaver.cpp, lib/Backends/CPU/GlowJIT.cpp, lib/Backends/CPU/GlowJIT.h, lib/Backends/CPU/LLVMIRGen.cpp
*Description*: Sigh.  Facebook's internal LLVM is lagging the stable release, so this is reintroducing a stopgap to get glow to build.
*Testing*: `ninja all` works in OSS repo, internal build also works
=> Compatibility with FB-internal LLVM

lib/Onnxifi/onnxifiGlow.cpp
*Description*:
Wrap onnxifi function names into macro. Now those can be controlled externally.
*Testing*:
build + manual test.
n/a
cc: @Maratyszcza @yinghai
=> [onnxifi] Wrap onnxifi function names into macro.

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/graphTest.cpp
*Description*
Copying Modules around would make them share the same underlying memory
for all the functions, variables, and placeholders.
Therefore, if we were to copy a module by mistake (e.g., by forgetting
to put & after the typename of a local variable), when this copy
would get deleted, it would leave the original module with dangling
pointers.
This patch also adds a clear method for the one test case where the
copy of a module was made on purpose.
*Testing*
Added test case for the clear mehod and changed the one test case
that was using Module copy.
*Description*:
*Testing*:
=> [Graph] Make Module non-copyable

include/glow/Graph/Node.h, lib/Graph/Node.cpp, tests/unittests/graphTest.cpp
* Description *
Prior to this patch the only way to change the type of a Node was
to create a new one with a different type and manually set the
arguments to match the node you want to replace.
This patch introduces a setType method that allows to change the
type of a specific result.
This method only changes the type of the specified result, in other
words if this type is only valid if the type of the inputs are changed
as well, these inputs have to be updated independently.
E.g.,
tensor<float> A
tensor<float> B
tensor<float> = batchAdd A, B
Changing the type of the result of batchAdd won't change the type
of A and B. Thus if those are not updated the verifier will complain
that the type for the sources and the result are incompatible.
* Testing *
* Documentation *
N/A …
=> [Node] Add a setType method

include/glow/Base/Tensor.h, lib/Base/Tensor.cpp, tests/unittests/tensorsTest.cpp
*Description*
This patch adds a convertToType method that allows to convert the content
of a tensor from its current type to a new type.
The shape of the tensor remains unchanged, but the element type
gets updated to the new type.
For now, this method only supports conversion between float and
float16_t.
*Testing*
Related to #1329, this patch adds the functionality required to
change the content of a network while doing conversion from one
type to another.
*Description*:
*Testing*:
=> [Tensor] Add a convertToType method

.travis.yml
We have an issue with a cat failing on travis after `travis_wait` not exiting correctly. I don't know why this has suddenly started occurring. It seems to be a quirk of `travis_wait`. This PR basically duplicates some functionality of `travis_wait` -- it will write to the terminal every minute to make sure travis doesn't fail early, waiting until the tests end. Based on https://github.com/travis-ci/dpl/issues/568#issuecomment-272465349
Here's another potential solution to fix this problem, which would allow us to keep using `travis_wait`: https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959
=> [travis.yml] Use keep_alive() instead of travis_wait

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, lib/Importer/Caffe2.cpp, tests/models/caffe2Models/dot_product_predict_net.pbtxt, tests/unittests/caffe2ImporterTest.cpp
This commit fixes #1701 and adds support for the `DotProduct` Caffe2
operator to the Caffe2 model importer. This operator accepts two tensors
of the same shape and with at most 2 dimensions, and computes their
row-wise dot product. This dot product operator is immediately lowered
to a `Mul` node if the inputs are 1D, and to a `Mul` node followed by a
`BatchedReduceAdd` on `axis=1` if the inputs are 2D.
**Testing**
This commit adds two test cases to `caffe2ImporterTest.cpp`, one for 1D
inputs and the other for 2D inputs.
All other unit tests pass.
=> [Caffe2] Implement DotProduct operator

include/glow/Importer/ProtobufLoader.h, lib/Importer/ProtobufLoader.cpp, tools/loader/ImageClassifier.cpp, tools/loader/Loader.cpp, tools/loader/Loader.h, tools/loader/ModelRunner.cpp, tools/loader/TextTranslator.cpp
*Description*:
Refactor the load APIs to remove the use of Variable:
[PH] remove getVariableByName from the loader. NFC.
[PH] Remove the variables from the run() interface.
*Testing*: Ran ninja check and run.sh.   I did not test the textual model runner. 
*Documentation*: none.
=> [Placeholder] Refactor the loader APIs to remove some use of Variable (NFC)

lib/Graph/Graph.cpp, lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphOptzTest.cpp, tests/unittests/graphTest.cpp
[Optimizer] Teach the bacthNorm(Conv) optimization about FP16
*Description*
Prior to this patch the optimization that merges convolution followed
by batchNorm would assert on fp16 because the handles expect a regular
single precision floating point type.
This patch templatizes this part of the optimization so that it
works seamlessly with single or half precision floating point numbers.
*Testing*
=> [Optimizer] Fix the batchnorm(conv) opt for FP16

lib/Importer/ONNX.cpp
Issue #1755, test case 3 (test_maxpool_with_argmax_2d_precomputed_strides).
=> [onnx] Glow does not support argmax output when pooling

lib/Backends/Interpreter/InterpreterNodes.cpp, tests/unittests/OperatorTest.cpp
*Description*
This commit adds the right dispatch code to run the Splat node
in half precision.
*Testing*
Related to #1329.
=> [Backend][Interpreter] Implement fp16 splat

include/glow/Support/Float16.h, lib/Backends/Interpreter/InterpreterNodes.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/float16Test.cpp
[Backend][Interpreter] Implement fp16 max pooling
*Description*
This commit adds the right dispatch code to run the MaxPool node
in half precision.
*Testing*
Related to #1329.
=> [Backend][Interpreter] Implement fp16 max pooling

tests/unittests/OperatorTest.cpp
Make sure FP16 tensorview works properly.
We rely on some tensor method under the hood that already support fp16, hence NFC.
=> [Backend][Interpreter] Add a test case for FP16 tensor view. NFC.

lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, tests/unittests/OperatorTest.cpp
*Description*
This commit templatizes the implementation of SoftMax and adds the
dispatch code to execute the single precision or half precision
variant for floating point types.
*Testing*
=> [Backend][Interpreter] Implement FP16 SoftMax

include/glow/Graph/Graph.h, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit_matmul.cpp, lib/Graph/Graph.cpp, tests/unittests/OperatorTest.cpp
*Description*:
Add row-wise quantized FC for CPU backend.  
*Testing*:
Enable the unittest `rowwiseQuantizedFCTest` with CPU backend.
[Optional Fixes #1402 ]
=> [Quantization] Add row-wise quantized FC for CPU backend

lib/Backends/CPU/libjit/libjit_defs.h
*Description*: Surprisingly, this was the only blocking issue I hit when trying to compile with gcc 4.8.5, which is the CentOS 7 default.
=> [libjit] Make BroadcastFloat8 compatible with gcc 4.8.5

tools/CMakeLists.txt, tools/IncludeBin/CMakeLists.txt, tools/IncludeBin/IncludeBin.cpp
*Description*: We need a tool to package binary data inside our libraries.  This tool, include-bin, is a stripped down implementation of `xxd -i`, since we can't depend on `xxd` existing on all our target platforms.
*Testing*: `ninja include-bin`
=> [include-bin] A tool to convert binary files to include-able char arrays

lib/Importer/Caffe2ModelLoader.cpp
This commit adds support for the `Copy`, `EnsureCPUOutput`, and `EnsureDense`
Caffe2 operators. These operators do not make much sense in the context
of Glow and have been implemented as no-ops.
**Testing**
**Fixes**
This commit fixes #1700.
=> [Caffe2] Add support for Copy, EnsureCPUOutput, EnsureDense operators

lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, tests/unittests/OperatorTest.cpp
*Description*
This commit templatizes the implementation of ElementMax and adds the
dispatch code to execute the single precision or half precision
variant for floating point types.
*Testing*
=> [Backend][Interpreter] Implement FP16 ElementMax

include/glow/ExecutionEngine/ExecutionEngine.h, include/glow/Importer/Caffe2ModelLoader.h, include/glow/Importer/CommonOperatorLoader.h, include/glow/Importer/ONNXIFIModelLoader.h, include/glow/Importer/ONNXModelLoader.h, include/glow/Importer/ProtobufLoader.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Importer/Caffe2ModelLoader.cpp, lib/Importer/ONNXIFIModelLoader.cpp, lib/Importer/ONNXModelLoader.cpp, lib/Importer/ProtobufLoader.cpp, lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, tests/unittests/ImporterTestUtils.h, tests/unittests/caffe2ImporterTest.cpp, tests/unittests/onnxImporterTest.cpp, tools/loader/ImageClassifier.cpp, tools/loader/Loader.h, tools/loader/ModelRunner.cpp, tools/loader/TextTranslator.cpp
*Description*: This is a WIP PR. This PR ports the last major piece of code to use Placeholders instead of variables. This PR will be followed by cleanup PRS. 
*Testing*: At one point I was able to run the loader. Some tests are still failing. 
#1334
=> [PH] Port the C2/ONNX loader to using Placeholders.

lib/Backends/CPU/CMakeLists.txt, lib/Backends/CPU/LLVMIRGen.cpp, tools/CMakeLists.txt, tools/IncludeBin/CMakeLists.txt, tools/IncludeBin/IncludeBin.cpp
Description: Glow will be easier to distribute if we can package libjit into the library, rather than keeping it as an external file dependency. This PR uses `include-bin` to compile libjit.bc into LLVMIRGen.
Testing: ninja check
Documentation: N/A
=> [cpu] Compile libjit into CPU backend using include-bin

tests/unittests/graphSchedulerTest.cpp
*Description*
We use a temporary std::vector because we compare directly two iterator
to check which instruction comes first in the final schedule.
Instead if we compare the distance from the beginning for each
iterator, we don't need our iterator to support random accesses and
we can avoid the temporary object.
This is what this patch does.
NFC
=> [NFC][unittests][GraphScheduler] Avoid the use of a temporary std::vector

.travis.yml
*Description*:
As part of the CI we run tests with Glow compiler optimizations turned off.
This PR enables such tests only for DEBUG builds but not for ASAN.
This speeds up ASAN run from 40+ to 23 mins.
*Testing*:
CI
N/A
=> [travis] Run unopt only for debug build.

lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, tests/unittests/OperatorTest.cpp
*Description*
This commit templatizes the implementation of BatchedAdd and adds the
dispatch code to execute the single precision or half precision
variant for floating point types.
*Testing*
=> [Backend][Interpreter] Implement FP16 BatchedAdd

lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphOptzTest.cpp
*Description*:
An internal net model I'm working on has explicit transpose nodes for convolution weights. This prevents BatchNorm + Conv merge optimization from triggering.
The patch moves transpose constant folding before BatchNorm optimization in order to get rid of these transposes and make BatchNorm + Conv merge happen.
*Testing*:
Added a unit test.
N/A
=> [GraphOptimizer] Move transpose constant folding optimization before merging BatchNorm into Convolution

include/glow/ExecutionEngine/ExecutionEngine.h, include/glow/Graph/Graph.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Grad.cpp, lib/Graph/Graph.cpp, lib/Importer/Caffe2ModelLoader.cpp, lib/Importer/ONNXModelLoader.cpp, lib/Optimizer/Lower.cpp, lib/Optimizer/Partition.cpp, tools/ClassGen/NodeGen.cpp
*Description*:
1.    [Placeholder] Remove the support for variables from SaveNode.
2. [Placeholder] Remove the ability to create SaveNode that saves into a variable.
This commit removes the SaveNode constructor that saves into a variable.
It also fixes the lowering method and makes it create a placeholder for
the GSUM storage.  It also renames createSaveNodePH into createSaveNode.
At the moment we need to initialize the context after lowering because
lowering creates new placeholders. When we migrate the context into the
execution method we'll be able to move the initialization outside of the
compilation code.
*Testing*: Ran ninja check and run.sh
#1334
=> [Placeholder] Remove the ability to save into variables.

lib/Backends/CPU/CMakeLists.txt
Use a custom linker language to change the linker invocation for the CPU
Runtime.  This allows us to properly track the dependencies and ensure that
Ninja does not rebuild the target unnecessarily.  As a small benefit, the linker
invocation is now also more portable.  The compiler rule still prevents the use
of the Makefile generator :-(.
*Description*:
*Testing*:
=> CPU: change the way that we generate the JIT runtime

lib/Onnxifi/Base.h
*Description*: [ONNXIFI] Add a getter to silence the unused var warning. NFC.
*Documentation*: none
=> [ONNXIFI] Add a getter to silence the unused var warning. NFC.

lib/Backends/OpenCL/CMakeLists.txt, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/kernels.cl, lib/Backends/OpenCL/kernels_fwd_conv.cl, lib/Backends/OpenCL/kernels_fwd_quantized_conv.cl, utils/format.sh
*Description*:
It is now possible to treat the OpenCL sources as real C source files in the editors, formatting tools, etc.
It should also solve issues with compilers which could not handle raw string literals that are too long.
Also take the opportunity to make format.sh run on the OpenCL sources we have.
*Testing*:
ninja test
=>  Generate OpenCL kernel inc header files from original OpenCL kernel sources directly using the new include-bin utility

include/glow/Graph/Graph.h, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/batch_box_cox_predict_net.pbtxt, tests/unittests/caffe2ImporterTest.cpp
This commit adds support for the `BatchBoxCox` Caffe2 operator. This
operator accepts a matrix `data` and two vectors `lambda1` and `lambda2`
as input and computes the two-parameter Box-Cox transform of each column
`c` of `data` with parameters `lambda1` and `lambda2`. The transform
`y_i` for each element `c_i` of the input column is given by
<a href="https://www.codecogs.com/eqnedit.php?latex=y&space;\left&space;(&space;x,&space;\lambda_{1},&space;\lambda_{2}&space;\right&space;)=&space;\begin{cases}&space;\ln&space;\left&space;(&space;\max(x&space;&plus;&space;\lambda_{2},&space;1&space;\times&space;10^{-6})\right&space;)&space;&&space;,\lambda_{1}&space;=&space;0&space;\\&space;\frac{(\max(x&space;&plus;&space;\lambda_{2},&space;1&space;\times&space;10^{-6}))^{\lambda_{1 …
=> [Caffe2] Implement BatchBoxCox Caffe2 operator

include/glow/ExecutionEngine/ExecutionEngine.h, include/glow/Graph/Graph.h, include/glow/Graph/Nodes.h, include/glow/Importer/CommonOperatorLoader.h, lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/CPU/BundleSaver.cpp, lib/Backends/CPU/Transforms.cpp, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/IR/IRGen.cpp, lib/Importer/Caffe2ModelLoader.cpp, lib/Importer/ONNXModelLoader.cpp, lib/Importer/ProtobufLoader.cpp, lib/Optimizer/GraphOptimizer.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/graphOptzTest.cpp, tests/unittests/graphTest.cpp
*Description*:
This PR contains 3 commits that clean up Variable and prepare for the rename to Constant. Most of the changes are NFC, but there were some changes that are related to the use of visibility.
[Var] Remove isTrainable from Variable.
[Var] Remove the visibility flag from Variable.
[Var] Remove unused variable methods. NFC.
*Testing*: Ninja check and run.sh
=> Remove the training logic and visibility from Variable.

lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/fcTransposed_init_net.pbtxt, tests/models/caffe2Models/fcTransposed_predict_net.pbtxt, tests/models/caffe2Models/fc_init_net.pbtxt, tests/models/caffe2Models/fc_predict_net.pbtxt, tests/unittests/caffe2ImporterTest.cpp
*Description*:
Support caffe2 FCTransposed op.
https://caffe2.ai/docs/operators-catalogue.html#fctransposed
*Testing*: 
Added unittest in caffe2ImporterTest.cpp
[Optional Fixes #1697 ]
=> [Caffe2] Support FCTransposed op.

include/glow/Base/Traits.h, include/glow/IR/IRBuilder.h, include/glow/IR/Instrs.h, lib/Backends/CPU/AllocationsInfo.cpp, lib/IR/IRBuilder.cpp, lib/IR/IRGen.cpp, lib/Optimizer/IROptimizer.cpp
*Description*: This PR removes the VisibilityKind from WeightVar. It is not needed anymore now that we have Placeholder and Constants. We can rely on the mutability of the variable for everything. Thanks @jfix71 for identifying this. 
*Testing*: Ninja check. 
=> Remove VisibilityKind from WeightVar.

lib/Graph/Graph.cpp, tests/unittests/graphTest.cpp
*Description*: This verify pass was broken during the Placeholder migration. I moved to a `dyn_cast` instead of `isa` followed by `cast` to make it less error prone.
*Testing*: Added a unit test so that it won't be accidentally broken again in the future.
=> [Graph] Fix verify one writer

lib/Onnxifi/onnxifiGlow.cpp
*Description*:
Some of the function calls were missing GLOW_ONNXIFI_LIBRARY_FUNCTION_WRAPPER wrapper.
*Testing*:
Manual.
N/A
=> [fix] Fix calls to onnxifi methods.

lib/Optimizer/GraphOptimizer.cpp
**Description**: A lot of our codebase still references Variables instead of Constant/Placeholder/Storage (in comments, variable names, etc.). This PR updates the GraphOptimizer to reflect the recent migration.
**Testing**: ninja test
**Documentation**: N/A
=> [GraphOptimizer] Updates to reflect Variable migration

tests/images/CMakeLists.txt
*Description*: imagenet_299 directory is not copied to build directory currently, so the test fails to find files from imagenet_299
*Testing*: `tests/images/run.sh`
This is followup to PR #1651
=> [Imagenet tests] Add cmake rule for imagenet_299 directory.

include/glow/Converter/FunctionConverter.h, lib/CMakeLists.txt, lib/Converter/CMakeLists.txt, lib/Converter/FunctionConverter.cpp
*Description*
Converting some operators of a function from one type to another,
for instance single precision floating point to half precision
floating point, single precision floating point to quantized type,
and son on, does not depend on the source and destination types.
Therefore, it is possible to share the same core framework for all
such conversion.
This patch introduces a new helper class FunctionConverter that
realizes this concept. In particular, it features the main conversion
procedure (FunctionConverter::convert) and relies on the specialization
of the class to implement the type specific bit like how to materialize
the conversion from the source type to the destination type, what type
should be used for a specific value and so on.
The main conversion procedure works like …
=> [Converter] Introduce a FunctionConverter helper class

lib/Graph/Graph.cpp, tests/unittests/graphTest.cpp
*Description*
Prior to this patch, Function::eraseNode(Node *N) would erase a node
with the same value as N, but not necessarily N. This means that
as soon as two nodes were identical, there was a non-zero chance
that deleting one would actually make the other one being a dangling
pointer.
*Testing*
The added test case would assert (Could not find node to delete) in
debug mode and segmentation fault in release mode without this patch.
=> [Function] Fix a nasty bug in eraseNode(Node *)

tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/CMakeLists.txt, tests/unittests/OCLTest.cpp
*Description*: Our BackendCorrectnessTests are all float. We ideally would also test them quantized. It is preferable not to have to rewrite them all quantized. This PR intends to provide a better API for constructing a Function, optionally profiling/quantizing it, and then comparing its output to the Interpreter. For now I only did this for `BasicFCNet` as a trial -- if it's agreed this is a good direction I will convert over the other BackendCorrectnessTests in a future PR.
=> [unittests] New BackendCorrectnessTest API enabling easy quantization

utils/build_llvm.sh
*Description*: Our `build_llvm.sh` script uses RelWithDebInfo mode, which works OK on Darwin, but seems to cause crazy memory usage during linking on most Linuxes I've tried (Ubuntu, CentOS), leading to oomkiller invocation and general badness.  Since most glow developers don't need to debug LLVM internals, let's default to Release mode here.
As an aside, I'd be inclined to advise devs to get LLVM from a package manager, but it's often pretty hard to get recent LLVM versions from package managers, so I fall back on build locally a lot.
*Testing*: Tried it.
Fixes #1628 (even though that was already closed)
=> [build_llvm] Build LLVM in Release mode to reduce memory pressure

lib/Backends/CPU/CMakeLists.txt
*Description*: We were missing some deps, as pointed out in #1505.
Fixes #1505, mostly.
=> [cpu] Add some missing LLVM deps to CPUBackend

include/glow/Converter/TypeAToTypeBFunctionConverter.h, include/glow/Graph/Graph.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Converter/CMakeLists.txt, lib/Converter/TypeAToTypeBFunctionConverter.cpp, lib/Graph/Grad.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, tests/unittests/CMakeLists.txt, tests/unittests/OperatorTest.cpp, tests/unittests/graphGradTest.cpp, tests/unittests/typeAToTypeBFunctionConverterTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/NodeGen.cpp
Note: The diff will be much more approachable when #1821 and #1820 land, since this PR includes both these PR and the change for this new feature. Reviewing just the last commit of this PR would have the same effect as waiting for #1821 and #1820  to be merged.
*Description*
This patch specializes the FunctionConverter class to feature a converter
from one element type to another.
In essence this new TypeAToTypeBFunctionConverter class scans the
function, morph the node from TypeA to TypeB and inserts the right
conversions to/from typeA and typeB around the converted nodes.
This initial version follows the same schema as the quantization
of function, meaning there are no attempt to eliminate useless conversion.
This feature will be added later.
*Testing*
Tests added.
=> [Converter] Add a helper class to converter a function from type A to type B

include/glow/Graph/Graph.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Grad.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/graphGradTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/NodeGen.cpp
*Description*
This node/instruction represents a type conversion (a.k.a. a cast)
from the input type to the output type.
The shape of the input and output type must be identical, only the
element type is allowed to change.
This node will allow us to represent type conversions when converting
a graph from one type to another.
This patch adds the support for this node in the interpreter and
teaches the differentiation mechanism how to deal with ConvertTo
node.
Note: We could technically introduce different nodes for the different
conversion (e.g., fpext, fptrunc, inttofp, and so on) since this
node would have different interpretation based on the input and output
types. Right now, we decided not to do that because we expect this
node to not hit any backends. In particular, this node is only …
=> [Graph&IR] Add a ConvertTo node

.travis.yml, utils/install_protobuf.sh
*Description*:
Mostly time is saved on utils/install_protobuf.sh run (~10%).
Going to merge this and then CircleCI might give us some wins later on.
*Testing*:
CI
n/a
=> [travis] Cache what's possible to speed up the build

.circleci/config.yml
*Description*:
Dummy circle ci config.
*Testing*:
CI
N/A
Tracking here: https://github.com/pytorch/glow/issues/1836
=> [CI] Make dummy circleci config to avoid failures on master.

lib/Onnxifi/onnxifiGlow.cpp
*Description*:
We don't want to mangle the name of ONNXIFI interface or dlopen will fail. 
*Testing*:
Build onnxifi-glow.so and use `nm` to verify that names are not mangled. 
=> [ONNXIFI] Don't mangle the name of ONNXIFI interface functions

tests/unittests/OperatorTest.cpp, tests/unittests/caffe2ImporterTest.cpp
*Description*:
MSVC requires the `f` suffix on single-precision `float` literals.  This PR fixes float literals for MSVC.
=> Fixes float literals for MSVC.

lib/Importer/ONNXIFIModelLoader.cpp
*Description*:
The assumption that ONNX model only contains one node doesn't hold because Caffe2 op might be exported into multiple ONNX nodes. 
*Testing*:
Run the ONNXIFI integration test from Pytorch repo:
pytest python/onnx/test_onnxifi.py
And it should pass. 
=> [ONNXIFI] Fix resnet50 integration test

lib/Backends/CPU/GlowJIT.cpp
*Description*:
Fixes GlowJIT.cpp for MSVC by
Change the function prototype from
GlowJIT::ModuleHandle GlowJIT::addModule(std::unique_ptr<Module> M)
to
GlowJIT::ModuleHandle GlowJIT::addModule(std::unique_ptr<llvm::Module> M) {
=> Fixes GlowJIT.cpp for MSVC.

lib/Backends/CPU/GlowJIT.cpp
*Description*:
Call findSymbol with hidden symbol.  Under win32, we can not find symbol with option true,
change to false instead.
=> Allow findSymbol to find non-exported symbols

lib/Quantization/CMakeLists.txt, lib/Quantization/Quantization.cpp, tests/unittests/quantizationTest.cpp
Note: The diff will be much more approachable when #1821 lands, since this PR includes both #1821 and the change for this refactoring. Reviewing just the last commit of this PR would have the same effect as waiting for #1821 to be merged.
*Description*
This patch refactors the code of the function that quantizes a function
to reuse the framework set by the FunctionConverter.
This patch is not strictly speaking NFC because unlike the original
implementation the conversion process does not leave the original,
not use after conversion, node around. Other than that, it should
be NFC.
*Testing*
Ran the quantizationTest
Ran different quantized profiles (asymmetric, symmetric, symmetric
with uint8) with and without the patch for resnet50 and checked
that the output IR were identical (modulo some …
=> [Quantization] Specialize the FunctionConverter to quantize a function

include/glow/Importer/ONNXIFIModelLoader.h, lib/Importer/ONNXIFIModelLoader.cpp, lib/Onnxifi/onnxifiGlow.cpp
*Description*:
Return 2 supported backends + some cleanup.
Currenty C2 just uses backend[0] for execution.
*Testing*:
Int test
N/A
cc: @yinghai
=> [ONNXIFI] Return 2 supported backends + some cleanup.

lib/Backends/CPU/CMakeLists.txt, tests/benchmark/CMakeLists.txt, tests/unittests/CMakeLists.txt
*Description*:
Disable CPURuntimeNative for MSVC
because libjit can not compiled with cl.exe
Related to  https://github.com/pytorch/glow/issues/1144
=> Disable CPURuntimeNative for MSVC

lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/avgpool_nhwc_predict_net.pbtxt, tests/models/caffe2Models/avgpool_predict_net.pbtxt, tests/models/caffe2Models/conv_nhwc_init_net.pbtxt, tests/models/caffe2Models/conv_nhwc_predict_net.pbtxt, tests/models/caffe2Models/maxpool_nhwc_predict_net.pbtxt, tests/models/caffe2Models/maxpool_predict_net.pbtxt, tests/unittests/caffe2ImporterTest.cpp
*Description*:
Add arg "order" in Caffe2 Conv, MaxPool and AveragePool ops.
The "order" can be "NCHW" (by default) and "NHWC".
*Testing*: 
Unittests added.
N/A
Needed for https://github.com/pytorch/glow/issues/1727
=> [Importer] Support arg "order" in Caffe2 Conv, MaxPool and AveragePool ops

tools/ClassGen/NodeGen.cpp
*Description*
Clarify that the ConvertToNode is not supposed to be used for quantized
types. Instead call out in the docstring that the related quantization
nodes should be used.
Sorry for the delay @jfix71!
=> [NodeGen] Update the docstring for ConvertToNode. NFC

tests/models/caffe2Models/eq_op_net.pbtxt, tests/unittests/caffe2ImporterTest.cpp
*Description*: Added EQ node test to caffe2ImporterTest. This checks that the node is imported and the graph is the expected shape.
*Testing*: Run caffe2ImporterTest caffe2.EQ1D passes.
#985
=> [caffe2ImporterTest] Add eq unittest to caffe2ImporterTest

include/glow/Graph/Nodes.h, lib/Graph/Nodes.cpp, lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphTest.cpp
*Description*
Right now, the type of a constant and the type of its underlying tensor
are stored in two different places. As a result, it is possible to
modify one without modifying the other ending up in a situation
where the constant and its tensor have different types.
This patch makes sure that the verifier reports this problem.
*Testing*
=> [Verifier] Check that the type of a constant and its tensor matches

lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/CPU/BundleSaver.cpp
*Description*: Updated CPU AllocationInfo and CPU Bundle saver to support Placeholder migration. Memory is now properly allocated and the correct symbol table is emitted. The bundle works again.
*Testing*: Build and run resnet50, vgg19, and zfnet512. They all run without error. *Note vgg19 and zfnet incorrectly label 285 as 281. 
Fixes #1800
=> [Bundle] Fix Resnet50 Bundle to support Placeholder Migration

tools/loader/CMakeLists.txt, tools/loader/Loader.cpp
*Description*
This patch adds an option `-convert-to-fp16` to convert all fp32 operators
into fp16 ones.
We may want to expose more conversion options in the future and change
the `convert-to` option to something taking an enum like fp32-to-fp16.
As part of the conversion mechanism it is possible to choose which nodes
are okay to convert (`-do-not-convert-nodes=<listOfNodes>`).
The conversion process does not alter the inputs and outputs of the
network. Thus, the converted graph will have ConvertToNode at least
at its start and end.
*Testing*
Able to convert and run resnet50 in fp16 with the interpreter.
*Documentation*
None so far, we want the interpreter to fully support fp16 before people
play with it.
=> [Loader] Add an option to run a model in fp16

examples/char-rnn.cpp, examples/cifar10.cpp, examples/fr2en.cpp, include/glow/ExecutionEngine/ExecutionEngine.h, lib/Converter/FunctionConverter.cpp, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Graph.cpp, lib/IR/GraphScheduler.cpp, lib/Onnxifi/Base.cpp, lib/Optimizer/IROptimizer.cpp, lib/Optimizer/Lower.cpp, lib/Optimizer/Partition.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/GemmTest.cpp, tests/unittests/HyphenTest.cpp, tests/unittests/MLTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/caffe2ImporterTest.cpp, tests/unittests/gradCheckTest.cpp, tests/unittests/graphTest.cpp, tests/unittests/onnxImporterTest.cpp, tests/unittests/partitionTest.cpp, tools/loader/ImageClassifier.cpp, tools/loader/TextTranslator.cpp
*Description*:
Removing references to variables when appropriate.
*Testing*:
unit tests
N/A
Related to https://github.com/pytorch/glow/issues/1334
=> [NFC/cleanup] Remove more entries of variables.

tools/loader/ImageClassifier.cpp
NFC. I didn't like how the topk labels were being printed. This makes it so that the top label is always printed on the same line as the file, and all other labels are on new lines aligned with it. E.g.
```
File: tests/images/imagenet/cat_285.png        Label-K1: 285 (probability: 0.5823)
Label-K2: 281 (probability: 0.3601)
Label-K3: 282 (probability: 0.0456)
```
=> [ImageClassifier | NFC] Improve topK label printing

lib/Importer/ONNXIFIModelLoader.cpp, lib/Importer/ONNXModelLoader.cpp, tests/models/onnxModels/batchBoxCox.onnxtxt, tests/unittests/onnxImporterTest.cpp
This commit adds support for the `BatchBoxCox` operator to the ONNX model
importer. Most of the work to support this operator was done in an
earlier commit that added support to the Caffe2 loader. Consequently,
this commit only includes code that parses inputs, outputs, and arguments
from an .onnxtxt and calls `Graph::createBatchBoxCox` to implement the
operation.
**Testing**
This commit adds a unit test to onnxImporterTest.cpp to test loading
this operator from a .onnxtxt file.
**Fixes**
This commit fixes #1705.
=> [ONNXifi] Add support for BatchBoxCox operator

tests/benchmark/CMakeLists.txt, tests/benchmark/ConvBench.cpp
Description:
This is a benchmark for convolution in the same style as GemmBench. There are lots of parameters to convolution, and those parameters are subject to a set of requirements. I’ve tried to enforce those requirements in the creation of each benchmark instance.  Convolution also takes a while to run if you have large parameters, so the number of reps is smaller than for GemmBench. We may need to tweak the test cases. Another key difference is that I'm reporting the time in seconds as opposed to gflops.
Testing:
To test, run the ConvBench binary in the tests subdirectory of the build output.
[Fixes #1616 ]
=> Add benchmark for convolution

lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, lib/Onnxifi/CMakeLists.txt, lib/Onnxifi/ThreadPool.cpp, lib/Onnxifi/ThreadPool.h, lib/Onnxifi/onnxifiGlow.cpp, tests/unittests/CMakeLists.txt, tests/unittests/onnxifiThreadPoolTest.cpp
This commit modifies `onnxRunGraph` to make graph execution asynchronous
by submitting it as a lambda to an instance of `ThreadPool` (a new class
encapsulating a thread pool) stored in the `Backend` class. `ThreadPool`
consists of an adjustable number of threads that continuously pop and
execute an item from a common queue of `std::function<void(void)>` objects.
This commit fixes #1570.
**Testing**
This commit adds a unit test for the new `ThreadPool` class. It has also been tested on two known good ONNXifi tests, `test_concat_2d_axis_1`
and `test_concat_2d_axis_1`:
```
$ .setuptools-cmake-build/onnxifi_test_driver_gtests /tmp/onnx_tests
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from …
```
=> [ONNXifi] Make onnxRunGraph execute Glow graph asynchronously

lib/Backends/OpenCL/OpenCL.cpp
*Description*:
Starting with MacOS Mojave, using OpenCL results in a bunch of compiler warnings, because Apple is going to deprecate OpenCL. The warnings suggest defining CL_SILENCE_DEPRECATION to silence any such warnings.
*Testing*:
ninja test
=> Silence Apple's warning about the deprecation of OpenCL

include/glow/Graph/Graph.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/sparse_to_dense.pbtxt, tests/unittests/OperatorTest.cpp, tests/unittests/caffe2ImporterTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/NodeGen.cpp
This commit adds support for the `SparseToDense` Caffe2 operator. This
operator takes a sparse representation of a tensor specified by an array
of indices and an array of tensor values and converts it into a dense
representation. In this dense representation, `values[i]` is stored at
`indices[i]`, and the rest of the dense representation is zero-filled.
Indices can appear twice in the sparse representation, and in this case, all
corresponding values are summed and stored in dense representation.
This operator is implemented as its own Glow node and instruction.
**Testing**
This commit adds tests for this operator to `caffe2ImporterTest.cpp` and
`OperatorTest.cpp`.
**Fixes**
This commit fixes #1702.
=> [Caffe2] Add support for SparseToDense operator

lib/Importer/ONNXIFIModelLoader.cpp, lib/Importer/ONNXModelLoader.cpp, tests/models/onnxModels/replaceNaN.onnxtxt, tests/unittests/onnxImporterTest.cpp
This commit adds support for the `ReplaceNaN` operator to the ONNX model
importer. Most of the work to support this operator was done in an
earlier commit that added support for the Caffe2 loader. Consequently,
this commit only includes code that parses inputs, outputs, and arguments
from an .onnxtxt and calls `Graph::createReplaceNaN` to implement the
operation.
**Testing**
This commit adds a unit test to `onnxImporterTest.cpp` to test loading
this operator from a .onnxtxt file.
**Fixes**
This commit fixes #1704.
=> [ONNXifi] Add support for ReplaceNaN operator

include/glow/Converter/FunctionConverter.h, include/glow/Converter/TypeAToTypeBFunctionConverter.h, include/glow/Graph/Node.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Converter/FunctionConverter.cpp, lib/Converter/TypeAToTypeBFunctionConverter.cpp, lib/Graph/Nodes.cpp, lib/Quantization/Quantization.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/typeAToTypeBFunctionConverterTest.cpp, tools/loader/ImageClassifier.cpp
[ImageClassifier] Add a convert-inout-to-fp16 option
*Description*
This teaches the image-classifier how to convert the input and output
of a network to fp16.
*Testing*
Ran resnet50 with -convert-inout-to-fp16
=> [ImageClassifier] Add an option to convert the input and output to fp16

lib/Converter/TypeAToTypeBFunctionConverter.cpp
*Description*: Got an unused parameter lint warning and thought this was a good assert to add.
*Testing*: `ninja all && gtest-parallel tests/*Test`
=> [converter][easy] Assert destTy == dstKind_ when converting

include/glow/Importer/CommonOperatorLoader.h, tests/models/onnxModels/sumN.onnxtxt, tests/unittests/onnxImporterTest.cpp
*Description*:
Support Add with more than 2 inputs. 
Resolves https://github.com/pytorch/glow/issues/1916
*Testing*:
Unit test. 
=> [ONNX] Support Add with more than 2 inputs

CMakeLists.txt, examples/CMakeLists.txt, lib/CodeGen/CMakeLists.txt, lib/Graph/CMakeLists.txt, lib/IR/CMakeLists.txt, lib/Onnxifi/CMakeLists.txt, lib/Quantization/CMakeLists.txt, lib/Support/CMakeLists.txt, tests/unittests/CMakeLists.txt, tools/loader/CMakeLists.txt
*Description*: It seems we were getting away with lax dependencies, which were exposed when I tried building with `-DBUILD_SHARED_LIBS=ON`.  (Incrementally relinking tests is somewhat faster with shared libs, which is why I was trying this.)
*Testing*: `ninja all && ninja test`
=> [cmake] Fix a bunch of dependencies so BUILD_SHARED_LIBS works

include/glow/Base/Type.h, include/glow/Graph/Graph.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Quantization/Base/Base.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/graphOptzTest.cpp, tests/unittests/quantizationTest.cpp, tools/ClassGen/InstrBuilder.cpp, tools/ClassGen/InstrBuilder.h, tools/ClassGen/InstrGen.cpp
This PR builds on top #1905 and allows for taking any model, converting it into fp16 and then quantizing it. It is useful for running models on the backends without fp32 support.
You can now do the following:
```
bin/image-classifier tests/images/imagenet/cat_285.png -image_mode=0to1 -m=resnet50 -model_input_name=gpu_0/data -convert-to-fp16  -convert-inout-to-fp16 -load_profile resnet50_symmetric_q8.yml
```
The following changes were required:
- updating a bunch of checks/assertions that assumed that only FP32 can be used
- extending the interpreter to support quantize/dequantize with fp16 operands
=> Allow -convert-inout-to-fp16 to be used in combination with -load_profile

examples/char-rnn.cpp, examples/cifar10.cpp, examples/fr2en.cpp, examples/mnist.cpp, include/glow/Backends/CompiledFunction.h, include/glow/ExecutionEngine/ExecutionEngine.h, lib/Backends/CPU/CPUFunction.cpp, lib/Backends/CPU/CPUFunction.h, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Onnxifi/Base.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/GemmTest.cpp, tests/unittests/HyphenTest.cpp, tests/unittests/MLTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/caffe2ImporterTest.cpp, tests/unittests/gradCheckTest.cpp, tests/unittests/graphTest.cpp, tests/unittests/onnxImporterTest.cpp, tests/unittests/partitionTest.cpp, tests/unittests/quantizationTest.cpp, tools/loader/Loader.cpp
*Description*: Create runctx and execute(ctx) functions for moving placeholder memory allocation from compile time to run time and update tests.
*Testing*: Ninja all
Progress on #1904 This would bring us to completion of the second step.
=> [ExecutionEngine] Create runctx and execute(ctx) functions

tests/unittests/OperatorTest.cpp
*Description*: FP16QuantizeAndDequantize was merged just before the change adding context to run. Context is now being passed in and everything compiles again.
*Testing*: ninja all and test
=> [unittests] Fix FP16QuantizeAndDequantize

lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Importer/ONNXIFIModelLoader.cpp, lib/Importer/ONNXModelLoader.cpp, tests/models/onnxModels/sparseToDense.onnxtxt, tests/unittests/OperatorTest.cpp, tests/unittests/onnxImporterTest.cpp
This commit adds support for importing the `SparseToDense` operator from
an ONNX model and running it on the CPU backend.
**Testing**
This commit modifies the existing operator test for `SparseToDense` to
run on both CPU and interpreter, and adds a test to the ONNX importer
test to make sure it is imported correctly from a .onnxtxt file.
=> [ONNX] Add ONNX support for SparseToDense operator

lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/OpenCL/OpenCL.cpp, tools/ClassGen/InstrGen.cpp
Adjust CPU and OpenCL backends accordingly. Allmost all of the required changes are mostly mechanical.
We forgot to mark these quantization-related operations as data-parallel and I noticed it just now.
*Description*:
*Testing*:
ninja test
run.sh for all of our NN models
=> Mark quantize, dequantize and rescale_quantized as data-parallel operations

include/glow/Quantization/Base/Base.h, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/CPU/libjit/libjit_conv.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Backends/OpenCL/kernels.cl, lib/Backends/OpenCL/kernels_fwd_quantized_conv.cl, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/IR/Instrs.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Quantization/Base/Base.cpp, lib/Quantization/Quantization.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/graphTest.cpp, tools/ClassGen/Backends/OpenCL/OpenCLSpecificInstrs.h, tools/ClassGen/InstrGen.cpp
*Description*:
We are working on loading quantized ResNet50 model directly. 
So far, we quantize weights and bias into int8. Both the interpreter and CPU backend support int8 bias. However, this quantized Resnet50 model quantizes weights into int8, but bias into int32. It is because the partial sum of the matrix-matrix multiplication is accumulated into int32, so int32 bias can be added to the int32 partial sum for better accuracy (i.e. int8 bias caused accuracy drop). 
Now we plan to add support of conv with int32 bias and eliminate int8 bias.
*Testing*: 
Added unittest.
#1727, #1762
=> [Quantization] Support int32 quantized bias for quantized Conv

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/logit_op_net.pbtxt, tests/unittests/OperatorTest.cpp, tests/unittests/caffe2ImporterTest.cpp
*Description*: This implements the Logit operator (Graph node and Caffe2 model loader support).
Domain asserts on the `eps` value correspond to the following ones in `caffe2::LogitFunctor`: `CAFFE_ENFORCE_GT(eps_, 0.0);`, `CAFFE_ENFORCE_LT(eps_, 0.5);`.
Cf. https://github.com/pytorch/pytorch/blob/master/caffe2/operators/logit_op.h
*Testing*:
- differential testing (oracle: comparison against C++ re-implementation using randomized inputs),
- property-based randomized testing (zero-sum property for the log-odds for complementary events probabilities; right-inverse property of the logit function with respect to the logistic function),
- Caffe2 model importer test (Output shape, high level checks on the content of the graph).
*Documentation*: Comments in the interface and the implementation …
=> [Graph] Implement Logit operator

lib/Backends/Interpreter/InterpreterNodes.cpp
*Description*:
Forgot to removed the unused code after rebasing my last PR:
[Quantization] Support int32 quantized bias for quantized Conv #1876
*Testing*:
=> [Clean up] Clean up the unused code.

tests/unittests/OperatorTest.cpp
Doesn't work because log is not supported
=> [OperatorTest][fix] Do not run logit test on OCL

lib/Optimizer/GraphOptimizer.cpp, tests/unittests/graphOptzTest.cpp
*Description*:
Optimizer may be called after backend specific transformations and some nodes may have become unused. It is a good idea to remove them, before proceeding with any further optimizations. Without it some optimizations do not kick in as they may check for the number of users of a given node and count the unused nodes as users as well.
I caught this issue when I was investigating why transpose(constant) is not optimized away at compile time after some backend-specific transformations. The reason was that the constant was used by the newly created transpose node and dead, but not yet removed node that initially used it.
*Testing*:
ninja test
=> Run a round of DCE before any other graph optimizations

include/glow/Graph/Graph.h, include/glow/Importer/CommonOperatorLoader.h, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Importer/ONNXIFIModelLoader.cpp, tests/models/caffe2Models/lengths_sum.pbtxt, tests/models/onnxModels/lengths_sum.onnxtxt, tests/unittests/OperatorTest.cpp, tests/unittests/caffe2ImporterTest.cpp, tests/unittests/onnxImporterTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/NodeGen.cpp
This commit adds support for the `LengthsSum` operator, which
performs a `BatchedReduceAdd` operation on groups of consecutive
zero-axis slices of the `data` input. The sizes of these groups
are defined by the `lengths` input. This operator has implementations in
both the CPU and interpreter backends, and can be imported from a Caffe2
and ONNX model.
**Testing**
This commit adds an interpreter and CPU operator test as well as Caffe2
and ONNX importer tests.
**Fixes**
This commit fixes #1884.
=> [Caffe2/ONNX] Add support for LengthsSum operator

lib/Base/Image.cpp, tests/unittests/CMakeLists.txt, tests/unittests/imageTest.cpp
*Description*
The 90 degree rotation was simply a swapping of the column and row indices
when accessing the tensor.
The black image output was a misuse of the range input. The range represents
the range of values the image should have, not the range of values the input
tensor has.
In other words, we were doing:
- read: tensor = image * scale + bias
- write: image = tensor * scale + bias
Whereas we should be doing:
- read: tensor = image * scale + bias
- write: image = (tensor - bias ) / scale
Fixing both these issues makes the image being written properly.
*Testing*
The added test loads an existing image into a tensor, then writes it
into an image and finally load that image back.
The tensor obtained from the final image loading is expected to be
the same (modulo scale and bias rounding) …
=> [Image] Fix writePngImage 90 degree rotation and black image output issues

lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/kernels.cl, lib/Graph/Nodes.cpp, lib/Quantization/Quantization.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/graphTest.cpp
*Description*:
As #1876 stated, now we support FC with int32 bias.
*Testing*:
unittests added. Can dump and profile resnet50.
#1727 
=> [Quantization] Support int32 quantized bias of FullyConnected.

docs/Lexicon.md
*Description*:
These terms can be confusing for those that do not have a background in
compilers.  Some of the collaboration terminology is derived from LLVM, and that
requires a specific background as well.
This PR covers docs.
=> [docs] add some collaboration and compiler terminology

docs/JIT.md, include/glow/Backends/CompiledFunction.h, lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/CPU/AllocationsInfo.h, lib/Backends/CPU/BundleSaver.cpp, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUFunction.cpp, lib/Backends/CPU/CPUFunction.h, lib/Backends/CPU/DebugInfo.cpp, lib/Backends/CPU/LLVMIRGen.cpp, lib/ExecutionEngine/ExecutionEngine.cpp
*Description*: Migrate CPU Backend to allocate and initialize memory at runtime. Added a new runtimeInfo object that contains information needed for runtime memory allocation. 
*Testing*: ninja test passes, AOT bundles still work, testing with run.sh --iterations=20 -cpu -time showed minimal performance difference.
Progress on #1904
=> Migrate CPU Backend to allocate memory at runtime.

lib/IR/CMakeLists.txt, lib/IR/ChildMemSizeBasedScheduler.cpp, lib/IR/GraphScheduler.cpp, lib/IR/GraphScheduler.h, lib/IR/TopologicalSortBasedScheduler.cpp, tests/unittests/graphSchedulerTest.cpp
*Description*: Add a simple topological sort graph scheduler
*Testing*:
There are many scheduling policies to mapping a computation graph to a certain backend. This PR adds a simple topological sort based graph scheduler and exposes a command line interface for users.
=> [GraphScheduler] Add a simple topological sort graph scheduler

lib/Onnxifi/Base.cpp
*Description*:
We allocate memory for the Tensor object but do not free it. Fix this.
Note, underlying tensor data is unowned by tensor so we should be fine to delete tensor.
From the internal tool:
```
==87496==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 80 byte(s) in 1 object(s) allocated from:
#0 libtools_build_sanitizers_asan-ubsan-py.so+0x29708 operator new(unsigned long)
#1 glow/glow/lib/Onnxifi/Base.cpp:106       glow::onnxifi::Graph::run(llvm::DenseMap<...> const&, llvm::DenseMap<...> const&)
```
*Testing*:
onnxifi_driver tests.
N/A
cc: @yinghai
=> [fix] Fix memory leak when allocate Tensor object.

lib/Backends/CPU/AllocationsInfo.cpp
*Description*:
If we don't have constant weights, previous behavior will still asking to allocate for a 0-sized memory, which fails the alignment check when used with jemalloc. This fixes it by not doing any processing if we don't have constant weights. 
*Testing*:
Unit tests. 
=> Fix memory allocation issue when we don't have constant weights

lib/Importer/ONNXIFIModelLoader.cpp
*Description*:
Allocate tensor on a stack and fix memory leak when parsing.
*Testing*:
Unit tests. The leak itself should be handled by ASAN on fbcode run.
N/A
cc: @yinghai
=> [memory leak] Fix memory leak when parsing onnx model

lib/Backends/CPU/libjit/libjit.cpp, tests/unittests/OperatorTest.cpp
*Description*:
Previous CPU backend implementation of Sigmoid does `e^x/(e^x + 1)` which is prone to overflow. This PR uses `1/(1 + e^{-x})`. 
*Testing*:
Added a unit test. Without this fix, it will fail. 
N/A
=> Fix overflow of Sigmoid in CPU Backend

lib/Backends/CPU/CPUFunction.cpp, lib/Backends/CPU/CPUFunction.h
*Description*:
In cases when we need not allocate memory we just bail.
```
grep -ir 'alignedAlloc' lib/
lib//Backends/CPU/AllocationsInfo.cpp:      (uint8_t *)alignedAlloc(constantWeightVarsMemSize_, TensorAlignment);
lib//Backends/CPU/CPUFunction.cpp:    baseActivationsAddress_ = (uint8_t *)alignedAlloc(
lib//Backends/CPU/CPUFunction.cpp:    baseMutableWeightVarsAddress_ = (uint8_t *)alignedAlloc(
```
This should be enough to get going.
*Testing*:
Unit tests + fbcode internal tests.
n/a
cc: @yinghai
=> [fix] Do not allocate memory when size is 0 for CPU backend.

include/glow/Base/Tensor.h, lib/Base/Tensor.cpp
*Description*:
Replace several instances of `Tensor *` with `const Tensor *` in Tensor.h and Tensor.cpp where taking non-const Tensor * was unnecessary.
*Testing*:
compile and run `ninja check`, all tests passed
Fixes #1968
=> [Tensor] Make dumpImpl(Tensor*) take a const ptr

include/glow/Backends/BackendUtils.h, lib/Backends/BackendUtils.cpp, lib/Backends/CMakeLists.txt, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/ExecutionEngine/ExecutionEngine.cpp
*Description*: Move OpenCL memory allocation to runtime. This is in support of #1904. 
*Testing*: Ran ninja test all pass. run.sh --iterations=10 -opencl -time. Accuracy is the same as master now. Time is almost identical for all except resnet 50. 
Master:
Wall time per iteration (s): 0.1335
---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
1.1925 (100.0%)   0.1420 (100.0%)   1.3345 (100.0%)   1.3350 (100.0%)  Infer
1.1925 (100.0%)   0.1420 (100.0%)   1.3345 (100.0%)   1.3350 (100.0%)  Total
Wall time per iteration (s): 0.4013
Current Branch:
Wall time per iteration (s): 0.1628
---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
0.8187 (100.0%)   0.1483 (100.0%)   0.9670 (100.0%)   1.6282 (100.0%)  Infer
0.8187 (100.0%) …
=> Moved OpenCL memory allocation to runtime.

lib/Graph/Graph.cpp, tests/unittests/quantizationTest.cpp
*Description*: We use `llvm::sys::fs::createTemporaryFile` but don't always clean up afterwards.  Fix it!
*Testing*: `ninja check`
Fixes #1982
=> [easy] Clean up temporary files

lib/Quantization/Quantization.cpp
*Description*: Really minor thing, I just like having function-local stuff in anonymous namespaces so it's obviously not used elsewhere.  If anyone dislikes this I'll just drop the PR :)
*Testing*: compile
=> [quantization][trivial] Put FunctionQuantizer in anonymous namespace

lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Nodes.cpp, lib/Quantization/Quantization.cpp, tests/unittests/OperatorTest.cpp
*Description*: Conservative interpreter support.  Dequantize the inputs to float, accumulate as floats (hence the `std::vector<float>` to hold the line-sized accumulator), then quantize the output.
*Testing*: New tests.  I was lazy and duplicated the existing FP tests :-/.
=> [interpreter] Implement i8 quantized SparseLengthsWeightedSum

lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Nodes.cpp, lib/Importer/ONNXIFIModelLoader.cpp, tests/models/onnxModels/lengths_to_ranges.onnxtxt, tests/models/onnxModels/sparseLengthsSum.onnxtxt, tests/unittests/OperatorTest.cpp, tests/unittests/onnxImporterTest.cpp, tools/ClassGen/InstrGen.cpp
*Description*:
`Lengths` for sparse matrix related operators should be `int32` instead of `int64`. We introduced `Int32ITy` a while ago but didn't really use it. This PR fixes that. Affected ops includes `SparseLengths(Weighted)Sum`, `LengthsSum` and `LengthsToRanges`. 
Also fixes Interpreter and CPU backend. 
*Testing*:
unittest. 
=> Use Int32ITy for Lengths input of Sparse matrix operators

include/glow/Graph/Node.h, include/glow/Graph/Nodes.h, include/glow/Graph/VerifierHelper.h, include/glow/Support/Support.h, lib/Graph/CMakeLists.txt, lib/Graph/Graph.cpp, lib/Graph/Node.cpp, lib/Graph/Nodes.cpp, lib/Graph/VerifierHelper.cpp, lib/Support/Support.cpp, tests/unittests/graphTest.cpp, tools/ClassGen/Backends/CPU/CPUSpecificNodesVerification.h, tools/ClassGen/Backends/OpenCL/OpenCLSpecificNodesVerification.h, tools/ClassGen/NodeBuilder.cpp
*Description*
The verifier is a valuable tool to validate if an input graph is valid.
Right now, a lot of checks are *not* done in the loader because it knows
the verifier will catch them. However, the verifier does nothing
in release mode and thus we cannot rely on it in that mode.
To be able to use the verifier in release mode, we need to refactor it
so that it does not rely on asserts anymore.
This patch goes in that direction by doing the switch for the classes
related to Node.
Moreover, since the use case from the verifier switches from purely
debugging to error reporting, this patch improves the way error are
reported. In particular, it prints details on the node that fails so
that a potential user doesn't have to debug the compiler to see what
is wrong with the input graph.
E.g., …
=> [Verifier] Switch the node verifier from assert to returning bool for the nodes

include/glow/Backends/CompiledFunction.h, lib/Backends/Interpreter/CMakeLists.txt, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/Interpreter/InterpreterFunction.h
[runtime] Moved context use to runtime for Interpreter Backend
*Description*: Migrated use of passed in context from compile to execute for Interpreter. This is work on #1904.
*Testing*: Ninja test all pass. run.sh --iterations=10 -interpreter -time looks good with no significant time difference.
Progress on #1904
=> [runtime] Moved context use to runtime for Interpreter Backend

tests/images/run.sh, tools/loader/ImageClassifier.cpp
*Description*: Allow softmax to have at least 2 dimensions: batchSize, numLabels, and then trailing 1s. I moved this to use `getUnowned()` instead of `extractSlice()`, as the latter creates a copy of the slice which we do not need. 
I also added `-compute-softmax` to densenet121 in run.sh, and cleaned up one other place we had leftover naming from the Variable -> Placeholder migration.
*Testing*: `run.sh`
Fixes issue as mentioned in https://github.com/pytorch/glow/pull/1937
=>  [ImageClassifier] Fix slicing of different dim sizes of softmax

lib/Graph/Nodes.cpp, lib/Quantization/Quantization.cpp, tests/unittests/quantizationTest.cpp
*Description*
Some nodes, at least in their interpreter implementation, expect that
their inputs and outputs are scaled with the exact same parameters.
These constraints were not enforced in the function quantizer for
the slice, transpose, and reshape nodes leading to a mismatch between
how the consumers of a value expect it to be quantized and how it
was actually quantized.
This patch teaches the function quantizer how to fix those constraints
for these additional nodes (the mechanism already existed) and adds
checks in the verifier to catch this kind of problem earlier.
*Testing*
Added test cases, but only for two nodes. Given they all use the same
code path I didn't bother adding them all.
Related to issue #1989.
=> [FunctionQuantizer] Fix rescaling happening in the middle of nodes

lib/Importer/ONNXModelLoader.cpp, tests/models/onnxModels/constant.onnxtxt, tests/unittests/onnxImporterTest.cpp
*Description*:
We need to support load of int32 tensor too because Caffe2 concat will output such tensors. In addition, at output, we need to consider outputing that tensor instead of the node. 
*Testing*:
Unit test
=> [ONNX] Support load of int32 Tensor

lib/Backends/BackendUtils.cpp, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/OpenCL/OpenCL.cpp
*Description*:Updated BackendUtils to not call alignedAlloc on size 0.
Fixed OpenCL backend to not copy size 0 constants to card.
*Testing*: ninja test and run.sh look good.
=> [BackendUtils] Fix BackendUtils allocation

tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/CMakeLists.txt, tests/unittests/OCLTest.cpp, tests/unittests/convTest.cpp
*Description*:
I played with our implementation of convolutions in an attempt to figure out how to implement matrix multiplication using a convolution using @bertmaher 's method. During the investigation I discovered that when I break our convolutions the unit tests still pass. This PR improves the test coverage using two methods: 
[Test] Add a new unit test to verify float convolutions. -- On my machine the test passes in 4.1 seconds in debug mode.
[Test] Improve a few unit tests. - -This commit fixes a few places in our test that made the CPU backend test only the slow fallback code.
*Testing*: This is a test.
*Documentation*: Inline.
=> [Unittest] Improve the testing of convolutions. 

include/glow/Base/Image.h, lib/Base/Image.cpp, tools/loader/ImageClassifier.cpp
*Description*: I'd like to use correctly-processed PNGs in a standalone utility, so I thought factoring this functionality out of the ImageClassifier executable would make sense.
*Testing*: ./tests/image/run.sh
Part of #1976
=> [image] Factor out PNG processing

.circleci/build.sh, CMakeLists.txt, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTest.cpp, tests/unittests/CMakeLists.txt, tests/unittests/MLTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/convTest.cpp
*Description*:
Add an option to compile with OpenCL support but do not run tests.
This is a first step to enable catching issues with OpenCL.
No major changes in build CI time for/after this PR.
See https://github.com/pytorch/glow/issues/1181 for details.
*Testing*:
CI
N/A
Follow up needs to enable tests with all the below fixed.
Failing tests:
```
[  FAILED  ] 11 tests, listed below:
[  FAILED  ] OpenCL/Operator.matMul/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.Transpose3Dims/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.ScatterAssign/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] OpenCL/Operator.TestQuantizedRescaleSequence/0, where GetParam() = 4-byte object <01-00 00-00>
[  FAILED  ] …
```
=> [opencl ci] Compile Glow with OpenCL and run some unit tests on CI.

include/glow/Graph/VerifierHelper.h, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Nodes.cpp, lib/Graph/VerifierHelper.cpp, lib/Importer/ONNXIFIModelLoader.cpp, tests/models/onnxModels/gather.onnxtxt, tests/unittests/OperatorTest.cpp, tests/unittests/onnxImporterTest.cpp, tools/ClassGen/InstrGen.cpp
*Description*:
The indices input of `Gather` can be either `int32_t` or `int64_t`,  we need to support both. This PR does this and adds support for Interpreter and CPU backend. 
*Testing*:
Unit test
=> Support int32 index for Gather

docs/Testing.md, utils/imagenet_topk_accuracy_driver.py
*Description*: This script is used as a driver to calculate Top-1 and Top-5 accuracy across Imagenet. It will resize+center-crop images prior to inference. This resize+center-crop can also be done to pre-process the images without performing inference, so that the images can be used many times repeatedly without having to resize+center-crop them over and over again.
On Resnet50, here is what I found (showing results with and without specialized imagenet normalization https://github.com/pytorch/glow/pull/2007):
- Float: 
- Interpreter/CPU Backend (same results):
- Standard normalization:
- Top-1 accuracy: 0.6846
- Top-5 accuracy: 0.8863
- Specialized Imagenet normalization:
- Top-1 accuracy: 0.7613
- Top-5 accuracy: 0.9293
- Quantized:
- Interpreter:
- Standard normalization:
- Top-1 …
=> [utils] Add driver for determining imagenet topk accuracy

tests/unittests/BackendTest.cpp, tests/unittests/caffe2ImporterTest.cpp, tests/unittests/graphOptzTest.cpp, tests/unittests/onnxImporterTest.cpp
*Description*: These are bad practice and should only be used when really necessary.
=> [cleanup | NFC] Remove many unnecessary uses of getNthInput()

include/glow/Graph/Graph.h, include/glow/Graph/VerifierHelper.h, lib/Converter/FunctionConverter.cpp, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Graph.cpp, lib/Graph/VerifierHelper.cpp, lib/IR/IRGen.cpp, tests/unittests/graphGradTest.cpp, tests/unittests/graphTest.cpp, tests/unittests/typeAToTypeBFunctionConverterTest.cpp
*Description*
This patch extends the work already done for the nodes to the function
and module. Essentially, this moves the verify method of the related
classes from assert based to returning a bool.
Thus, the caller can decided whether this should only be run in assert
mode or anytime, e.g., for error checking.
On top of that, this commit provides more context when things break
using the same framework (VerifierHelper) that we introduced for the
nodes.
*Testing*
Updated test cases
Related to #1517.
=> [Verifier] Switch the node verifier from assert to returning bool for the function and module

include/glow/Base/Image.h, lib/Base/Image.cpp, tools/loader/ImageClassifier.cpp
*Description*: Pull command line options for controlling image processing into Image.{h,cpp} so they can be easily reused by other utilities.
*Testing*: `ninja image-classifier && ./tests/image/run.sh`
=> [nfc] Move image processing cli args to Image.{h,cpp}

docs/CodingStandards.md
*Description*:
I've noticed myself making repetitive, kind of trivial mistakes on PRs, so I wrote up a checklist of things that I've forgotten more than once.  Since these are often issues for others as well, I thought it'd be helpful to put in our coding standards.
These are probably documented elsewhere, e.g., the LLVM coding standards, but having a succinct list should make it easier to sanity check.  (Of course, almost all of these could be checked by a linter, but I don't know how to get that done quickly.)
*Testing*: n/a
=> [docs] Add a nits checklist to CodingStandards

include/glow/Base/Image.h, lib/Base/Image.cpp
*Description*: Two things here:
- Default `-image_mode` to `0to255`, since that implies no rescaling
- Make it so the flag values are `extern` rather than the `cl::opt`s themselves, so we don't have to include `CommandLine.h` everywhere.
*Testing*: `run.sh`
=> [image] Improve preprocessing command line options

lib/Onnxifi/onnxifiGlow.cpp
*Description*:
Check the capacity provided by `numBackends` in `onnxGetBackendIDs()` before writing to `backendIDs` to check that there is enough space available.
*Testing*:
`ninja all && ninja test`
no changes
=> [onnxifi] Check capacity in onnxGetBackendIDs before writing backendIDs

README.md
*Description*: This commit adds instructions for using OpenCL with Glow on Ubuntu.
*Testing*: The instructions added were successfully tested on my Ubuntu 16.04.1 laptop with an i7-7600U (with Intel HD Graphics 620 onboard graphics).
=> README Updates for OpenCL on Ubuntu

include/glow/Backends/BackendUtils.h, include/glow/Backends/CompiledFunction.h, lib/Backends/BackendUtils.cpp, lib/Backends/CPU/AllocationsInfo.h, lib/Backends/CPU/CPUFunction.cpp, lib/Backends/CPU/CPUFunction.h, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h
*Description*: Converted RuntimeBundle to a class and added helper methods for getting symbolInfo. Moved RuntimeBundle to BackendUtils. Updated Backends to use new helper methods.
*Testing*: ninja test and ruh.sh both pass
Fixes #1967
=> [BackendUtils]Convert RuntimeBundle to a class

lib/Backends/OpenCL/OpenCL.cpp
*Description*: This commit allows for building with -Werror without incurring failures due to the usage of the deprecated clCreateCommandQueue() function in the OpenCL backend.  This commit should allow #2064  to succeed.
*Testing*: Tested build with -Werror and -DGLOW_WITH_OPENCL=ON on Ubuntu 16.04.1 laptop (with OCL runtime installed).
=> Prevent errors from use of deprecated OpenCL 1.2 function

CMakeLists.txt, include/glow/Base/Image.h, lib/Base/CMakeLists.txt, lib/Base/Image.cpp, tests/unittests/CMakeLists.txt
*Description*: I suspect no one ever builds glow without libpng because it's been broken for a while :-).
*Testing*: Actually pretty hard; I removed find_package(PNG) and got things to compile, but that's still not a guarantee that everything works because libpng is still in my system path, even if I haven't told CMake to go find it.  Anyways, at least it doesn't choke as quickly.
=> [image] Fix build when libpng not found

README.md
I know the "glow" phrase is already a direct link, but I think putting the full topic path front and center will help direct people to the right place.
=> [docs] Direct link to glow topic on forums

include/glow/Backends/BackendUtils.h, include/glow/Graph/Node.h, lib/Backends/BackendUtils.cpp, lib/Backends/CPU/AllocationsInfo.cpp, lib/Backends/CPU/AllocationsInfo.h, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/Graph/Graph.cpp, lib/Graph/Node.cpp, lib/Graph/Nodes.cpp, lib/IR/IRBuilder.cpp, lib/Optimizer/IROptimizer.cpp, lib/Optimizer/Lower.cpp
*Description*: This change is pretty trivial, but I think enforcing the rule consistently makes the code base feel cleaner and less haphazard.
*Testing*: n/a
=> Add vertical whitespace between top-level definitions

docs/AOT.md, docs/ModelLoader.md, docs/Quantization.md, docs/Testing.md, examples/bundles/lenet_mnist/CMakeLists.txt, examples/bundles/lenet_mnist/Makefile, examples/bundles/resnet50/CMakeLists.txt, examples/fr2en.cpp, include/glow/Base/Image.h, lib/Base/Image.cpp, tests/images/run.sh, tools/loader/ImageClassifier.cpp, tools/loader/Loader.cpp, tools/loader/TextTranslator.cpp, utils/imagenet_topk_accuracy_driver.py
*Description*: Search and replace command line options in camelCaseStyle or underscore_style to use hyphen-style. Changed model-loader, image-classifier, text-translator and fr2en example.
*Testing*: Ran run.sh, and manually followed instructions in AOT.md to dump a profile, load a profile and emit a bundle. 
grepped docs for each changed option and updated them.
fixes #1965.
=> [image-classifier] Commonalize command line arguments to hyphen-style

lib/Graph/Nodes.cpp, lib/Quantization/Quantization.cpp, tests/unittests/quantizationTest.cpp
*Description*:
In our previous quantization procedure, we forced the quantized avgpool node output have the same quantization param as the input, which is not necessary. This PR removes this restriction.
*Testing*:
1. added unittest.
2. run 
```
>$./bin/image-classifier tests/images/imagenet/*.png -image_mode=0to1 -m=resnet50 -model_input_name=gpu_0/data -dump_profile="profile.yaml"
Model: resnet50_profile
File: tests/images/imagenet/cat_285.png	Label-K1: 285 (probability: 0.5823)
File: tests/images/imagenet/dog_207.png	Label-K1: 207 (probability: 0.9616)
File: tests/images/imagenet/zebra_340.png	Label-K1: 340 (probability: 0.9902)
>$ ./bin/image-classifier tests/images/imagenet/*.png -image_mode=0to1 -m=resnet50 -model_input_name=gpu_0/data -load_profile="profile.yaml"
Model: resnet50 …
```
=> [Quantization] Allow the input and output of a quantized AvgPool node have different quantization param.

lib/Backends/CPU/libjit/libjit_matmul.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, tests/unittests/OperatorTest.cpp
*Description*:
Now we support int32 quantized bias for Conv and FC. Therefore, for RowwiseQuantizedFullyConnected, we would like to support int32 quantized bias as well.
*Testing*: 
ninja check
=> [Quantization] Improve RowwiseQuantizedFullyConnected node to support int32 quantized bias.

lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/empty_predict_net.pbtxt, tests/models/caffe2Models/fill_test_init_net.pbtxt, tests/unittests/caffe2ImporterTest.cpp
*Description*: GivenTensorIntFill was using `int64_t`, but should be using `int32_t`.
*Testing*: Added a test for all the different supported TensorFills.
=> [Caffe2ModelLoader] Load GivenTensorIntFill using int32_t

examples/CMakeLists.txt, examples/lenet-loader.cpp, include/glow/Importer/Caffe2ModelLoader.h, include/glow/Importer/CommonOperatorLoader.h, include/glow/Importer/ONNXIFIModelLoader.h, include/glow/Importer/ONNXModelLoader.h, include/glow/Importer/ProtobufLoader.h, include/glow/Support/Error.h, lib/Importer/Caffe2ModelLoader.cpp, lib/Importer/ONNXIFIModelLoader.cpp, lib/Importer/ONNXModelLoader.cpp, lib/Importer/ProtobufLoader.cpp, lib/Onnxifi/Base.cpp, lib/Support/CMakeLists.txt, lib/Support/Error.cpp, tests/unittests/caffe2ImporterTest.cpp, tests/unittests/onnxImporterTest.cpp, tools/loader/ImageClassifier.cpp, tools/loader/ModelRunner.cpp, tools/loader/TextTranslator.cpp
**Description**:
07e0f13 implements error handling for the model importer portion of the compiler using llvm::Error/Expect. Instead of `assert`ing, fallible code must return either a valid result or an Error containing a string message explaining the problem and this Error can be propagated up the call stack to the compiler interface where it can be dealt with properly and reported back to the user. There are some helper macros to improve the ergonomics of creating and handling errors implemented in `Support/Error.h` and `Support/Error.cpp`.
**Testing**:
`ninja check`
ran C2 onnx integration tests with `pytest -s caffe2/python/onnx/test_onnxifi.py`, 3/3 tests passed
**Documentation**:
Doxygen comments
=> [Error Handling] Add Error handling to model importer related code

tools/ClassGen/CMakeLists.txt, tools/ClassGen/MemberType.cpp, tools/ClassGen/MemberType.h, tools/ClassGen/NodeBuilder.cpp, tools/ClassGen/NodeBuilder.h
This commit adds support for enum members on nodes. An enum type
can be defined within `NodeGen` itself, or defined externally.
In the latter case, it must be declared in `NodeGen` so
that it can be forward declared correctly when defining `Nodes` that
have members of that type.
The API looks something like this:
```
auto e = BB.newEnum("glow::greatBackend::tremendousEnum");
e.addValue("FIRST").addValue("SECOND");
BB.newNode(...).addMember(e, "EnumMember");
```
**Testing**
Tried out new features with a new autogenerated node class with four
different enum members, two of one type and two of another. The two enum
types were declared in different namespaces:
```
auto &e = BB.newEnum("newbackend::namespace1::enum1");
e.addEnumCase("FIRST", "first comment"); …
```
=> [NodeGen] Support enum members on nodes

tests/unittests/tensorsTest.cpp
*Description*: Visual studio was reporting error with type narrowing because Q8H that was instantiated as int8_t and initialized with offsetQ8 which is int32_t.
*Testing*: Usual
=> [Fix] Small fix for VS regarding type conversion.

CMakeLists.txt, lib/Graph/CMakeLists.txt, lib/IR/CMakeLists.txt, tests/unittests/CMakeLists.txt
*Description*: I've been wanting to build with shared libraries for a while, if for no other reason than tests will link faster.  I think I've leveled up my cmake skills enough to actually do it.
*Testing*:
```
mkdir build && cd build
cmake -G Ninja ../.. -DCMAKE_PREFIX_PATH=/usr/local/opt/llvm -DBUILD_SHARED_LIBS=ON
ninja all
```
Based on #2109.  Github needs stacked diffs.
=>  [cmake] Fix Graph/IR deps so Glow can build with shared libs

lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Nodes.cpp, tests/unittests/OperatorTest.cpp, tools/ClassGen/InstrGen.cpp
This commit modifies the `BatchOneHot` operator to use 32-bit integer
values in the `lengths` input rather than 64-bit integers. This change
was supposed to be part of an earlier commit that migrated the index
inputs of all sparse operators to 32-bit integer, but it was overlooked
at the time.
**Testing**
This commit modifies the operator test for `BatchOneHot` to use 32-bit
integers. The modified test passes, as do all other unit tests.
**Fixes**
This pull request fixes #2033.
=> [Nodes] Make lengths input of `BatchOneHot` int32

lib/Backends/CPU/CMakeLists.txt
*Description*: Due to the usage for NaN in the runtime, `-fno-finite-math-only` is needed to disable `-ffinite-math-only` activated by `-ffast-math`, while benefiting from math optimizations.
*Testing*: after this fix, test `CPU/InterpAndCPU.replaceNaN/0` doesn't fail anymore in our environment.
Fixes #2073
=> [bugfix] Fix the NaN related test failure

examples/CMakeLists.txt, examples/resnet-verify.cpp, include/glow/Graph/Hook.h, lib/Graph/CMakeLists.txt, lib/Graph/Hook.cpp, tests/unittests/graphTest.cpp
*Description*:
In bringing up backends, I found it useful to be able to truncate a network at some arbitrary intermediate layer and compare the output against the interpreter.  This is (more or less) the utility I wrote to do it, plus an example of going layer-by-layer through ResNet-50 (which is very slow, but that's OK).
If you're reviewing, the first commit is the hooking logic itself; the second is the example.
I'd like some feedback on whether people think this is generally useful.  If so, happy to do some cleanup and write docs.
*Testing*: `bin/resnet-verify`
*Documentation*: not yet
Fixes #1976
=> [graph] Utilities for hooking intermediate net layers

.circleci/build.sh, .circleci/config.yml, .circleci/test.sh
*Description*: Since we've gone to the trouble of making shared libraries work let's make sure it stays that way.
A couple alternatives:
- Switch CI to shared (but most people are using static, so this seems bad)
- Switch our default to shared in root CMakeLists.  This could be OK.
I liked just adding test coverage so we can be sure all configs work, but I'm open to discussion.
*Testing*: new CI config
=> [ci] Test with shared libraries

include/glow/Importer/Caffe2ModelLoader.h, include/glow/Importer/ONNXIFIModelLoader.h, include/glow/Importer/ONNXModelLoader.h, include/glow/Importer/ProtobufLoader.h, lib/Importer/Caffe2ModelLoader.cpp, lib/Importer/ONNXIFIModelLoader.cpp, lib/Importer/ONNXModelLoader.cpp, lib/Importer/ProtobufLoader.cpp, lib/Onnxifi/onnxifiGlow.cpp
*Description*:
This diff removes the last asserts and unhandled errors from the model loading layer. These are the asserts and errors that were in the model loader constructors which makes them uniquely unergonomic to deal with. The general pattern employed here for handling errors that may occur during construction is to have each constructor take an extra parameter that is a pointer to an error and if any errors are raised and if that pointer is not null then assign the error to the error pointer and return early otherwise if an error occurs but the pointer to the error parameter is null then abort. These error pointers get passed down the inheritance chain to each constructor.
This diff also handles any error that may have occurred during model loading in …
=> [Error handling] Remove last asserts from loaders

include/glow/Backends/CompiledFunction.h, lib/Backends/CPU/CPUFunction.cpp, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/ExecutionEngine/ExecutionEngine.cpp
*Description*: Removed memleak from OpenCL backend and added logic to executionEngine to only call setupRuns and tearDownRuns once.
*Testing*: ninja test all pass
Partially fixes #2104
=> Fix OpenCL memleak and update ExecutionEngine

include/glow/Graph/Graph.h, include/glow/Quantization/Quantization.h, lib/Graph/Graph.cpp, lib/Quantization/Quantization.cpp, tests/unittests/quantizationTest.cpp, tools/loader/Loader.cpp
*Description*:
This PR adds a option to enable RowwiseQuantizedFullyConnected in Glow's quantization procedure:
When a FC node needs to be quantized, if both of the conditions are satisfied, we replace the quantized FC node by RowwiseQuantizedFullyConnected:
1. The weights of this FC is constant.
2. -enable-rowwise is set or set enableRowwise param in                                                                                                        
quantization::quantizeFunction to true. In unittest, the later one is used.
*Testing*:
Added unittest.
Also manually checked -enable-rowwise opt.
=> [Quantization] Enable RowwiseQuantizedFullyConnected under the option -enable-rowwise

include/glow/Graph/Graph.h, include/glow/Graph/Nodes.h, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Importer/ONNXModelLoader.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Optimizer/Lower.cpp, tests/models/onnxModels/padConstant.onnxtxt, tests/models/onnxModels/padConstantPositive.onnxtxt, tests/models/onnxModels/padDefault.onnxtxt, tests/models/onnxModels/padEdge.onnxtxt, tests/models/onnxModels/padReflect.onnxtxt, tests/unittests/graphOptzTest.cpp, tests/unittests/onnxImporterTest.cpp, tools/ClassGen/MemberType.cpp, tools/ClassGen/MemberType.h, tools/ClassGen/NodeBuilder.cpp, tools/ClassGen/NodeGen.cpp
This PR adds a partial support for the Pad operator: 1/ a Pad node, 2/ Support of Pad in the ONNX importer, 3/ Some Pad related optimizations. 
ONNX spec: https://github.com/onnx/onnx/blob/master/docs/Operators.md#Pad
This PR is related to a use-case we got where a set of Pad nodes could **all** be merged into Convolution nodes. Due to the fact that Convolution introduces transpose nodes (conv doesn't follow the ONNX/Caffe2 convention and is NHWC), we had to add an extra transpose/pad sink optim. In our use case, all Pad nodes disappear at optimization, so we decided not to spend (much) more effort supporting Pad at the instruction level and in the various backends. This will need to be implemented at a time a real-use case appears with this need or when a 100% coverage of …
=> [ONNX] Add a partial support for the Pad operator

tests/unittests/graphOptzTest.cpp
I'm going to keep fighting this battle until someone introduces something that's too hard for me to work around.  Please don't take that as a challenge! :-D.  Seriously I can't believe template argument deduction fails on this.
=> [tests] Make pad fusion test work with g++ 4.8.5

include/glow/Importer/CommonOperatorLoader.h, lib/Importer/ONNXModelLoader.cpp, tests/models/onnxModels/addUniBroadcastOp6Axis.onnxtxt, tests/models/onnxModels/addUniBroadcastOp6NoAxis.onnxtxt, tests/models/onnxModels/divUniBroadcastOp6Axis.onnxtxt, tests/models/onnxModels/divUniBroadcastOp6NoAxis.onnxtxt, tests/models/onnxModels/mulUniBroadcastOp6Axis.onnxtxt, tests/models/onnxModels/mulUniBroadcastOp6NoAxis.onnxtxt, tests/models/onnxModels/subUniBroadcastOp6Axis.onnxtxt, tests/models/onnxModels/subUniBroadcastOp6NoAxis.onnxtxt, tests/unittests/onnxImporterTest.cpp
*Description*:
My previous PR about broadcasting added the support for multidirectional broadcasting (ONNX opset 7+). But by doing extra tests, i noticed that it broke the unidirectional broadcasting in some cases for ONNX opset <7. This PR fixes this and enables a fully functional broadcasting for any ONNX opset. 
I also take advantage of this fix to add tests for ONNX unidirectional broadcasting.
Some information:
- ONNX unidirectional broadcasting: https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Mul-6
- Caffe2 unidirectional broadcasting : https://caffe2.ai/docs/operators-catalogue.html#mul
- ONNX multidirectional broadcasting: https://github.com/onnx/onnx/blob/master/docs/Broadcasting.md
*Testing*: 
Added tests for ONNX arithmetic operation with unidirectional broadcasting …
=> [hotfix] Fix unidirectional broadcasting for arithmetic ops (ONNX opset <= 6)

include/glow/Importer/CommonOperatorLoader.h, tests/models/onnxModels/UniBroadcastIssue2135.onnxtxt, tests/unittests/onnxImporterTest.cpp
Hopefully, this is the last iteration for broadcasting :)
There were an issue when handling the unidirectional broadcasting (Caffe2 and ONNX opset <7) with an `in0` operand that has multiple outputs (TopK in the particular failing case).
The problem is due to  `NodeValue `-> `Node *` -> `NodeValue` conversion chain that fails in the last stage because `Node *` -> `NodeValue` can't be implicitly done when the node has multiple outputs.
This fix just removes the useless initial `NodeValue` -> `Node * ` conversion.
*Testing*: 
The problem has been detected with Caffe2, but I reproduced the issue with ONNX that I'm more familiar with (Caffe2 and ONNX opset <6 almost behave the same way for broadcasting). I added reproducer test `importUniBroadcastMultiOutput`. …
=> [fix] Fix uni-directional broadcasting 

tests/unittests/graphOptzTest.cpp
*Description*:
I was working on some creating some Constant related tests and finally noticed that these tests were already developed, but with the PrivateVar naming. This PR rename the existing tests with Constant.
*Testing*: N/A
=> [tests] Simply replace PrivateVar by Constant in test names

tests/unittests/BackendCorrectnessTest.cpp
*Description*:
This is failing in one of the testing environments. I'm relaxing the threshold here, not sure if we could have some principled way to detect and fix this in general.
This PR is just to make CI green for that env.
*Testing*:
CI
n/a
=> [test] Relax check against error a bit for unit test to pass.

lib/Onnxifi/CMakeLists.txt
*Description*: I don't understand why CI didn't catch this.
*Testing*: cmake -DBUILD_SHARED_LIBS=ON ...
=> [cmake] Shared library dep for onnxifi-glow-lib

include/glow/Support/ThreadPool.h, lib/Onnxifi/Base.h, lib/Onnxifi/CMakeLists.txt, lib/Support/CMakeLists.txt, lib/Support/ThreadPool.cpp, tests/unittests/CMakeLists.txt, tests/unittests/ThreadPoolTest.cpp
*Description*: Per @jackm321's suggestion, we should reuse the Onnixifi ThreadPool in the runtime, so moving it into the common area.
I also split out the shutdown stage into a separate function to allow more flexible control of shutting down the pool.
=> [support] Move the Onnixifi thread pool into Support/ so it's easier to reuse.

README.md, docs/LIT.md
*Description*
With PR #2097, glow gained the ability to run LLVM LIT style tests.
This patch documents what are the prerequist to be able to run these
and gives an overview of the difference pieces involved in the LIT
environment for glow.
*Testing*
N/A
*Description*:
*Testing*:
=> [docs] Document our usage of LIT in glow. NFC

lib/Onnxifi/CMakeLists.txt
*Description*: Defining ONNXIFI_BUILD_LIBRARY so that ONNXIFI_PUBLIC is defined as dllexport in onnxifi.h. 
*Testing*: Unit tests win/linux.
*Documentation*: https://msdn.microsoft.com/hu-hu/library/a90k134d.aspx
=> [Fix] Fix for windows build with VS. Setting ONNXIFI_PUBLIC to dllexport.

include/glow/Support/ThreadPool.h, lib/Support/ThreadPool.cpp, tests/unittests/ThreadPoolTest.cpp
*Description*: The ThreadPool is storing tasks as std::functions which prevents using move only types in the lambda capture. std::packaged_task is a better abstraction for one time run lambdas and does not have this limitation. We'll have to monitor performance of the thread pool as we scale up.
*Testing*: ninja test, but especially two new ThreadPool tests - one which verifies move-only captures, and another which demonstrates we can use the packaged_tasks's included future to tell when the task has executed.
=> [Support] switch from std::function to std::packaged_task in ThreadPool

CMakeLists.txt
*Description*: I'm building Glow on Ubuntu 16.04 where the default cmake package is 3.5, and it seems to work happily.  Does anyone know if there's a reason against relaxing this?  @compnerd?
*Testing*: cmake && ninja
=> [cmake] Require only version 3.5

utils/docker/Dockerfile, utils/docker/build.sh
Docker is very useful tool to setup dev or CI environment
Does glow have any plan to provide the dockerfile like [TVM] (https://github.com/dmlc/tvm/tree/master/docker)?
*Testing*: passed testsuites without OpenCL backend. 
=> [DOCKER] add Dockerfile for cpu env

CMakeLists.txt
*Description*: We don't support installing glow system-wide yet, but I tried `ninja install` anyways, and got a bunch of gmock/gtest targets installed.  I think we should exclude them so as not to inadvertently pollute the user's system.
*Testing*: `ninja install` properly does nothing
=> [cmake] Don't install googletest

lib/Onnxifi/CMakeLists.txt
*Description*: Onnxifi/Base.cpp uses glow::lower which needs `Optimizer` as a dependency. I'm not sure why this worked in the CI system.
*Testing*: ninja all in release.
=> Fix Onnxifi lib build dependencies

lib/IR/IR.cpp, lib/IR/Instrs.cpp, tests/unittests/BasicIRTest.cpp
*Description*: It seems that previously there was no verification to make sure Instructions are correctly using memory instructions. This adds more verification for these.
*Testing*: Added a couple tests.
=> [Instructions] Add memory-related verification for operands

include/glow/IR/IRBuilder.h, lib/IR/IR.cpp, lib/IR/IRBuilder.cpp, lib/IR/IRGen.cpp, tests/unittests/BasicIRTest.cpp, tools/ClassGen/InstrBuilder.cpp
*Description*: We were using `setName()` in many places on Instructions without checking that the name was unique. This PR removes all problematic calls I found, in AutGenIRGen and in the IRBuilder. I added a verify check to make sure all Instrs and WeightVars have unique names.
Fixes https://github.com/pytorch/glow/issues/2179
=> Ensure/verify that Instructions and WeightVars have unique names

lib/Backends/CPU/CMakeLists.txt
*Description*: Modifying CPU backend cmake file to use clang to build libjit files within VS.
*Testing*: UnitTests linux/windows
*Documentation*: https://cmake.org/cmake/help/v3.2/command/add_custom_target.html
I would like to revisit this. This approach is similar to another PR, #1849, that was close due to inactivity, but a more generic approach. It doesn't hardcode files, and plays around with add_custom_target, and add_custom_command to address some of the issues in another PR.
Behavior I see:
Visual Studio
After touch/modification of libjit:
1>Generating CPURuntime/libjit_obj_file_1.o
1>Generating ../../../libjit.bc
1>Generating ../../../glow/libjit_bc.inc
========== Build: 1 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
Doing Build again:
1>------ …
=> [Improvement] Building libjit in VS using clang

lib/Onnxifi/Base.cpp
*Description*:
I tried some tests and upstream code no longer sends weights as inputs. 
*Testing*:
Unit tests. 
=> [ONNXIFI] Remove Fixed TODO

include/glow/Importer/CommonOperatorLoader.h, include/glow/Importer/ONNXIFIModelLoader.h, include/glow/Importer/ONNXModelLoader.h, include/glow/Importer/ProtobufLoader.h, lib/Importer/ONNXIFIModelLoader.cpp, lib/Importer/ONNXModelLoader.cpp, lib/Onnxifi/Base.h, lib/Onnxifi/onnxifiGlow.cpp, tests/unittests/GlowOnnxifiManagerTest.cpp
*Description*:
This PR refactors the ONNXIFIModelLoader to let it not inherit ONNXModelLoader. Instead, it uses it. This can separate the dependency of ONNXIFI on ONNX and allows us to load other models through ONNXIFI interface. 
*Testing*:
Unit tests
=> Refactor ONNXFIModelLoader

lib/CMakeLists.txt, lib/Graph/CMakeLists.txt, lib/IR/CMakeLists.txt
If target does not link with Graph/IR.
It may failed with AutoGenXXX header missing during build with -j
AutoGen target is for explicit dependency check with target which using AutoGenXXX headers
*Testing*: no test
*Documentation*: no doc updated
=> [CMake] add target AutoGen for explicit dependency check

examples/bundles/lenet_mnist/CMakeLists.txt, examples/bundles/resnet50/CMakeLists.txt
*Description*:
```
[100%] Linking CXX executable ../../../bin/LeNetMnistBundle
cd /home/zakk/glow-build/examples/bundles/lenet_mnist && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/LeNetMnistBundle.dir/link.txt --verbose=1
/usr/bin/c++   -Wall -Wnon-virtual-dtor -fno-exceptions -fno-rtti -g -fno-omit-frame-pointer -O0  -lpng CMakeFiles/LeNetMnistBundleMain.dir/main.cpp.o  -o ../../../bin/LeNetMnistBundle lenet_mnist.o 
CMakeFiles/LeNetMnistBundleMain.dir/main.cpp.o: In function `readPngImage(char const*, std::pair<float, float>, float*&, unsigned long*)':
/home/zakk/glow/examples/bundles/lenet_mnist/main.cpp:65: undefined reference to `png_sig_cmp'
/home/zakk/glow/examples/bundles/lenet_mnist/main.cpp:71: undefined reference to `png_create_read_struct'
... …
```
=> [CMake] fix link order issue

include/glow/Graph/Graph.h, include/glow/Graph/Node.h, include/glow/Graph/Nodes.h, include/glow/IR/IR.h, include/glow/Importer/CommonOperatorLoader.h, lib/Backends/CPU/Transforms.cpp, lib/Backends/OpenCL/Transforms.cpp, lib/Converter/FunctionConverter.cpp, lib/Graph/Grad.cpp, lib/Graph/Graph.cpp, lib/Graph/Node.cpp, lib/IR/IR.cpp, lib/Importer/Caffe2ModelLoader.cpp, lib/Importer/ProtobufLoader.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Optimizer/Quantization.cpp, lib/Quantization/Quantization.cpp, tests/unittests/GraphTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/QuantizationTest.cpp, tests/unittests/TypeAToTypeBFunctionConverterTest.cpp, tools/ClassGen/NodeBuilder.cpp, tools/ClassGen/NodeBuilder.h
As mentioned in https://github.com/pytorch/glow/issues/2194#issuecomment-449008434, there are places where we use indices explicitly to specify inputs or outputs of Nodes. It's a really bad practice as these indices could change if the Node definition or NodeBuilder change. This PR improves the situation by adding input and output indices enums to each node.
There's a commit here with a couple examples of places it can be used to clean things up. There are other places to update if we agree this approach makes sense. It could also be useful for use in the new design of `isOpSupported()` (https://github.com/pytorch/glow/issues/2194).
Here's what the enums look like for the `ConvolutionNode` in `AutoGenNodes.h` with this PR:
```cpp
class ConvolutionNode final : public Node {
...
enum …
```
=> [NodeBuilder] Add Input and Output Indices enums

.circleci/build.sh, .circleci/suppressions.txt, .circleci/test.sh, tests/unittests/TestMain.cpp, tools/loader/Loader.cpp
*Description*: Enabling this signal handler makes it quicker to debug a crash since you get a stack trace without needing to run under a debugger.  (Unlike a debugger, this option doesn't seem to give line numbers, which is weird.  But still pretty useful.)
*Testing*: Add an error to one of the unittests and observe that a stack trace is printed.
=> Print stack trace on error signal

include/glow/Importer/Caffe2ModelLoader.h, lib/Importer/Caffe2ModelLoader.cpp, lib/Importer/ONNXIFIModelLoader.cpp, lib/Importer/caffe2.proto
*Description*:
This PR enables ONNXIFI model loader to load a caffe2 model proto string. The function names and stuff can be more polished. And I think c2 and onnx loader can be more unified in terms of interface. But not sure I want to do it in this PR. 
*Testing*:
Internal integration test
=> Enable ONNXIFI to import Caffe2 model proto

README.md
Fails to build without OpenCL, added this to the install requirements.
*Description*:
*Testing*:
=> Update README.md to include opencl-headers

CMakeLists.txt, lib/Importer/CMakeLists.txt
*Description*:
This is a more localized version of #2228.
After rebasing against glow master, and dropping all local commits also found out /w2 flag I had set globally was suppressing some warning from VS header files that were treated as errors in onnx_proto.
=> [Windows Fix] A more localized fix for onnx_proto compilation issues using VS.

include/glow/Graph/Graph.h, include/glow/Importer/CommonOperatorLoader.h, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, tests/models/caffe2Models/gather_ranges.pbtxt, tests/models/onnxModels/gatherranges.onnxtxt, tests/unittests/Caffe2ImporterTest.cpp, tests/unittests/OnnxImporterTest.cpp, tests/unittests/OperatorTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/NodeGen.cpp
This commit adds support for the [`GatherRanges` operator (click me!)](https://caffe2.ai/docs/operators-catalogue.html#gatherranges). This operator
is not lowered and this commit includes interpreter and CPU backend
implementations for it.
**Testing**
This commit adds two unit tests (one with 32-bit ranges and another with
64-bit ranges) to `OperatorTest` that check operator correctness and one
unit test to `OnnxImporterTest` to check that the operator can be loaded
from a `.onnxtxt` correctly.
**Fixes**
This commit fixes #2210.
=> [C2/ONNX] Add support for GatherRanges operator

lib/Backends/CPU/Pipeline.cpp
*Description*:
If custom backend includes additional libjit functions implementations that have dllexport set, it sets them to internal linkage. This allows LLVM to optimize away functions that are not used, and speeds up compilation, if there are a bunch of them, since it doesn't have to run other optimization passes on those functions.
=> [Improvement] Sets linking to local from dll export/import. 

lib/Importer/Caffe2ModelLoader.cpp, lib/Importer/ONNXModelLoader.cpp, tests/unittests/OnnxImporterTest.cpp
**Description**: Now that we have error handling support in place we can return an error after importing a model if the model does not pass verification. Prior to this PR we did not verify Functions at all in Release mode.
**Testing**: All unit tests and run.sh pass. Updated a couple Pad unit tests that are not yet supported/which fail during verification.
Fixes https://github.com/pytorch/glow/issues/2247
Related to https://github.com/pytorch/glow/issues/1517
=> [Importer] Return error when importing a model if verify fails

include/glow/IR/IR.h, lib/IR/IR.cpp
*Description*: We don't usually need a name for an IRFunction, but when we do (e.g. `dump`) we rely on having its parent `Function` available, which isn't guaranteed.  I don't think it's too costly to just copy the name over.
*Testing*: existing tests cover this
=> [ir] Make IRFunction Named

tests/unittests/CMakeLists.txt, tests/unittests/OperatorTest.cpp
*Description*: Some backends have requirements on weights/biases being Constants and not Placeholders. I added many places here to convert Placeholders to Constants.
*Testing*: All unit tests still pass.
=> [OperatorTest] Convert PHs to Constants where necessary

include/glow/Base/Tensor.h, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Nodes.cpp, lib/Quantization/Quantization.cpp, tests/unittests/OperatorTest.cpp, tools/ClassGen/InstrGen.cpp
*Description*:
* Add macros for quantized ops and quantized ops with accumulation (conv, gemm, etc)
* Int16 support for conv, gemm, rescale quantized, max pool
* Relaxing verifiers to support wider range for quantization formats (including int16) for certain ops
More generic quantization handling to int8/int16, etc.
*Testing*:
* Existing tests should cover base scenarios of int8.
* Will add couple of tests for int16 (although), handling of int16 is not much different except wider accumulators.
n/a
=> [quantization] More flexible general quantization support (int8/int16)

tests/unittests/OperatorTest.cpp
*Description*: Relax a few tests' allowed error -- different backends use different quantization implementations, impacting precision/reasonable error.
*Testing*: Tests still pass.
=> [OperatorTest] Relax allowed error on a few tests

.github/stale.yml
*Description*:
Mark PRs as stale after 5 days of inactivity and close after additional 5.
*Testing*:
Let Github to run it!
n/a
=> [stale bot] Mark inactive PRs as stale and close later.

docs/Quantization.md, lib/Quantization/Quantization.cpp
*Description*:
* Tanh and Sigmoid does not need to have the same quantization params (verifier looks good). Code and doc update.
* Docs on quantization-precision param.
*Testing*:
n/a + existing tests for tanh+sigmoid.
Doc update here.
=> [docs/quantization] Tanh+Sigmoid and quantization precision.

include/glow/Runtime/RuntimeTypes.h, lib/Backends/CPU/CPUDeviceManager.cpp, tests/unittests/CPUDeviceManagerTest.cpp
*Description*: Make ResultCode a class to not pollute the Runtime namespace. 
*Testing*: unittests
*Documentation*: This was a review comment from @bertmaher which I now realized I forgot to do, sorry Bert.
=> [Runtime] Change ResultCode to an enum class

tools/ClassGen/Backends/OpenCL/OpenCLSpecificInstrs.h, tools/ClassGen/Backends/OpenCL/OpenCLSpecificNodes.h
*Description*: We use build/glow/ paths in the CPU backend classgen to placate an FB internal build tool, and we need to do the same for OpenCL.
=> [classgen] Add glow/ prefix to OpenCL include paths

include/glow/Support/Error.h, lib/Importer/ONNXModelLoader.cpp, lib/Support/Error.cpp
*Description*:
Create an llvm::Error that holds a string and/or an enum that classifies the error so that this information can be used to send correct ONNXIFI statuses.
In followups, handle error codes to send ONNXIFI statuses. Use error codes in the rest of model loading stack.
*Testing*:
`ninja all`
doxygen
=> Create GlowErr type with informational error code enum

tests/unittests/CMakeLists.txt, tests/unittests/CPUDeviceManagerTest.cpp, tests/unittests/GlowOnnxifiManagerTest.cpp, tests/unittests/GraphSchedulerTest.cpp, tests/unittests/LLVMIRGenTest.cpp
*Description*: While it's best for tests to only use the "public" headers of a library, it sometimes makes sense to use the private/internal headers directly.  Instead of adding to the include path via cmake, let's refer to them using relative paths like `../../lib/Foo/Bar.h`.  This seems to be LLVM's approach, and I see two advantages:
1. It makes clear you're testing internal implementation, and
2. It plays nicely with FB's internal header layouts O:-)
=> [tests] Include private headers using relative paths

include/glow/Backends/Backend.h, include/glow/ExecutionEngine/ExecutionEngine.h, lib/Backends/Backend.cpp, lib/Backends/CMakeLists.txt, lib/ExecutionEngine/ExecutionEngine.cpp, tests/unittests/CPUDeviceManagerTest.cpp
*Description*: Move optimizeFunction from ExecutionEngine into the base Backend so it can be used outside of the EE. This lets us remove some code duplication.
*Testing*: sanity unittests, shouldn't be any behavoural change.
=> Move optimizeFunction into the base Backend.

include/glow/Backends/CompiledFunction.h, lib/Backends/CPU/CPUDeviceManager.cpp, lib/Backends/CPU/CPUFunction.cpp, lib/Backends/CPU/CPUFunction.h, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/ExecutionEngine/ExecutionEngine.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.h
*Description*: To support running a compiled function multiple times, particularly concurrently on different devices, we must remove per-run state from the CompiledFunction. 
This is a suggested solution for the CPU and Interpreter backend:
* For the CPUFunction: we stored the contiguous buffers for activations and weights and so could only have one concurrent run. These buffers need live only as long as the execution, so have moved into the scope of the execute() method. This means also delaying filling of those buffers until execute() as well.
* For the InterpreterFunction: We use various Tensor objects rather than a single weights/activation buffer. These Tensors were stored in the InterpreterFunction itself, which meant concurrent runs would overwrite intermediate values. The sensible …
=> [RFC] Refactor CPUFunction and InterpreterFunction to remove per-run state

tests/unittests/GlowOnnxifiManagerTest.cpp
*Description*:
Test takes ~30 mins on internal run. Limit # iterations/threads. Should not affect test quality.
*Testing*:
CI
n/a
=> [trivial/test] Run less threads and iterations.

lib/Backends/CPU/CPUDeviceManager.cpp, lib/Backends/CPU/CPUDeviceManager.h, tests/unittests/CPUDeviceManagerTest.cpp
*Description*: We assumed that all functions in the module would be added to a given device at the same time, but this isn't a useful or necessary restriction. Also simplified the module map, we didn't use the CompiledFunction* here.
*Testing*: CPUDeviceManager tests + a new test.
=> [CPUDeviceManager] Relax restriction of addNetwork to allow reusing the Module*.

include/glow/Base/TaggedList.h, include/glow/Support/Error.h, lib/Optimizer/GraphOptimizer.cpp, lib/Partitioner/Partitioner.cpp, tests/unittests/CMakeLists.txt, tests/unittests/CPUDeviceManagerTest.cpp, tests/unittests/ProvisionerTest.cpp, tests/unittests/ThreadPoolTest.cpp
*Description*: As long as CentOS 7 is a target platform we need to support gcc 4.8.5.  Sorry.  I'm going to see if we can use gcc 4.8.5 in CI to enforce this.
=> Fix g++-4.8.5 build

.travis.yml
*Description*: For compatibility with CentOS 7 I want to keep Glow building with gcc 4.8.5.
*Testing*: this diff
=> [ci] Run coverage test with gcc-4.8.5

include/glow/Support/Support.h
*Description*: VS doesn't support __attribute__((__format__(__printf__, 1, 2)));. Looking around it doesn't look like in VS there is equivalent or a clean way of doing this check. This fixes compile issue at the expense of slight less compile time checks when compiling with VS.
*Testing*: UtilsTest.exe which tests this function
Although VS provides some checks, it won't help here since it's function specific:
https://blogs.msdn.microsoft.com/vcblog/2015/06/22/format-specifiers-checking/
https://github.com/pytorch/glow/issues/2305
=> [Fix] Windows build fix for Support

lib/Partitioner/Partitioner.cpp, tests/unittests/PartitionerTest.cpp
*Description*:
In this PR:
1.  Updated the unittest : when create a FC op, use the interface which allows the weights and bias to be constant.
2. Improved the initial partitioning: after BFS, if the memory consumption of all the nodes in one level exceeds the device memory constraints, separates this level in initial partitions. After this, each initial partitions is guaranteed to meet memory constraints.
*Testing*:
Added unittest. 
#2298 
=> [Graph Partitioner] Improve initial partitions and updated unittest

include/glow/Backends/DeviceManager.h, include/glow/Backends/QueueBackedDeviceManager.h, lib/Backends/CMakeLists.txt, lib/Backends/CPU/CPUDeviceManager.cpp, lib/Backends/CPU/CPUDeviceManager.h, lib/Backends/DeviceManagers.cpp, lib/Backends/QueueBackedDeviceManager.cpp, tests/unittests/CPUDeviceManagerTest.cpp
*Description*: add a createDeviceManager static method for creating devices without needing to pull in backend specific code from lib. Also a couple of requests from @gcatron for use by the HostManager: adding a name parameter to DeviceManager constructor, and changing evictNetwork from taking the Module* to a function name.
*Testing*: unittests with asan.
=> [CPUDeviceManager] Factory for creating devices, additions for HostManager

lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, lib/Onnxifi/onnxifiGlow.cpp, tests/unittests/GlowOnnxifiManagerTest.cpp
*Description*:
Enable calling into the Glow runtime from ONNXIFI through the HostManager.
This diff enables running onnxifi inference through HostManager once HostManager is implemented.
This diff is intended to get end-to-end support for the runtime working but there are many things that we cannot yet do such as multiple runs with the same Graph, running multiple onnxifi Graphs on the same onnxifi Backend, etc. To enable these things, some more larger refactoring steps will be needed in followups including 1. Moving all resources necessary for running graphs into BackendId, 2. Abstracting BackendId to enable separate implementations for HostManager and ExecutionEngine backed BackendIds (module is still always owned by ExecutionEngine no matter what), 3 move all graph state into the graph …
=> Enable calling into runtime from onnxifi

examples/CMakeLists.txt, examples/resnet-concurrent.cpp
*Description*: Adds a new example binary demonstrating concurrent execution of resnet50 using a configurable number of CPUDeviceManagers. We're able to keep cores mostly in use (some slight delays because file loading is inline):
*Testing*: run binary with 500 normalized images from imagenet, manually checked their identified class.
=> [examples] Add resnet-concurrent example

include/glow/ExecutionEngine/ExecutionEngine.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, lib/Onnxifi/CMakeLists.txt
*Description*:
Enable running multiple onnxifi graphs on the same onnxifi backend by moving the ExecutionEngine (and thus all state) to the onnxifi graph. This diff also enables ExecutionEngine to run with Backends that it does not own.
Next steps include:
- Make Backend::isOpSupported and Backend::shouldLower static so we can call them from HostManager as well without issue.
- Make onnxifi::Graph and onnxifi::Backend abstract classes and create a new type of graph and backend that integrates more closely with the HostManager interface.
*Testing*:
`ninja test`
sync to fbcode and run tests
doxygen
=> [ONNXIFI] Move ExecutionEngine to Graph

lib/Backends/CMakeLists.txt, lib/Backends/CPU/CMakeLists.txt, lib/Importer/CMakeLists.txt, lib/Runtime/Provisioner/CMakeLists.txt
*Description*: I think we were getting away with some questionable dependencies because our Linux CI build is more permissive than our macOS build (That's a guess.  Maybe it's a cmake versioning issue, or maybe it's something else.  Anyways.)
The most interesting stuff here is the DeviceManager library refactoring.  It's similar to our Backends library, in that there's an "interface" component (the Backend and DeviceManager pure virtual base classes) and a "factory" component (the createBackend and createDeviceManager methods that know how to create all possible derived classes).  Rolling both the interface and factory into one library creates circular dependences with the derived class libraries; luckily the "interface" is header-only, so the derived classes don't actually need to depend …
=> [cmake] Fix dependence structure to allow shared libs

lib/Backends/CPU/CPUDeviceManager.h, tests/unittests/ProvisionerTest.cpp
*Description*: Small fix for some none standard types.
*Testing*:
For one of them:
https://stackoverflow.com/questions/42979055/should-i-use-c-types-uint8-t-uint64-t-or-u-int8-t-u-int64-t
=> [GLOW] Windows build fix.

lib/Backends/CPU/CMakeLists.txt, lib/Support/CMakeLists.txt
*Description*: that's it
*Testing*: On CentOS 7 (or at least FB's variant):`cmake ../.. -G Ninja -DBUILD_SHARED_LIBS=ON  -DGLOW_WITH_OPENCL=OFF && ninja all`
=> More shared library fixes

lib/Backends/DeviceManagers.cpp
Was working on some other backend and figured this was failing to compile.
=> [DeviceManagers] If there is no device manager for the new backend, just fail.

include/glow/Backends/DeviceManager.h, lib/Backends/CMakeLists.txt, lib/Backends/CPU/CMakeLists.txt, lib/Backends/DeviceManagers.cpp, lib/Backends/Interpreter/CMakeLists.txt, lib/Backends/Interpreter/InterpreterDeviceManager.cpp, lib/Backends/Interpreter/InterpreterDeviceManager.h, lib/Backends/Interpreter/InterpreterFunction.cpp, tests/unittests/CMakeLists.txt, tests/unittests/DeviceManagerTest.cpp
*Description*: Adds an InterpreterDeviceManager which is currently identical to the CPU equivalent. I expect it will diverge over time so still worth having both. Made the CPUDeviceManager tests parametric on BackendKind so it tests both backend.
*Testing*: ninja test with asan.
=> Add InterpreterDeviceManager and update DeviceManagerTests to be parametric

include/glow/Optimizer/Optimizer.h, lib/Optimizer/GraphOptimizer.cpp, lib/Optimizer/Lower.cpp, tests/unittests/GraphTest.cpp
*Description*:
DCE should be performed after lowering like in other graph optimizations that can produce dead code. This may incur an extra call to DCE here or there but this should be relatively low overhead and the trade off is that the various places around the compiler that call lower() do not need to worry about manually doing DCE themselves.
*Testing*:
`ninja all`
doxygen
=> Always DCE after lowering

lib/Quantization/Base/Base.cpp, tests/unittests/QuantizationTest.cpp
*Description*: This case is kind of pathological, but symmetric quantization was failing to find a proper zero point when min/max was infinite.  Work around it by forcing infinities to lowest/max as appropriate.
*Testing*: New QuantizationTest
=> [quantization] Choose symmetric params even with infinities

include/glow/Importer/CommonOperatorLoader.h, tests/models/caffe2Models/alias_op_net.pbtxt, tests/unittests/Caffe2ImporterTest.cpp
*Testing*:
`ninja test`
`Alias` is non-op in Glow
=> [new operator] Support Alias as non-op

include/glow/Graph/Graph.h, include/glow/Importer/CommonOperatorLoader.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, tests/models/caffe2Models/sparse_to_dense_mask_op_net.pbtxt, tests/unittests/Caffe2ImporterTest.cpp, tests/unittests/OperatorTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/MemberType.cpp, tools/ClassGen/MemberType.h, tools/ClassGen/NodeBuilder.cpp, tools/ClassGen/NodeGen.cpp
*Description*:
It is unfortunate that we now need to create a hash map inside an operator. Luckily, `mask` is known in advance, so we can precompute the hash map. I decided not to do it yet, because the goal of Interpreter backend is simplicity.
*Testing*:
`ninja test`
Introduce `SparseToDenseMask` operator, which matches Caffe2 semantics:
https://caffe2.ai/docs/operators-catalogue.html#sparsetodensemask
=> [New operator] Implement SparseToDenseMask

include/glow/Backends/BackendUtils.h, include/glow/Graph/Context.h, include/glow/Runtime/Executor/Executor.h, lib/Graph/Context.cpp, lib/Runtime/CMakeLists.txt, lib/Runtime/Executor/CMakeLists.txt, lib/Runtime/Executor/Executor.cpp, lib/Runtime/Executor/ThreadPoolExecutor.cpp, lib/Runtime/Executor/ThreadPoolExecutor.h, tests/unittests/CMakeLists.txt, tests/unittests/ExecutorTest.cpp
This commit adds `Executor`, an interface for a component of the Glow
runtime that is capable of running a partitioned directed acyclic Glow
graph and returning the results of that execution. This commit also adds
`ThreadPoolExecutor`, an implementation of this interface that runs
graphs using a thread pool. The  workers essentially do a
concurrent breadth-first search through the node graph to execute all
nodes, repeatedly copying partition components outputs to their descendents along
the way.
**Testing**
This commit adds eight unit tests for the following scenarios:
- empty graph
- single node
- several instances of a single node graph at once
- duplicate runIds
- multi node graph
- multi node graph with a node that fails
- multi node graph with nodes running on …
=> [Runtime] Add runtime Executor class

tests/unittests/DeviceManagerTest.cpp
*Description*:
Currently Device Manager CPU test gets run even if Glow was not compiled with CPU support. Fix this.
```
[5/12] Linking CXX executable tests/DeviceManagerTest
FAILED: tests/DeviceManagerTest 
: && /bin/c++  -Wall -Wnon-virtual-dtor -fno-exceptions -fno-rtti -Wno-psabi -g -fno-omit-frame-pointer -O0   tests/unittests/CMakeFiles/DeviceManagerTest.dir/DeviceManagerTest.cpp.o  -o tests/DeviceManagerTest  lib/Backends/libBackends.a lib/Backends/libDeviceManager.a lib/Graph/libGraph.a lib/IR/libIR.a lib/ExecutionEngine/libExecutionEngine.a lib/Optimizer/libOptimizer.a tests/googletest/googlemock/gtest/libgtestd.a tests/unittests/libTestMain.a lib/Support/libThreadPool.a lib/Backends/Interpreter/libInterpreterDeviceManager.a lib/Backends/libBackends.a …
```
=> [trivial/fix] Run device manager test on CPU only when CPU is enabled.

include/glow/ExecutionEngine/ExecutionEngine.h, lib/ExecutionEngine/ExecutionEngine.cpp
*Description*:
A temporary home for Function families.
Enable multiple compiled functions in a single EE. This is useful for the ExecutionEngine onnxifi backends and probably for unit testing now.
*Testing*:
I'll write some unit tests for this but just wanted to get feedback on the approach first.
doxygen
=> Add support for multiple compiled functions in ExecutionEngine

include/glow/Graph/Graph.h, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/modulo_op_net.pbtxt, tests/unittests/Caffe2ImporterTest.cpp, tests/unittests/OperatorTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/MemberType.cpp, tools/ClassGen/MemberType.h, tools/ClassGen/NodeBuilder.cpp, tools/ClassGen/NodeGen.cpp
*Description*:
Implements caffe2 Mod operator.
I chose to call the IR node/instruction Modulo instead of Mod to avoid confusion with Modules which are referred to throughout the codebase as mod.
*Testing*:
`ninja test`
doxygen
Fixes #2330
=> [New Operator] Implement Mod operator

lib/Backends/Interpreter/InterpreterDeviceManager.h
*Description*: @ayermolo noticed this was wrong, fixing the windows build.
=> [trivial] Fix Windows build (u_int64_t -> uint64_t)

include/glow/Backends/DeviceManager.h, include/glow/Backends/QueueBackedDeviceManager.h, lib/Backends/CPU/CPUDeviceManager.cpp, lib/Backends/CPU/CPUDeviceManager.h, lib/Backends/Interpreter/InterpreterDeviceManager.cpp, lib/Backends/Interpreter/InterpreterDeviceManager.h, tests/unittests/ExecutorTest.cpp
*Description*:  Since the work is done on a separate thread there was no guarantee the string would still be backed when the work was done. So changing interface to a string.
*Testing*: DeviceManager tests pass
=> Changed DeviceManager::EvictNetwork to use a string instead of llvm::stringRef

examples/resnet-concurrent.cpp
*Description*: The resnet50 model expects a batch, and we were giving it only a single image which caused a "Mismatch on Placeholder and Tenor types." assertion in the ExecutionEngine. This actually works fine in release, but fixing the debug build is easy.
*Testing*: Ran resnet-concurrent example in Debug.
=> Fix resnet-concurrent example

docs/Backends.md, include/glow/Backends/Backend.h, include/glow/IR/IR.h, include/glow/IR/IRGen.h, include/glow/Optimizer/Optimizer.h, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/IR/IRGen.cpp, lib/Optimizer/IROptimizer.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/GraphTest.cpp
*Description*:  Extending framework to support custom translation from Node IR to Instruction IR. Right now there is auto generated lowering for custom nodes to custom instruction IR. This allows more flexibility. For example regularly supported Node that can be lowered to something custom BE adds for Instruction IR
Refactored `IRGenVisitor` to a header so that it can be used by a backend to generate custom Instructions during IRGen. Otherwise no real change to IRGen or the `IRGenVisitor`. A couple helper functions were added too. And then there's an extra call to `Backend::generateInst()` at the beginning of `post()` to check if the backend wants to IRGen the current node, otherwise our default IRGen logic takes place.
*Testing*: Unit tests
fixes …
=> [Improvement] Custom translation from Node IR

lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, lib/Onnxifi/onnxifiGlow.cpp
*Description*:
Implement `onnxSetIOAndRunGraph` ONNXIFI extension.
Right now this is implemented very similarly to `onnxSetGraphIO` followed by `onnxRunGraph` but once this is tested and caffe2 switches to using `onnxSetIOAndRunGraph`, we can simplify this implementation and remove the mutex in onnxifi::graph.
Also implement `onnxGetExtensionFunctionAddress` for finding ONNXIFI extensions implemented by glow.
Updated onnx to latest version to include `onnx/onnxifi_ext.h`
*Testing*:
`ninja test`
Will test c2 implementation once it's ready
Doxygen
Fixes #2351
=> [ONNIFI] Implement onnxSetIOAndRunGraph onnxifi extension

utils/format.sh
*Description*: that's it
*Testing*: utils/format.sh fix
*Documentation*: na
=> [format.sh] Alternate extensions for C(++) files

examples/fr2en.cpp, include/glow/Optimizer/Optimizer.h, include/glow/Quantization/Quantization.h, lib/Backends/CPU/Transforms.cpp, lib/Graph/Graph.cpp, lib/Optimizer/Lower.cpp, lib/Optimizer/Quantization.cpp, lib/Quantization/Quantization.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/MLTest.cpp, tests/unittests/QuantizationTest.cpp, tools/loader/Loader.cpp, tools/loader/Loader.h
This is a somewhat controversial change, but something I've considered for a while and it seems it could solve a couple pain points we're running into right now.
Basically, when doing profiling, lower *everything*, but keep track of what was lowered from what. This allows us to get quantization parameters of lowered nodes, while still allowing for profiles to stay backend-agnostic.
E.g. if we lower an FC to MM + BA, we keep track of that via a StringStringMap, mapping between their quantization output names (e.g. `ba:0` maps to `fc:0`, as we did `FCResult.replaceAllUsesOfWith(BAResult)`).
This map is used to write both the unlowered and lowered names into the profile. So before this PR, the profile would contain just `fc:0`. With this PR, the profile would additionally contain `mm:0` and …
=> Lower everything before profiling, allowing for lowered profile to be gathered

include/glow/Backends/BackendUtils.h, include/glow/Runtime/Executor/Executor.h, include/glow/Runtime/HostManager/HostManager.h, include/glow/Runtime/Provisioner/Provisioner.h, include/glow/Runtime/RuntimeTypes.h, lib/Backends/BackendUtils.cpp, lib/Backends/CPU/CPUDeviceManager.h, lib/Runtime/CMakeLists.txt, lib/Runtime/HostManager/CMakeLists.txt, lib/Runtime/HostManager/HostManager.cpp, lib/Runtime/Provisioner/Provisioner.cpp, tests/unittests/CMakeLists.txt, tests/unittests/HostManagerTest.cpp, tests/unittests/ProvisionerTest.cpp
*Description*: This is a resurrected PR for the HostManager. It is almost ready for merging, once Executor, Partitioner, and Provisioner are merged this will be updated and be ready. 
The HostManager will serve as the entry point for execution calls and handle orchestrating the rest of the runtime components.
*Testing*: Will write Unit Test before merge.
Related to #2045
=> Add Host Manager

include/glow/Runtime/Provisioner/Provisioner.h, lib/Runtime/HostManager/HostManager.cpp, lib/Runtime/Provisioner/Provisioner.cpp, tests/unittests/ProvisionerTest.cpp
*Description*: Update the Provisioner to remember the last device it assigned to so it can distribute network assignments. This enables a concurrent resnet50 through HostManager example.
*Testing*: Provisioner and HostManager unit tests pass.
=> Updated Provisioner to allow round robin network-device allocation

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/rowwise_quantized_sparse_lengths_sum_init_net.pbtxt, tests/models/caffe2Models/rowwise_quantized_sparse_lengths_sum_predict_net.pbtxt, tests/models/caffe2Models/rowwise_quantized_sparse_lengths_weighted_sum_init_net.pbtxt, tests/models/caffe2Models/rowwise_quantized_sparse_lengths_weighted_sum_predict_net.pbtxt, tests/unittests/Caffe2ImporterTest.cpp
*Description*: Add support in the Caffe2 model loader for `SparseLengthsWeightedSum8BitsRowwise` and `SparseLengthsSum8BitsRowwise`.
*Testing*: Added unit tests
Related to https://github.com/pytorch/glow/issues/1698
=> [Importer] Add C2 importer support for RWQ SLWS/SLS

docs/Backends.md, docs/NewBackendSpecificNode.md, include/glow/Backends/Backend.h, lib/Backends/Backend.cpp
*Description*: As mentioned in https://github.com/pytorch/glow/issues/2339, I don't think we need `transformPreLowering()` anymore.
1. I don't think any of our backends are using this functionality given the ability to prevent lowering via `shouldLower()`, and then later transform the graph during `transformPostLowering()`.
1. Simplify the compilation pipeline since it doesn't seem useful/used.
1. Now that https://github.com/pytorch/glow/pull/2311 has landed, when quantizing we lower prior to `transformPreLowering()` anyway, so it's a misleading function and could cause bugs and/or confusion.
*Testing*: All unit tests still pass.
*Documentation*: Updated.
Closes https://github.com/pytorch/glow/issues/2339
=> Remove transformPreLowering()

lib/Importer/Caffe2ModelLoader.cpp
*Description*:
Detect 0 dim tensors earlier and return error so that it doesn't goes down into the code and crash the process. 
*Testing*:
Fixes https://github.com/pytorch/glow/issues/2369
=> Return error if we import tensor with 0 dims

include/glow/Partitioner/Partitioner.h, include/glow/Partitioner/PartitionerUtils.h, lib/Partitioner/CMakeLists.txt, lib/Partitioner/Partitioner.cpp, lib/Partitioner/PartitionerUtils.cpp, tests/unittests/PartitionerTest.cpp
*Description*:
Based on the initial partitions, this PR adds:
1) Adjust the initial partition (moving nodes from one partition to another partition) to minimize the communication cost.
2) Combine the partitions if necessary.
*Testing*:
For unittest PartitionerTest::Basic1, the communication cost is `288 bytes->256 bytes`.
For PartitionerTest::Basic2, the communication cost is `160 bytes->64 bytes`. And the number of partitions is `3 -> 2`.  The following 2 pics shows the initial partition and optimized partitions:
**The initial partition ( Memory 2048 bytes. 3 partitions, with memory (1152 bytes, 1152 bytes, 1376 bytes)**
**The optimized partition (Memory 2048 bytes. 2 partitions, with memory (1728, 1728) :**
*Documentation*: #2298
Please see a detailed explanation …
=> [Graph Partitioning] Add optimization to minimize communication cost and number of partitions.

README.md
*Description*:
This commit updates `README.md` with instructions for using MacPorts instead of Homebrew on macOS. It also adds a note re. non-traditional header layout in newer macOS versions.
=> [Glow] Update README.md with MacPort instructions

include/glow/Partitioner/Partitioner.h, include/glow/Partitioner/PartitionerUtils.h, lib/Partitioner/Partitioner.cpp, lib/Partitioner/PartitionerUtils.cpp
*Description*:
This PR : 
1. Polished the BFS data structure. 
2. Using the longest distance between a node and the root as this node's level.  Therefore, we won't need to test and eliminate this case in the future : partition1 uses some nodes from partition2 while partition2 uses some nodes in partition1. 
*Testing*:
Current tests, Resnet50.
*Documentation*: #2298 
=> [Graph Partitioner] Improve and polish getBFSLevel function.

docs/Quantization.md, include/glow/Base/Tensor.h, include/glow/Base/Type.h, include/glow/Graph/Graph.h, include/glow/Quantization/Base/Base.h, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Base/Tensor.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Importer/Caffe2ModelLoader.cpp, lib/Quantization/Base/Base.cpp, tests/models/caffe2Models/fused_rowwise_quantized_sparse_lengths_sum_init_net.pbtxt, tests/models/caffe2Models/fused_rowwise_quantized_sparse_lengths_sum_predict_net.pbtxt, tests/models/caffe2Models/fused_rowwise_quantized_sparse_lengths_weighted_sum_init_net.pbtxt, tests/models/caffe2Models/fused_rowwise_quantized_sparse_lengths_weighted_sum_predict_net.pbtxt, tests/unittests/Caffe2ImporterTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/TensorsTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/NodeGen.cpp
*Description*: As noted in https://github.com/pytorch/glow/pull/2292, we decided to implement both fused and unfused versions of rowwise-quantized SLWS.
*Testing*: Added OperatorTests and Caffe2ImporterTests.
*Documentation*: Added.
Closes https://github.com/pytorch/glow/issues/1698
=> [New Operator] FusedRowwiseQuantizedSparseLengthsWeightedSumNode

include/glow/Base/Type.h, include/glow/Graph/Graph.h, include/glow/Graph/Nodes.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, tests/unittests/GraphTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/NodeGen.cpp
*Description*:
Create a new `Convolution3D` node and instruction and the associated verification and graph node creation methods. Interpreter implementation for `Convolution3DInst` and `Convolution3DGradInst` will be implemented next pr.
I considered using the existing `Convolution` node and gating everything on the dimensionality of the inputs because they share the same input and output structure however there wasn't much to be gained by doing this because much of the verification code can't be shared and neither will the backend implementation be able to be shared likely so it seemed better to just create the correct node up front during loading and not worry about which implementation to use after that.
*Testing*:
`ninja all`
Added a very basic test.
Doxygen
=> [Conv3D] Types, plumbing, and verification

include/glow/Runtime/Executor/Executor.h, include/glow/Runtime/Provisioner/Provisioner.h, include/glow/Runtime/RuntimeTypes.h, lib/Runtime/Executor/ThreadPoolExecutor.cpp, lib/Runtime/Executor/ThreadPoolExecutor.h, lib/Runtime/HostManager/HostManager.cpp, lib/Runtime/Provisioner/Provisioner.cpp, tests/unittests/ExecutorTest.cpp
*Description*:
Make it so HostManager owns DeviceManagers and the rest of the runtime just uses them. Make the blocking on shutdown in Executor explicit to ensure that no inflight requests will be using DeviceManagers. Prevent processing new requests while shutting down.
*Testing*:
`ninja all`
cd to downloaded_models and `../bin/resnet-runtime ../../tests/images/imagenet`
Fixes #2384 
Fixes #2297
=> Make HostManager own Devices

lib/Backends/CPU/CMakeLists.txt, lib/Backends/Interpreter/CMakeLists.txt, lib/Runtime/Executor/CMakeLists.txt, lib/Runtime/HostManager/CMakeLists.txt, lib/Runtime/Provisioner/CMakeLists.txt
*Description*: This has been broken locally for me for awhile but seems to build fine in circleci so I never worried about it, but that time has passed.
*Testing*: Build with the following config:
`
cmake -GNinja -DCMAKE_CXX_FLAGS=-Werror -DGLOW_WITH_CPU=ON -DCMAKE_BUILD_TYPE=Debug -DGLOW_WITH_OPENCL=ON -DBUILD_SHARED_LIBS=ON ../
`
*Documentation*: I am assuming that circleci passes because it uses an older version of the compiler? Can't quite work out exactly what the difference is.
=> Fix runtime build with BUILD_SHARED_LIBS

tests/unittests/Caffe2ImporterTest.cpp, tests/unittests/OperatorTest.cpp
*Description*: Caffe2ImporterTest currently tests both that a DotProduct
operator can be loaded and that it produces correct results. With this change,
the numerical checks are moved to OperatorTest.
*Testing*: Unit tests pass.
=> [unittests] Move DotProduct numerical tests to OperatorTest.cpp

examples/CMakeLists.txt, examples/tracing-compare.cpp, include/glow/Backends/Backend.h, include/glow/Backends/CompiledFunction.h, include/glow/Backends/TraceEvents.h, include/glow/Graph/Context.h, lib/Backends/Backend.cpp, lib/Backends/CMakeLists.txt, lib/Backends/CPU/CMakeLists.txt, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/CPU/CPUFunction.cpp, lib/Backends/CPU/CPUFunction.h, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/CMakeLists.txt, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Backends/OpenCL/CMakeLists.txt, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/TraceEvents.cpp, lib/ExecutionEngine/CMakeLists.txt, lib/Runtime/HostManager/CMakeLists.txt, tests/unittests/CMakeLists.txt, tools/ClassGen/InstrGen.cpp
*Description*: Implement auto instrumentation and handling of TraceEvents in the CPU and Interpreter backends. If instrumentation is enabled then every Instruction in the IR will be timed. 
The included example (tracing-compare) runs resnet50 on both the CPU and Interpreter backends and outputs a json file in the chromium TraceEvents format, which can be loaded in the chrome about://tracing page. It looks like this:
*Testing*: The example and manual testing. Will write unit tests in a follow up.
=> Add tracing/profiling for the CPU and Interpreter backends

tests/unittests/Caffe2ImporterTest.cpp, tests/unittests/OperatorTest.cpp
Move the parts of `Caffe2ImporterTest` that check numerical correctness over to `OperatorTest`, to better separate FC operator loading tests from numerical correctness tests.
=> [testing] Move numerical FC tests to OperatorTest

include/glow/Backends/BackendUtils.h, lib/Backends/BackendUtils.cpp, lib/Backends/CMakeLists.txt, lib/Backends/DeviceManagers.cpp, lib/Backends/OpenCL/CMakeLists.txt, lib/Backends/OpenCL/OpenCLDeviceManager.cpp, lib/Backends/OpenCL/OpenCLDeviceManager.h, tests/unittests/DeviceManagerTest.cpp
*Description*: Added OpenCLDeviceManager. Currently this does not support a compiled function on more than one device. That can be updated after executionInfo is added.
*Testing*: Added OCL deviceManager to deviceManager unit test. Passes. Also tested on resnet50 and it passes.
=> [Runtime] Added OpenCL device manager

tests/benchmark/GemmBench.cpp, tests/unittests/DeviceManagerTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/QuantizationTest.cpp
Use C++11’s override and remove virtual where applicable.
=> [NFC] Apply modernize-use-override

lib/Backends/OpenCL/CMakeLists.txt
CI doesn't build with OpenCL so this got missed.
=> Fix shared build (with OpenCL)

tools/ClassGen/InstrGen.cpp
This commit removes code that marks the source and destination buffers
of the `LocalResponseNormalization` instruction as in-place. The value of
an output element depends on the values adjacent to the corresponding
input element, so there is no way to perform the local response
normalization operation in-place.
**Testing**
**Fixes**
This commit fixes #2356.
=> [InstGen] LocalResponseNormalization src/dest should not be in-place

utils/decode_caffe2_protoc.sh
*Description*:
Fix proto path in `encode_caffe2_protoc.sh`.
Create a `decode_caffe2_protoc.sh` that decodes `.pb` to `.pbtxt`.
*Testing*:
* encode:
* ran `./utils/encode_caffe2_protoc.sh ./build/downloaded_models/resnet50/predict_net.pbtxt | diff ./build/downloaded_models/resnet50/predict_net.pb -`
* no changes observed
* decode:
* ran: `./utils/decode_caffe2_protoc.sh ./build/downloaded_models/resnet50/predict_net.pb | diff ./build/downloaded_models/resnet50/predict_net.pbtxt -`
* observed the following changes that look like rounding errors, not sure if they are significant: https://gist.github.com/jackm321/a1ad4cb3c2cb882093a906fe91aea675
comments in script
=> Update scripts for calling protoc with caffe2 models

.circleci/build.sh, .circleci/config.yml, .circleci/test.sh, CMakeLists.txt, cmake/modules/GlowTestSupport.cmake, docs/Testing.md, tests/CMakeLists.txt
*Description*:
Create a set of tests with the `EXPENSIVE` label (`add_glow_test(EXPENSIVE ...)`) and only run those tests with `ninja check_expensive`. Make all existing OutputCheck tests use the `EXPENSIVE` label. Build all tests all the time, only run OutputCheck tests when all build requirements were satisfied.
*Testing*:
`ninja check`
`ninja check_expensive`
Comments, Updated docs
=> Create an optional EXPENSIVE label for tests

tests/unittests/DeviceManagerTest.cpp
When not building with CPU this was causing the build to break.
Perhaps would be nice to unit test even just building with just the Interpreter backend.
I tried wrapping this in its own gtest CPUOnly case/class but couldn't get it to build successfully. If someone has a better suggestion/fix on this let me know!
=> [DeviceManagerTest] Disable CPU-only test when not building with CPU

include/glow/Base/Tensor.h, include/glow/Base/Type.h, lib/Backends/CPU/LLVMIRGen.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/kernels.cl, lib/Base/Tensor.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Quantization/Quantization.cpp, tests/unittests/GraphTest.cpp, tests/unittests/IROptTest.cpp, tests/unittests/OperatorTest.cpp, tools/ClassGen/InstrGen.cpp
*Description*: Add in a new `ElemKind::BoolTy`. This removes the hacky implementation we had before for which just used the same `ElemKind` for the bool result/input. Note that I went with `BoolTy` instead of `PredicateTy`, but I can switch it if preferred.
While this is implemented with `bool` in the Interpreter, I used `int8_t` in the CPU/OpenCL backends.
*Testing*: Updated all impacted tests, and added a simple test for testing CmpLTE by itself.
Closes https://github.com/pytorch/glow/issues/1581
=> Add in new ElemKind::BoolTy for use with Compare, Select instructions

tests/models/caffe2Models/dce_test_init_net.pbtxt, tests/models/caffe2Models/dce_test_predict_net.pbtxt, utils/scripts/dce_caffe2_model.py
*Description*:
Basic script that takes caffe2 predict_net and init_net protobuf files and removes all dead nodes (nodes that aren't used to calculate the external_output of the predict_net then outputs this back to protobuf files.
The motivation behind this script is that sometimes we get models that have a bunch of extra nodes in them that we don't need for computing the prediction output and some of them we don't support in Glow (for example the [Python op](https://caffe2.ai/docs/operators-catalogue.html#python)) so this can clean out these nodes so that we can then import them using the model loader.
*Testing*:
Added a test init_net and predict_net and manually checked the output of running the script on those files.
Ran the script on a large graph with lots of dead nodes and eyeballed …
=> DCE script for caffe2 nets

examples/fr2en.cpp, include/glow/Optimizer/Optimizer.h, include/glow/Quantization/Quantization.h, lib/Backends/Backend.cpp, lib/Onnxifi/Base.cpp, lib/Optimizer/Lower.cpp, lib/Quantization/Quantization.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/GraphTest.cpp, tests/unittests/MLTest.cpp, tests/unittests/QuantizationTest.cpp, tools/loader/Loader.cpp, tools/loader/Loader.h
*Description*: Refactor LoweredNamesMap to LoweredInfoMap. The LoweredInfoMap maps to a set of NodeNameAndKind structs containing the node's outputName and NodeKind. This is used to correctly quantized BAs lowered from FCs, so that during quantization we know if a batched add came from a fully connected. This also requires keeping track of the LoweredInfoMap prior to quantization, whereas before it was only prior to profiling.
*Testing*: Added to unit tests to verify the batched add is Int32QTy, and correct scale/offset.
Fixes https://github.com/pytorch/glow/issues/2395
=> Refactor LoweredNamesMap to LoweredInfoMap and correctly quantized BAs lowered from FCs

include/glow/Backends/Backend.h, include/glow/ExecutionEngine/ExecutionEngine.h, include/glow/Graph/Graph.h, lib/Backends/Backend.cpp, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/IR/IRGen.cpp, tests/unittests/CMakeLists.txt, tests/unittests/TraceEventsTest.cpp, tools/ClassGen/NodeGen.cpp
*Description*: To support profiling the graph as provided (ie. before optimization) this adds TraceEventNodes: Nodes in the graph that explicitly trigger metrics collection. They get compiled right down to TraceEventInstrs which are handled the same way as the automatic instrumentation.
*Testing*: new unit tests!
This diff demonstrates the need to refactor various calls to compile, which is next on the list.
Also I guess it would be nice to simplify adding TraceEventNodes and automate generation of the backing Tensor.
=> [profiling] Add TraceEventNode for manual tracing

include/glow/Backends/CompiledFunction.h, lib/Backends/CPU/CPUDeviceManager.cpp, lib/Backends/CPU/CPUFunction.h, lib/Backends/Interpreter/InterpreterDeviceManager.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/OpenCL/OpenCL.h, lib/Backends/OpenCL/OpenCLDeviceManager.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/DeviceManagerTest.cpp
*Description*: Adds a `getCompileBackendKind()`method to CompiledFunction which returns the kind of backend used to create it. In the DeviceManager we can use this to prevent CompiledFunctions of the wrong type from being added.
*Testing*: Ran unit test, found and fixed a bad DeviceManagerTest.
*Documentation*: fixes #2410 
Worth noting this adds a new pure virtual method to CompiledFunction, so new Backends will need to fill this out in their CompiledFunction-subclasses.
=> Check type of CompiledFunction in DeviceManager before adding

lib/Backends/CPU/libjit/libjit_defs.h, lib/Backends/CPU/libjit/libjit_matmul.cpp
*Description*: As a performance optimization the libjit matmul has a branch where if a tensor dimension is >= 1024 it allocates about 2 mb on the stack and does the multiplication in that memory. 
Some systems (looking at you OSX) limit the stack size of created threads such that any graph with a large Tensor would crash if the compiled CPUFunction was run on the DeviceManager or on any new thread.
The fix is to allocate the scratchpad dynamically.
*Testing*: unit tests w/ ASAN.
Also, GemmBench to compare performance regression (3 runs each impl):
```
Alloc on Stack:
utX, outY, lhsX, lhsY, rhsX, rhsY, gflops/s,
1024, 1024,   1024, 1024,   1024,  1024,   108.48
1024, 1024,   1024, 1024,   1024,  1024,   109.21
1024, 1024,   1024, 1024,   1024,  1024,   116.51
32, 32  ,     32, 1024, …
```
=> Avoid large stack allocation in libjit matmul

docs/Quantization.md, include/glow/Optimizer/Optimizer.h, lib/Optimizer/Lower.cpp, tests/unittests/GraphTest.cpp, tools/loader/Loader.cpp
*Description*: Add option on the command line for loaders to prevent lowering during profiling. By default everything will be lowered for profiling. However this may cause performance issues for some models, e.g. if a model has group Convolutions which explode the size of the graph when lowered. Thus, this PR allows for disabling certain NodeKinds for profiling. This means that during quantization, these nodes should also not be lowered by the backend.
*Testing*: Added test. Also verified shufflenet works with the new command line option while making profiling much faster (what is was previously).
*Documentation*: Added documentation.
Fixes https://github.com/pytorch/glow/issues/2413
=> [Lowering/Loader] Add CLI option and plumbing to disable lowering specified node kinds.

include/glow/Support/Error.h, tests/unittests/OnnxImporterTest.cpp
*Description*:
TIL `llvm::Error::operator bool()` only sets the checked bit [if the error is not filled](https://github.com/llvm-mirror/llvm/blob/9ed230bd09dbdc4d85f34ac3c2b824726245f17e/include/llvm/Support/Error.h#L236).
*Testing*:
Built LLVM from source with `LLVM_ABI_BREAKING_CHECKS` on
Configured glow to use this llvm version with -DCMAKE_PREFIX_PATH
`ninja test`
Fixes #2432
=> Check unchecked Error

examples/resnet-concurrent.cpp, examples/resnet-runtime.cpp, examples/resnet-verify.cpp, examples/tracing-compare.cpp
*Description*:
I noticed some cantFails in the code where there should be EXIT_ON_ERRs which provides more details on failure and works whether compile with debug or not which is good for examples. Also, this code can actually fail so better to use EXIT_ON_ERR.
*Testing*:
`ninja test`
none
=> Replace cantFails with EXIT_ON_ERRs

include/glow/Backends/DeviceManager.h, include/glow/Backends/QueueBackedDeviceManager.h, lib/Backends/CPU/CPUDeviceManager.cpp, lib/Backends/CPU/CPUDeviceManager.h, lib/Backends/Interpreter/InterpreterDeviceManager.cpp, lib/Backends/Interpreter/InterpreterDeviceManager.h, lib/Backends/OpenCL/OpenCLDeviceManager.cpp, lib/Backends/OpenCL/OpenCLDeviceManager.h, lib/Runtime/HostManager/HostManager.cpp, tests/unittests/DeviceManagerTest.cpp, tests/unittests/ExecutorTest.cpp
This commit updates the `DeviceManager` interface; `init`/`stop` now
return a `glow::runtime::ResultCode` and `DeviceManager::evictNetwork`
now takes a callback.
**Testing**
This commit modifies `DeviceManager` test to check for the return codes
from `init`, `stop` and `evictNetwork` (via its callback). All tests
pass.
**Fixes**
This commit fixes #2357.
=> [DeviceManager] Update DeviceManager interface

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/elementwise_linear_default_net.pbtxt, tests/models/caffe2Models/elementwise_linear_net.pbtxt, tests/unittests/Caffe2ImporterTest.cpp, tests/unittests/OperatorTest.cpp
This commit adds support for the `ElementwiseLinear` Caffe2 operator. It
is lowered early in the `glow::Function::createElementwiseLinear`
implementation to `Broadcast`, `Mul` and `Add`.
**Testing**
This commit adds a test for this operator to `OperatorTest` (CPU,
Interpreter and OpenCL backends) and two tests to `Caffe2ImporterTest`;
one that has `axis` specified in the test protobuf and one that does
not. These new tests and all old unit tests all pass.
**Fixes**
This commit fixes #2420.
=> [Operator] Add ElementwiseLinear Caffe2 op

include/glow/Backends/Backend.h, include/glow/Backends/CompiledFunction.h, include/glow/Backends/DummyDeviceManager.h, include/glow/ExecutionEngine/ExecutionEngine.h, lib/Backends/BackendUtils.cpp, lib/Backends/CMakeLists.txt, lib/Backends/CPU/CMakeLists.txt, lib/Backends/CPU/CPUBackend.h, lib/Backends/CPU/CPUDeviceManager.cpp, lib/Backends/CPU/CPUFunction.cpp, lib/Backends/DeviceManagers.cpp, lib/Backends/Interpreter/CMakeLists.txt, lib/Backends/Interpreter/Interpreter.h, lib/Backends/Interpreter/InterpreterDeviceManager.cpp, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/OpenCL/CMakeLists.txt, lib/Backends/OpenCL/OpenCL.h, lib/Backends/OpenCL/OpenCLDeviceManager.cpp, lib/ExecutionEngine/CMakeLists.txt, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Runtime/Provisioner/CMakeLists.txt, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/CMakeLists.txt, tests/unittests/DeviceManagerTest.cpp, tests/unittests/QuantizationTest.cpp
*Description*: There are currently two ways to execute a compiled function: using the ExecutionEngine, or using the DeviceManager. The ExecutionEngine has a good interface but it would be good to have a single path to maintain for execution. This is the first part of making that change: backing the ExecutionEngine by a DeviceManager.
*Documentation*: We'll fall back to the DummyDeviceManager if the BackendKind does not have a DeviceManager of its own, but this should be a short term solution.
=> Build ExecutionEngine on DeviceManager

lib/Graph/Graph.cpp
*Description*: I think we need to keep the dot file after calling dumpDAG(). The use scenario is calling dumpDAG() in somewhere but user can't got the file. 
*Testing*:
=> [Graph] keep the dotFile

include/glow/Backends/BackendUtils.h
*Description*: RuntimeBundle has a default constructor but no default initializers for its members.  But the destructor reads `constants_` to determine if it needs to free, and thus can free a garbage pointer.
*Testing*: This must have been missed because all our backends now create compiled functions with runtime bundles?  But I have a private backend that does not use runtime bundle, and thus hit this problem.  In an ideal world I would write a test case demonstrating this crash...
=> [runtime] Initialize RuntimeBundle safely

.gitmodules, CMakeLists.txt, docs/Onnxifi.md, include/glow/Importer/CommonOperatorLoader.h, include/glow/Importer/ONNXIFIModelLoader.h, lib/Importer/CMakeLists.txt, lib/Onnxifi/Base.h, lib/Onnxifi/onnxifiGlow.cpp
*Description*: Use foxi instead of onnxifi in onnx
*Testing*: CI
=> Switch to foxi

lib/ExecutionEngine/ExecutionEngine.cpp
*Description*: This seems like a leak, since we assign device_ in setBackend (below), and LSAN reports it to me, but only when I'm using an experimental private backend.  I don't see any such warning on trunk, which makes me suspicious that I've done something wrong...
*Testing*: 
=> [ee] Don't leak DeviceManagers

examples/tracing-compare.cpp, include/glow/Backends/Backend.h, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/QuantizationTest.cpp, tests/unittests/TraceEventsTest.cpp
*Description*: We have 3 different methods in the Backend to invoke compile: `compileWithoutConstants()`, `instrumentAndCompile()` and the plain `compile()` (uh oh what if you want to compile without constants but with instrumentation?!). This PR collapses the three down to a single compile() function which takes a CompileOptions struct which indicates how the compile should be done. At the moment it's got only those options (collectConstants & autoInstrument).
*Testing*: unit tests.
*Documentation*: This changes the Backend interface and so all backends will need an update, but I kept the standard `compile()`to make migration easier.
=> Refactor Backend::compile so it takes an options struct.

include/glow/ExecutionEngine/ExecutionEngine.h, lib/ExecutionEngine/ExecutionEngine.cpp
*Description*: Per #2456 this should be a unique_ptr since we don't want to leak it and we never copy it.
*Testing*: Tests with ASAN.
=> [EE] Make device a unique_ptr

include/glow/Partitioner/PartitionerUtils.h, lib/Partitioner/Partitioner.cpp, lib/Partitioner/PartitionerUtils.cpp
*Description*:
When I run a testcase for several times, I found the final partitions of each run could be a little bit different. It was caused by the sequence of the nodes of each BFS levels (The key of the map we used is a pointer, which could be different value for each run. ) Therefore, to make sure the results are consistent for each run, I would like to add a sort for each level.
*Testing*:
unittest.
=> [Partitioner] Fix a BFS issue.

examples/resnet-concurrent.cpp, examples/tracing-compare.cpp, include/glow/Backends/Backend.h, include/glow/Backends/CompilationOptions.h, include/glow/ExecutionEngine/ExecutionEngine.h, include/glow/Optimizer/Optimizer.h, lib/Backends/Backend.cpp, lib/Backends/CPU/CMakeLists.txt, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/CPU/Transforms.cpp, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/Backends/OpenCL/Transforms.cpp, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Runtime/HostManager/HostManager.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/DeviceManagerTest.cpp, tests/unittests/QuantizationTest.cpp, tests/unittests/TraceEventsTest.cpp, tools/loader/Loader.cpp
*Description*: As a follow up #2451, push the CompileOptions struct down into the Optimize functions as well for future expansion of optimization configuration. I kept the existing CompilationMode function to ease transition.
*Testing*: unit tests, w/ ASAN.
This changes the Backend interface and will require updating any new backends.
=> Refactor optimize() functions to take a CompileOptions

lib/Onnxifi/Base.cpp
*Description*:
Graphs should go through transformPostLowering in checkGraphCompatibility because this is what will happen in initNet
*Testing*:
ninja check
Fixes #2190
=> [Easy] Add transformPostLowering call to checkGraphCompatibility

lib/Quantization/Quantization.cpp, tests/unittests/QuantizationTest.cpp
*Description*: After https://github.com/pytorch/glow/pull/2417, Select no longer was quantized correctly, as it no longer has all float inputs.
*Testing*: Added a new test.
=> [Quantization] Correctly quantize Select

docs/Backends.md, include/glow/Backends/Backend.h, include/glow/ExecutionEngine/ExecutionEngine.h, include/glow/Graph/Node.h, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/CPUBackend.h, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/Interpreter.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Nodes.cpp, lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, lib/Quantization/Quantization.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/QuantizationTest.cpp
*Description*: This PR redesigns `isOpSupported()` to allow a backend to specify what ops it supports based on the input and output types of Nodes. It updates all of the open source backends we have.
*Testing*: All tests are passing. I've also done my best to make sure bigger tests (e.g. those in `tests/images/run.sh`) also still work.
*Documentation*: Updated.
Fixes https://github.com/pytorch/glow/issues/2194
=> Redesign isOpSupported()

lib/ExecutionEngine/ExecutionEngine.cpp
This commit modifies `ExecutionEngine` to initialize the `DeviceManager`
instance that it creates in `ExecutionEngine::setBackend`. This code has
been working so far because this method is a no-op for
`CPUDeviceManager` and `InterpreterDeviceManager`. This may not be the
case for other `DeviceManagers`.
**Testing**
All tests pass.
=> [ExecutionEngine] Initialize DeviceManager instance in setBackend

include/glow/Backends/CompiledFunction.h, lib/Backends/CMakeLists.txt, lib/Backends/CompiledFunction.cpp, tests/unittests/CMakeLists.txt
*Description*:
`Backends` shouldn't depend on `Backend` and it's doing so makes it easy to add a cyclic dependencies when adding static functions to backends.
Also move `CompiledFunction` methods that depend on other symbols in `Backend` target to cpp file.
*Testing*:
CI
None
=> Remove Backends dependency on Backend

lib/Backends/OpenCL/OpenCLDeviceManager.cpp, lib/Runtime/Provisioner/Provisioner.cpp
*Description*: Fixed provisioner not updating node->deviceId, and fixed opencl device manager not collecting constants properly
*Testing*: ninja test and resnet-runtime
=> Fix resnet-runtime when using opencl

lib/Backends/OpenCL/OpenCLDeviceManager.cpp, lib/Backends/OpenCL/OpenCLDeviceManager.h, lib/Runtime/HostManager/HostManager.cpp
*Description*: Moved OpenCLDeviceManager initialization from ctor to init.
Added call to deviceManager->init to HostManager.
*Testing*: ninja all passes and resnet-runtime when using opencl passes
Fixes #2439
=> Moved OpenCLDeviceManager initialization from ctor to init.

tests/unittests/OperatorTest.cpp
*Description*:
What we'd need is to specific backends that each test case is enabled for, however, GTEST is incapable of parameterizing each test case separately since GTEST's parameterization only works per harness.
We could create a new harness for a test case to achieve that, but it's too verbose. This diff proposes a compromise:
We put all test cases under a single harness instantiated for all possible backends -- as a result all test cases will be running for all backends. To whitelist specific backends for each specific test case, ENABLED_BACKENDS(backend1, backend2, ...) is used as a guard for each test to enable it only for specific backends.
*Testing*:
Ran OperationTest to see it passes.
Fixes #2170
Please see a detailed explanation of how to fill out the fields …
=> [unittests] Enable each test case for specific backends in OperatorTest.cpp.

include/glow/Partitioner/Partitioner.h, include/glow/Runtime/RuntimeTypes.h, lib/Partitioner/Partitioner.cpp, tests/unittests/PartitionerTest.cpp
The PR adds cost functions in terms of compute and memory bandwidth costs so that later stages in partitioning can use them. 
*Testing*:
Add a test with manually computed bounds into PartitionerTest.
The PR adds a field to the Partitioner class: ComputeTimeMapTy computeTime_ in Partitioner.h. It adds a function to fill out these fields. 
The field is a map from each Node in the Function being partitioned to the corresponding roofline for the op. This roofline is computed as the max of compute time, and the SRAM/DRAM read+write times for the inputs and outputs of the node. In order to compute these rooflines, fields have been added to DeviceInfo struct in RuntimeTypes.h
The PR is related to Graph Partitioning #2298
=> [Partitioner] Add cost functions to partitioner

lib/LLVMIRCodeGen/FunctionSpecializer.cpp
If a non-specialized call is replaced by a specialized call and the original call produces a value, all uses of this return value should be replaced by the return value of the specialized call.
Detected by building Glow with a debug version of LLVM.
=> [function-specializer] Fix a bug related to the removal of non-specialized calls

include/glow/Base/Type.h, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/OpenCL/OpenCL.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/CMakeLists.txt, tests/unittests/OperatorTest.cpp
*Description*: Some of our unit tests were executing a graph that included both fp32 and reduced precision nodes on the backend to compare their execution. However, not all backends support fp32. 
This PR refactors `compareAgainstInterpreter()` to support executing a graph on both the Interpreter and some other backend, including profiling if we need to quantize, and comparing the results.
This should simplify adding tests for new operators into the future, as you only need to specify the fp32 graph, and then can call into `compareAgainstInterpreter()` to get comparisons of that graph in any precision desired and compared to any backend desired.
*Testing*: Updated all unittests that are listed in https://github.com/pytorch/glow/issues/2396. This included adjusting some allowed errors …
=> [unittests] Refactor reduced precision tests to prevent backends from needing to execute fp32

docs/Optimizations.md, include/glow/Graph/Graph.h, include/glow/Importer/CommonOperatorLoader.h, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Optimizer/Lower.cpp, tests/models/onnxModels/reduceMean2AvgPool.onnxtxt, tests/models/onnxModels/reduceMean2AvgPoolNoKeep.onnxtxt, tests/models/onnxModels/reduceMean4Dto3D.onnxtxt, tests/models/onnxModels/reduceMean4Dto4D.onnxtxt, tests/models/onnxModels/reduceSum4D.onnxtxt, tests/unittests/GraphOptzTest.cpp, tests/unittests/OnnxImporterTest.cpp, tests/unittests/OperatorTest.cpp, tools/ClassGen/NodeGen.cpp
`reduceMeanOrSum`  Importer function is split into into `reduceSum` and `reduceMean`. `reduceMean` is not lowered in Importer but in Optimizer. `reduceMean` is also optimized with `AvgPool` node if the reduce parameters are suitable:  input is 4D, last two dimensions are reduced, `keepdims=true`. 
*Testing*: 
OnnxImporterTest:  Add 4 reduce* testcases that run 4 newly added `reduce*.onnxtxt` models.
GraphOptzTest: Add a testcase that covers ReduceMean substitution with AvgPool.
OperatorTest: Add testcases that covered both optimized and lowered ReduceMean transformations.
*Documentation*: 
Updated Optimizations.md
Fixes #2343
=> Lower ReduceMean in Lower or optimize with AvgPool when possible.

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCLDeviceManager.cpp, lib/CodeGen/MemoryAllocator.cpp, lib/IR/ChildMemSizeBasedScheduler.cpp, lib/LLVMIRCodeGen/AllocationsInfo.cpp, lib/LLVMIRCodeGen/BundleSaver.cpp, lib/LLVMIRCodeGen/FunctionSpecializer.cpp, lib/Optimizer/IROptimizer.cpp
*Description*: Some llvm headers #undef this macro, which leads to undefined symbol errors.  It's safer to #define it after all the other #includes.
*Testing*: build with an fb-internal platform where the issue repros.
=> Move DEBUG_TYPE after #includes

include/glow/LLVMIRCodeGen/LLVMIRGen.h, lib/LLVMIRCodeGen/LLVMIRGen.cpp
*Description*:
[LLVMIRGen] Use TargetMachine for sizeof(size_t).  Start moving LLVMIRGen to be more cross-compiler friendly.
*Testing*:
ninja check
None
=> [LLVMIRGen] Use TargetMachine for sizeof(size_t).

tests/unittests/OperatorTest.cpp
*Description*: Small fix to build in VS. It had issues with #ifdef within macro.
*Testing*:
=> Minor fix for VS. Didn't like ifdef within macro.

tests/unittests/CMakeLists.txt
Forgot to include all necessary libs for BackendTestUtils in https://github.com/pytorch/glow/pull/2474. Don't know why this is breaking locally on Mac but not on the CI shared build...
=> [unbreak][unittests] Fix shared build for BackendTestUtils

include/glow/Partitioner/Partitioner.h, include/glow/Runtime/HostManager/HostManager.h, include/glow/Runtime/Provisioner/Provisioner.h, include/glow/Runtime/RuntimeTypes.h, lib/Partitioner/Partitioner.cpp, lib/Runtime/HostManager/HostManager.cpp, lib/Runtime/Provisioner/Provisioner.cpp, tests/unittests/PartitionerTest.cpp, tests/unittests/ProvisionerTest.cpp
*Description*:
This PR refactors DAGNodeList, which is used in Partitioner, Provisioner and HostManager. The discussion can be found in https://github.com/pytorch/glow/issues/2353
*Testing*:
[Optional Fixes #2353]
=> [Runtime] Refactor DAGNodeList

tests/CMakeLists.txt, tests/examples_tests/resnet-concurrent-test.sh, tests/examples_tests/resnet-runtime-test.sh
*Description*:
Add EXPENSIVE tests to run resnet-runtime and resnet-concurrent examples in CI.
*Testing*:
`ninja check_expensive`
Comments
fixes #2493
=> Add resnet examples to EXPENSIVE tests

tests/unittests/OperatorTest.cpp
A couple fixes due to https://github.com/pytorch/glow/commit/6a909023ec8a695fe955c50de18a2cb853cf8355
1st commit: Accidentally dropped `BasicAddNetFloatVsInt16` 
2nd commit: Increase allowed error threshold for a few tests failing on private backend. Due to differences in quantization implementation.
=> [OperatorTest] A couple assorted fixes required from recent refactor

tests/CMakeLists.txt
*Description*:
as title
*Testing*:
`ninja check_expensive`
none
=> Disable runtime OutputCheck tests

include/glow/Importer/CommonOperatorLoader.h, lib/Importer/Caffe2ModelLoader.cpp
*Description*: For now, support loading uint8 types into `Int8QTy`. We load with a dummy scale and offset; this is currently only used for rowwise-quantized data, where we already use a dummy scale and offset.
*Testing*: This enables some internal tests to pass.
=> Add support for ONNXIFI_DATATYPE_UINT8 and caffe2::TensorProto::UINT8

lib/Graph/Graph.cpp, tests/unittests/OperatorTest.cpp
*Description*: Allow for reduction down to zero-dim tensor (scalar). https://github.com/pytorch/glow/pull/2465 changed an assert that disallowed this.
*Testing*: Added missing unit test.
=> [Graph] Allow reduction down to zero-dim tensor

examples/resnet-concurrent.cpp, examples/resnet-runtime.cpp, examples/tracing-compare.cpp, include/glow/Backends/DeviceManager.h, include/glow/Backends/DummyDeviceManager.h, include/glow/Backends/QueueBackedDeviceManager.h, include/glow/Runtime/HostManager/HostManager.h, include/glow/Runtime/RuntimeTypes.h, include/glow/Support/Error.h, lib/Backends/CPU/CPUDeviceManager.cpp, lib/Backends/Interpreter/InterpreterDeviceManager.cpp, lib/Backends/OpenCL/OpenCLDeviceManager.cpp, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Runtime/Executor/ThreadPoolExecutor.cpp, lib/Runtime/Executor/ThreadPoolExecutor.h, lib/Runtime/HostManager/HostManager.cpp, lib/Support/Error.cpp, tests/unittests/DeviceManagerTest.cpp, tests/unittests/ExecutorTest.cpp, tests/unittests/HostManagerTest.cpp, tests/unittests/OnnxImporterTest.cpp, tests/unittests/ProvisionerTest.cpp
*Description*:
Finish migration from `ErrorCode` to `GlowErr` in Glow runtime. The last step was migrating `ResultCBTy` to include an `llvm::Error` which meant some changes to the state that `Executor` maintains per-run.
*Testing*:
`Ninja check`
Run `resnet-runtime` example binary.
Comments
=> Replace ErrorCode with GlowErrs

docs/Quantization.md, include/glow/Base/Tensor.h, lib/Quantization/Base/Base.cpp, lib/Quantization/Quantization.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/QuantizationTest.cpp
*Description*: Previously rowwise-quantized SLWS was only enabled by directly loading it as quantized. This allows for rowwise-quantizing it through our normal profile + quantization flow.
*Testing*: Added two unit tests; tested on other private models.
*Documentation*: Updated.
=> [Quantization] Add support for fused rowwise-quantizing SLWS

include/glow/Runtime/RuntimeTypes.h, lib/Partitioner/Partitioner.cpp
*Description*: VS doesn't like explicit initialization of nodes, and reports build failure. This should accomplish the same thing.
*Testing*:
=> Minor build fix for VS.

lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/fcTransposed_4d_init_net.pbtxt, tests/models/caffe2Models/fcTransposed_4d_predict_net.pbtxt, tests/models/caffe2Models/fc_4d_init_net.pbtxt, tests/models/caffe2Models/fc_4d_predict_net.pbtxt, tests/unittests/Caffe2ImporterTest.cpp
*Description*:
We need to match the behavior of Caffe2. When number of input dimensions to FC is greater than 2, Glow flattens down to 2 dimensions using axis but does not reshape the output back to original dimensions before the axis.
*Testing*:
Create a new C2 Graph and test that the output shape is the expected shape.
Fixes #2522
=> Resize output of FC with dims > 2

docs/Backends.md, include/glow/Backends/Backend.h, tests/unittests/BackendTest.cpp
*Description*: Added new compileFunctions method which takes an ArrayRef of functions and returns a vector of compiledFunctions. This allows the compile to reason over shared constants between functions. Also added a new unittest and updated backends.md
*Documentation*: Updated backends.md
Related to #2045
=> Added new compileFunctions method

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h
*Description*: As we did with the CPU and Interpreter backend, removing the requirement of calling setupRuns, beforeRuns, afterRuns and tearDownRuns in the OpenCL backend by moving their logic into `execute()`. This is the first step in making OpenCLFunction stateless, but we still need to move the buffers and kernelLaunch vector into DeviceBindings.
*Testing*: unit tests.
*Documentation*: Requires no change to calling code (although we could remove the unnecessary calls to the removed methods).
=> Remove OpenCLFunction dependence on old stateful execute scheme.

tests/unittests/Caffe2ImporterTest.cpp, tests/unittests/OperatorTest.cpp
*Description*: I noticed some gaps we had in testing ops in `OperatorTest`:
- There was no `BatchBoxCox` operator test, so I added one. I also added a commit here to remove the functional correctness from the `Caffe2ImporterTest`, which I stole the logic from for the `OperatorTest`, since the `Caffe2ImporterTest` wasn't loading any data anyway.
- There were no tests for `Mul`/`Div`/`Sub`. There were also two tests for `Max`. I bundled them all up into a single macro.
*Testing*: That's all there is...
=> [unittests] Cleanup/fill in assorted gaps

include/glow/Backends/BackendUtils.h, lib/Backends/BackendUtils.cpp
*Description*: changed RuntimeBundle's getSymbolInfo to now return a const reference. 
*Testing*: ninja test passes
=> getSymbolInfo now returns a const reference

include/glow/Base/Type.h, include/glow/Graph/Graph.h, include/glow/Graph/Nodes.h, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, tests/unittests/ConvTest.cpp, tests/unittests/GraphTest.cpp, tests/unittests/OperatorTest.cpp
*Description*:
3D convolution implementation for interpreter backend (quantized and non-quantized).
Next steps include: CPU implementation, import conv3D in c2 model loader, implement backwards passes
*Testing*:
New unit tests added. Some reference outputs are computed in test when easy to do so, the others are from convolution computed by hand.
Comments in code
=> Conv3d on interpreter

include/glow/Partitioner/Partitioner.h, include/glow/Partitioner/PartitionerUtils.h, include/glow/Runtime/RuntimeTypes.h, lib/Partitioner/Partitioner.cpp, lib/Partitioner/PartitionerUtils.cpp
*Description*:
Use uint64_t to replace size_t everywhere for memory size type since it's guaranteed to be a 64 bit int. size_t will in practice always be 64 bit but it could be different if we run on a different architecture.
*Testing*:
ninja check, resnet-runtime
=> [Runtime] Use uint64_t for memory size type

lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, tests/unittests/OperatorTest.cpp
*Description*: Add Interpreter support for `ConvertTo` to cast from `Int64ITy` to `FloatTy` and vice versa.
*Testing*: Added new unit tests, and merged other tests in to use cleaner test helper.
=> Add ConvertTo support for Int64ITy <-> FloatTy

include/glow/LLVMIRCodeGen/GlowJIT.h, lib/LLVMIRCodeGen/DebugInfo.cpp, lib/LLVMIRCodeGen/GlowJIT.cpp
*Description*: Some minor fixes to get the master to build against the current LLVM 8.0 release branch.
*Testing*: Similar unit test results than with 7.0. Runs at least the MNIST example network. CIFAR10 still running.
=> [llvm] A few fixes to build against LLVM 8.0.

lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, tests/unittests/OperatorTest.cpp
*Description*: Add support for BatchOneHot for `Int32ITy`, and then add tests for all the types we currently support.
*Testing*: Added unit tests for all types.
=> Add support for Int32ITy BatchOneHot, and add missing unit tests for all types

examples/resnet-concurrent.cpp, examples/tracing-compare.cpp, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Runtime/Provisioner/Provisioner.cpp, tests/unittests/ExecutorTest.cpp
*Description*: On Windows the LLVM JIT doesn't always work when executed on a different thread than the compile (see discussion in #2460). Until we work out how to fix that, just have windows build run unit tests in the DummyDeviceManager.
*Testing*: unit tests when forcing the ExecutionEngine through both branches.
cc @ayermolo
=> [Win32] Remove std::promise<llvm::Error>

include/glow/LLVMIRCodeGen/LLVMBackend.h, include/glow/LLVMIRCodeGen/LLVMIRGen.h, lib/LLVMIRCodeGen/BundleSaver.cpp, lib/LLVMIRCodeGen/FunctionSpecializer.cpp, lib/LLVMIRCodeGen/LLVMBackend.cpp, lib/LLVMIRCodeGen/LLVMIRGen.cpp
This allows for redefinition of createCall by backends, which can be very useful if there is a need to e.g. add custom run-time processing for each call (e.g. logging the names of all functions being called).
=> Make createCall a method in LLVMIRGen

include/glow/Runtime/HostManager/HostManager.h, lib/Backends/CPU/CPUDeviceManager.h, lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, lib/Onnxifi/CMakeLists.txt, lib/Onnxifi/GlowOnnxifiManager.cpp, lib/Onnxifi/GlowOnnxifiManager.h, lib/Onnxifi/onnxifiGlow.cpp, lib/Runtime/HostManager/HostManager.cpp, tests/onnxifi/test.sh, tests/unittests/GlowOnnxifiManagerTest.cpp
*Description*:
Replace `ExecutionEngine` with `HostManager` for Onnxifi.
Clean up ownership of tensors by `Context`
`GlowOnnxifiManager` manages HostManagers, creating at most one `HostManager` for each `BackendKind` and sharing this between `onnxifi::BackendId`s that use the same kind.
Next steps after this pr include removing `glow::Backend` from `onnxifi::BackendId`, this isn't yet possible though because this is needed for compatibility checks. Once the required functions are made static we can remove this.
*Testing*:
`ninja check`
Will run c2 tests later
Code comments
=> Use HostManager for ONNXIFI

tests/unittests/OperatorTest.cpp
Added a few more tests that we didn't have for `Gather`/`GatherRanges`:
- `Gather` now has Int8 and Float16 data versions
- `GatherRanges` now has Float and Float16 data tests.
=> [OperatorTest] More missing tests for Gather/GatherRanges

lib/Backends/CMakeLists.txt, lib/Backends/CPU/CMakeLists.txt, lib/Backends/Interpreter/CMakeLists.txt, lib/Backends/OpenCL/CMakeLists.txt
*Description*:
Move backend and device manager additions to the corresponding backend dirs.
Autodiscovery of backend.
*Testing*:
CI
n/a
Addressing some @opti-mix offline comments.
=> [Backends] Autodiscovery of registered backends. Minimize changes in Backend CMake.

tests/CMakeLists.txt
*Description*:
This was previously having sporadic issues, it was likely due to image folder not being specified which is fixed now so hopefully this works.
*Testing*:
`ninja check_expensive`
=> Re-enable runtime ci checks

include/glow/Support/Support.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Graph/Graph.cpp, lib/Support/Support.cpp, tests/models/caffe2Models/predict_net.pbtxt, tests/unittests/Caffe2ImporterTest.cpp, tests/unittests/SupportTest.cpp
*Description*:
Since one placeholder's name will be legalized before registration, when we update one placeholder by name, the name should be processed in the same way. Otherwise, finding the placeholder may be failed.
*Testing*:
unittest.
[Optional Fixes #2565]
=> [test] Legalize a name when the placeholer is updated by name.

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, tests/unittests/OperatorTest.cpp
We have many operators which are not being tested with different ElemKinds -- most gaps in fp16/int8. I tried to address many of the gaps here, reusing the existing logic for the test as much as possible.
=> [OperatorTests] Fill in many missing tests across various ElemKinds

lib/Backends/CPU/libjit/libjit.cpp
Now CPU backend should be able to print results correctly on quantized resnext, which will help with issue #2581
=> [CPU backend] Fix dump_tensor in libjit.

lib/Backends/OpenCL/OpenCL.cpp, lib/LLVMIRCodeGen/LLVMCompiledFunction.cpp, tests/unittests/BackendTest.cpp
*Description*: The way we load placeholders right now assumes that all CompiledFunctions know about all symbols in the module (at least when we use `PlaceholderBindings.allocate(module.getPlaceholders())` which we do in a few different places). When loading placeholders we should just skip any that don't have an entry in the symbol table (since they won't be used anyway).
*Testing*: unit tests + the new unit test, which fails on all backends without this change.
*Documentation*: This won't break anything in any other backends, but they probably want to be doing something like this as well.
=> Skip unknown symbols when loading Placeholders.

.gitmodules, CMakeLists.txt, tests/benchmark/CMakeLists.txt, tests/benchmark/DeviceManagerBench.cpp
This commit adds the Google benchmark library as a submodule to the Glow
project for use in runtime microbenchmarks.
**Testing**
This commit adds a stub for DeviceManager benchmarks to make sure that
the submodule is set up properly:
```
$ ./tests/DeviceManagerBench 
2019-03-25 16:12:46
Running ./tests/DeviceManagerBench
Run on (8 X 3100 MHz CPU s)
CPU Caches:
L1 Data 32K (x4)
L1 Instruction 32K (x4)
L2 Unified 262K (x4)
L3 Unified 8388K (x1)
Load Average: 2.61, 2.65, 2.57
***WARNING*** Library was built as DEBUG. Timings may be affected.
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
--------------------------------------------------------------------- …
```
=> [Benchmarks] Add google benchmark submodule

lib/Backends/Interpreter/InterpreterNodes.cpp
*Description*: Surprisingly, Caffe2 doesn't check this rigorously, which causes some internal integration tests to fail.  Arguably Caffe2 should be stricter, but it doesn't really hurt anything as far as I can tell.
*Testing*: internal test
=> [interp] Loosen checking on SparseLengthsSum lengths

include/glow/Base/Tensor.h, tests/unittests/TensorsTest.cpp
This was missing from when I added `UInt8FusedQTy`.
=> [Tensor] Add randomize() for UInt8FusedQTy

examples/fr2en.cpp, include/glow/Graph/Graph.h, include/glow/Quantization/Base/Base.h, include/glow/Quantization/Quantization.h, lib/Graph/Graph.cpp, lib/Quantization/Quantization.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/MLTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/QuantizationTest.cpp, tools/loader/Loader.cpp
*Description*: Right now schema is hard coded in some of the glow function. Changing to use the command line option. Follow up step can be storing it and loading it from profile to avoid potential issue with profile being created under one quantization and used under another.
*Testing*: UnitTests
=> Added schema parameter to graph

include/glow/Base/Tensor.h, lib/Base/Tensor.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/TensorsTest.cpp
*Description*: While looking at https://github.com/pytorch/glow/pull/2593 I decided Xavier initialization doesn't make sense for non-float ElemKinds. If we want random data for integral ElemKinds just use `randomize()`.
*Testing*: Updated tests.
=> Remove Xavier initialization from non-Float ElemKinds

tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/OperatorTest.cpp
Made the schema a default argument, as most use cases use asymmetric anyway.
Broke due to https://github.com/pytorch/glow/pull/2533
=> [unbreak][unittests] Unbreak due to compareAgainstInterpreter()

lib/LLVMIRCodeGen/LLVMIRGen.cpp
*Description*:
Simple fix described in the title.
*Testing*:
Locally
N/A
=> [LLVMIRGen] add missing support to 16 bit to emitValueAddress

lib/Support/Debug.cpp
The original `-debug-only` in LLVM always had this semantics. This PR follows the LLVM lead and makes the `-debug-glow-only` option more flexible as it allows for using multiple debug types at once.
=> [debugging] Make -debug-glow-only option take a list of comma-separated debug types names

tests/unittests/OperatorTest.cpp
This is for a private backend.
=> [OperatorTest][trivial] Increase error threshold for Basic*NetFloatVsInt8

lib/Backends/Interpreter/CMakeLists.txt, lib/Backends/OpenCL/CMakeLists.txt
*Description*: @rdzhabarov's Backend Registry addition needs extra dependencies in local SHARED build - at least on my machine. The symbol that is missing for the factories is  llvm::DisableABIBreakingChecks but not sure exactly where that gets called.
*Testing*: build & test shared build locally.
=> Fix local shared build

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, lib/Graph/Nodes.cpp, lib/Importer/Caffe2ModelLoader.cpp, lib/Optimizer/Lower.cpp
We were already flattening FC inputs when lowering the FC on open source backends, and when loading FCs in the C2 loader. I basically moved the flattening logic from `lowerFullyConnectedNode()`/the C2 loader for FCs into `createFullyConnected()`, along with allowing for specifying the axis. And then added verification for FC that is has 2D input.
=> Require FC node to have 2D input

include/glow/Base/Tensor.h, lib/Base/Tensor.cpp
*Description*: I use dumpImpl for debugging all the time, and it's really nice to be able to dump arbitrary amounts of the tensor without hunting down this constant in Tensor.cpp and recompiling.
*Testing*: tried it in model-runner
=> [tensor] Allow specifying number of elements in dumpImpl

include/glow/Backends/BackendUtils.h, lib/Backends/BackendUtils.cpp
*Description*: Apparently the runtime (provisioner, I guess?) needs a symbol table to properly set up the placeholders for the partitioned subgraphs.  Since some backends don't use IRFunction we need a way to generate a symbol table for them, hence this diff.
*Testing*: used internally (sorry)
*Documentation*: We should probably add something to Backends.md.
=> [runtime] Build runtime bundle with only Function (no IR)

include/glow/Base/Tensor.h
This static_cast shouldn't have been there; it was causing this assert to always pass.
=> [Tensor] Fix incorrect cast in assert

include/glow/Importer/Caffe2ModelLoader.h, include/glow/Importer/CommonOperatorLoader.h, lib/Importer/Caffe2ModelLoader.cpp, lib/Importer/caffe2.proto
*Description*:
This the onnxifi quantization support in glow side, we accept two quantized tensors, intQ32ty and int8Qty.
*Testing*:
Only internal test is supported now, using resnet50_quantized.
=> add onnxifi quantization support

tools/loader/ImageClassifier.cpp, tools/loader/Loader.cpp, tools/loader/Loader.h
*Description*: People often care about # of images/second more than batches/second,
since the batch size is a tunable parameter.
*Testing*: image-classifier
=> [image-classifier] Report time per image rather than per batch

include/glow/Backends/BackendUtils.h, include/glow/Backends/CompiledFunction.h, include/glow/Runtime/RuntimeTypes.h, lib/Backends/BackendUtils.cpp, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/LLVMIRCodeGen/LLVMBackend.cpp, lib/Runtime/Executor/ThreadPoolExecutor.cpp, lib/Runtime/Provisioner/Provisioner.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/ExecutorTest.cpp
*Description*: I was bitten hard today because the backend I was working on didn't build a RuntimeBundle (because it doesn't need one), and I discovered only through lots of debugging that the Provisioner requires the symbol table from a runtime bundle.  To help prevent others from making this mistake, let's make the illegal state (of a dummy RuntimeBundle hanging out in CompiledFunction) unrepresentable by deleting its default constructor.
I was going to force everything to use the static factory methods, but that got really messy in ExecutorTest so I gave up, and will allow people to shoot themselves in the foot as long as the type RuntimeBundle(SymbolTable(), 0, 0, 0) while doing so.
*Testing*: existing unit tests
Stacked on #2611
=> [runtime] Force RuntimeBundle to be properly constructed

docs/Optimizations.md, lib/Optimizer/GraphOptimizer.cpp, tests/unittests/GraphOptzTest.cpp, tests/unittests/OperatorTest.cpp
*Description*:
`TransposeNode` is optimized into `ReshapeNode` when it moves no data.  This allows for further optimizations. Currently, the algorithm only looks for cases when dimensions of size 1 are shuffled around. 
*Testing*:
GraphOptzTest: Add a testcase that covers `TransposeNode` substitution with `ReshapeNode`.
OperatorTest: Add a testcase that tests if the optimized model is still functionally correct. 
Updated Optimizations.md
Fixes #2629
=> Optimize TransposeNode into ReshapeNode when it moves no data.

examples/tracing-compare.cpp, include/glow/Backends/ExecutionContext.h, include/glow/Backends/QueueBackedDeviceManager.h, include/glow/Backends/TraceEvents.h, lib/Backends/Backend.cpp, lib/Backends/CMakeLists.txt, lib/Backends/CPU/CPUDeviceManager.cpp, lib/Backends/Interpreter/InterpreterDeviceManager.cpp, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/OpenCL/OpenCLDeviceManager.cpp, lib/Backends/TraceEvents.cpp, lib/LLVMIRCodeGen/LLVMCompiledFunction.cpp, tests/unittests/TraceEventsTest.cpp
*Description*: Adds trace events in the three DeviceManager implementations (CPU, Interp, OpenCL) and machinery for collecting trace events inside the runtime. The new events cover enqueueing time vs time in `execute()` and the time to load placeholders onto the device. Not totally sure which events are going to end up being useful to us.
*Testing*: unit tests & the tracing-compare example.
In Chrome trace viewer the new events look like this:
Next step is adding equivalent TraceEvents to the Executor.
=> [Tracing] Add DeviceManager tracing and the TraceContext

examples/resnet-runtime.cpp, include/glow/Graph/Graph.h, include/glow/Runtime/HostManager/HostManager.h, include/glow/Runtime/RuntimeTypes.h, lib/Graph/Graph.cpp, lib/Onnxifi/HostManagerOnnxifi.cpp, lib/Onnxifi/HostManagerOnnxifi.h, lib/Partitioner/Partitioner.cpp, lib/Runtime/HostManager/HostManager.cpp, tests/unittests/HostManagerTest.cpp
*Description*:
Make it so that HostManager and runtime owns the Module. HostManager will take ownership of Module in `addNetwork` and keeps the PlaceHolders around internally.
*Testing*:
`ninja check`
Run resnet-runtime example
comments
Fixes #2567
=> Pass ownership of Module to HostManager

examples/fr2en.cpp, include/glow/Quantization/Quantization.h, lib/Onnxifi/InlineOnnxifi.cpp, lib/Quantization/CMakeLists.txt, lib/Quantization/Quantization.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/GradCheckTest.cpp, tests/unittests/HyphenTest.cpp, tests/unittests/MLTest.cpp, tests/unittests/QuantizationTest.cpp, tools/loader/Loader.cpp
This allows the Quantizer to depend on Backend instead of ExecutionEngine.
=> Provide Backend instead of EE to Quantizer

examples/tracing-compare.cpp, include/glow/Backends/TraceEvents.h, lib/Backends/Backend.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/Backends/OpenCL/kernels.cl, tests/unittests/TraceEventsTest.cpp
*Description*: Adds both auto instrumentation and manual TraceEvents for the OpenCL backend. This builds on the existing profiling support leaving it unchanged (ie. `-opencl-profile` still works).
OpenCL has a bit of concurrency in its execution, e.g. below you can see the enqueueKernels stage overlapping with the execution of early kernels in the run. We could model this as separate threads in the future but not worrying too much about how it looks yet.
*Testing*: unit tests (particularly TraceEventTests)+ the tracing-compare example.
looks like this"
=> [tracing] Add TraceEvent support for OpenCL

include/glow/Graph/Graph.h, include/glow/IR/IR.h, lib/Backends/Backend.cpp, lib/Backends/BackendUtils.cpp, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Graph/Graph.cpp, lib/IR/GraphScheduler.cpp, lib/IR/IR.cpp, lib/LLVMIRCodeGen/AllocationsInfo.cpp, lib/LLVMIRCodeGen/BundleSaver.cpp, lib/LLVMIRCodeGen/LLVMIRGen.cpp, tests/unittests/BackendTest.cpp
*Description*: This PR modifies compilation to no longer check all placeholders/constants in the module. It now uses symbols that are associated with the function being compiled. 
*Testing*: ninja test and check_expensive pass
*Documentation*:  NA
Fixes #2548
=> Modify compilation to only use function symbols

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp
We generally take operands as `NodeValue`s in such node creation functions. These functions are pretty old and were never converted to use this style.
=> Take NodeValue instead of Node * as arguments for createFullyConnected functions

lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Backends/OpenCL/OpenCL.cpp
*Description*: The TraceEvent format expects usec not msec, adjusting the domain of auto instrumentation timestamps.
*Testing*: sanity unittests & the tracing-compare example
=> [tracing] Convert all TraceEvent timestamps to microseconds.

lib/Optimizer/GraphOptimizer.cpp, tests/unittests/GraphOptzTest.cpp
*Description*:
This might be a controversial change but before https://github.com/pytorch/glow/issues/1641 in place there is no easy way to disable opts per backend.
Many HW backends would benefit from disabling this optimization.
Pros:
1) Sinking Relu below MaxPool might only have benefits in case of buffer sharing is done which potentially have some memory benefit. (We could pass shouldShareBuffers in optimization pass but I'd like to avoid it).
Cons:
1) This eliminates fusion opportunities with convolution as it's typical sequence of conv->relu->pool.
Many HW has fusion of conv + relu.
2) Swapping ops has negative effect on quantization accuracy.
Ideal scenario is having per backend optimizations as described in the https://github.com/pytorch/glow/issues/1641.
*Testing*:
Unit tests. …
=> [optimizer] Remove optimize pool optimization.

lib/Quantization/Quantization.cpp, tests/unittests/QuantizationTest.cpp
*Description*:
Semantically it does not make sense to have non 0 offset for quantized int32 (any value can be covered by int32 itself).
Also, from performance standpoint it's beneficial to have 0 offset.  
*Testing*:
CI
n/a
=> [quantization] Keep 0 offset for int32 fc and conv.

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/Backends/OpenCL/OpenCLDeviceManager.cpp, lib/Backends/OpenCL/OpenCLDeviceManager.h, tests/unittests/BackendTest.cpp
*Description*: Added support for DeviceBindings to the OpenCL implementation and migrated to use them for memory buffers and CL device information. This moves allocation out of the execute method. The compiledFunction is still not thread safe, it currently uses member variables to pass state it will require this to change #2651 .
=> Added openCLDeviceBindings and moved OpenCLCompiledFunction to use them.

lib/LLVMIRCodeGen/BundleSaver.cpp, lib/LLVMIRCodeGen/CommandLine.cpp, lib/LLVMIRCodeGen/CommandLine.h
Add new command-line options:
*  `-llvm-compiler` specifies the which compiler binary should be run (path)
* `-llvm-compiler-opt` specify options to be passed to the external compiler.
Testing:
```
#Compile ResNet50 bundle using an external LLVM compiler.
bin/image-classifier tests/images/imagenet/*.png  -image-mode=0to1 \
-m=resnet50 -model-input-name=gpu_0/data -emit-bundle . \
-cpu -llvm-compiler /usr/local/opt/llvm/bin/llc
```
Fixes #2636
=> [LLVMIRCodeGen] Support using an external LLVM compiler for converting LLVM bitcode files into object files

examples/resnet-runtime.cpp, include/glow/Backends/Backend.h, include/glow/Runtime/HostManager/HostManager.h, include/glow/Runtime/RuntimeTypes.h, lib/Backends/CPU/CPUBackend.h, lib/Backends/Habana/Habana.h, lib/Backends/Interpreter/Interpreter.h, lib/Backends/OpenCL/OpenCL.h, lib/Onnxifi/HostManagerOnnxifi.cpp, lib/Runtime/HostManager/HostManager.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/HostManagerTest.cpp, tests/unittests/QuantizationTest.cpp
*Description*: We currently have two structs for configuring devices: DeviceManagerConfig (used by the HostManager) and DeviceConfig (used by the DeviceManager). This is unnecessary and confusing, so removing DeviceManagerConfig and plumbing DeviceConfig all the way through.
Also, added a `getBackendName()` to get a string name for a device which can be used for logging and, in the next PR, used to generate the trace log.
*Testing*: unit tests, asan, etc
*Documentation*: This is a breaking change for Backends which need to implement the `getBackendName()` method.
=> Commonalize DeviceManagerConfig and DeviceConfig

lib/Partitioner/Partitioner.cpp
*Description*:
When the Partitioner was created, I assumed one Node only has one output when creating the intermediate ph,  which is wrong.  Eg. TopK has 2 outputs and we need to know which one should be used when creating the intermediate ph during partitioning. This PR fixed this part.
*Testing*:
Existing tests. 
I wrote a runtime e2e test using En2gr model, which is used to test this PR as well. The testcase will be added later. 
* Documentation*:
=> [Partitioner] Create the intermediate ph based on the NodeValue in case that one node can has more than 1 output.

examples/CMakeLists.txt, examples/resnet-runtime.cpp, include/glow/Backends/QueueBackedDeviceManager.h, include/glow/Backends/TraceEvents.h, lib/Backends/CPU/CPUDeviceManager.cpp, lib/Backends/Interpreter/InterpreterDeviceManager.cpp, lib/Backends/OpenCL/OpenCLDeviceManager.cpp, lib/Backends/TraceEvents.cpp, lib/LLVMIRCodeGen/LLVMCompiledFunction.cpp, lib/Runtime/Executor/CMakeLists.txt, lib/Runtime/Executor/ThreadPoolExecutor.cpp, lib/Runtime/Executor/ThreadPoolExecutor.h, lib/Runtime/HostManager/HostManager.cpp, tests/examples_tests/resnet-runtime-test.sh
*Description*: Adds some simple events in the Executor and the HostManager and adds the plumbing to enable tracing and retrieve TraceEvents (auto instrumentation is not yet supported).
Also fix a couple bugs, particularly we now export timestamps in the right domain. Next steps are to improve the process and thread labels and look at showing thread movement flow.
We treat the whole runtime as a monolithic "thread" even though it has several. Uncertain if we get much from modeling internal threads in the runtime here, open to opinions.
*Testing*: unittests with asan & the upgraded resnet-runtime example 
Here's the output of the resnet-runtime example with tracing enabled (6 CPU devices, 100 images):
Thread #50 is a placeholder for the Runtime threads in this example. You …
=> [tracing] Add TraceEvents into the Runtime Execution Engine

lib/Optimizer/GraphOptimizer.cpp, tests/unittests/GraphOptzTest.cpp
_Description:_
#2630 is incomplete as it doesn't execute DCE after the optimization. DCE is needed to remove old uses, that prohibit other optimizations, e.g. Reshape(Constant) one.
_Testing:_
GraphOptzTest: Add a testcase that tests for Reshape(Constant) w/  Transpose2Reshape optimizations, effectively failing on the current code base.
Fixes #2629
=> For Transpose2Reshape optimization make sure DCE is executed.

cmake/modules/CoverageSupport.cmake
*Description*: Adds the `-V` flag to the test invocation in the coverage target, which means we can debug issues found in the GCC regression test.
*Testing*: Look at the coverage target in travis below.
Fixes #2677
=> Add verbose flag to tests in the coverage target

include/glow/Graph/Node.h, lib/Backends/CPU/CPUBackend.cpp, lib/Backends/Interpreter/Interpreter.cpp, lib/Optimizer/Lower.cpp, lib/Quantization/Quantization.cpp, tests/unittests/QuantizationTest.cpp
*Description*: This was previously done during lowering (i.e. quantize these nodes and then later lower them to IntLookupTables), but it was kind of a hack and required a backend to report that it supported these nodes as quantized even though it really only supported them as IntLookTables.
*Testing*: Added two missing unit tests. All other unit tests pass. Also tested on en2gr.
=> Replace Quantized Log/Sigmoid/Tanh by IntLookupTable in Quantizer

include/glow/Optimizer/Optimizer.h, lib/Optimizer/GraphOptimizer.cpp, tests/unittests/GraphOptzTest.cpp, tools/loader/Loader.cpp
*Description*:
1) Added partial support for LeakyRelu:
- LeakyRelu Node in the IR
- LeakyRelu lowering for CPU/interpreter backends
2) Added an optimization to fold Max(Mul(Constant, A), A) to LeakyRelu (We've got some model where LeakyRelu is expressed this way).
From this PR, implementing LeakyRelu in importers will be simple for the day someone encounters directly the LeakyRelu operator in an ONNX or Caffe2 model.
For information, here is the ONNX LeakyRelu description:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#LeakyRelu
*Testing*:
- Test node creation and lowering
- Test the folding optim
=> Add partial support for LeakyRelu via "folding"

include/glow/Partitioner/Partitioner.h, lib/Partitioner/Partitioner.cpp, lib/Runtime/HostManager/HostManager.cpp, lib/Runtime/Provisioner/Provisioner.cpp, tests/unittests/PartitionerTest.cpp
*Description*:
If the number of devices is fewer than the number of partitions, we used to let Provisioner to report this error. Now we move the error detection into Partitioner.  If a proper partition can't be found, an error is reported.
Testing*:
Added unittest.
[Optional Fixes #2661 ]
=> [Partitioner] If a proper partition is not found, return an error.

lib/Backends/Habana/Habana.cpp, tests/unittests/HabanaBackendTest.cpp
Summary: Add support for non 0 offset for quantized ops.
Differential Revision: D14808564
=> [habana] Support non 0 quantized offset

include/glow/Backends/DeviceManager.h, lib/Runtime/HostManager/HostManager.cpp
Summary: Passing nullptr here is kind of brittle; it assumes that the backend's
DeviceManager is aware of the contract that "nullptr" here means "provide a
default behavior".  Instead, let's just provide a NOP callback.  The DM is
always free to log (or not) as it sees fit.
Test Plan: A bit hard to test, but if you remove the default behavior from
CPUDeviceManager and run resnet-runtime, you'll get a runtime failure.
Fixes #2681
=> [runtime] Use default eviction callback in HostManager

lib/Backends/Habana/Habana.cpp
Summary:
The graph is no longer available at run time.  Use the saved I/O lists
to determine what tensors to enqueue.
Differential Revision: D14816918
=> [habana] Enqueue based on saved input/output lists

examples/resnet-runtime.cpp, include/glow/Backends/DeviceManager.h, include/glow/Backends/TraceEvents.h, include/glow/Runtime/RuntimeTypes.h, lib/Backends/TraceEvents.cpp, lib/Runtime/Executor/ThreadPoolExecutor.cpp, lib/Runtime/HostManager/HostManager.cpp
*Description*: Allow setting the name of threads and the process in the tracing output. This is managed by a map of integer thread id to string name in the TraceContext.
*Testing*: unittests & resnet-runtime example.
=> [tracing] Add human readable trace thread names

lib/Backends/CPU/libjit/libjit.cpp, lib/Base/Image.cpp, lib/Graph/Graph.cpp, lib/LLVMIRCodeGen/LLVMIRGen.cpp, tools/loader/ImageClassifier.cpp
If we want to perform the quantization profile generation on many images. The batch size (which corresponds to number of images passed as parameter) becomes too large and Glow requires a too huge amount of memory. This PR allows to (partially) decouple the image list and the batch size. In such a way, quantization profile generation can be performed on a very large number of images.
Content of this PR:
- new `-minibatch` option that specifies the batch size to be used for the compilation
- Bug fix in the implementation of the `QuantizationProfile` node in libjit. On the contrary to the Interpreter implementation, it was not 'accumulating' profile results across successive inference runs.
- Bug fix in the initialization of `QuantizationProfile` min/max values (was I guess …
=> Make quantization profiling scalable

lib/Onnxifi/GlowOnnxifiManager.cpp, lib/Onnxifi/GlowOnnxifiManager.h, lib/Onnxifi/HostManagerOnnxifi.h
*Description*:
This is important for avoiding static destruction order fiasco between DeviceManagers owned by HostManager and device api. It also ensures that HostManagers don't outlive their usefulness and are destroyed when onnxifi destroys all BackendIds.
*Testing*:
synced to internal, all tests pass
updated comments
=> Share HostManagers in onnxifi BackendIds

lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/convrelu_init_net.pbtxt, tests/models/caffe2Models/convrelu_pred_net.pbtxt, tests/unittests/Caffe2ImporterTest.cpp
*Description*:
The ConvRelu is same to Conv or Int8Conv, so just use it directly.
=> Add ConvRelu shape/input info in Caffe2ModelLoader.cpp

lib/Importer/ONNXModelLoader.cpp, tests/models/onnxModels/averagePool2DAutoPadSameLower.onnxtxt, tests/models/onnxModels/averagePool2DAutoPadSameUpper.onnxtxt, tests/models/onnxModels/averagePool2DAutoPadValid.onnxtxt, tests/models/onnxModels/simpleConvAutoPadSameLower.onnxtxt, tests/models/onnxModels/simpleConvAutoPadSameUpper.onnxtxt, tests/models/onnxModels/simpleConvAutoPadValid.onnxtxt, tests/unittests/OnnxImporterTest.cpp
*Description*:
Add support for SAME_UPPER and SAME_LOWER auto_pad modes per the spec at
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Conv
Also applies to AveragePool.
*Testing*:
Added unit tests for VALID/SAME_UPPER/SAME_LOWER.
ninja check
*Issues*:
Related to #2504
=> [OnnxModelLoader] Add SAME_UPPER/SAME_LOWER auto_pad modes.

include/glow/Backends/BackendUtils.h, lib/Backends/BackendUtils.cpp, tests/unittests/BackendTest.cpp
*Description*: This PR adds two new symbol Categories, TensorViewPlaceholder, and TensorViewConstant. This allows us to differentiate between the view and weight.
=> Added TensorView enums to SymbolCategory

lib/Backends/Habana/HabanaDeviceManager.cpp, lib/Backends/Habana/HabanaDeviceManager.h
Summary:
I took this idea from @jackm321, we need to actually estimate
memory or the host manager doesn't work.
Differential Revision: D14816916
=> [habana] Stub getMemInfo

lib/Backends/Habana/HabanaDeviceManager.cpp, lib/Backends/Habana/HabanaDeviceManager.h
Summary: The active topology can't be changed while requests against the old topo are in-flight.  This solution is not perfect since an inactive topo can starve, but at least it does not have that race condition.
Differential Revision: D14819242
=> [habana] Block topo-switching until prior enqueues finished

lib/Backends/CPU/CPUDeviceManager.cpp, lib/Backends/Interpreter/InterpreterDeviceManager.cpp
*Description*: This PR is a quality of life change and adds two new command line options, interpreter-mem and cpu-mem, which set the max memory for the interpreter and cpu device managers respectively. 
*Testing*: ninja test, also ran resnet-runtime with different values and noted that the partitioner could not find a valid partitioning if memory was too low.
*Documentation*: Do we document all of our flags somewhere?
=> Add command line options to set interpreter max mem and cpu max mem.

examples/resnet-concurrent.cpp, examples/tracing-compare.cpp, include/glow/Backends/Backend.h, include/glow/Optimizer/Optimizer.h, lib/Backends/Backend.cpp, lib/Backends/CMakeLists.txt, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Optimizer/CMakeLists.txt, lib/Optimizer/GraphOptimizer.cpp, lib/Runtime/HostManager/CMakeLists.txt, lib/Runtime/HostManager/HostManager.cpp, tests/benchmark/RuntimeBench.cpp, tests/unittests/DeviceManagerTest.cpp, tests/unittests/HabanaBackendTest.cpp, tests/unittests/TraceEventsTest.cpp
*Description*: For #2700, the library containing `optimizeFunction()` (prior to this PR in `Backend`) must depend on `Quantization`. `Quantization` already depends on `Backend`, so #2700 would create a cyclic dependence. This PR moves `optimizeFunction()` to `GraphOptimizer.cpp`, removing the cyclic dependence for #2700 . I think `optimizeFunction()` more naturally fits into `Optimizer` anyway. 
TL;DR:
Before: `Quantization --> Backend --> Optimizer`
Before (with #2700): `Quantization <--> Backend --> Optimizer`
After: `Quantization --> Backend <-- Optimizer`
After (with #2700): 
```
Quantization <-- Optimizer
\     /
v   v
Backend
```
*Testing*: Everything still builds/passes.
=> Move optimizeFunction() to GraphOptimizer

tests/unittests/BackendTestUtils.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/QuantizationTest.cpp
*Description*: Added tests for rowwise-quantized FC using Symmetric quantization. This included using the schema parameter inside calls to `compareAgainstInterpreter()` when generating NodeQuantizationInfos.
*Testing*: Yup.
=> Add tests for symmetric rowwise-quantized FC

lib/Importer/ONNXModelLoader.cpp
*Description*:
Accidentally changed this line when I was converting some other items to SmallVector.
*Testing*:
./bin/image-classifier tests/images/imagenet_299/cat_281_299.png   -image-mode=0to1 -m=googlenet_v4_slim/googlenet_v4_slim.onnx -model-input-name=input:0 -image-layout=NHWC -label-offset=1
Before: seg fault.
After: works OK.
=> Undo bug introduced in my last PR

include/glow/Importer/ONNXModelLoader.h, lib/Importer/ONNXModelLoader.cpp, tests/models/onnxModels/leakyRelu.onnxtxt, tests/models/onnxModels/leakyReluDefault.onnxtxt, tests/unittests/OnnxImporterTest.cpp
*Description*: Adding LeakyRelu to ONNX Importer, and mapping it to PRelu internally.
*Documentation*: https://github.com/onnx/onnx/blob/master/docs/Operators.md#LeakyRelu
=> LeakyRelu ONNX loader support

lib/Base/IO.cpp, tests/unittests/UtilsTest.cpp
Description: Needing to know the tensor type out-of-band makes it a lot harder
to use these routines for instrumentation and debugging.  Since these tensor
dumps aren't intended to be a real serialization format, we can just
fwrite/fread the Type struct to get the information we want.
Testing: Modify existing test to not rely on type knowledge.
=> [tensor] Improve file I/O routine

include/glow/Graph/Graph.h, lib/Graph/Graph.cpp, tests/unittests/GraphTest.cpp
*Description*:
Adding getOutputSave method into common glow code.
*Testing*:
GraphTest
getOutputSave method will be used across specific backends implementations
#2692
=> Moving method getOutputSave to the common glow code.

include/glow/Base/Traits.h, lib/Partitioner/PartitionerUtils.cpp
*Description*:
Replaced static comparison function with the correspondent lambda.
*Testing*:
ninja test
Class Named exposes the comparison function by names.
Any lambda can use it to compare two instances of class Node and make code inlined.
=> Inlining std::sort predicate.

lib/Backends/OpenCL/CMakeLists.txt, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCLDeviceManager.cpp
This commit moves the hexified OpenCL kernels from `glow/...` to
`glow/OpenCL/...`.
**Testing**
Ran `OCLTest` and it passed.
=> [OpenCL] Move hexified OpenCL kernels from glow/ to glow/OpenCL

lib/Backends/BackendUtils.cpp, lib/Runtime/Provisioner/Provisioner.cpp, tests/unittests/BackendTest.cpp
*Description*: This updates the create method on RuntimeBundle to properly set input and output status for symbols. 
*Testing*: ninja test: 
Fixes #1953
=> Update createBundle to set symbol input and output

.circleci/build.sh, .travis.yml, CMakeLists.txt, include/glow/LLVMIRCodeGen/GlowJIT.h, lib/Backends/CPU/CMakeLists.txt, lib/LLVMIRCodeGen/BundleSaver.cpp, lib/LLVMIRCodeGen/DebugInfo.cpp, lib/LLVMIRCodeGen/GlowJIT.cpp, lib/LLVMIRCodeGen/LLVMIRGen.cpp, tests/unittests/QuantizationTest.cpp
*Description*:
Removing code support in LLVM package versions <= 6.
*Edited*: CI scripts were modified to use LLVM version 8.
The reason for skipping LLVM-7 is a problematic llvm-7 distribution for Ubuntu-16.04 (xenial), which has been built with old C++ ABI and therefore is incompatible. Locally (MacOS) tests pass also on llvm-7.   
Should be followed up (in next commit) by removing all FACEBOOK_INTERNAL branches (with the specific patch number).
*Testing*:
* cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../glow
-- Found LLVM 7.0.1
...
ninja test
* cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../glow -DCMAKE_PREFIX_PATH=/usr/local/Cellar/llvm/8.0.0/
-- Found LLVM 8.0.0
...
ninja test
* On a devserver (changes copied manually, llvm version 8):
buck build //glow/...
buck test //glow/... …
=> removing support in llvm 6 and below

lib/Quantization/Quantization.cpp, tests/unittests/QuantizationTest.cpp
*Description*: Turns out #2670 needs to be reverted -- the logic was there for a reason, but was not being unit tested. I've added the missing unit test as well as better documentation for why the logic is necessary.
*Testing*: Added a new unit test that covers this (previously not unit tested) path.
=> [Quantization] Revert removal of nodeToTQP_ update in postProcessing()

lib/Onnxifi/Base.cpp, lib/Onnxifi/onnxifiGlow.cpp
*Description*:
It is possible that input tensor descriptor has a null buffer with dim [0]. For example, we can look up 0 elements in embedding table in current batch. We need to allow this case. Also fix a bug where we return incorrect error code. 
*Testing*:
Internal test. 
=> Allow zero sized tensor inputs

CMakeLists.txt
I have LLVM 7.1 on my laptop. #2699 was requiring 7.0 specifically. This fix seems to work. I'm no CMake master so let me know if this makes sense or if there's a better way 😃
=> [CMakeList] Allow for LLVM 7 with any minor version

include/glow/Runtime/Provisioner/Provisioner.h, lib/Runtime/Provisioner/Provisioner.cpp
*Description*:
No need to use the factor. NETWORK_PADDING_FACTOR was added to reflect the memory use of the instruction. 
*Testing*:
=> [Provisioner] Remove NETWORK_PADDING_FACTOR

include/glow/Quantization/Base/Base.h, include/glow/Quantization/Quantization.h, include/glow/Quantization/Serialization.h, lib/Optimizer/Lower.cpp, lib/Quantization/Base/CMakeLists.txt, lib/Quantization/Serialization.cpp, tests/unittests/BackendCorrectnessTest.cpp, tests/unittests/BackendTestUtils.h, tests/unittests/OperatorTest.cpp
These make more sense in `QuantizationBase` and allow other files using them to include less. 
This included changing the constructor for `NodeNameAndKind` to just take the info from the `NodeValue` instead of the `NodeValue` itself, so that it doesn't need to depend on anything from Graph.
=> [Quantization][NFC] Move some structs/using to QuantizationBase

lib/Graph/Graph.cpp, tests/unittests/GraphTest.cpp
*Description*: getOutputSave returns the SaveNode associated with a particular Placeholder, but did not check that if a Placeholder was used for a SaveNode in multiple Functions that it returned the one associated with the provided Function. Now it does.
*Testing*: unittests, extended `getOutputSaveTest` to check this case, test fails without this fix.
=> Fix getOutputSave so it returns a SaveNode from the right Function

include/glow/Quantization/Base/Base.h, lib/Quantization/Quantization.cpp
Since we're using LLVM 7 and above now, SmallSet is now iterable 😄
=> [trivial] Move loweredMapInfo to use llvm::SmallSet

include/glow/Runtime/RuntimeTypes.h, lib/Partitioner/Partitioner.cpp, lib/Runtime/Executor/ThreadPoolExecutor.cpp, lib/Runtime/Executor/ThreadPoolExecutor.h, lib/Runtime/HostManager/HostManager.cpp, lib/Runtime/Provisioner/Provisioner.cpp, tests/benchmark/RuntimeBench.cpp, tests/unittests/ExecutorTest.cpp, tests/unittests/ProvisionerTest.cpp
*Description*: This PR updates the DAGNode data structure to support networks being duplicated on multiple devices. This is the first step, the next step would be updating the provisioner and partitioner to handle duplication.
*Testing*: ninja test, and resnet-runtime
=> Update DAGNode to support network duplication.

lib/LLVMIRCodeGen/LLVMIRGen.cpp
This solves the issue with  "LLVM ERROR: Inline asm not supported by this streamer because we don't have an asm parser for this target" reported when compiling libjit by some backends.
=> [LLVMIRCodeGen] Initialize all asm parsers

CMakeLists.txt
Add a `GLOW_USE_LLD` option that will switch the build to use lld.  This option
requires `clang`, but can result in reduced build times.
*Description*:
*Testing*:
=> build: add a helper option to use lld

lib/Runtime/Provisioner/Provisioner.cpp, tests/unittests/ProvisionerTest.cpp
*Description*: This PR adds the logic to the provisioner to support loading a network on multiple devices. This is done by assigning more than one logicalDevice to the DAGNode for the function.
*Testing*: Extended the Provisioner test to duplicate networks. 
=> Adds network duplication support to the Provisioner

lib/Backends/Habana/Habana.cpp, lib/Backends/Habana/HabanaDeviceManager.cpp
*Description*: (backport from glow-h) Since #2668 we may have copied placeholders with the same name but a different pointer. Sometimes we need to fall back to searching by name.
*Testing*: sanity unittests, but really tested in glow-h
*Documentation*: I don't really like this change and would love an alternative.
=> [habana] Fall back to looking up Placeholders by name

examples/fr2en.cpp, include/glow/Quantization/Quantization.h, lib/Onnxifi/InlineOnnxifi.cpp, lib/Quantization/Quantization.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/MLTest.cpp, tests/unittests/QuantizationTest.cpp, tools/loader/Loader.cpp
*Description*: This PR changes `quantizeFunction()` by moving many of its current params into a simple aggregate struct `QuantizationConfiguration`. #2700 includes many of these parameters in `CompilationOptions`; I will rebase it on this PR to instead include `QuantizationConfiguration`. #2746 also adds another param which will be wrapped into `QuantizationConfiguration` too.
*Testing*: Updated all tests.
=> [Quantization] Add QuantizationConfiguration struct for quantizeFunction()

examples/resnet-runtime.cpp, include/glow/Partitioner/Partitioner.h, include/glow/Runtime/HostManager/HostManager.h, lib/Partitioner/Partitioner.cpp, lib/Runtime/HostManager/HostManager.cpp, lib/Runtime/Provisioner/Provisioner.cpp
*Description*: This PR adds a new saturateHost method to the Partitioner. If the saturateHost flag is set the Partitioner will duplicate networks to use all available devices on the host.
*Testing*: updated resnet-runtime to use new method, runs across multiple devices correctly.
=> [Runtime] Added saturateHost flag and method to partitioner

examples/bundles/lenet_mnist/Makefile, examples/bundles/resnet50/CMakeLists.txt, examples/fr2en.cpp, include/glow/Quantization/Quantization.h, lib/Quantization/Quantization.cpp, tests/text-translator/en2gr_quantization_test.sh, tests/unittests/BackendTestUtils.cpp, tests/unittests/MLTest.cpp, tests/unittests/OperatorTest.cpp, tests/unittests/QuantizationTest.cpp, tools/loader/Loader.cpp
*Description*: This PR adds an `assertAllNodesQuantized` option to `quantizeFunction()`. If true, the Quantizer will die if it would have skipped quantizing a node because the backend does not support it as quantized. This is intended to be used by unit testing/testing bigger models via the Loader. For now it is disabled by default in the Loader, but by default true for `quantizeFunction()`. The motivation is explained in #2464.
*Testing*: Added tests for this functionality specifically. Also updated/removed tests where applicable.
*Documentation*: Added command line option with documentation on what it's for; added doxygen.
Fixes #2464
=> Add assertAllNodesQuantized option to quantizeFunction()

include/glow/Runtime/RuntimeTypes.h, lib/Partitioner/Partitioner.cpp, lib/Runtime/Executor/ThreadPoolExecutor.cpp, lib/Runtime/Executor/ThreadPoolExecutor.h, tests/unittests/ExecutorTest.cpp
*Description*: This PR adds a reference to Module in the DAGNode so the executor can use the PHs in the Module rather than needing to create its own.
*Testing*: Updated Executor Test. unit tests pass and resnet-runtime
*Documentation*: Will be added to Runtime doc once runtime doc is added to docs. :D
fixes #2749
=> Removed PH creation from Executor

examples/resnet-runtime.cpp, examples/tracing-compare.cpp, include/glow/Backends/TraceEvents.h, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/TraceEvents.cpp, lib/LLVMIRCodeGen/LLVMCompiledFunction.cpp, lib/Onnxifi/Base.cpp, lib/Runtime/Executor/ThreadPoolExecutor.cpp, lib/Runtime/HostManager/HostManager.cpp, tests/unittests/TraceEventsTest.cpp
*Description*: Replace Manual setting of thread id with automatic ids, which eliminates issues where multiple work was happening "concurrently". This disables thread names for now.
*Testing*: unit tests, tracing-compare and resnet-runtime
=> [tracing] add automatic thread ids

lib/Backends/CPU/CMakeLists.txt
This helps to eliminate mismatch between given LLVM's linker and system's standard llvm-link
=> [NFC] Use llvm-link from the given LLVM build directory

include/glow/Quantization/Base/Base.h, lib/Quantization/Quantization.cpp
This reverts commit 88bae3142230edf79c18803afe2663d323cec860.
The llvm version that internal builds use don't have the begin/end operations available.
=> Revert "[trivial] Move loweredMapInfo to use llvm::SmallSet"

lib/Backends/TraceEvents.cpp
*Description*: Internally we use system_clock for the timestamp domain, changing Glow trace events to match.
*Testing*: unittests
=> [tracing] [trivial] switch to std::system_clock for timestamps

tests/images/run.sh, utils/download_onnx_models.sh
*Description*:
This image classification model currently works with glow.  The
probabilities match those reported by Caffe2 model of this RCNN.  The
labels reported match the following list:  See Table 8
of https://arxiv.org/pdf/1311.2524.pdf
*Testing*:
`ninja all && ./tests/images/run.sh`
or
`bin/image-classifier tests/images/imagenet/cat_285.png -model bvlc_reference_rcnn_ilsvrc13/model.onnx -model-input-name data_0 -image-mode 0to255`
The result should identify that image as "Label-K1: 58"
Fixes #2505
=> [ModelZoo] Add RCNN ILSVC13 ONNX model

tests/unittests/CMakeLists.txt, tests/unittests/ProvisionerTest.cpp
*Description*:
- Noticed some unit tests were missing in TARGETS file used internal to FB. Fixed that in internal repo. Keeping the tests sorted alphabetically makes it easier to maintain these in sync.
- Changed the include path used in ProvisionerTest to use relative path, instead of a target_include_directories in CMakeLists.txt (consistent with rest of tests, easier to deal with in TARGETS).
*Testing*:
ninja all
ninja test
=> [NFC] Minor tweaks to tests/unittests/CMakeLists.txt

lib/Graph/Nodes.cpp
*Description*
Originally the error messages were identical.  Making them more specific, and unique, simplifies debugging.
=> [graph] Make the "mismatched dimension" error diagnostics more specific. NFC.

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/kernels.cl, tests/unittests/OperatorTest.cpp
This commit adds an OpenCL implementation of `SparseLengthsWeightedSum`.
It is very similar to the CPU backend implementation; the only difference
is that the outputs for each segment are computed in parallel.
**Testing**
This commit enables `SparseLengthsSum` and `SparseLengthsWeightedSum` operator tests for
OpenCL and they pass. 
```
$ ./tests/OperatorTest --gtest_filter=*\.SparseLengths*Sum/*
Note: Google Test filter = *.SparseLengths*Sum/*
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from OperatorTest/OperatorTest
[ RUN      ] OperatorTest/OperatorTest.SparseLengthsSum/0
[       OK ] OperatorTest/OperatorTest.SparseLengthsSum/0 (69 ms)
[ RUN      ] OperatorTest/OperatorTest.SparseLengthsSum/1
[ …
```
=> [OpenCL] Add OpenCL implementation of SparseLengthsWeightedSum

lib/Backends/OpenCL/CMakeLists.txt
This dependency was introduced by mistake as a result of a copy&paste.
=> [OpenCL] Remove the spurious dependency on CPURuntime

lib/Backends/BackendUtils.cpp, lib/Backends/CPU/CMakeLists.txt
*Description*: Updated cmake to work with windows also. On windows with VS bin folder is under ${Configuration}. Made comparison explicit with node. On windows it was resulting in build failure.
=> window fixes

include/glow/Backends/CompiledFunction.h, include/glow/LLVMIRCodeGen/LLVMCompiledFunction.h, lib/Backends/Interpreter/InterpreterDeviceManager.cpp, lib/Backends/Interpreter/InterpreterFunction.cpp, lib/Backends/Interpreter/InterpreterFunction.h, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/OpenCL.h, lib/LLVMIRCodeGen/LLVMCompiledFunction.cpp
This commit fixes the `resnet-runtime` example for the Interpreter
backend. This wasn't working because constants (i.e. weights and biases)
were not being set before the execution of an `InterpreterFunction`.
**Testing**
The `resnet-runtime` example now passes on the Interpreter backend.
```
$ ../build_RELEASE/bin/resnet-runtime ../glow/tests/images/imagenet/ -interpreter-memory 2000000000
Initializing 5 Interpreter Devices on HostManager.
Loading resnet50 model.
Loading files from ../glow/tests/images/imagenet/
Started run ID: 0
Started run ID: 1
Started run ID: 2
(0) ../glow/tests/images/imagenet/zebra_340.png: 340
(0) ../glow/tests/images/imagenet/cat_285.png: 281
(0) ../glow/tests/images/imagenet/dog_207.png: 207
Finished classifying 3 images.
```
=> [examples] Fix resnet-runtime for the Interpreter

examples/fr2en.cpp, include/glow/Optimizer/Optimizer.h, include/glow/Quantization/Quantization.h, lib/Onnxifi/InlineOnnxifi.cpp, lib/Optimizer/Quantization.cpp, lib/Quantization/Quantization.cpp, tests/unittests/BackendTest.cpp, tests/unittests/BackendTestUtils.cpp, tests/unittests/GraphTest.cpp, tests/unittests/MLTest.cpp, tests/unittests/QuantizationTest.cpp, tools/loader/Loader.cpp
*Description*: As discussed in #2700, this removes cloning the function for quantization and profiling. If the caller wants the original function after quantization/profiling it should clone the function prior to calling `quantizeFunction()`/`profileQuantization()`.
*Testing*: All tests still pass.
=> Remove cloning of functions for quantization and profiling

lib/Backends/CPU/CPUBackend.cpp, lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/Interpreter.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Graph/Grad.cpp, lib/Graph/Nodes.cpp, lib/IR/IRGen.cpp, lib/LLVMIRCodeGen/LLVMIRGen.cpp, tests/unittests/MLTest.cpp, tools/ClassGen/InstrGen.cpp, tools/ClassGen/NodeGen.cpp
This commit adds support for training the `SparseLengthsWeightedSum`
operator. The gradient for this node is computed by initializing the
`data` gradient to be zero, and then accumulating into `dataGradient[index]`
the gradient of the result slice that `data[index]` was added to during
the `SparseLengthsWeightedSum` operation multiplied by `weight[index]`
(the same weight that `data[index]` was multiplied by during the
`SparseLengthsWeightedSum` operator).
**Testing**
This commit adds a unit test to `MLTest` that trains the data input of a
`SparseLengthsWeightedSum` node so that the operation outputs a
specified `Tensor`. The indices, lengths, weights are fixed.
=> [Training] Add support for training SparseLengthsWeightedSum

include/glow/Importer/CommonOperatorLoader.h
*Description*:
This PR syncs foxi and updates Glow's `loadWeights` function so that it reads the first quantization parameter for quantized tensors. Reading multiple quantization parameters into separate biases and scales tensors is left for a future PR
*Testing*:
* [in progress] sync with caffe2 and test on quantized resnet50
doxygen
=> Sync foxi including multiple quantization params per tensor

tests/unittests/OperatorTest.cpp
Two trivial commits here for a private backend:
- Change error threshold for FC_Float16 to 0.02
- Make weights/bias Constant in FCWithFlatten
=> [OperatorTest][trivial] A couple unit test changes for private backend

include/glow/Graph/Graph.h, lib/Importer/Caffe2ModelLoader.cpp, lib/Importer/ONNXIFIModelLoader.cpp, tests/unittests/Caffe2ImporterTest.cpp
*Description*:
In the context of hand crafted partitions we need to make sure that C2 graphs coming to Glow will be deterministic through the optimization phase.
This PR sorts nodes by name ensuring same traversal order for same C2 graphs, even if nodes are supplied in a different order.
*Testing*:
Unit tests
n/a
=> [C2 loader] Make sure that node ordering persists for loaded C2 models.

lib/Runtime/HostManager/CMakeLists.txt
*Description*: Make glow build without the CPU backend which was previously impossible due to HostManager always being linked against CPUDeviceManager.
*Testing*: The build doesn't break, the basic backend tests seem fine.
=> [CMake] Don't link with CPUDeviceManager unless GLOW_WITH_CPU=ON

README.md
*Description*:
The CMakeLists.txt file requires llvm 7.0 or higher to build Glow.  This patch
updates the version number in the README documentation to reflect the configuration file
constraint.  We should update the instructions in the  building
on Ubuntu 16.04 section too, as that still refers to llvm 6.0.  I was
uncomfortable modifying that section as I cannot test it as written on
my setup at the moment.
=> [readme] Update the required llvm version from 5 to 7. NFC.

include/glow/Graph/Node.h
This is useful if e.g. isOpSupported needs to use a name information and for debug printing.
=> Allow NodeInfo objects to have names

include/glow/LLVMIRCodeGen/LLVMBackend.h, include/glow/LLVMIRCodeGen/LLVMIRGen.h, lib/LLVMIRCodeGen/FunctionSpecializer.cpp, lib/LLVMIRCodeGen/LLVMBackend.cpp, lib/LLVMIRCodeGen/LLVMIRGen.cpp, lib/LLVMIRCodeGen/Pipeline.cpp
- Make it possible for backends to provide custom logicto decide which symbols need to be preserved during the LLVM's internalizeModule pass
Some backends may have a custom logic for deciding which symbols need to be preserved.
- Provide APIs for setting target, arch and cpu properties of LLVMBackend
Backends can now override these settings by setting these properties to appropriate, backend-specific values.
- Make it possible for backends to provide custom logic to decide which calls are eligible for specialization
=> [LLVMIRCodeGen] Minor improvements making LLVMIRCodeGen more customizable by backends

lib/Importer/Caffe2ModelLoader.cpp, tests/models/caffe2Models/maxpool_legacy_padding_predict_net.pbtxt, tests/unittests/Caffe2ImporterTest.cpp
*Description*:
Caffe1 legacy padding rounds the shape dimensions up for MaxPool
operators and Caffe2 rounds down.  According to Caffe2's
caffe2_legacy.proto definition, legacy padding is deprecated.
During graph generation, Glow might insert Caffe2 MaxPool nodes unaware
of the padding strategy.  If a MaxPool node is defined in the Caffe2
file, that follows the legacy strategy, we result in a model where some
MaxPool nodes will round their shapes up and others will round down.
Instead of introducing this confusion, we reject the deprecated logic in
favor of what we have always done, support non-legacy/Caffe2 padding.
See: https://github.com/pytorch/pytorch/blob/master/caffe2/proto/caffe2_legacy.proto
*Testing*:
`ninja test`  ... nothing should fail, in particular the OperatorTest should …
=> [importer] Detect legacy (Caffe1) padding and exit.

include/glow/Importer/CommonOperatorLoader.h, tests/models/onnxModels/preluBroadcastSlope.onnxtxt, tests/models/onnxModels/preluInvalidBroadcastSlope.onnxtxt, tests/models/onnxModels/preluSlopeHasSameShape.onnxtxt, tests/unittests/OnnxImporterTest.cpp
Adding PRelu to ONNXModelLoader.
Handling the simple case of broadcasting the same number of dims (possibly different values).
Still needs to figure out handling different number of dimensions. 
*Testing*: unit tests added to ONNXImporterTests with corresponding test models.
Fixes #2501
=> adding prelu to onnx model loader

lib/Backends/CPU/CPUDeviceManager.cpp
*Description*: There is name conflict when OptionCategory gets created between CPUDeviceManager.cpp and OptionCategory.cpp. The underlying llvm object is global.
*Testing*: UnitTests
=> Trivial Fix for llvm assert.

CMakeLists.txt
*Description*:
This updated configuration matches the documentation at
https://github.com/pytorch/glow/blob/master/docs/Building.md
Notably, the line:
"By default Glow builds with only the interpreter backend enabled."
It was also mentioned that not everyone has OpenCL installed.  I think
it makes sense to not make OpenCL a requirement; however, I can also see
where it might be expected as a requirement.  I figured I'd at least put
this PR out for discussion.
*Testing*:
The unittests should still build and run correctly:
`ninja all && ninja test`
Fixes #2466
=> [cmake] Disable OpenCL support by default.

utils/build_llvm.sh
*Description*: I don't know how common this is for people, but when trying to build
Glow on my increasingly-ancient CentOS 7 box I needed to build clang locally
too (I assume for compiling libjit to bitcode).
*Testing*: Used it
=> [utils] Build clang alongside llvm

lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/kernels.cl, tests/unittests/MLTest.cpp
This commit adds an OpenCL implementation of `SparseLengthsWeightedSumGrad`. This implementation is identical to the CPU backend implementation. It is difficult to parallelize this operation without giving each global ID its own copy of the dataGrad buffer and adding together the copies at the end. As a result, this has been left as a future work item.
**Testing**
This commit enables `learnSparseLengthsWeightedSum` for the OpenCL backend in MLTest and it passes.
```
...
[ RUN      ] OpenCL/MLTest.learnSparseLengthsWeightedSum/0
[       OK ] OpenCL/MLTest.learnSparseLengthsWeightedSum/0 (338 ms)
...
```
=>     [OpenCL] Add OpenCL implementation of SparseLengthsWeightedSumGrad

lib/Backends/CPU/libjit/libjit.cpp, lib/Backends/Interpreter/InterpreterNodes.cpp, lib/Backends/OpenCL/OpenCL.cpp, lib/Backends/OpenCL/kernels.cl, lib/IR/IRGen.cpp, lib/LLVMIRCodeGen/LLVMIRGen.cpp, tests/unittests/MLTest.cpp, tools/ClassGen/InstrGen.cpp
This commit adds support for computing the gradient for the weights
input of `SparseLengthsWeightedSum` for Interpreter, CPU and OpenCL
backends.
**Testing**
This commit adds a test to `MLTest` that is similar to the existing
`SparseLengthsWeightSum` training test, except that it trains the weights
instead of the embeddings.
=> [Operators] Add weight gradient for SparseLengthsWeightedSum

lib/Backends/Habana/Habana.cpp, lib/Backends/Habana/Habana.h, lib/Backends/Habana/HabanaDeviceManager.cpp, lib/Backends/Habana/HabanaDeviceManager.h
*Description*: Add in some more detailed trace events into the Habana function and simplify it's threading logic. Multiple Runner and Waiter threads in the HabanaDeviceManager aren't providing any advantage since it's serialized in the H runtime, so put them both down to 1.
This reduces cold start time of the device quite a bit (see below) due to optimistically activating the topology on model load.
before:
after:
*Testing*: manual test with a device
=> Add TraceEvents to Habana backend and simplify

lib/Backends/Habana/Habana.cpp
* Introduced LRN, fixed #144
* Added Concat node to the list of supported quantized nodes
* Added RescaleQuantized node, replaced quantized MatMul with GEMM
=> [habana] Misc fixes for vision nets

lib/Backends/Habana/Habana.cpp
*Description*:
Intermediate tensors don't need to be materialized; their host data
pointers just serve as unique identifiers.  So instead of allocating a full
buffer, this diff mallocs a single float, which is an easy (if ever-so-slightly
kludgy) way to guarantee uniqueness.
*Testing*: HabanaBackendTest
=> [habana] Don't allocate buffers for intermediate tensors.

lib/Backends/Habana/Habana.cpp
*Description*: We only need to insert intervening memcpy between a concat and its src
if the src is used in multiple places.
=> [habana] Optimize away some conservative memcpys before concats

examples/tracing-compare.cpp, include/glow/Optimizer/Optimizer.h, include/glow/Support/Error.h, lib/ExecutionEngine/ExecutionEngine.cpp, lib/Optimizer/GraphOptimizer.cpp, lib/Runtime/HostManager/HostManager.cpp, tests/benchmark/RuntimeBench.cpp, tests/unittests/DeviceManagerTest.cpp, tests/unittests/HabanaBackendTest.cpp, tests/unittests/TraceEventsTest.cpp
*Description*: This is something we do in the ExecutionEngine. We should also check it somewhere in the HostManager, especially as PRs like #2799 move to using HostManager instead. This error represents some internal compilation error during optimizeFunction.
*Testing*: All unit tests pass.
=> Add HostManager check that all nodes are supported after optimization

lib/Partitioner/Partitioner.cpp, lib/Runtime/Provisioner/Provisioner.cpp, tests/unittests/CMakeLists.txt, tests/unittests/ProvisionerTest.cpp
*Description*:
It's useful to know the exact constraints causing the partitioner/provisioner to fail.
*Testing*:
PartitionerTest: Observe the improved error message.  Ahh, lovely.
ProvisionerTest: Add a failing case.  Made the net setup use FCs so they have enough weight to possibly fail.
Good error messages *are* documentation!
=> Improve partitioner/provisioner error messages

include/glow/Runtime/RuntimeTypes.h, lib/Partitioner/Partitioner.cpp, tests/unittests/ProvisionerTest.cpp
*Description*:
{root,nodes}DAGNodeTy don't follow our naming convention (begin with capital letter) and are kind of hard to understand without looking up the definitions.
*Testing*:
`ninja all`
=> Clarify DAGNode-related type names

include/glow/LLVMIRCodeGen/LLVMIRGen.h, lib/Backends/CPU/libjit/libjit.cpp, lib/LLVMIRCodeGen/LLVMIRGen.cpp
Determine the size of size_t from the actual libjit bitcode, rather than from the TargetMachine. This seems to be more reliable as libjit kernels are the ones being invoked and the type used by the codegen should exactly match whatever size_t type was used to compile libjit into LLVM bitcode.
Related to #2836
=> [LLVMIRCodeGen] Make LLVMIRCodeGen more cross-compilation friendly

include/glow/Backends/TraceEvents.h, lib/Backends/Habana/HabanaDeviceManager.cpp, lib/Onnxifi/Base.cpp, lib/Onnxifi/Base.h, lib/Onnxifi/HostManagerOnnxifi.cpp, lib/Onnxifi/InlineOnnxifi.cpp, lib/Runtime/Executor/ThreadPoolExecutor.cpp, lib/Runtime/HostManager/HostManager.cpp
*Description*: Add trace events in the ONNXIFI layer so we can can determine latency costs there, also updated the naming of events a bit to make it easier for people who aren't me to interpret the traces.
before:
after:
*Testing*: I did run unit tests, but we don't have coverage of ONNXIFI yet. Ran a manual test on a H device to verify.
=> [tracing] Add TraceEvents to ONNXIFI and clean up naming

lib/Onnxifi/Base.cpp, lib/Onnxifi/CMakeLists.txt
*Description*: Pulling the latest version of foxi with some TraceEvents changes. Just updating glow to build and work with no behavioural change. Will add support for `complete` events in a follow up.
*Testing*: build and test
=> Update foxi and remove onnxTraceEvent name alloc

include/glow/Backends/Backend.h
*Description*: This is apparently the only place in the codebase that includes llvm headers using <> instead of "".  
Testing: compile
=> [trivial] include llvm with "" not <>

.circleci/build.sh
*Description*: There's work ongoing to figure this out, but in the meantime we've sorta lost all signal from the Debug build config.  Let's just turn these off until it can get sorted.
*Testing*: This PR
=> Disable OpenCL tests temporarily due to sporadic double free in POCL

lib/Onnxifi/Base.cpp
*Description*: I forgot the null terminator when switching from strcpy to strncpy.
*Testing*: unittests, manual test in C2.
=> [tracing] fix null termination in Onnxifi trace event names

include/glow/Base/Tensor.h, include/glow/Graph/Graph.h, include/glow/Graph/Nodes.h, lib/Graph/Graph.cpp, lib/Runtime/HostManager/HostManager.cpp
*Description*: This fixes an issue with OpenCL in the runtime. The module was being cleared but OpenCL needs tensor type information. This adds a new release method to the tensor that frees the data and converts the tensor to an unowned tensor. This also introduces a strip method to the module that releases constants memory and frees functions.
*Testing*: ninja test, and resnet-runtime with openCL
=> Add Tensor release and Module strip.
